---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-registry-secret
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgDILjBmafBKZBTkmsbzPR8pOu45TmPW9UWwXGSj23w5a+toJ1GBaFIt2WQzgA4ARl5heL0ygvHYsuTd+axmF+2d6tHmm20uUP/WoIu16USYH/cAMlWM49z4PPKLq98T37pR9/tp/jBqanjoJFMUvuj9LpeWqrsatSBLFxFybVf3wP+YLqJlMWN/uXRjeJpAWHrkS2vMB9QNB+Tmqe5UmyAKjp0/rZC0RJ9YaFvpc2DI+KmdYTHjBwuBFL60sLV9TQJTsc9P66tneVGqtP3WLOzv9OY0B4Yiv0tnaNfmGDlRsHg1fyJvNFOMxCwGfhdZ3Dzf4GV2+Iq3idnhhZF7AOJJmDamcWLd7grgEXhNvC7a0HBxpUNAR24XmXG3NAYiNvGzcogbT+9voOnlXmIa01G0FEJlHJAEUxJFjtbGDf/Yis3pnr5rU53bZISlDCvFjE1cP+o0VE1/b2qgzSbUltrSleH0bSh6WxNRaX5Dy0LoBS58TxmvNgN4L0EpL2XnfDsO2NlLSv4/Pr30FCQbENZVhbRmer3B98X6gkps61rv/OvpLCW3jbXwj9f62eUDjOfusodrRhcH/k28zYh674DW8qrF0KFv0/PUcgS61TR4i+3JLfuvJEFGDEx9OBo9ADbva+EZ43HrCKNGysTr2p8dUDLJMoo4Ul3afT6pD7Yav59AOf6LXPy6eDcAYb9OPfkNUXfsaEIodyE65wJyU2bGjwOEgFPq+ryRgXraaGC3QpbuPq4nDlfMfaiOlv5LOEFzVqtQeh7pzBjxkhNr6XlWTc/ONQFO33MxYx5ydVQGCsuem4Sz9ioYcJ5m3ol+DCG19WaZol1R+caUvdHG3V7CpseRgShAoE5Q2srn7Qj3wE7unMZocBWnNV6bbt2xSnnvZnx+bAXXooKfLXPd3FAFDc5EzrXsV2RWPopgl+JYYu0cwab1Dqnm16d8MjsMX24c5q6PX566ivEKqn5/Gyb8pUTHULvr4BCdSCAMIMtePozxjXSli7hX
  template:
    metadata:
      name: harbor-registry-secret
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson
