---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opsbridge-secrets
  namespace: monitoring
spec:
  encryptedData:
    GITEA_TOKEN: AgB4TZOH5h/Cm7RxE3PAvL8lGHz/VxeqLWoTgTCPwnYZ12Zegs/f9f53+5phX2aGj+Th3lI1mutHvK7crnYKMfjVxapMhsDjcIhgDp1vIV0ZZZH/Q+p2FJG5E9epTdK2QxWE3LA2qcwfF3vjMYbOMUIiBac8oiGjQ7ucptxtsQKe0jeUXa8GTl2EAx0u62wH6G65uvfMfSM8q8afe79qCZoaQpm80fTfSOIuoVktMscR8h1ttV0DYBYOwkrL5iQ4xNLqobnKy0o12+/Ia8G2ZWjifETSyoh24w5Gy7rU5+hoDDrPRq+9ENmbJR+Se6pxJK7wXLXOmYW559DHHvYNUC+jR7T57YO/QviHOwem5URC/M9LtTOH8Lb0NeU/dyvzWA+QSmXIVefkgKqgR9v6qnGVzQfBc3d3vwA2gjg+xhk9j1bXe3tywmHufWvrY+m6nUPBGV/N3AxEsePd6koorTp7mQDnnDsp2Yz5zoHm7OBYSHTIbQ8Ur3N5gh010VEx85UNWjyGArhJ9mRBIVZ8Hx840m+cEmDMYV5PUecZeoHuX1945AAmO9GSNwEXNgvUYvf238DAdNRNoMyrUlzrVl3JttRSHkbFbc9OtMlmrANaiws9LtL/+plArT3NjVDU4wNLIItCrFKP85cN2hwgyQgyVNYqO+uaAy1h1QgpCy/xV4pT1FIsHn+RYl90RAS0vBmkXq6nBLzompXcip30PpIJ08qg2Fk2wVLwDo48dCV3wyq0wR1y7m8C
    MATTERMOST_BOT_TOKEN: AgALQ8Xc41uUIiAF1FyUz7Tt0mltNCYKqz60qFO1AzS/e3BAJlButMItQZIW2N0nTJ+7UoiLD6ojCs/JSh/yLF7Ebqm+nvPhZbiULRBU2Zn7iR9VKkWYi+9wMfOIbSHzrTNc4Nc1HN+pP4/4HrjM+CyH5UVa/WY7m99T4/WRt6l/GRGis4XO/uH8LA2yEvMLmDHIvq25XeinGWaCGN+jIqhCejGDgtaSFRyWjrAyYWFt/5/2x/6uYyxD+jy3AtIdzDE/xxRTLb0GG+ENoXgX0VEwFziPHKRFD5kwUdarbWm41rv4hgt1Mkkv5fS6t2YvOXav+KzfUfI3sGzd6lcwMNa9U+NMM9/RAGrqki39b6NWrynp5ggNCUXe733r7NcQHCtcfXgkfGu8gw6VCJaWxFspjnGaCy8I8miN0NMyFessrQrTAL1DIcKkxpFO40sZT+XIuvaGuUqCIRA7taNK8FNDT1XbVgPFBr7buxBaengPWLmPqri3IyGVSld/VEYYtR43mhwxSMki2OxyykG8wK53bLHvOJl1qCbzq+Uu3GyeDYok1ws7ZtCRxfYIVkJ36Gcyu4alHLeyRKaVtUxJE27FiGwjyEmDiMJLYH1eyIRpewfERck320vkxLh00T7Wqj1YrXqVeBdcjIuTIBAnsi4Cb6wBR2GCeVlD7gF62B0mzhIjeuhcWRcudtxaE2poRKH/Y7jmH1n5cqZESfAe3O7SeQJ5elWB3p84hg==
  template:
    metadata:
      name: opsbridge-secrets
      namespace: monitoring
