---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opsmondo-registry-secret
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgBjliwk6vDZgYw9OvOez2wZSWoObh7bdimo20slUpNupmXMjBHpSzD0G2ZuDq4B7OH5ZVdu/+oO/aFBBApg9htPbBqFVEqVpypIRwv4sqLLU5XZxQk7uhvHCuv4OpL50XzCwu3UlYMM2uNSJtIMDA08qOfmJKZl2jtxm/Ww85FWufaRUzJSmTIZoAlGFpU/kDtSrbUFMTlT56G8rZ3MGsO9meq6XKWbNvGeOoJLjn2j8UbKjqJg594tUyrpenUo9Wb5nTRqzxBi5jz2uqD1hTr2xhmGmaWrlFMz8k+H8EuTD1FSnRdITUXcIy3oWBSIGwLjNKs5AFwW5Kz0o6InZdR+rYPAa+X9sw8qICU1V48V43KhjJIEqJfevcZ1ESbHINOpDb6lpH3ZyNdTJ0pHG+G8ph3dXrOR/MHN4BTY8PD4Mq77u7l4OHs+gxHqfEw+7mnsYiERzFRSNOTH2WPFY0QdYOxjibDKUlAJXJII4DMvmq3nCwoG3ry96iznV0gNQethrqqH+RsMDMfZdhk6oI6hqkBJm8lIARphHr/sPdfMZzhy/Bu11B+w6dqEtWqnMu3ECFNPd9zNaPi0ratk70uFQL2p6oZaAn9Qhxs5S7eG+TqKHBIeX+AB8RvQDiw/slnWNsLqPGcUNfA3mhiZXUZa4NOdAZQgPr/nU9pv1/1cpt+VXy9u/zGLTXJicjPNQQstpRTUDywVPYWHVjDro6TmF1c22gfnVYQJzlIISwB5VL8AvNx/Z3+TIgOGRTgCv7TpDA91a2W/dkrt8DW1SzlIZXPH61ReKqMLi6LG8vHgqk6hN21CfILVJdK26+tbcCnlzMVWQbK52BTCgvPmIkRrV4Wdy0qt2dkPK760yvTmjGcUhNQfiTdePQ0yu1xZlFeYjAOJrJMt4oek5ff8teAVZSYTSU87uQoCQ5R1MLTCCEZHgBCHGP6EyAV7dD1C+/yc0Rur9rYJbB1oynaZscfh4WmpTxZhxqoEyNb+q+lgoPC585eAzZDL
  template:
    metadata:
      creationTimestamp: null
      name: opsmondo-registry-secret
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson
