---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-cluster-enableit-kcm-obmondo-com
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/KubeAid.git
      path: argocd-helm-charts/capi-cluster
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/capi-clusters/values-enableit-kcm-obmondo-com.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
