---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ccm-hetzner
  namespace: argocd
spec:
  destination:
    namespace: caph-system
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/KubeAid.git
      path: argocd-helm-charts/ccm
      targetRevision: hetzner_cluster_api
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-ccm.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: hetzner_ccm
      ref: values
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
