apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enableit-website
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: enableit-website
  project: default
  sources:
    - repoURL: https://gitlab.enableit.dk/enableit/enableit-website.git
      path: helm/enableit-website
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-enableit-website.yaml
    - repoURL: https://gitlab.enableit.dk/kubernetes/kubernetes-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
