apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erpnext
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: erpnext
  project: default
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/KubeAid.git
      path: argocd-helm-charts/erpnext
      targetRevision: erpnext
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-erpnext.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: erpnext
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
