apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-stats-exporter
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obmondo
  project: default
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/gitea-stats-exporter.git
      path: helm/gitea-stats-exporter
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-gitea-stats-exporter.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
