apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy
  project: default
  sources:
    - repoURL: https://gitlab.enableit.dk/kubernetes/k8id.git
      path: argocd-helm-charts/haproxy
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/common/argocd-apps/values-haproxy.yaml
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-haproxy.yaml
    - repoURL: https://gitlab.enableit.dk/kubernetes/kubernetes-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
