apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-linuxaid-abbnoa6nlk
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
    path: argocd-helm-charts/kube-prom-linuxaid
    targetRevision: HEAD
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
        - ../../k8s/kbm.obmondo.com/argocd-apps/values-kube-prom-linuxaid-abbnoa6nlk.yaml
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - ApplyOutOfSyncOnly=true
