apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obmondo-common
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: k8s/common/argocd-apps/
    repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
