apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obmondo-uiwork
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obmondo-uiwork
  project: default
  sources:
    - repoURL: https://gitlab.enableit.dk/kubernetes/k8id.git
      path: argocd-helm-charts/obmondo-uiwork
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-obmondo-uiwork.yaml
    - repoURL: https://gitlab.enableit.dk/kubernetes/kubernetes-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
