apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obmondo-web-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obmondo-website
  project: default
  source:
    path: helm/obmondo-web-app
    repoURL: https://gitlab.enableit.dk/obmondo/obmondo-web-app.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - /tmp/https___gitlab.enableit.dk_kubernetes_kubernetes-config-enableit/k8s/kbm.obmondo.com/argocd-apps/values-obmondo-web-app.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
