apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oncall
  namespace: argocd
spec:
  destination:
    namespace: oncall
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://gitlab.enableit.dk/kubernetes/k8id.git
      path: argocd-helm-charts/oncall
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-oncall.yaml
    - repoURL: https://gitlab.enableit.dk/kubernetes/kubernetes-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
