apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsmondo-staging
  namespace: argocd
spec:
  destination:
    namespace: monitoring-staging
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/opsmondo.git
      path: helm/opsmondo
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-go-opsmondo-staging.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - ApplyOutOfSyncOnly=true
