apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8id-pushupdate
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: obmondo
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - repoURL: https://gitlab.enableit.dk/kubernetes/kubernetes-config-enableit.git
      path: argocd-helm-charts/k8id-pushupdate
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-k8id-pushupdate.yaml
    - repoURL: https://gitlab.enableit.dk/kubernetes/kubernetes-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
