apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: relate
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: relate
  project: default
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/KubeAid.git
      path: argocd-helm-charts/relate
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-relate.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: deploy-relate
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
