apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tigera-operator
  namespace: argocd
spec:
  destination:
    namespace: tigera-operator
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/KubeAid.git
      path: argocd-helm-charts/tigera-operator
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-tigera-operator.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubernetes-config-enableit.git
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
