---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: mattermost-operator
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgBB0Ihml4lSL/SJz3p44Cenz7l0CHj3ipgHEpflXQ2MYP5l6la4X4upIKT865x3l27z0AbsVy6/JaXk6QYsVQrLo9EiugcB85pJUC/5vCQOHY+41IalaHKAC5Zmi+Dl/jLvcaZikL8zJHq/pfa44jRoFXa+YJpCd1KiYLkRYqJZ1PxTOMaOgQGIE7sg0omDxfL28SIQVx7RDqm/MU8/BKe2UzxNeTQZHyuWtfFaUy2YvBHA760rvxMJ245VkaIgRugwbkYnqIzvxllGeFdJ4kl4H5XE7OL4IW1BajLZiQ1mDXZ8oOMAyyi8mlss883a0MoUO2XOCu8xbRwdiNOetCcSc3FW55WLZF4LdIPkJyAwZOr80ZPLwuCOY6+XmXm4KkBBR0tlF41u0h9tDa0pTyOfecjwEsfN2HqAIvhj1ZWgrRcGghjmM80KbjqlB4TbniyyS5aYz6cjL2+7nY6USyPNEKvCngg1kkJ7tvVpD+jeM82qaXLn/8IIMI7jx6dm1kwogtZ9mgolH8K4RQF1ofYHZysy9/sljVR3bKspMvM78USVNfm7J52T6JQCEhY5ETrDT7JmGKj4qhZgsituO9BZDGLkVNDLdVf+sFefc3XHipRCTZEWjEl/3h2V/cFIX4xPrPQThZ0nTemp9sm+kombpW7nuejmKNZZtaV5AaFNgwdbsDbLN1EOyZEw0liPiGGQJmYtY19rdCDbb3ErhacKrb4zND0g1zFvPvCVrjT90Yv+Qktqg8E/3W6yVtfIMvtUaOri5vkpJQdrfzSH9cFxJtzFp60KkumcXirxeSz2//eJeLwKdK/NzYZOK4pU2AnASEURK4VDEoeeaptE8YyZDSTP5CEB1VxkD39yzQGPfof0KLxGyUvlZYoKffJt
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: mattermost-operator
