---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: file-store-credentials
  namespace: mattermost-operator
spec:
  encryptedData:
    accesskey: AgBtlhvNYyIy8ObikFRO/pXtaYvmYazzerjO8mp6KnHN3fT6tmZ7upcFZ0ViMEBd8KRHTynJV4u9ASZa+C6jBwMJ0lXuRP5b1yBGkQjBdceJ6PDogiVJHSRWp4U8WqD5tG4XiE6UddjSFzS6RlzXACbHDhdm7h+J6eIsZWbrur2l7mSz4iYpd49CUgxl6UGkK07kN7Av7e1FXovVyRJeOv/0cioZg4ia9OiunXYdkpqMMlJqn2hxu554nvRbyTqmv9BX8SPt4Xk2ZMG2xeQAR2RENFl8yx860AqoGxfyC7c3J0qaSueIKTU7DLOSQC3A+iKqw9OO8IztsGNmkmk4CtWrLKROyjPUPNgq1mdcHsxi0FvNmU51J4qpZjVz4cLU9gu1DIZcJZ3OT0Y2PCO06EiA89CvqWQc+GzriETEyM3rAPudLRHNKa/azRHqvrnwteeWG2FEBajAR7c93e5fSF1LhtPyAT5DQ+yOHe3vSy1eShoPeaBgK2ji3xIZpGUqCvLtL40aCk7Ur+errNrW+mJMAf5Rd687FK8tMTw8Qnzx38dFC52idYGK+aTPMW2uLmfmQLduubIzCBBSyqbBB1Vw/yIEHeK/NrQBiyv/h9vHGEDCZ6Ukcvn7mtctelk9LPqJ5a2ZHYzTOjDRfmoLzfvpWqjCw9z9wp+f+T5fyOAmCw6wQoD2v3oXDp206v5A1DBoAKw=
    secretkey: AgBRL85BMoo7wSD6Xy3Eo3cbdKKlxo2namgWzymV52Q2lmPN8VVIsiRcwZOyAw/bhtChXdZQjUYJOO08h14q2bvRR4l/EvFpHiGp0sw+M6FpmhmHapaUIl4Oo3KzeNKATlrnNaFlX1/1R0GYQbVXrQijgRAd5H9RyNoq36tvgFfShmLzvZDmX0Jw9VQeBSotxQaO6e3GIYk7+UwEw1jr3o76YCwNNYJ1JAo/wvx52CQ1VrnHTbZUyA43AbFoVf7Uh15RojAIEYpQ/yJILK0MFV7kqKdqRgoJqdrBHKvbY7UzJvbuMiMtEM+wxoJbIllbQevXCAe5K+1WAxKEsTJxyETZuhtWh7YXjjLd8nSx0XwSb+TByXjlNP8NLbfHhW/9XSCwk0YKv4TyJLxz+Tf8665rBE8YDA0mnGgYsGZz9ytvmknFb9eBhVZqZT5tKGAnGr6f8QnKVlE/jnVuxJHbsSnbXy7pt28hARJt5lI4kxT2R7FHUKrhnxl+Xp7DrptdCsxIs79DYE+i92TviW8HtoQNyEzGELC5BKnsnxumcaJp/w0e4Ane5cJG0oFd+dk9kA+jVPuvQdBczu3i8VPQdPNQy2uyUlG5Q43fDgojPiwLOc3jGJHvZoTyjegSfhKEADi93ct9QgG10Ug+S0Fbu6cJRrA/3vKUIGtrfUOf5OkmeIhZz8MtEOvWP/2tQBzTG5PS2krvfVzutb2/ADOmTejixPKPSyvGQoQ=
  template:
    metadata:
      creationTimestamp: null
      name: file-store-credentials
      namespace: mattermost-operator
