apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-runner-token
  namespace: gitea
spec:
  encryptedData:
    act-runner-token: AgB0wrHLH3zc12QMw8aBaDO+3P4p5F6YF4XVdFhAF4Tje0J7vjD4reqOXbgnoRnlagQmdtjlW4/8h33qtGix9Bib+kmzHGeBcv9lmH1Uln9Vsm6I3BK50AS8rwyPDeWFBxE/b0kNWe/EtvMz44P6ocU4T3peEbfLMBzN8mQJh7h0GxOyNFfG2KD888dFgdXWm+ykogT01Zz5tVF8bmHg9UlHo9QEE+szoVt8YcIHsserd47DJHyeCA0UULsyY1FWW6cCLIPQVqYi7Xw9TKWE8TR1pqVsGaVuPSTu8UIPV+J2uj5NgpX/aiFFq/dUo7VO2dQvwSXQ+CtfBqhpq4GS2Wze7eDV5cfOo72WQ7MBf479mTrNXPSoh1/aCxldt5+4h0drphhxMffjxXBzajwM1V4Q359hk2YqzxOxCXwHPqQmaGhj+7QdV0qipl6sYClRZJYmKR059uaEzyc6Afe8hzgtE7fkIy15OxnMsX+U9A0Qfu1hZlcJ7FvpyUTuT7rfifgFzhGoSGTvvNAIIoaxmHknJ8UvgLSFASugraVgG4gDS8mPTGLtLDj2sOe84xsAykGAuf9F9ONBeiyqai+ubM+M6XXZfPtTwRaAY72RLMkuSJ0O+MF/brw/hh6MGj/koZQXffnIKjm0sqPtx23By+BW5PWqRUVi8pCk+gSYg5HoQ97torq9kOJc84mE0SiF78H7+7htpFVDE3ur7FJdf1W0i6md5ThER2hlpuyfEFa7j2NjU5ASbOXT
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-runner-token
      namespace: gitea
