apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloakx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloakx
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/keycloakx
      targetRevision: v1.0.0
      helm:
        valueFiles:
          - $values/k8s/kbm.obmondo.com/argocd-apps/values-keycloakx.yaml
    - repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
