apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 29.8.1
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: kubeaid-agent
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obmondo
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/kubeaid-agent
      targetRevision: 29.8.1
      helm:
        valueFiles:
          - $values/k8s/kbm-obmondo-com/argocd-apps/values-kubeaid-agent.yaml
    - repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
