apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-team-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost-operator
  project: default
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/mattermost-operator
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kbm-obmondo-com/argocd-apps/values-mattermost-operator.yaml
    - repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
