---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAj9Nz/C4+9TI0hmlCgCk1CQRuasWYbnteR9u3aP0oEpnYaR33wEKrdxiEW6ZJdbzQ9FHQhKsDofMxQP10i7cSEUjULZjFQckaevNlKIv0AhexW+M1wqTZBHYO4OgyRULYOlMHPeqI+q0GBWt0MH7nEftV6f+gsWixFSjAlE42W8pxiCRLdU3ZgR/D9XUFB2wa6GicISBxOjt9WDv/l5v+IjRGw3snuN/qWDJ5cXBa1GV4NcQ5B+brL81esBSPAntlFCgkY66Wl5pTEax5An13NagDXZ9UFhdlZYYo2pmHCzYv9hm7OrFPBzM8bUHq865u3qDKvexR6dzeYN6Y+Pvkc08q8tKBD7rx3BJEoBtPumpfTFzNbW2WO3hC5CAT0ikv9OK3zOZmLW3bfLuCIkNvZOF7KsX4xLUyFCFnbNkfA2WaHJ0GXRjM5oTKF4a/TinEDEeq6oYhSp+oCmvOJHDcC8nPr80LwWLB+mTlOwi85yZzUwZUMTpiwyN0r5BpM/AmFgWFfockKCA0mutOKFkna31Gmuhh0zn+UY07Pdk+DYzkZuxgEuGrVH6nsw7FpwvDFdNDhnCyT8rwZE6Ahp/W8RCEAjoGoLvd0I022EchJIhbu8nnd2JpcRlanK+5LJ1CikD49vLR0ZJ3QvL5fRk6OO2gquM9TYTfZYZGU2lLlL787tt+sSa86nD+0ZJ3RH2NtYW+DBTXCsd0nksAp3/9JO4gEIp+USzXfeZKEsXYYQdlJqy0KF0xpPAeXCTYeqKgB3sDbIR/nUnFTbqwVqx0W
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
