apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBt2kuGHQUM8KEyRsv2zUjXN8yn6CcPClgJCFcmGOSvlXddd0aqiAOUgTGhZltZK+8rYUkNPgW5bDtkpGoJqX8NkNXrYLdVGHqnxaXRZAhYprNcf6bIq7a1EAXTWqDzNOkrcBx5zcCIOF3DDA3jTq9qm1cIEGtlO5qdOj+qsXh0+ysgZJbM0aai3l4Sw4iBMMxRv4aFUGxx4YUYB0Yxy0lqlPixb1/j1MzkwVWVPxmbXGIzx3gz9D+ANPTJNEsSoDrziKUq9PXpAEbhbnydQbttqULPVu4T1GdzrryKwS1lWZiwpZQhlEHVtRbRfw0id7uUwoz28v+Eu+uUMHWrPK5iB0GaIQSkdor2csUUiAA1KQeCNgDeQ7GPOWZVLhsdotf6rdjOIdHQXvaqEBVnNIrIUt5p4mfKHOyT9licwqRdbYnTedQLJBsPwV67fuzyLzO8Ekn0ps6/VMxSsyczBKoPgiIulfC2FiW39GFlQoQsLfoZdgjrRBiy2YtMITM12i+u8+dciE97/DALxXXCC9LRJozfcYkh63SW92lpLGb2m89vkN6z41ETL49r6MGMwlhhl5oszbe0lBin+p3gv/4vFTxrAHmcLTzTC79hg2Rqnt/P3oF/VrwVB1SD2RthsLflKXUMr+eRZ0mM1pHUHJ7Bi8Qe6a5m3AQKcSt4sTTQ9C47M/t7s5jR9EqjIoEuKX9/1uOFp9g/4O8pggczuAQXOdCgle7hl4sddrEI/EYpg1c3PYAnpiAgTONIYPF9QCxQEKRTU174jZraGtc/IttmQLeZ0NDVz6ZciHIwAwofeK/xvA==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque

