apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCmZp8lwqXF1N+pwtAnoh1y0LceAythOY2l6oa7ZNnv/y/RtRYArnyIhbWvgOGHYr/jxweE7dgtsogbWg2Nvnl6AEIddIcXqzS/5of3dblRF9iBNU/A6aw/EfnXdi8z4gNVloqaZKos/H8gGIDQqyw+fz93jyzJehoVrBlt7N7iN1DK/LA13iAjZ9ATuXIJMxUxVSmQTeIkXnA9SEp56O1xNz7uusUtIkwh0W+/DNQ4S78JXCVmZWxRKxJ75ixgWL41QMa1j0XfprHDXIb05xJXIM7nPAZVD9+a91+7sHIcXNp9rBmrcLf+sJ/FXaoHpj1Icg7Lf/+c8ylA4tTVX1vYwTgz2R8+SsNpzkbsijZ7QeU6+P926z7S0OwO+uar/KBkPddCy8E10puHb50sEuQxKUfpOSEQhkFtbr2Y9r48XDGlqmXdRYDNN4/bCfmGcer7RgNzGiCzMmgUZflOMWNUwnpH/ERKmgCxbohTVdJbykJ9Qv/uNNI3uMXohmq8EjSaZ2E0NkLP7Rr3hLimM9gwV2EvqPQHoeG6uLxlwgYbKhTZ6sxNC5aA303V5QYRiDc5rlhwOwzeKC+P7+p/b8oDx7KpXb96txm1w9M1B5krfxptNr+Txr2ZLPdbPo6RvSHeDYW+vZyQ8vvxmvAA4juOUIE821ukr/KZULasMQwYyto7oUPdoO6lJAscqwJfw+7CJje+Qk026uxX8OXz44Ctiy8hoZ0nEzXJF7+doHLr3DAz4KvFwY9UP55KOQCeFbHJfl0z8R+N+fg2fDWgvCLz
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

