# kubeaid-sha256: 97f06a4f7e9cba3d35f9954eb4e251816ad6001d44579acfc3ca4ac2da7126a3
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    robot-password: AgAb/uHX606YzFJ6AmofTcrb0gKUmbdkAludayuSa9QNd8TI0Ps5XkTNbrTfq1KFy8LMxoyAddXcrmsa+z3uE5FizLHZvNgxgqm23Z5MR5rFSq0N+EnDmF3o/gBFyxsxvWd3KIGuiv7znbL+UunoxmH1K+yy4ABB+GbrQWrEjpMq1VTw+l0f7LcUw65xQbpcT7j0qUntT4MK3/ioM7iCixIs817vgZtylWPFst7lBTqI3yFVRcd3fuBzypg1NXRJpZR9I4VQOp5cAIjgC6WdhN7hRbchqJjNoWmqMvrkWM06FbsGJGpOiSLmHyF3jc8YYRMeq/xUQzr/p4rvn05/WoM+4k26YY1oBi9y9217DjH/xzRzitybJOlGAC/xUrA4Ntd+POWyw+OgHwR7PYzTvtWg+lvgOIfmfcT4QDWdzbA/AHhLib5J3bN8TVAk2deC6G0fxBhooD7syDN4gEsO4fovjcIgfRDbT5VV/dXGpAVJ/1AlL3t7m0gXgKK0eLlIoYysOKvLZOEcDQdbg0H2OMiVCpjfOQpHYiXiwykV4i/FfRgY+jgfAg/0f2LUSsNjOpg2boekfrf3UU6wBOcV7nk36OO1Vdav0P/k/Z87QBl6GL4Bd3aJgOeyCx1vTIUsUznYzgoBwhAbF3jBOyNyRHpe1Bu1ia03HZyiMOw8uZtv1te89J6Ek0fJjbXgHj89h8hiRGE00XoeEUM4Xp6fHl+nq/dGkA==
    robot-user: AgBeanVnKglzelj1ThzAMni1cNRkc1WAehJ4HVI+kAMkPCPPShhtvVSZ34778wjhQ8GAs7OflDEQPPlF4quYbXGz6VxIjd0F1qZiKznNhpVhJK3BaTYaXYsEKbz+M8syoEFMrGZYlsLJSnU+QDmk28ExoKu3pH/gje6ibUP8/5p9ZUuPQ2hPg8TRFIeZBshHvcFuWogXFF7nBVMc7zzkGlsw43bzPQ9VQAYoyeB1a4E/oe65+s3xAS30hddYMXCSEZXhzg8fvZM/xtdEBdsMUO3tE5V0gHPBKtbqNSU3Bb021VCVAJFq64SbGgNbVuL35yZJG/z/wZ1dvzQKadhATLzXUqa62FTqjiTaMgOeHv1TWJBOYRzVQ66FF1cBOjW8nSXE1Esw6SeZkE/zWl1INAJqcFhd63JK9ay/am+qA/6x4CQoYOfdBrZmja7otyitYkC56xBnCth2G+d4y6cdT6nzK26azehc2ugQ0CFItj71SfiGliHQtcfJYJk2RQh13tGzUOWLkxV81modLlpKH0OuRkbT3jYOWiFmv7ZU/fWPBBpnf8lOegI6ArOsZYCuxhlvBN5/VSHQjyzpSNbCB2SLk0qs1khUZDgkRbaDcVGLYyBNzfY4+9baYPrKBTbUU3YAOwW76ZrzyStkcQjHeCnZYm3SLdPrjWeXGk4j8WAjEOZYNHV7m63HuRVevCC6Wk55DVmWic63PvOyskA=
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: cloud-credentials
      namespace: kube-system
