# kubeaid-sha256: 02624cf156e36e5054d5bd6bc6177152244d22037638828aef83144ca72f3740
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBs4YOR86GV9VR8o48Uc9/mAMItoqKHoxOKIoOS3jeDagTjLo48Ty8FaZoQhslhMgjB7MoQ0RfW6ok2CkaCkRIIr/cJVN9d1rcbvr+6xejmWmB3FrcRXVrAsdRG9ZteeUc0LXgsxiSx6mV6LujXJ7LuEuWPceB65WaCEk6t20Dy/sloSHagYFU0j1d+8gZ74O+hXnMWpIErMTstns6znUbUpVX61Iy4sU9vRzlSEjTP/wmK7FCOp0NfKVJaqVtZp2lI864GfzEEnFQeSqG3D1sGMgiO2X1lp3MQUblcnKYSgvfvLkpklFjUNjo5C04vyPCvwEoph2FK1JV0OP9e3rohi+BApDCZrR3C5EJSZSKAZN3fKTwpGlhvGUvI7h5ev1J2fpBOnWZYUxD0Tm42K126ZdEMsXqE0kWqONWH0TwqZXjmJuY9trIXOr0JnXm14NdT7ZsVoylOUpN2tSn2V0HgLA+YGSzvN3sG8F8Qhb59k81Tu+e2KxBtSXD8E5wwK196O7dVgux4M/2SyaxGn3tRR9HgnGKDsR/57Z8lch9s0mZoxcKhBslksgEuqi7KRggfNUuZjV3Fvad7n5uDhssHlo9JvTUPWeLKim02qxRnGKCLnQkz2PCEi0/2uzyolJpVhG47m6OtWPfwmcyIKG8YZR1kleeQ2jx1WAR0Lb1xJ98FnWozTU2GTEo6DxWfV5i0hD0xNtVjDWilNT2zVtJKKiG8GNH4U0LhyLFTSifqnUmDLw4NEYQNxbAfNGtxymbuR/DfzTvAqsTL+svXCT4M
    network: AgCHaMN7Os1U0riEcxrfabxgzkb4SzhO0s9/pEXgiGHu9xbDbE+A095OCYd5/zPNMRoid7fkVBsC+sB3rJrVRlnZmfEqV23hNXd5FLqbBAN+YK/42RNQR4ypgYmP02KEr670x1uxZli3VRLYjc29V2I/tegFiXQPIGiDTz4KzRD2FIrzwuU2mVvT5mK2pEZtaY0I/ip/NUZCSZjFgXeELfj4Sd9OxG4nYUnwlweRBZHKJF2oNdyNPxV4Bp+4QWdpA9KFsNTRbtYCJOg5f2ROWwI+u+z1MddJLpMlwEK+2NzKza2PYv06CU+TvxOWnnmYx1b400V530seDI8PQxEg+ox/8O4owTX5JsjVPUm2p9dTr93yeoIsTiaKoFTxbGI65x5fQCjPle7gzRrLiHf5xmpguCPYQJR8tqkjkt/sLR8OKPb9fycmP0Oj2be3kS7Ldq24Cm0+yr+dPIqabgUT/gGwD91RGtJHE7cp8MiB+s25e8bb+WYDhWLhQ54vJOeDF8NIQbcYwTuDKNa+YjkzC4cZ9WP7+XHhT3NX0XsJWp9GIIxI24mPXLXCkSZML1DRo8l3oqnBizMJ3Et8mC3Ow+qqXA8QpU1pi3NgNa0De3AGYFheRz3+HPTmmLb6O6mvsLSNXByl8f481MbCrN7XalX6NUMhSCmNYNB7z5BlyU4R+S1pl7I07qzodU7nBefusifj0Dv8i5pnJk4WHZmyLXFkZmr5
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: cloud-credentials
      namespace: kube-system
