# kubeaid-sha256: bb3798f7a7cc141416d157931e0c0a07c24343bf1e6deae3785a16fcba1229e0
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCw66slYZMBucAstfc2pxL5JdCcINPur77wbpUv//p1HXJiHGHBFXB/MO5auMmzpqXEJBJbPrBVT9eCd7ONVHXK9HXG79R6O3ejHlB+CFc0JJKFSXeX+CgudNIXMr+vQqc1SDhamqlRLvkELAWqgWuMPu45Ic78sWUxkHBeKNurKtZaa1c+Yh+vtcMlRyfomF9xaUv5T8rIfDMvdOeZK3Q1OuW9CX3kzOxw5AJqC2VyxX29+upRreLkm895rwVTtp8nKFv3tImvVX138eXXmlKy/lOQaIv0ocl2ZQPRULGLnURri1TDUBoVT73UPrt8ub4aFO6vrYMk9sejaI1S6Q9tUcns+0nyH+VWniNAHDFbHh27+2GpqhxCRQH8uneRssMzLZXyTCFrICSp7X/kC0Pmn/gQmciqeyloFQupbNrHpwvXdBxlHI3KU264onAT70uLjWUWlJjowAObnfrN8KDqJ3mgVR+gejGvWUDiz9SO2oeKJ3vsSx8UfwHExHlGkAmqGhXlPANKB91EUe8AiUYwLQYVX3583idNMGqkn9t+nztSjCOnFbnF58DzFBzgL25VjkaTq69II+gvKgLDQwz3iLczi/N1O7sYuOm/Bv3aRzRbg//pSkSNuFb3hejMHrAXS6YRa47yy0noilvLhyd1qFlF+gBTvp4xw+E+2rpyFHdr7xyRz5WDbg3PibNIQ03ARpNMPh6LAtkrGAd9bVAQF1s68tVI9mrv763o8ls0CK3JsIwPPQakdOlFnUlvvLF2548WQM9lpdk/5YgX9e9d
    network: AgCr9lHwcIPRorQ3quypoZWccjo0prQfXmIB9cdDn6rlGjs11kFrURXW9pvYgwBlfkEVsXD8gBO2TDkE3MpPJRLwi7fVXyP5AGUj+1IJzoQXizFBeitAM6lvDD7Iz8ug7qwBw5UeDfc5Yz4y8/Vmg2YvSSEyfmGAEHu1nicFKz8iq8EVirxa0tBHSc/UT83g6rrK+2fjpdiFohyPYkEKFSjjchERkntBazIJTiz+mUngunrY8yCvSomM8X6yCSxGrM2sbHB5RyAEty79Phukns3y/WGRvO6DQ5LYsOJ05oPLEgXeeLWwFvQ237af7f6zVT76ISCWaMp+u3HCeJSEJXNzudqUqEewg5q3v7nkJdT9T6A15gwx0B9XWxzTaGW7FkQzZMF3/cVRwuWd2FK46svOHwVWjj9XH1OGNm+8i2W+wlnLTyLS775IwtGbTWwgMCE33AzeQXj05idDxz0UHxoxnFNYM7Gk93K/paBg3maoqWYPqGlExR3VAcF9SrFuK9px2zDwqrqF9q9HPTv/K7btnJ7o6Paz9vw5sxDLfr+ZdqNz099Cqez7OZ+Ioft04I2JIPeOuSgpt1qhWfUyhgUiawp1HrSvyVZiCSLws7fArcMAqhHAtP3z/kYBf71SeWK6Yj3CoR5YL0+B+tzCAE82eDpxALC2+X/XLemgcLK+z5e44TEU+GSPj1o6xKR9n3MGYA6lYaeN4wmteznl0sI94ddl
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: cloud-credentials
      namespace: kube-system
