---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAQ4cxcRgWSbDZukHMoS0MaW3gqXVSsaPRp6m2P9fKRMiM0JdOYt/hrqgv9hlAEkhkHRCQ9v2lFr2me2fz9KRxtSQlcWVwwfLItHo9ePs5ilrTGsSEjLoWb/RLnKWtDm5OIIFOBwPfZADnrq7sC96cBVsXnWpDc6E4O1F7Z7RN8zjxNj6v8dvGp/lUTmZsjTpUYLmQjXsOQ4XgayXTTh45qVfOxeKOPe9iVohcV8bRtx4l9fxExL0jYUIvGxMyVLMhBOgXSxU5CdXxI+aRu/+7seFNxelpcVrNf4zIiokSOcX/P1Imm0wBNqqFP7juYTbqw7dmCu3PRaB9ZnUwwZCExpue7Lk0Xm/wImN4u0PM6ZXbkWcd5VJ6qweksZKpcgwHb5rmm86/NQCLqb4i0jkZaQrhNwjRI0IlD8vLXAp7l2pM+/xisWMxgsEn157o8yzaE203buAyBIKYBLCpttgWqUnRJ++hBdNcn6R6TujMCmpSccfUa2S8o3CPGTCevXbHClXQ8RQGz3A432jTVAiw1WAuBwLDAsUPbuHvOo3pRWNwytJ7RCCT4eb2sR0H2Wnsw7x0NAn+LO5QEIhctwt8Y+BFCQLuU0JvfCy0sxlvLI3JXsRMB2vUTLzLxCfFwhrhMwlusCMsjjEMlGL2vx9AvQpQkmWLbjQuZ6zg0x9XaqopP1meDt3Njh3Zbk8T0eHxWMLFjiORV6DRvHLMpQ5Lbd9/3jM3uFQlzgeiHLKBsUbHgvpN/Ergw/xCQk5erbi1xoi5F/xsSyzsGwiKfvCnh
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
