apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: v1.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: kubeaid-agent
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obmondo
  project: kubeaid
  sources:
    - repoURL: https://github.com/shubham-cmyk/KubeAid.git
      path: argocd-helm-charts/kubeaid-agent
      targetRevision: v1.0.0
      helm:
        valueFiles:
          - $values/k8s/mytestcluster7/argocd-apps/values-kubeaid-agent.yaml
    - repoURL: git@github.com:shubham-cmyk/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
