apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik-internal
  name: alertmanager
  namespace: monitoring
spec:
  rules:
  - host: alertmanager.kcm.obmondo.com
    http:
      paths:
      - backend:
          service:
            name: alertmanager-main
            port:
              name: web
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - alertmanager.kcm.obmondo.com
    secretName: kube-prometheus-alertmanager-tls
