apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
  name: velero
  namespace: monitoring
spec:
  groups:
  - name: velero
    rules:
    - alert: VeleroUnsuccessfulBackup
      annotations:
        description: Velero backup was not successful for {{ $labels.schedule }}.
        summary: Velero backup for schedule was unsuccessful.
      expr: |
        (
          (
            (time() - velero_backup_last_successful_timestamp{schedule=~".*6hrly.*"} > (60 * 60 * 6))
            and on(schedule) (velero_backup_attempt_total{schedule=~".*6hrly.*"} > 0)
            and on() (hour() >= 6 and hour() <= 18)
          )
          or
          ((time() - velero_backup_last_successful_timestamp{schedule=~".*daily.*"}) + on (schedule) group_left () velero_backup_attempt_total > (60 * 60 * 24) and on () day_of_week() != 0 and on () day_of_week() != 1)
          or
          ((time() - velero_backup_last_successful_timestamp{schedule=~".*daily.*"}) + on (schedule) group_left () velero_backup_attempt_total > (60 * 60 * 48) and on () day_of_week() == 1)
          or
          ((time() - velero_backup_last_successful_timestamp{schedule=~".*weekly.*"}) + on(schedule) group_left velero_backup_attempt_total > (60 * 60 * 24 * 7))
        )
      for: 30m
      labels:
        schedule: '{{ $labels.schedule }}'
        severity: warning
    - alert: VeleroNoFirstSuccessfulBackup
      annotations:
        description: '{{- with $labels.schedule -}} No successful Velero backups have been detected for schedule: {{ . }} while the Velero pod is running.This likely indicates a configuration or permission issue preventing backups from completing. {{- else -}} Velero backup metrics are missing while the Velero pod is running. This may indicate that the backup metric is not being emitted or there is a configuration/permission issue. {{- end }}'
        summary: Velero backup has not completed once successfully for any schedule.
      expr: |
        (
          (
            absent(velero_backup_last_successful_timestamp{schedule=~".*(daily|6hrly|weekly).*"})
            or
            velero_backup_last_successful_timestamp{schedule=~".*(daily|6hrly|weekly).*"} == 0
          )
          and on() (up{pod=~".*velero.*"} == 1)
          and on() ((time() - process_start_time_seconds{pod=~".*velero.*"}) > (60 * 60 * 25))
        )
      for: 15m
      labels:
        schedule: '{{ $labels.schedule }}'
        severity: critical
