apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-webhooks
  namespace: obmondo-website
spec:
  encryptedData:
    gitea: AgAd9LuVbCRd/o0gQDyCPM+5Fyq4RgRgQrJWLUoU75edXL/wAYhKq9QY64ia2nG/cwOMF5JmhYxCXZO6jkTAxl5CQApWkIHOHcXz3DEP8cnLiSvu74anc2MarwywfIN7judqNjPw5PJ955xgam73yg1HWlG3LE3qpwfyrIzo8RzXDZbNPsXNSNUDN6qjKng6sScJ0dp+gPFefGSY9vPrJMtDdZFqi4O2cS7Ajj9kV6ktlbe6c0xu4qtmSK2xray7MYlWdVCcsSlfIpzYaDNTvdUuPDTYoMOa9pLOslfDP/QQ6b7FNGAcyxDz/cDmwhMJPCmXMGlc2nBp6cTkREYOWgrU3Q3+hwu34NlqvIG1350ZBTzRDMuJnG3MTARf6J7rjdD/Nc9ZJJT6Avuud4ivBpeHj9bPUI3BbrQVubrCm8zuzgD2qmL+9M86/MoIOwL3VoJE9OQXEIrir4qv9D7HOvAnSo6Q5224aT4I724z2jqm9xO4tkAhb47l1u6iaMvOCtFDdkLt8Zhsi5fV3NaazSMoDAgO+FVkqvysqrOBu3avg0FJfXUEaprRsHKinnjQAOk7xUPsuRUbPeHcvjGrlNoRq5oFSgfgmWDZ3mL3z+C9SatyjacVHwRcPe7MV8KLSlPrYRy6T5xurVrmjiciMKaRxUyf9mGlSUUME4mPw+/UipnFYpiWNzS+BYApwTXx/nfsrImKozjY5/hKkaZW34Nr
  template:
    metadata:
      creationTimestamp: null
      name: api-webhooks
      namespace: obmondo-website
