apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: enableit-go-api-registry-secret
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgB70fQGCyo5xkVJSg1QS24tio9YoDm4gkPjSrIF5VfTWmGRbFzH14VcIWWvJK242A0SM8liEsZLgShyNsHy/S5avg1y+fX0L4q9U/isKf7hDpCRwdsQdgr7hcGW+JAZR9d3QaZCaGY2x4FcgEON6gVlFHOj81DWWCNGK0XsH/YHiv+YlIpv7YbKVuSQYekEUP03cG4wCEcUyldoiVJvKSwQIZP5/ERU/OL4Q9YiYSxCpAahyLf3Tm4eMbmLpx6PV7cTft+4HjRLPM5S+9iB7t8rOnKNJfzhSvuKa9Ru1Brp+Lu+Xj4/s9LwVMRkQRx6G2J4sYO+LtozGN2NZmN6Zey14MM+Xb8YZFq5WYT4tPcCFnpajlEyk9r2oLykYLpZeD/rFoUY2LskRF6w2yDzeRs6M3Xzt5hNL+EKFiCtGzoTEmjRkznjPG+Eapl4duZiQoEiddlE7d0OBPYAOi8k8hvUjsPhCIAIPKYHMDGOsOY/kvpUjYAZvrXRc8Z/sDjJtN2NyCMlQA+ed3NJfXvGFGKcNSAXZVBFHFCREwg0/c2v7QZVRQbaG309LiHs4757cyfYdtyl3GFKIwuABb7vC5SbpIULsCl7wL2N5kZI6vpObw1JKFQLthR9L/Bz7bs/LFdLVTLmrSNKkKZ412K50IVBw+c5qGWVQ+uEG9lsuJcWJPUVJ6FlbR5ReGfB5+m3GwUj9NYj4vpOTLCC466bWvNfEkjOpJ2R7qfPGqYA8QE3psj6PV40bbLRtqqIRctGTkB8+KRObyrG2cHZd1bywtea4tAuVeuamUCdQRXiF7qA5sFQNaKqKvgQhd8EHTygsQgIj5783eEqZVHUPwoKpE2wp30Widdxz0u7lEVcm07G2o2lRZUGlGJ4Fn5fPDeFXKDiMEM=
  template:
    metadata:
      creationTimestamp: null
      name: enableit-go-api-registry-secret
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
