apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: enableit-go-api-registry-secret
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgBpZIQb6tR4szGu8Vqw3je/u1Qy3viNazEPnvuDa/fdXWjFfhmPAGOaLCSplXIZfY3a/qc10dla4VprN6Z561YCt73K1yxZ6jDafu0mwYIRYvH294r+tVd0DLkVQM9Czdclnrbz6Q/LIXQEgvKTzWozcNLDdXqXV/Hlh6t8s0KPpDhxAH3eHQRiQQu8ZIl1VWmtjFNi/GqyWNhLv5+k/cqJo3dM/SwAamHJzLBlAgTRCW5ZlRksnpx1m5HL4lAsj4IazlBT/8DrrQvQAfWQ9+U8mldKt+FWTUNjamsHNKIdn6OiCnhwdw1giQxYOJpliXb4woVw0LqR9sijrVwMseST+lymNI26LVz1tTSGnyuBfARlwZ3Ksr7qFZZi+F2zWxgrHujf6GBOVhdoKyUq6lpt0QB3AFiOtPflyenG6YG26XT+0tGIkVg3Jq/uivGJsRMnD5HmjfWk/0nUXpP4Fq53YisAKfyJOPj/e42K15olF2UrvhMvfCo/1eHDeUm7drDmjOIwrOBqlfxxUpMhm9+9icX3pNGYveW7AeWowSE3SEQ8j48/ZuLXw3jBrQ3GrAHVp38TWHaT6DJALLHYdAKo4pOWABhzrk6z8nyesvfNFpJlVdZy0WGpDLS/+gBxxmNAcjkxl9TMmomaQLUGVOfUCngz7c8skM57mzE0XGhTmOyE1RvgNwMSL/xZ4qclXdmAN/zo0iUe65q2qiZYbYlK3xMqkDdjAgtoFqibaXMoeZl6zfzC2xfx3tYf4AS9JX23C66BGj8mICULQ8YoEvz1FIWEyyT3nwQPP7gOjjK63GnrHVJUWBTApwWpj2lqCRgXzFUy45dnoilrbQpwDBgQnq+DCRaoJ3CASiMtLDT8DNcPqPIKjQYW6mCZoi8hxGX84IwIpCo4BAtUnjY/V35UOQGF8gik0R+YymIwIVNDfQ==
  template:
    metadata:
      creationTimestamp: null
      name: enableit-go-api-registry-secret
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
