apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: go-api-gitea-token
  namespace: obmondo-website
spec:
  encryptedData:
    gitea: AgAibAqEeMGnClHDT49TyQSoWdX1GhL688G699Vt4NBn2x8sMszvnkh6Hi3OeXbrHo5f9Rb4h3RBTBY4YR+sDu/AWieLQrgw3m6+Q5bvEe0MWBNCrkIVL5jT4kzOd3iYsb/OUm5jw5WsVAVWUGE6IdQ1dvuEFVgbrktSBaI6FYGrRkIQQUf4hv/lkBw/VEquE3q0wut3/cuQl/aMKkLtWYLG+yJxIjPlFLAixiyzFpu8XhkoNXrP8QVIMVRuqWdTcxJlsoAlfpqMMS4IL6iZUiH0RWga/XQVovQtu9bD4nIo4OlPE+E4ZQcMAv/SycT18mNsVjiADOxf/BZFmAIJ80zglbdHAdAn7MR7El0VB+h+UTAhokktJ7NYVFrf/CcQDpm/UVwflriiLyA5SROCj6CfHSdmaELFTVkrxs1kScdOneLuq2/abrcMDG0CAr0TU2hTwtAXQhTH4G9bBGcVSz6OixpGkIqebeIlbnwucY/rVICjBhJTWuE2ncuEYTrllbVvnUVzuTqRrabaT2ceVdEsOFy+hyvJmX8VlmtcjnQvnnVrKHbSMhJNB3dQIjcER5cYGDqW1BFx3cNGZ6XmqjtA8lnQd6wow5eUjHKmdgoTisQEzfXM0Cn06n+jqN7XtinqdHKpffchtDfuvz0rGqd4W7BaXOg3dSabeVSeFKu9gDGRXTaN+IElKdc8758VlDaxZ3XZ0Ot2/N5215xlts/2YqgoxrhK//tUiwqukgJ3mFFYeDtgqQA+
  template:
    metadata:
      creationTimestamp: null
      name: go-api-gitea-token
      namespace: obmondo-website
