---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgArvf9UlkbksIgaLjmcysH1zIcYX30qWSm050q7zLqH4Ic6ZlZxCXCy//kovXyRTisS/mjKbUcOgRYMUmVPJz4rBNYmitVihk05+zse/rxwCPfPojTBQuRPgo8Y3VYlLK3nolEV4P2HOnBe9YaFfj6QDbS8NilOtn9GmDakVNFjM35rVGp80enGBxVk5HtfV4xywqbmCeCJjS0EriFB3YPtjxWxR+TZi5fpMfNP95J2sya9V0qmPrhGKz64sf9VLjovWDiwI1uDKWPPNibXXH8UAtdfmGHv9Hz0qDqEUWma8cnZKgIs7s2UvgNv8IigvslUPxx1Dkva4aqtJUSpuYdPYqPaeuYC1sDbF3dFEuyFKME3hX+q++OVysDEW0rFCDEgHXXGBtQcyJKw9zmROV8GExxqUN6EoBLpyM/GyisQGcDf9X0QOHA+EjKHA2H5bXUDG5I01Qm+CjVp4bbxNJlo6whr2444w9NDaTZBIXOqCsdoiP/UcsqaQA9sd0vW9uDNM8syrfRk3pBPBEFV2nKZZsXooVACQNwWlWHcABQ0kWcVB26xH3ebTmujgly/W8rmq64/eMAbonuSIgbw3ahcpQN+CKGe1aO5kg3TEYPoNWI8l/EtOXloFwuuf73BaQTFmBZ28l43A47xhbiA69tVJsNdR8birn978VCuoR5F/32G+3e0Amt99BvJjkHJo98KFqm7ccl77lH/jgzeLi+c3eQhtlPutzYUdfdt46P5a0FGZabmo8AZdZ7EZ33fBlfnTIBc3XsBBWVFEAZPgm5CXPIl9KReCQHr1SGPxvsboVq0XEiw4w/ZF7vTXLYWNKRujeHlHsiyePlf+eDN1tHdvAEpW98CwKOoWEu/7QfkUGTZueNg8pZ3ttx9bCJd498QGwTE0LupJeFOK2W+Ml+PWUtsDG/iJOLd8476rMZ6RZBhta5xFAjl8NxUyL6q9WPnpx8=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
