apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jwt-public
  namespace: obmondo-website
spec:
  encryptedData:
    public-key.pem: AgB/nUODTAG2l49cc/H75qYDldRe/e4rgMzsZRy22vvIK0EL0PxxuZxiaNJ8BnFPzvixIKtrd/6uYO88O2f/s7Tw5V3B2zbOeHw9nvYBknReC+o56s3Z0BPnWH9ZA+HJsh1Vtv25+QRjQdV+V9Z7taEx6M+umX94HZq+jHFVT41dXQaD1A8pWlhGQ5rOBeMG+NwpqkmdUfSkN2dgkoEaTZ0afjQIofEb36BRGZSHKkAiuR4VklN+CrADN15Fr3hZDQYR7riOuar8C1pn62iyXE/xND1sPWIzt+JXko/0aDsjfZ+QI9COVs7Okk9xpVTDEX7wxtuGP+yT9DyyZChz6Vc+Hf0REXBbqxn2ADQIP9ZjJMWzEPZs3gTW/a1zUHB2MmxoDgDB0kvstpMHfst68kqjCI+TeHU3NJK3axlr7AbpRXcgKQYWTv7z0EAO6uCd0FDsFKvhQpM9sHtTt1eqXlqiqNcNOMor+ztvwwuvuSjNUvnPLUQw1tMup+z1f6vGRN6JHx9lMksS6S0nHWsp+kvWQ8wQuW0oGdQD6ZeYgDkXTY7DNxfTIkiTgoY9NmL3Wzqb8tsWpC5gXgEApnROVH4GXPq3D9YgTt/jpvkCX1dovaZjvFMsqBepAqcUHhq/sIpCvmRyjz5odnnNSqegA3/zAg/cCgaKoGOqwCxIIjQNJmOtCm2T7uxj+Ig+43qmSqQHet0kCkCTcP0lujLlFpzKD7XkyZRqDZ0p+SF3AiAIk0K1vGXmxi9iCbz+fWZXAJjrar20O1N0OhzjExgE9DlCxk5KVRkcYjoJKG1Wv1AV0qmFQNFGx+Jm8a6P6Jzqs9a9o/vQOxjrAbrGIwZm8fdIBbwYvTZ2rjosH+ExnbOqB3fJlhnrak9QNb6z9HiDK+yC7uNVrXzQKxii7tHOTG71L0poxlcvgaaF/U70TBajbe4yEzHIRQ/Jw5Ptm84ybyjCDEAY6UfHffStwRqiQpwz3qLOjL5WmrSstuuXZnYQgt5iDDwupAbmVUa3Jj9cU1HI6i0xkVB1y6MRlBWJAvbozUVifFwjI0CXOJIiYvQ/QxDG2tP6AElpETCEQ9YEfF5YTGdDf+lyYER4d9g4Rth3zwpGcxhcK9V+evjDdno80WlkoUHarpJHH1fbEt7o1BZE6xw/vnqCFQBJQPqHIZ6CMqQZbPHIYoIJsmviniVf42dWIHmAOpNwwMSADXO0+kJv6cmy9O0TX48+JanwTnGbBY5ztukULYV9NBb5OSynhY3EFyWrwo3tyDsdQVqoaQupqeDc/o/2UaNAqUHDx1N001Dk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: jwt-public
      namespace: obmondo-website
    type: Opaque
