apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k8id-web-app-gitlab-registry
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgBcXEIgHLBlyziE5La/yZKMCopNqMz89rjeINiANXBIneS/h2yHHayw0s6KEudPFAbhoDeSDtWs2KTCEMJxxbdqI0t7HoeppUIE5FeD5F0T5UpTOyr58j2fCIeLdCYmqaDUE6exqaiKZxpMYV5GZ7HXKlrLXffGQlSL/KybPA3l349jTgD3Fu4fOJVG3b2tPDiaG3QcpGbI1+R3uvIXNiCDofPXGq2x9HCAj9JzfNJJORGOMkhcxoeGS5bbC6o56o2iKNEZCb1Q85aSOV/s11NC/eRlue0ZVp6mnpzPooXZqg2R/EmfOWpM5h3OPNJdSmL5ftFRbC8TCEOcNdqM8dG+BSPHdIlyOsAEy6JY3tqYj9jEYgSwq1TWnjot8AlbRcFF3+OYnKDHnGjF551k1MPXn4+3bgSUeZOiIMVmLSs8nfo3lHrp++3z3w26BaBnAv59nFaaC5FJLRrKRJ7rQmGE4OsnNzkvIHazcQWzBa1bZMf+sSjCL8DBCkAsPXJT1iPiSA+cIyIgw7Wey+Klnf1YTC7X/A9a6V+kABw1iFfqHAZVKl/LSgRMwTi/CCeCRscAZMxGkqjtkzxrf98C5PVJHFrrX+3YsGEOOq39IUS1zocSuJ5FlmbRx54Vymklld5OURQ/j1ng+NLcDXPqaKwmP1+Jc52DNhUEPKyVoxIfgQTaYlH8Actjr4ojo5hwDFtUgxy32FGlj9z/1mglq25GdmilkrvrPsHPjjR5Y0ycJN1Ko54B2snUDgcIGnw5Dd4I5yS/9XLKrU134yk9VvooZryOJayL/AcdcXKz8BorhOzz212E47z5xcgJ7Od03DkErohR9Dzyw2+jXE1t9iZkXJQeoo6kdnoilXjNWflRLBBG9AMouYQaVSKCI8c9U+YbxAGsQ2NovOi/3sazLTihVjYWR6gmSnEILhuSwF5LkQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: k8id-web-app-gitlab-registry
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
