apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k8id-web-app-gitlab-registry
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgAXbMVFfqNqyaywS6S4DTShPzEiIprSUFm9OrW+vpVKkRzLErs9s3cmu5rRHFSdZLGLw/MkxYsxQ54Jn9OePUMwBgXnZ/LJ8l+mF21WeLJKuuts+pw9C2372pTs42Hspw3/W6HLo/TAehwmx9AC2HQEVap8+GRYRiG2UIsA84Npj4oa99JhjiAwcGL25K9yFVHUsCy++intQVm/srbVJrUrdg2wKIkM+WEkQOntKhUYAAH4gDZyt8vyypBUn/gshci7FebVvxfEC/zcWjKG0Pk4lD4rJpZzi6pqUc5z94lFEtS3oewbat8gP1xJ2wfOzsfjJSoFC6XXXnes+CMjqGwzWl0/Pqca0dyMSCg9+KY4yVu2yqwHcSQHRx849uWiAO/7MH+41PQwR13AuFqs3O5XfqeBXx2rZSrK3ZfAhgmzeVELWOPHPTBE2xAwAGlIwG9wbAFUSNSHftnGwY6CDj+vZ8L+W2C9K4xYKw8ddcS5zcFsb721yrqAT1PQ5whzbDoj+2Iej5YtKpwEbU3xFDg2Ah2fcjm3eh/ErLf4vmJpsn9YFjYbJCWaveqDQc9gFoYigqlgG4TCNgkhaoS1ap1HoBIqjwfJ93ZEGWSLLILXoZgm6aT5uBzGebEluiPuMnje0zCe2fMv7zGjzsQx5QK+aSLh2jtyLtMDXTEMj6qJkOd6xdMza0ggZPevOJO68Gd1ZivQFKnMrrXbsTo3o3RV5kvTNUR8KG1M94XHYnaroXBFts2TNtyjySIEJtpIIlXqqD1uhwwYjxmidXDOBj+QbN4fV4FS3iJtHviaUb0k1cj8+Mr54mCJEGBksaHBgmsJ8OO73EYxvW4ZkuyOKR7OsEDv1a/83AIMlxdXN6Z6rygYUuzY6tztdhb7AdnQ0EzzDLpY69VfXVF+1eczguvKgG0lApgO+uLpM5m3Mpec6Q==
  template:
    metadata:
      creationTimestamp: null
      name: k8id-web-app-gitlab-registry
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
