apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k8id-web-app-gitlab-registry
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgCTV4quoAA6p2X94RyGmVqpTD/Kj5sfiEgFeSaIyDWEogRxcTgFx1vE8y9s88e+0VOvhnKYDR7MK9kERKeHgmyRfHC9AnOYn0SgHfh19v4Yctv9PUibE3VolDDvQ0dIjsqqvLjvPcG4bDU06qIbkOIUxtP726q4qxpSwtuy/8MSBKNjUEaXEPdFnUE045ry2zz/TnwIxff3bJ52PhcmKx6Qlqm36Fy7h2eo+grUuWyb8kIn3cbBrXPEdmfynmjXpRmoKU3Ycw8B+IP+HlapGE/JV4+srK3ppZuAgruyAU1jWGXeFJo5SDpbLOVrpiy1BKwHBH76eVew/uYFixl6KE5bjplSQIUpwlxL0XQPRvb9fnBthJd4XlemEbxS/WY8bW16twEZMTJWPnfx5hQQPEVdhwxTz6Ei0b3Fn+iQBOh64xxw0IVh6cDmvT2Iu+18u/ZZ+C49ULVZ9Pwl2QqYrIppxyT6MpbXe2Tyrzfh5M8D6+ny1Ot1LajfhKhLF48Vtqno2OULrRCGVfquu0hQI0dgxBDVi/CjuUqabS1Jp1fVxYCI4a9gN4qs0h/BfHAYLcoxMr/dMC0vFUHUAVPuJlHvifCcRggxplISWQtaDBnvu4w/iLwGjz8+akdPO+zeXWMVVyIYTrbS/57pmlP0buwgvJdLlGhLLdAxhHgIlQ/gi59PQF1ZchbUAtN4a3q3u5gzyYru2Pb4XUQWA00tuQlqEq51CNNf/0UgSeNLsTeD49PX7ULV08ri2Dqd8wFIRDZJif5vhlWubM43WKT7j73IDoT/gZH9Cq6VSJG+sJ6SR0WlsT1Bwutr0rammeWB4q33HVcxSb44eH56XivWedqfjt+MQo4KRCzNSRlXCS0zozR51wZsfa6GHUpgRd/TX+jBPPJ010nRFhYc81xNSA932Py6wmf1Jiarpr3MBOoD6Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: k8id-web-app-gitlab-registry
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
