networkpolicies: false
LoadCustomCRDs: true
schedule:
  daily: true
  weekly: true
  sixhourly: true
velero:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  configuration:
    backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero-kbm-obmondo-com
      config:
        region: "atat"
        s3ForcePathStyle: true
        s3Url: https://s3.obmondo.com
    volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: "atat"
        profile: "default"
    features: EnableCSI
  initContainers:
  - name: velero-plugin-for-csi
    image: 'velero/velero-plugin-for-csi:v0.3.1'
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /target
      name: plugins
  - name: velero-velero-plugin-for-aws
    image: 'velero/velero-plugin-for-aws:v1.5.1'
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /target
      name: plugins
  credentials:
    useSecret: true
    name: cloud-credentials
