traefik:
  deployment:
    kind: DaemonSet
  ports:
    websecure:
      hostPort: 443
    web:
      hostPort: 80
  tlsOptions:
    tls-client-auth:
      clientAuth:
        clientAuthType: VerifyClientCertIfGiven
        secretNames:
          - puppetca-cert
  service:
    type: NodePort
    externalIPs:
      - 95.216.30.44
  experimental:
    plugins:
      enabled: true
  additionalArguments:
    - '--providers.kubernetesingress.ingressclass=traefik-cert-manager'
    - '--entrypoints.websecure.http.tls'
    - '--metrics.prometheus=true'
    - '--experimental.plugins.jwt.moduleName=github.com/team-carepay/traefik-jwt-plugin'
    - '--experimental.plugins.jwt.version=v0.0.13'
    - '--log.level=DEBUG'
  # https://github.com/argoproj/argo-cd/issues/1704#issuecomment-904741817
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true

middleware:
  jwt:
    enabled: true
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsRR1/Uje+xTmF9bXX29G
      FN0FyEuxanwjd0dgv/IU4htUtTC469QJmDiZoMK73evYEuklk3zZ929hst9ddHEK
      8YVhrJiaYYojTw/qc7X4++Vxya2Ao7x3NjxKGFHYy3q7s9I4BKEFYbAL3pCXRhsZ
      +SZLZ3YSAKn0UfZ7hD538c++h58bQhSm/KHnP5gcWN4FJneZUtsdLH81a03YtSL1
      Sv0UW2RWbt7PBMTFTxhMOU9w6kceJuUvsxb8R+zQ5vKhPjZo+jbLRBp8UEaLWrax
      4/jbFyJA28RBcDkBnSliIqEFStJJacGP4PFXxDlB2PkGi69cn7pj4OdafhJKN58z
      YOFbr7ulHQJcC/MlSPFxCDdd7Dr2T9admyrdYNSevEKC9yw1cZKn2YAYInB+ghUp
      vA+0ElEt4kRGgijTKYtr0Gv4fwMO2AYTenEQv55z1yQh40sfzp461Ra3S+IoJFKq
      vUckPOs3eyQdACTnmJbvVcIykOG7zOh8+xrchT7OxLeXQPBcjXKznYmqGShavVOg
      VPx1dpz2JeYyjE722sdU+k2TpNqWWxcm8K+ejvrp9lptYIkgwn3SQuZ9q/aQs0eh
      Ot+a/7zaanJoOyi2Z4QvAhaCximlJ99KyMrwVpDV/tPCSOUaFAmz668lcI4YUqS8
      dPSNCPvcbwR3PxT+QuWQgCMCAwEAAQ==
      -----END PUBLIC KEY-----
