kafkaTopics:
  - topicName: service-window-certnames
    cluster: strimzi-kafka
    partitions: 3
    replicas: 1

kafkaUser:
  - name: opsmondo
    cluster: strimzi-kafka
    authentication:
      type: tls
    authorization:
      type: simple
      acls:
        - type: allow
          resource:
            type: topic
            name: service-window-certnames
            patternType: literal
          host: "*"
          operations:
            - Read
        - type: allow
          resource:
            type: group
            name: opsmondo-consumers
            patternType: literal
          host: "*"
          operations:
            - Read

  - name: obmondo-api-go
    cluster: strimzi-kafka
    authentication:
      type: tls
    authorization:
      type: simple
      acls:
        - type: allow
          resource:
            type: topic
            name: service-window-certnames
            patternType: literal
          host: "*"
          operations:
            - Write
        - type: allow
          resource:
            type: group
            name: obmondo-api-go-consumers
            patternType: literal
          host: "*"
          operations:
            - Read

ingress:
  enable: true
  class: traefik-cert-manager
  annotations:
    kubernetes.io/ingress.class: traefik-cert-manager
    cert-manager.io/cluster-issuer: letsencrypt
  name: kafka
  rules:
    - host: kafka.kbm.obmondo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strimzi-kafka-kafka-internal-bootstrap
                port:
                  number: 9094
