customerid: 7ejidqmfi9
puppetserver:
  puppetserver:
    masters:
      fqdns:
        alternateServerNames: 7ejidqmfi9.puppet.obmondo.com
  hiera:
    hieradataurl: https://gitea.obmondo.com/EnableIT/linuxaid-config-7ejidqmfi9.git
