---
argo-cd:
  dex:
    enabled: false
  repoServer:
    replicas: 2
    autoscaling:
      enabled: false
  configs:
    secret:
      createSecret: false     # managed by sealed-secrets now
    params:
      server.insecure: true
    rbac:
      policy.csv: |
        g, ArgoCDAdmins, role:admin
        g, ArgoCDDevs, role:readonly
        g, deepak@obmondo.com, role:admin
        g, divyam@obmondo.com, role:admin
        g, rishikesh@obmondo.com, role:admin
        g, basit@obmondo.com, role:admin
        g, sanskar@obmondo.com, role:admin
        g, archisman@obmondo.com, role:admin
        g, bhavishya@obmondo.com, role:admin
        g, anantharam@obmondo.com, role:admin
        g, suwarna@obmondo.com, role:admin
        g, sgupta@obmondo.com, role:admin
        g, hritik@obmondo.com, role:admin
        g, sidharth@obmondo.com, role:admin
        g, kanha@obmondo.com, role:admin
        g, mdasif@obmondo.com, role:admin
        g, vitamax@obmondo.com, role:admin
        g, mayank@obmondo.com, role:admin
        g, victorine@obmondo.com, role:admin
        g, timothy@obmondo.com, role:admin
        g, esther@obmondo.com, role:admin
        g, olayinka@obmondo.com, role:admin
        g, francodavid@obmondo.com, role:admin
        g, smahar@obmondo.com, role:admin
        g, yulian@obmondo.com, role:admin
        g, nmalang@obmondo.com, rolle:admin
        g, deep@obmondo.com, role:admin
      scopes: '[groups, email]'
    cm:
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.obmondo.com/auth/realms/Obmondo
        clientID: argocd
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]
  server:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik-cert-manager
        # necessary for bare-metal only - for unknown reason.
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - argocd.kbm.obmondo.com
      tls:
      - secretName: argocd-ssl
        hosts:
        - argocd.kbm.obmondo.com
  global:
    # -- Default domain used by all components
    ## Used for ingresses, certificates, SSO, notifications, etc.
    domain: argocd.kbm.obmondo.com
  controller:
    resources:
      requests:
        memory: 3Gi
      limits:
        memory: 3Gi
