oncall:
  base_url: oncall.kbm.obmondo.com
  grafana:
    persistence:
      enabled: true
      size: 2Gi
    plugins:
      - https://grafana.com/api/plugins/grafana-oncall-app/versions/1.3.21/download;grafana-oncall-app
    grafana.ini:
      analytics:
        check_for_updates: true
      server:
        domain: oncall.kbm.obmondo.com
        root_url: https://oncall.kbm.obmondo.com/grafana
      auth:
        disable_login_form: false
        disable_signout_menu: false
        signout_redirect_url: 'https://keycloakx.kam.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/logout?redirect_uri=https://oncall.kbm.obmondo.com/grafana'
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        scopes: 'openid profile email'
        name: 'Keycloak'
        auth_url: 'https://keycloakx.kam.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/auth'
        token_url: 'https://keycloakx.kam.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/token'
        api_url: 'https://keycloakx.kam.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/userinfo'
        client_id: 'grafana'
        role_attribute_path: "contains(not_null(roles[*],''), 'Admin') && 'Admin' || contains(not_null(roles[*],''), 'Editor') && 'Editor' || contains(not_null(roles[*],''), 'Viewer') && 'Viewer'|| ''"
    env:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
    envValueFrom:
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
        secretKeyRef:
          key: grafana-keycloak-secret
          name: oncall-grafana-keycloak
  oncall:
    telegram:
      enabled: true
      webhookUrl: https://oncall.kbm.obmondo.com
      existingSecret: telegram-bot-token
      tokenKey: telegram-token
  ingress:
    enabled: true
    className: traefik-cert-manager
    annotations:
      kubernetes.io/ingress.class: traefik-cert-manager
      cert-manager.io/cluster-issuer: letsencrypt
  backup:
    cloud: "aws"
    destinationPath: s3://kbm-oncall-postgres-backups
    endpointURL: https://s3.obmondo.com
  recover: false

postgresql:
  size: 10Gi
