matomo:
  mariadb:
    enabled: false
  externalDB:
    # when mariadb enabled is false we have to provide external db params
    # enabled: true
    host: ""
    port: 3306
    user: bn_matomo
    password: "test"
    database: bitnami_matomo
    existingSecret: ""

mariadb:
  host: ""
  port: 3306
  user: bn_matomo
  password: "test"
  database: bitnami_matomo
  existingSecret: ""
