replicaCount: 1
image:
  tag: linuxaid-beta-v2.5.5
  pullPolicy: Always
middleware: true
ingress:
  hosts:
    - host: beta.linuxaid.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: beta-linuxaid-io-tls
      hosts:
        - beta.linuxaid.io
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
    traefik.ingress.kubernetes.io/router.middlewares: obmondo-website-linuxaid-web-app-redirect@kubernetescrd
