sealed-secrets:
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 1m
      memory: 16Mi
backup:
  enabled: true
  image: ghcr.io/obmondo/backup-sealed-secrets-keys@sha256:21119359a94efdbf6ce81e8887e0ae35e9988d9e5ce0c485879ffc4f42aaf1ae
  provider: aws
  s3Bucket: kbm-sealed-secrets-backups
  s3Endpoint: https://s3.obmondo.com
  s3Secret: backup-sealed-secrets-s3-credentials
