traefik:
  deployment:
    kind: DaemonSet
  ports:
    websecure:
      hostPort: 443
    web:
      hostPort: 80
  tlsOptions:
    puppet-agent-auth:
      maxVersion: VersionTLS13
      minVersion: VersionTLS12
      clientAuth:
        clientAuthType: RequireAndVerifyClientCert
        secretNames:
          - puppetca-cert
  service:
    type: NodePort
    externalIPs:
      - 95.216.30.44
  experimental:
    plugins:
      enabled: true
  additionalArguments:
    - '--providers.kubernetesingress.ingressclass=traefik-cert-manager'
    - '--entrypoints.websecure.http.tls'
    - '--metrics.prometheus=true'
    - '--experimental.plugins.jwt.moduleName=github.com/Obmondo/traefik-jwt-plugin'
    - '--experimental.plugins.jwt.version=v0.2.0'
    - '--log.level=DEBUG'
  # https://github.com/argoproj/argo-cd/issues/1704#issuecomment-904741817
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true

middleware:
  jwt:
    enabled: true
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqOrZ8sVK6HuTImOpGjUp
      fByvQoPmGYY8MkLhHXpVc3Avt9svBh+kZkF8dVHD7ufeSL1KFA6mTUJQutQq0Det
      xu4JzaZl1T5/aQq2sH8B4L03amwlpwKjnBPc+YMrlmOXhYstWFFyDevPPuimgGbf
      Rr2Kt7QMI53ZXlEj1HTBNRuNv79Cjl3holDGTsrqCz8kPFd0dc/pLZzDvqYDPZ0X
      UB6+BQUtHeXvxnMiJ/IrwQWDVbxcPr2PbyIClJj1FxnZvqA2CuXWz0trqog72cYV
      EQn+uJRX/KpfHWHIdIJQEe2dm4a9pc3/Uue/eFS5Bzb3fYyUgNrG+JN0Ki5ATFTy
      DwIDAQAB
      -----END PUBLIC KEY-----
