whoami:
  ingress:
    hosts:
      - host: whoami.kbm.obmondo.com
        paths:
          - /
    tls:
      - secretName: whoami-kbm-obmondo-com-tls
        hosts:
          - whoami.kbm.obmondo.com
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: obmondo-website-cn-header@kubernetescrd
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: traefik-mtls@kubernetescrd
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
