whoami:
  ingress:
    hosts:
      - host: whoami.kbm.obmondo.com
        paths:
          - /
    tls:
      - secretName: whoami-kbm-obmondo-com-tls
        hosts:
          - whoami.kbm.obmondo.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
      traefik.ingress.kubernetes.io/router.middlewares: monitoring-goopsmondo-go-opsmondo@kubernetescrd
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.domains.0.main: whoami.kbm.obmondo.com
      traefik.ingress.kubernetes.io/router.tls.options: traefik-prometheus-puppet-agent-tls-auth@kubernetescrd
