# NOTE: This is a common values for all the Obmondo customers
# if you dont want these default, you can override in customer specific values file
puppetserver:
  global:
    extraEnv:
      OPENVOXSERVER_ENC_PATH: /etc/puppetlabs/code/environments/master/puppet_enc.rb
      AUTOSIGN: /etc/puppetlabs/code/environments/master/puppet_autosign.rb

  puppetserver:
    puppeturl: ssh://git@gitea.obmondo.com:2223/EnableIT/LinuxAid.git
    persistence:
      code:
        size: 20Gi
        storageClass: ceph-filesystem
        accessModes:
          - ReadWriteMany
    masters:
      extraEnv:
        AUTOSIGN_CLIENT_CERT: /etc/puppetlabs/puppet/ssl/certs/puppet.pem
        AUTOSIGN_CLIENT_KEY: /etc/puppetlabs/puppet/ssl/private_keys/puppet.pem

  storage:
    storageClass: openebs-zfspv-shared

  hiera:
    eyaml:
      existingSecret: eyaml-keys

ipAllowedList:
  - "135.181.21.167"   # kbm01
  - "135.181.21.154"   # kbm02
  - "135.181.21.153"   # kbm03
  - "135.181.223.235"  # kbw01
  - "65.21.130.86"     # kbw02
  - "65.21.130.85"     # kbw03
  - "78.46.72.21"      # kam01
  - "176.9.124.207"    # kam02
  - "85.10.211.48"     # kam03
  - "138.201.82.121"   # kaw01
  - "138.201.224.126"  # kaw02

g10k:
  code:
    viaSsh:
      credentials:
        existingSecret: g10k-git-secret
  hiera:
    viaSsh:
      credentials:
        existingSecret: g10k-git-secret
