whoami:
  ingress:
    hosts:
      - host: whoami.kbm.obmondo.com
        paths:
          - /
    tls:
      - secretName: whoami-kbm-obmondo-com-tls
        hosts:
          - whoami.kbm.obmondo.com
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: traefik-jwttest@kubernetescrd
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
