sealed-secrets:
  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 1m
      memory: 16Mi
backup:
  image: ghcr.io/obmondo/backup-sealed-secrets-keys@sha256:21119359a94efdbf6ce81e8887e0ae35e9988d9e5ce0c485879ffc4f42aaf1ae
  provider: aws
  backupBucket: kbm-sealed-secrets-backups
  s3endpoint: https://s3.obmondo.com
  access_key_id: ops+kbm+sealedsecret-backup
  access_secret: backup-sealed-secrets-pod-env
