gitlab-runner:
  replicas: 12
  gitlabUrl: https://gitlab.enableit.dk/
  runners:
    tags: kbm.obmondo.com, kbm

runner:
  nameSpace:
    create: true
    name: obmondo-ci
  serviceAccount:
    create: true
    name: obmondo-gitlab-ci

envVars:
  - name: KUBERNETES_POLL_TIMEOUT
    value: "1800"  # default is 180
