customerid: 7ejidqmfi9
puppetserver:
  puppetserver:
    masters:
      extraEnv:
        PUPPETDB_JAVA_ARGS: "-Xms3584m -Xmx3584m -XX:+HeapDumpOnOutOfMemoryError"
      resources:
        requests:
          memory: 4096Mi
          cpu: 500m
        limits:
          memory: 4096Mi
      fqdns:
        alternateServerNames: 7ejidqmfi9.puppet.obmondo.com
  r10k:
    hiera:
      extraRepository:
        7ejidqmfi9:
          remote: https://gitea.obmondo.com/EnableIT/linuxaid-config-7ejidqmfi9.git
          basedir: /etc/puppetlabs/code/hiera-data
          prefix: true
  hiera:
    hieradataurl: https://gitea.obmondo.com/EnableIT/linuxaid-config-7ejidqmfi9.git

postgresql:
  instance: 1
  size: 6Gi
  recover: false
  resources:
    limits:
      memory: 800Mi
    requests:
      memory: 600Mi
      cpu: 200m
