customerid: abbnoa6nlk
puppetserver:
  puppetserver:
    masters:
      fqdns:
        alternateServerNames: abbnoa6nlk.puppet.obmondo.com
  r10k:
    hiera:
      extraRepository:
        abbnoa6nlk:
          remote: https://gitea.obmondo.com/EnableIT/linuxaid-config-abbnoa6nlk.git
          basedir: /etc/puppetlabs/code/hiera-data
          prefix: true
  hiera:
    hieradataurl: https://gitea.obmondo.com/EnableIT/linuxaid-config-abbnoa6nlk.git

postgresql:
  instance: 1
  size: 3Gi
  recover: false
  resources:
    limits:
      memory: 800Mi
    requests:
      memory: 600Mi
      cpu: 200m
