replicaCount: 1
image:
  tag: beta-core-v3.7.0
  pullPolicy: Always
ingress:
  hosts:
    - host: core-ui.kbm.obmondo.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: beta-core-ui-com-tls
      hosts:
        - core-ui.kbm.obmondo.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
