name: kcm
nodes:
  1866472:
    maintenanceMode: false
    name: htzhel1-ax41d.enableit.dk
    wwn:
      - '0x50000397cb700acd'
      - '0x500003981be00179'
  1866482:
    maintenanceMode: false
    wwn:
      - "0x5000cca25ed86494"
      - "0x5000cca25ecf496b"
    name: htzhel1-ax41e.enableit.dk
  1866484:
    name: htzhel1-ax41f.enableit.dk
    maintenanceMode: false
    wwn:
      - "0x50014ee2097c6ca4"
      - "0x50014ee2097c9304"
