gitlab-runner:
  replicas: 6
  gitlabUrl: https://gitlab.enableit.dk/
  runners:
    tags: kbm.obmondo.com, kbm

runner:
  nameSpace:
    create: true
    name: obmondo-ci
  serviceAccount:
    create: true
    name: obmondo-gitlab-ci
