customerid: abbnoa6nlk
puppetserver:
  puppetserver:
    masters:
      fqdns:
        alternateServerNames: abbnoa6nlk.puppet.obmondo.com
  r10k:
    hiera:
      defaultRepoExtraConf:
        prefix: abbnoa6nlk
  hiera:
    hieradataurl: https://gitea.obmondo.com/EnableIT/linuxaid-config-abbnoa6nlk.git
