---
namespace: obmondo-website
admins:
  - "aman@obmondo.com"
  - "emilhp@obmondo.com"
  - "deepak@obmondo.com"
  - "ketan@obmondo.com"
  - "faizan@obmondo.com"
  - "divyam@obmondo.com"
  - "suwarna@obmondo.com"
  - "rishikesh@obmondo.com"
  - "basit@obmondo.com"
  - "ditesh@obmondo.com"
  - "hritik@obmondo.com"
  - "soham@obmondo.com"
  - "nitish@obmondo.com"
  - "klavs@obmondo.com"
  - "ashish@obmondo.com"
  - "archisman@obmondo.com"
  - "sgupta@obmondo.com"
masters:
  - "klavs@obmondo.com"
  - "ashish@obmondo.com"
approvers:
  - "klavs@obmondo.com"
  - "ashish@obmondo.com"
  - "aman@obmondo.com"
internalIpRanges:
  - 172.20.0.0/16
trustedProxies:
  - 10.96.0.0/12
image:
  pullPolicy: Always
api:
  website: https://beta.obmondo.com
  domain: api-beta.obmondo.com
  config:
    startSchedular: true
    addDevPrefixes: false
    allowTestData: false
  puppetdb:
    url: 'http://puppet.enableit.dk:58080'
  puppetserver:
    url: 'https://puppet.enableit.dk'
  mattermost:
    channel: testing
    enabled: false
  chat:
    teamid: dummy
    userid: dummy
  clojure:
    image:
      repository: harbor.obmondo.com/obmondo/clojure-api/api
      pullPolicy: Always
      tag: v3.0.24-xenial
  go:
    image:
      repository: harbor.obmondo.com/obmondo/enableit-go-api
      pullPolicy: Always
      tag: v0.0.44
  mode: beta

persistence:
  enabled: true
ci:
  enabled: false
pgdump:
  enabled: true
ingress:
  hosts:
    - host: api-beta.obmondo.com
      paths:
        - path: /api/ping
          pathType: Prefix
          servicePort: 8080
        - path: /api/notify
          pathType: Prefix
          servicePort: 8080
        - path: /api/window
          pathType: Prefix
          servicePort: 8080
        - path: /api/tag
          pathType: Prefix
          servicePort: 8080
        - path: /api/user-location
          pathType: Prefix
          servicePort: 8080
        - path: /swagger/go
          pathType: Prefix
          servicePort: 8080
        - path: /api/timereg
          pathType: Prefix
          servicePort: 8080
        - path: /api/report/error
          pathType: Prefix
          servicePort: 8080
        - path: /api/invoice/
          pathType: Prefix
          servicePort: 8080
        - path: /api/servers/
          pathType: Prefix
          servicePort: 8080
        - path: /Webtee
          pathType: Prefix
          serviceName: enableit-api-grpc
          servicePort: 8100
        - path: /
          pathType: ImplementationSpecific
          servicePort: 8088
  tls:
    - secretName: api-beta-obmondo-com-tls
      hosts:
        - api-beta.obmondo.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: traefik-api-puppet-agent-tls-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: obmondo-website-cn-header-enableit-api@kubernetescrd

postgresql:
  instance: 2
  logicalBackup:
    enabled: false

serviceMonitor:
  enabled: false

extraEnv:
  - name: PUPPET_API
    value: http://puppet.enableit.dk:58080
  - name: PUPPET_TIMEOUT
    value: 30
