cluster-api-operator:
  addon: helm
  bootstrap: kubeadm:v1.7.3
  controlPlane: kubeadm:v1.7.3
  core: cluster-api:v1.7.3
  resources:
    manager:
      limits:
        cpu: 100m
        memory: 350Mi
      requests:
        cpu: 100m
        memory: 300Mi
