gitlab-runner:
  replicas: 3
  gitlabUrl: https://gitlab.enableit.dk/
  podLabels:
    cluster_tag: kbm.obmondo.com
  envVars:
    - name: CLUSTER_TAG
      value: kbm.obmondo.com

runner:
  nameSpace:
    create: true
    name: obmondo-ci
  serviceAccount:
    create: true
    name: obmondo-gitlab-ci
