act-runner:
  replicaCount: 1
  act_runner:
    existingToken: gitea-runner-token
    storageclass: zfs-localpv
    storage:
      size: 100Gi
    instance: "https://gitea.obmondo.com"
    parallel_jobs: 30
    labels:
      # upstream link: https://hub.docker.com/r/gitea/gitea
      - "gitea:docker://gitea/gitea:1.21.3"
      - "ubuntu-latest:docker://node:16-bullseye"
      - "ubuntu-22.04:docker://node:16-bullseye"
      - "ubuntu-20.04:docker://node:16-bullseye"

runner:
  nameSpace:
    create: true
    name: obmondo-gitea-ci
  serviceAccount:
    create: true
    name: obmondo-gitea-ci
