replicaCount: 1
image:
  tag: obmondo-beta-v3.0.5
  pullPolicy: Always
ingress:
  hosts:
    - host: beta.obmondo.com
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: beta.obmondo.dk
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: beta-obmondo-com-tls
      hosts:
        - beta.obmondo.com
        - beta.obmondo.dk
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
    traefik.ingress.kubernetes.io/router.middlewares: obmondo-website-obmondo-web-app-redirect@kubernetescrd
