customerid: 7ejidqmfi9
puppetserver:
  puppetserver:
    masters:
      fqdns:
        alternateServerNames: 7ejidqmfi9.puppet.obmondo.com
    hiera:
      hieradataurl: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-7ejidqmfi9.git
      viaHttps:
        credentials:
          existingSecret: hiera-git-secret
