act-runner:
  act_runner:
    existingToken: gitea-runner-token
    storageclass: zfs-localpv
    storage:
      size: 80Gi
    instance: "https://gitea.obmondo.com"
    parallel_jobs: 10
    labels:
      # upstream link: https://hub.docker.com/r/gitea/gitea
      - "gitea:docker://gitea/gitea:1.21.3"
      - "ubuntu-latest:docker://node:16-bullseye"
      - "ubuntu-22.04:docker://node:16-bullseye"
      - "ubuntu-20.04:docker://node:16-bullseye"
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi
