harbor:
  expose:
    tls:
      certSource: secret
      secret:
        secretName: harbor-cert
    ingress:
      hosts:
        core: harbor.obmondo.com
      className: "traefik-cert-manager"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt

  externalURL: https://harbor.obmondo.com
