---
namespace: obmondo-website
trustedProxies:
  - 10.96.0.0/12
admins:
  - "klavs@obmondo.com"
  - "ashish@obmondo.com"
  - "aman@obmondo.com"
  - "emilhp@obmondo.com"
  - "deepak@obmondo.com"
  - "ketan@obmondo.com"
  - "faizan@obmondo.com"
  - "divyam@obmondo.com"
  - "suwarna@obmondo.com"
  - "rishikesh@obmondo.com"
  - "basit@obmondo.com"
  - "ditesh@obmonod.com"
  - "hritik@obmondo.com"
  - "soham@obmondo.com"
# Need to add service and pod CIDR here
internalIpRanges:
  - 192.168.0.0/16
image:
  tag: latest
  pullPolicy: Always
api:
  website: https://api-beta.obmondo.com
  domain: api-beta.obmondo.com
pgdump:
  enabled: true
ingress:
  hosts:
    - host: api-beta.obmondo.com
      paths:
        - path: /api/ping
          pathType: Prefix
          serviceName: enableit-go-api-enableit-api
          servicePort: 80
        - path: /api/notify
          pathType: Prefix
          serviceName: enableit-go-api-enableit-api
          servicePort: 80
        - path: /api/window
          pathType: Prefix
          serviceName: enableit-go-api-enableit-api
          servicePort: 80
        - path: /api/tag
          pathType: Prefix
          serviceName: enableit-go-api-enableit-api
          servicePort: 80
        - path: /api/user-location
          pathType: Prefix
          serviceName: enableit-go-api-enableit-api
          servicePort: 80
        - path: /swagger/go
          pathType: Prefix
          serviceName: enableit-go-api-enableit-api
          servicePort: 80
        - path: /api/timereg
          pathType: Prefix
          serviceName: enableit-go-api-enableit-api
          servicePort: 80
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: api-beta-obmondo-com-tls
      hosts:
        - api-beta.obmondo.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: traefik-tls-client-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: obmondo-website-cn-header-enableit-api@kubernetescrd

postgresql:
  access_secret: api-postgresql-postgres-pod-env
  logicalBackup: "false"

chat:
  teamid: 'cnuya58yz7njpxweab87aq7uth'
