prometheus:
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.domains.0.main: {{ .Values.prometheus.server }}
      traefik.ingress.kubernetes.io/router.tls.options: traefik-prometheus-puppet-agent-tls-auth@kubernetescrd
      traefik.ingress.kubernetes.io/router.middlewares: monitoring-{{ .Values.customerid }}-ipwhitelist-{{ .Values.customerid }}@kubernetescrd

middleware:
  jwt:
    enabled: true
    headers:
      X-Subject: sub
      X-Obmondo-Customerid:
        data: customer/id
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqOrZ8sVK6HuTImOpGjUp
      fByvQoPmGYY8MkLhHXpVc3Avt9svBh+kZkF8dVHD7ufeSL1KFA6mTUJQutQq0Det
      xu4JzaZl1T5/aQq2sH8B4L03amwlpwKjnBPc+YMrlmOXhYstWFFyDevPPuimgGbf
      Rr2Kt7QMI53ZXlEj1HTBNRuNv79Cjl3holDGTsrqCz8kPFd0dc/pLZzDvqYDPZ0X
      UB6+BQUtHeXvxnMiJ/IrwQWDVbxcPr2PbyIClJj1FxnZvqA2CuXWz0trqog72cYV
      EQn+uJRX/KpfHWHIdIJQEe2dm4a9pc3/Uue/eFS5Bzb3fYyUgNrG+JN0Ki5ATFTy
      DwIDAQAB
      -----END PUBLIC KEY-----
