issuer:
  enabled: true
  issuerEmail: klavs@obmondo.com
  production: true
  secret: kbm-letsencrypt-key
  solvers:
    - type: dns
      cloudProvider: cloudflare
      cloudProviderSecret: cloudflare-api-token-secret
      dnsNames:
        - obmondo.com
    - type: http

cert-manager:
  cainjector:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 1m
        memory: 128Mi

wildcardCertificates:
  enabled: true
  domains:
    - "*.kbm.obmondo.com"
