---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgATgHOFmtTeHGeZ4siPBN+0LvP/UpKHqlhqc3ExxYRImeB84xxWxR8kFLntE3ndOQUW6qbW4oTFev87+WUP4yuzfRAx9GCr0gh6ARer4evage2RdcxkNArHmeMc7H0NizVQI4GzS812Nyr/nOLWX1Ejd3Wol6mHLcvS0XTrkNuZ8K3rnTvbwZKttYWzu2eEO1JOGSA34Y9TjxwNFXGWl6I0IaGEafUNR1fUoxQ54r60qw4ngaCyLIC9vHadRXi2KojDITj74cPbkT+UGx4f6FTJNb036YzbJ9mDBlBWCjWyT854MTE3+9A9uTljnq1N6Q6G15/wju+DcudcTLqA6+7irC2ZoRMHorpYfRAB6oVBeMgCriGeJ2TK7UsrFpOp+ahCwSQOd4TQ0ZQ8NagkRSgO2sUnnNxOEtm5UdPMiueY3d9U/6RmMEDok7vxSYkcCmhA9IDLbWHIhAdwEmE7Ke0NojOI7nUYB2+9Pz0HYSg222Xkd7ounUCGMSp4JWKVE4RcAFhx/obNgIdN2nn7waflMwpH8PcVvy91lLuZ2AetIHBUVTNQJELuh0h9AZcnnaYIxUXsGLAFkq/SsXxqYmWFZ9tQikrYw3Q3vG5UMu19lYLDEblx9lzFHcwpaWAnmzOC96DALa6SpREfyafLgOxAziJPc1+S4Yiq8IOrZclKq+jq80+M9Vj4LaQTHVOu3gjvz3JjZWL7QOIJY599GjoA3d3ac2UNPygRx+5iNEYlVm0f7euYoAA5SbT2qxa0Sc1CVS4Ty0QmgraQm7UDxszb
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
