apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hiera-git-secret
  namespace: puppetserver-ebillet
spec:
  encryptedData:
    netrc: AgC5ke5xL7EJ6m2EKYTUHr8qLbn/oosPSmRKxmhE+zd6lKh/mgvTYkIP5tP93pSuJSRkHM5qt6pyS9FKbhhaHwYJACLzDeszJIXWq0ojfBWv560aOdrWW3v7uMowVj2DQSsfKoraB19LxzxCFUI6qmk4kn4hFYOYKwGC+liekNSQ3R25n2RruY72o6yKNgQuqmETygs3cHr19LiBypeA902YjNLncDUSADw/7N3AYdpXTLdIHysz5H7m9sNJsNpLghwQ/kYItCej9gNJW5c8esJq+cUApN6IFR75iloIe2T9W0oPX7T3FFHHXCi+/I5FENqSfkyYRdFQkNUnlPjNE1VdvjMiwoNLUY3QwpcF0pRcFjfEQe0ZgDjNBBCSvjTKvGraOA/SgAGea1+om+TzzH7bcycTp2cMD+1mLBJ+SZdxgNXLB1ui2/5JWTBU2zHaeAGbyVLVH3QLoMA/oj1jvwhK9ATZ/X1B0RJIBBH6X+2zwNbX68HDX3Jaj46IPLPpl5ZLv9dlXecKN5OUWPFC8GaAOOpIbhgOKSqsyitUPJcXNbS5kz2ybHrDPhUrD5j8EIyaCkQ/N/E9aw5cnGakFEWoX1MXljB9M2OSOG4HyULPFHyZ2gYoU3+aHDoAGDe/BLU4e78qfH+IDTC5RoMhiXPnoZxOewRttGi25wsmhFkORTOzno3lnhXHA6Esh25cP12U2Z+0Z2yjTMOAYm53Mgj+A3FxRp2Q2VjcwmcBboKHXiKPRwrdY3uMb1vMEeoNpcdsFE22DCV7s7TpTrQO2j/earE5UOrWSNU8wZGCZ5ylaN4KciMc0LHsuxliKebaTMBS5xZ6
  template:
    metadata:
      creationTimestamp: null
      name: hiera-git-secret
      namespace: puppetserver-ebillet
