apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  destination:
    namespace: cloudnative-pg
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/cloudnative-pg
      targetRevision: 16.0.1
      helm:
        valueFiles:
          - $values/k8s/kcm/argocd-apps/values-cloudnative-pg.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
