stages:
  - diff
  - lint
  - kube

lint:markdown:
  stage: lint
  image: registry.obmondo.com/obmondo/dockerfiles/markdownlint:latest
  script:
    - markdownlint --config .markdownlint .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lint_yamllint:
  stage: lint
  image: registry.obmondo.com/obmondo/dockerfiles/yamllint:latest
  script:
    - yamllint --strict --config-file .yamllint .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

helm:diff:
  stage: diff
  image:
    name: registry.obmondo.com/obmondo/dockerfiles/kubernetes-build:latest
  script:
    - "./bin/helm-diff.sh"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "k8s/**/argocd-apps/*"

kube:build:
  stage: kube
  image:
    name: registry.obmondo.com/obmondo/dockerfiles/kubernetes-build:latest
  script:
    - "./bin/build-kube-promtheus.sh"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - "k8s/**/*.jsonnet"
