---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA2UBHntk10vjTO4yur/HC9srTWunvJhLofAWQi1tVcSxIm+Ib4Ztm5zypWo2Doqlt137FMT2RD85X8Tii1FfDRdKWH7Dd7SYA8YUS4bBL1Na87et8e7mpyqrZVdLzf/5e8hJDVRhCF1XWsYvSwjd6QEdf80BP4bSlwtZ/q9C5vrkKETzpGGv8JwRzg2rUXeUY6zp6PHdsCo3iOJH9kODzyVgy/i1mv8MgrHEDt0pzGqohY8A1D+wQYJt7UNpipyPFpMXSs0GWSuGxZVAVLnt2Uj0HlLwJhYS87MwtsPXcBXqsZkDrixJKf9HzDf2wL9dPr0R6+EBOtNBerGFMVbA5FgmgfwKRszwqgUQ2QDkN5kdGdbUB3qzm9WycEXe2XayNfLlB0Ts/xQl1zrHzz2KYCh6AB1i5hKr5cizWHNGccUyqnAJUMvKqBK3Gq8zpPvUbXciclt33jrA5lFvVzRFUYK7ai4+YuAH4MN4PDMeSvAh1qVS/m8hSjRm6mUZkJOP41atBovciA2Etgh9XQP4T2h4ED46Yz7OuUv7l6s8UX+A4XN2gKv/8kkxtaRUv66gFermL/wXZjlSSR7NcwiyQtosq7+iq4Rlrqi0pWPmgPNzRDsCXoYt/pVeWCM4WEHMN/IokyQE5RMQR9UQM8xmyaaq9xfkhWZLzwr6G3M6jnDci36fx95bbRGtX14OwL0QzbMQHloucizo+ozcqqx9dRJ3bHkOsH61n05WhSeXRjlfzM/pJGq3Of
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
