---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCRLvsUdUrwzYVGX5cei5YIkpkdxOlh4VdAW4st7c1z0Q8M81Zi/164hLs4XE9edztnhPv7gtgaQn6ZvtFgUjRDxXZEBkJIrapEaT2a5h7c8R/kt4Glbj6ZvlUZOrST6RAV+ib3OdbyTEXYNhiS1VEUWPkKAbVBCeCQkdbx2coVRGFaVl57rqrpkzvN4oHu1dlH/mXg7zJOBDy8M8ichxeg0qb9ih3UrLcGNAwApxMLznMwXhFuUAuy4Tq/+6xlamamMDLwTdFFAjFAYo3aRiESwyMh4865Ne0q5e/qk5pXf5l5vX/mXR9w29AjJc0E/wfE8TaxqN82NywpyIbtSKboStE0QNFrn/VXEub8+YXnOE+B/GYgiDQ1jyx+Vm5XBf3sHxEbRhEy+QglU4DtZ/cD+x5Mbj3pcdIzT2+a1S7oSZD6AS6dvc7gzAq7UaT2Ww+ahMqY+/EYI3Rnx2g+Zt09VGzY7KV7dkQl479grAFSt5dILoC0urLpiGO3TY0JrYEyJrx3ycQGDji2J7B6DBc5OT83HZ/0pCVgwNkskvL+IbjEXwqzRBbdgM4jZIt04z1Inu7WCx/Bx/PgKTXsei8neaho7D2xkKsdefcY84ntnugD3r9eNN032ZWrwgsfd0aS7V4uXiorfWIkgX3y4DU/XCuOXU1adjqQCLvfc5KraxpU2n4PmjuS2Ab+D+tWkB4R2SaCyJcS3yBvugpL4DWxGLtZbKT+BAHLgmFoWkwGg/3vh4UlxrR6bY6EFk7ulk1fio1zmJRfZxcBFJWBbtRw
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
