---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgATQOxPf+95tTxvpv4IoAqMf5zcEQx7GYmrComDSdUtKXYnQa1rY7KZs5Li4D9jsWNXM8VO3cQ3pr70QWFTzTt7/+nNF60IP0szdsbcqhXC1osP4acwlpeTdwhE2nGmpMiVPBNVDcWsUdR3dy2w9Ca0bLcIn1hYu7/B+3d5EdxgaDIBpUOcPDEtrGEHX9TS3z9tHZCv9NSr94tBcs2K5jaJZ9uq+6vha4Y9xyUkAlcJ0RPJKgfGc+TX4ne7hqQPyqTZ+tZ5HwKoES3UfwRhQGJ1UoDZCt8QclVwCOc6D62zu2n4l1wLNMGFAE5l4KlhCd7Z+aEuvbsxO1oJg/xt5bOiIzSdPnPwSvRn8Re7oAe3yhFH/u7Jo680YkHDPFwLyIpFUgY4GHLefHazj2a/36rAO0J9rCbK7l48HA/gaG3bV6/4G4w97vStOyORJqdgiFnqPDfZYQAYayf7H7veaduTl9R7o7hsQ40shy5YSdJfZckuv/sGCjbMD9vD0DhEZ/fMtQyyeW+jS6n02Kl60X+1k+3DtEyqMEuWBLX3S8r5pfvPX6HJk6soPkRHzSv0HHS+QvlPhdoCRvnaydocs3DYwR/T81sJHnYxim/uQ4KFQoWdekBZToioZGoBV03HeBapMN4n4tq94XALMd7Afqo2caaPuFD1y0FanAC/U8R4VU5BwTvULrNXDc7snNO2d64e/ZvXvcrQmU0FCztSyTrRrEPXHE+WkJLtv2pMPgI8AyCbxq8jdCwhIVHLN6lKcRw/DT18LyPrQ96rHOCznK2K
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
