apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.postgresql.host }}
  namespace: {{ .Values.namespace }}
spec:
  teamId: api
  volume:
    size: 2Gi
  numberOfInstances: 1
  users:
    api:
      - superuser
      - createdb
  databases:
    api: api
  postgresql:
    version: "12"
  enableMasterLoadBalancer: false
