apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: relate-pgsql-backup-creds
  namespace: relate
spec:
  encryptedData:
    ACCESS_KEY_ID: AgB2PiDuvW2fiji26VPZ6nZn3MT58JEbJBkFIbHRfmSADW00/Xj1MAciXYC+ICbV4QS2+ezReqXj3tT8LUvXUq9x0u7C0plqZ56O5SEmD+qOqFsFdAuvhMwVMBTqXscNxPrH5ScfzZI8I8iYHk4GpxyRJNv1QCWzuNC0zMYXo7CTOyi+v3qpJydWQIB4oa77nlKZ5pU9xCkZHoyg7aVF5EyoozmzTn+BqtPcxFRIPqiujDG1kbHEvZZ+aYvhTqpwjWWTiAGHEVT/7EMTUuSSmHYfNVKUZGrg2tzMFaJskfCik0VPanhXru5lWhTaPWab9r0DyDWolzew7DsL7zmMAQZmyaxyEXHQ4O/aHyDtTD9HA3208s2WEDE26bcYbjPfbwzw8KpEmszvulbnTkqXAgj05OasYgW40pLZ/QwnQY+R/d0j1uMQnmgzYtlrFTpiEM2yMsxbtJKx5et87f/i74cW6CS7gpDkLN8SvAtL1qAfHYso/y6SVzznsoL/Dl7cEPBEQ9Tz53xKuXETfo/ixKRTM/RTuKom0KTUf1Af5Wx6/TMnq55vhBBbatGxbjFZcisR9ldfEf3BzXwW0+FyZ+wqFLPb0Ud87Qh5d0/HF9hjjgqiFSyDLzC6JaHlprHiGVrI2G5oia28Po6jxML5tzggusfJ67NAsYpZ3MSoQjyQAKKjibIE6QxXeQMl/5gd1QplY+A=
    ACCESS_SECRET_KEY: AgDFMe4dbISCVRX31ypW6OEy6LEaleONSpMewlH6rk3HozxT78xrwIZKDzLYP0OO+LgWLr+HB5WptD62inuQ+XYj6V2w+1U3aIgzKCGFwgHo35Gc6GDGaqYrCAxKH7IB1y97olrYXnFN3wAOem/kh+5l6m4gpGVUU+/XtCjkTigZlOcYs8GBSg34Z7zovRTFX09b9CkWJOUnmacSrr0GEaJSeWgx6479CCGKT9fp+QnNjkvuSraIYmXq9hRf834Y66Z3Xh3sP2sxZa2O3jIKarJlKann6N31HkTXU8/NxqZzJGQR8i9dnIMN/YLefZrDrIaIVvmnssa/KhFwL5bKVuJ1k8EYHpk/Zqg6tPPzaGEX4IfCyF/DffVYScMhd6xA8aZhOK4Sn1biiOf5rhFxBcyDh9bGiUcv9byvbZkRkHGiXanmiILu/iD76TRdX7iOX4997FT56y90v+/0ZI5+BcqGuT6hDF//MjbiGruVUckjJi6yp++XjDDMNvKHRqLfH/ghtizRF1/k2fi0qocyT4gKYWE68xWXtWvkJo89OvKlmq5UEVz39fI89uKA0grg04t8fmmYGkVr72IE7ix8KwQ/BJehysp0UYC6UnSmPG5t/adUs7yBnXR1gobbmlKBlr3UqklqyED3tvMh3j+06vwgr7GOtYN2yrsTcRtaQcEeQolZvswHo+vU2sS3kW7CluC6f/miLButU3l2OZ1KrMeubUTCw4NntzY=
  template:
    metadata:
      name: relate-pgsql-backup-creds
      namespace: relate
    type: Opaque
