apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obmondo-gitlab-registry
  namespace: obmondo-ci
spec:
  encryptedData:
    .dockerconfigjson: AgB0By7iSz16QboCd1h0DoR5Dg6sObOPobMe7Q5buqYrSz5R1H4G+gbpxMzYOQSNEmIQX5OJuUwlN4Jlm+3CWFSBGJc8cFWcgXX6WUZyv0L1YckELshra6a1C/BJej/c6WcATJrw5TnyuYRQYbFB0E7ipGKJEVXhVLkl2OsVf4u9kmKqcR+sp6UqmEI+dU1xNjN1GE+qprdsAVm08e5/+XS1ny/ZheHck21dOhNjiuTIQymXzpZruLYX4S9DEdShvMwl6nniOpVYvYCw3oMKtHx07tV4sHhPpeVN0ZWSQl7ZTcFdWQIwXiI4vilH5nrK7lkKyjhTMW/zx+N7Xc3YP9lB4XlVlECQWCKP2Daz+tI1ocdP8cJO5MFuodbMCftWYLB4cpMIKCT6gsRykBMEapBLyD0A6s/5nMK0xXD6/fp27sRrdSsu+aToErGz2/RhepLDP9XxDLa0F4HbjhMiir8er1CXQb6Oj4vAt9JErwBjGJ2lNhFeVuZ8lweKCRFv30llq1GEXD+HI2AoZqnnP8WYrZJSmnKfk4PNmh4n+EIs0Ngv+eeDPdOKuntWIGqNiTxGFLeZgUL2Iq89i3X92fmImjDE6wsxfaB6hA4L2GouPzSSn3ZDnmDGSeztx2d5Sl/0k3as403Yt/aSneyTn+nsTnsNt3O0NbaTeEdqLvs0ChGZPfNpUxpFSG1sbOYoJEwgDypiWse5UCsNaNgnng1BrdGKDvkmqos80zfRh1Revz8KpAqja3WPRecwz+BnV8DNKxNf+2Tfr1FVcSBC/b2xeYW7PQ9QkSDUMkFLD5KWYFw4/Hpp90RIW1sro/qAqTjuvR2bb2e3VDtq1YjSzdo8arcPHs51QSGqjiVwSS17KmElZbiefW9dqZleDGFzqZ7M8pT5lAmQ2kQa2Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: obmondo-gitlab-registry
      namespace: obmondo-ci
    type: kubernetes.io/dockerconfigjson
