---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCHrEtLijdNb8RkA6hg8rQlpbl1BXj26dPh5Ut7PBO87YgQ+IcJae6Go38GAdjtF8XRqH9LzM+lPHwyfEZkFJD33fjx9qgLgJR/zKfkrETMGuBm0w3Y6jQwshc2iDCV+XdmeheLha+5jArn99GGa/V6LzRHGmLYtJquEzaTML4fQ3lL7PYLukYs/ubViOC6eZvYXkpkR8rshmuK5AApCQOhfImGxXShP/a0nDiseiBT0XXwEOPWEcO5XugZeFxPSZ0uG5aJzXrfYVHWS6agOPMC4fM/TJkvRw1SmuhT8pw4//aulMh99diOACsP/j3PwrZG6mBL5vzhoa5xea03mdR3tgSH+NNm3WPhhX+vAX7VCjF4TBZlJaLeNalXi1DlBym+6YP0hTLciIrNgk6oKwHof7GLfpppqn0tMAs5KqQLYR8lf1fizIemR+Ei0A8rGoDNUBgmRWozBI34CD2QpYMCTiqMZfMGUjjPPVjpJpzJTHIvslAmsFPvNPdC4QkFGkosoylsCnRB1Cg4PKQhT/0mEPkBYEZpSlqlKgFx5udrOrYCcWEs7QV+GaXF/Me+agAi3aehNFbFLYdixEUb4Qhfxi4tolbSjdx8csZc8z22FGGB5e2GoDPrlDlkKHtqr4k0KcrLpiuqD7lp76k7g0+l/RuOUNg5nL1MEEs5mdaDGRwvDSCGO638pIj4TfL25A0gWf47R3Ci1QgYOFEcaVD6VmBKCYhTmTJhxgl0X8OYsutRx5H69g0UqprZmhtwWQau5Ug494ufsGeKVVJzsD+q
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
