apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-cluster
  namespace: argo-cd

spec:
  destination:
    namespace: capi-cluster
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git@github.com:Obmondo/kubeaid.git
      path: argocd-helm-charts/capi-cluster
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kcm.obmondo.com/argocd-apps/capi-cluster.values.yaml
    - repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
