apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeaid-agents
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obmondo
  project: kubeaid
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid.git
      path: argocd-helm-charts/kubeaid-agents
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kcm.obmondo.com/argocd-apps/values-kubeaid-agents.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
