apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    kubeaid.io/version: 20.1.1
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  project: kubeaid
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid
      path: argocd-helm-charts/ingress-nginx
      targetRevision: 20.1.1
      helm:
        valueFiles:
          - $values/k8s/kcm.obmondo.com/argocd-apps/values-nginx.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
