apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opendesk-coturn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opendesk
  project: kubeaid
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid.git
      path: argocd-helm-charts/opendesk-coturn
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kcm.obmondo.com/argocd-apps/values-opendesk-coturn.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true