apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsmondo
  namespace: argocd
spec:
  sources:
    - repoURL: https://github.com/Obmondo/kubeaid
      path: helm/opsmondo
      targetRevision: v0.28.0
      helm:
        valueFiles:
          - $values/k8s/kcm.obmondo.com/argocd-apps/values-opsmondo.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: kubeaid
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
