apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-smartctl-exporter
  namespace: argocd
spec:
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/Kubeaid.git
      path: argocd-helm-charts/smartmon-exporter
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kcm.obmondo.com/argocd-apps/values-prometheus-smartctl-exporter.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
