apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    kubeaid.io/version: 21.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  project: default
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid.git
      path: argocd-helm-charts/rook-ceph
      targetRevision: 21.0.0
      helm:
        valueFiles:
          - $values/k8s/kcm.obmondo.com/argocd-apps/values-rook-ceph.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
