apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgChKOsDUx+7rubmAhksV/91U2EmHnUGIUUSO3C5wUUVIFqmhNEJHECMsBrKUlhrAXSnQ5G0B8MOUXaTg3IcQ+DA2w5f1SkuJlHM0n31GQU9GplMJi/lyD2AyqWtDyoeBQmNxF96AW3hHBsXKTOwtsiLOe8tWS0plVU9ybQelDJ6ox0GQhagGYIfMGDMowA/Z2474lSGB6uDnboCvDMTrNv6qiIabuP32AFWEIfO9WoCR2haN6F7ZgCuC+zzAimqJ6pFQI+Ky6VTc+DJpkiOz4DtAv7++/GN2KZh6yGnRCuMsaIQJqfZulQA/CGIrOkhiGG7z3oF9KLohaziGxv48dlGLSYDPXbqz2vVTBFv5rtimkzoes1YCxFvtJJ9Rl9YZuKUJWL1h/HKgojmQ5P8me4ODFgSy8xO1oSDhIiXWp4tVJgcy+pIIlNoK0nIj6HKJpIqLX6091Ec4fvI6SBoZ3zZXbfCJre8L3LAqep6XN4q4k0LzTq7EqwkxBoEI6fjOdbxeSojg5j/8+cMueholM+Lgh/tiDx3unf/Q1yjOdape9ijtxEQjpboMtYMNTNFj3MqZ5CSxFKCOR9tGYhkwxGwFerNSwEpf8ztKjQQ3Sk2ciyK2/iM+TPNk/qjF34w2r/Lgk4FtD2qQ56byqoriYatHAoOkKN0EOGlCiZhlc3+z0ME0YpmTOr4Qgfmu4ght1zdQrqVT7UjfS/1heHo3M1VVRivcJWhibxp0jCKYXCMd3w75dXVyIYH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

