apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCsac6AMxnejdC1VZWst9TFJu5+b4JvxWeOda92KvF5swSNB1SEECYy6V6MbIEfztxEyto8w220Iao6xMyjUngGkCmsqYMnHwQpHETYiC5VD0NUO3Pl7G1DCOeke0YaxpS2YMGVC/spD5v9s7gFJvCUb6RVoB16zCe3MUeILl/OZjSbO6dR78Moh5TFIPq9rZMxvBdsKeDSBZjIIFBlUoviSlVHceIw61++Di/4pemzh9LSF/20Vy8ald7cLgiG0MDJlc1m6g85U7K1u4RnhUbJzUe11pxaP0k5CBhCnr1uqdoCfmPWdvHkwtI+pXzg2BSadVV7YCdYIIwf6VqVwhTnE8p4C9rx2Sbp1u9yWLwDXDgCXgRO5hFMNgfEqkuzVHPQbe1RlGRbyqk4m37x9yj/wO18z2EYE8tQ626d8CaWoMF+7CSzr8zKQegn84Zb5USitDxHOegTDk+Pyq7DC8ObrGEmatfJSNd5IhMP1bQpGdNykw5tylixUkiTZ4b2Xr4i2Tt476TPrsNRMG5ZW6fvf+UE9DnGUOHXO5yhZuP6YDDc6WDPF/PhITPjA+4wwAVZ02fwiMtSi3d2ylCbopZFrCh5TwgO5cBNAWXKfhahKskKlNNVUFu/RXQnicbYyCKmuXtpmfa2es3kOYzDJAUftnX2/5w0AC/kPhrGvm8gc122pzF+W8K4Ta0jKhB5+PJ5gOhDz6NpdXoI6NkPUIfcYl3sXmB7SvyQJC4KoJCTHXWZhymIa+up
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

