apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBQm5bOtDUjkUFmAapL8v4AMaRTR8glFWdLDG9Hv+UlSPhiKiGB5TNL3iX9wicyfV9preDOGRWkpLNt06L7lTbdYql679c06CNF1+0teSrvSInpKl91N9lOiM35Y9s7lD+gKp2ykHZif6Xxu1+VCIKPO1bUBElBuKosXCR60aEc8mewuF2HggK3v1phkZlrRKpz1bP7iGU7xSm86uF3OvJQoLA25UkJdDEbGLYkKhlF7bp2gKG1R0CP6q/5V3emQFLttl3EYPONXSACKvwvE/ZO/DXfsZqdtB2R+Yen/LTlgXIVSsDsHXb8ij18BLJcxWwhKz05KOTtTisoVA9DOJE6WOl7YddtfBpgAUa6GdrJeLYSZSSW4Kf/BPkYLNojNvHLBYOFusjiRMuK3sBkUFqEKMVWGl3kCPOYoFMr6FXYdMScs242IfrcEArDhTnQ3r1dGwjmHxWCxJziDO6rMog8NwwWruSASY0Z4BKXkYtLqCoLXay+tDdHKCFIc0Lt1MnfPa6kiC91WpWqI4tXuoExgHjTHhKD6JlAJLlBmBjkSlXDa61PUGi7eJlvFnibiXePiWO0eArwF9ryOnaW4YQ3J94A1FBqslvjUNmk8BR7HYvH2XkltS12N6nI0TMvOFw+UhzlsTB9szfD7aEOy/cv7jCe9tEJmShlztIH+6SrSd4tolRaPHQsTK7pCdBX+mGnetyiS/BuSuEyVRiL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
