apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k8id-web-app-gitlab-registry
  namespace: obmondo-ci
spec:
  encryptedData:
    .dockerconfigjson: AgAn+LOao1+fLlIpmVBcoDS3fc0yY6dgB0pHnL+eGK9MAPgnjQcN+4qfsEjG+AublZtoEDC/5DypgRoSvjAeWp1HOI+VA5Xi4IThHZbdKP4YmHDfJVna+YdUlpza2RkMAA93U7qDvlD8qLcPPIYC6y2ezT8hS+/f8DTyXQAxfJPnxDuXrxuajGx9/8VIBMVbJMN9Qlhglte8ZESTp4H9Q/JMCr2py/jvaauyygPaAQR2nVMPqJ0mHRO2Hcr83++sJujCggwKdxM81P2b8qQSGKGygpcpLnaqfx9FpfepDex5xfGoBNhu9NZagMo9LPJ9L3FI1lImKW6iMlO0uZwcT6Xgd9Ab6+QYMRul0j5jXJUOeHzP4yFCc6zSKiciolpO+wiRtsYZs68MYU5tktM5h1SxsECO/sKcq9JBkcGOCIk5zbl8GEB6/rEdHRzuVn0cVGdQyzdfFViBnGa45ZYE8hTKCd2qH1j+gO11lg592qRgb+I+jh9IJUeUbXPrvw4sRUS0GMCYp2vlFH03vvl/4lMIuG2vFIM/HTj/8L1EzWtalZ6EReH6+W41eFyF0JyjNe05BOgnOWpvMkMBu2Qx8uQWc6fZYqllf2LAqrV7CbBMDW10KEcSlCcSFcuAEAO15Kyb8TOgnwm5qozBmeDSNrKXhQvyBoqCQv1Kn69VbV28KZxT1cXwKfA2dXA9hzvYX2al9PZK2syG1cLpzQL1zZH3dSXTw4q+qfvXn8VN+HHFc8nOeyOQ+L/2FcGzRy/NImFM/JaQoQwbsrlFfSJKdQPEmZTBT1NouZLnzSQxVj7iEY3fnK0PVIlJPpd8CXUU6Ljn7KZFtBfZPZxUJwFFQQM95NQ0PmnN/WuepaKlNvBbHNiKHKZe2HvsYzfjpn63GntP/jgc7UJ1icNCV6Iellm6DATJ5AnuiAUyqWDbL838Zg==
  template:
    metadata:
      creationTimestamp: null
      name: k8id-web-app-gitlab-registry
      namespace: obmondo-ci
    type: kubernetes.io/dockerconfigjson
