apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mattermost-pgsql-pod-env-secret
  namespace: mattermost
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgANPQa0yzlMQBvilpMe8IDqhX1afGujm9yBAMsLUocPKIZf6t6+r1nOAwkRwufS8AELJkg7Fq1CdMxRTaAJzkjM6M7wn/jfcuf+EcmiEZnKKhm8tl2PdvAN9IjvkMuhuaH3NcnRSCOo7Pu4/OSF51moMrBprRbTcJtHorosDZpTrx1ckBWrJhA5TpmmLqISFCvcUyR8/+fmJLS/nVLgKkSdsnWFfw849q7+vbUulLBgXmKsp8othRw+QZ7R/E8Yt8qsJ3M9LLnfrEMKqF9nGqv/EAYYgZ5/OO2FARhPNBGuQhqLSXZArnSvlmAXKMQqw9Ni09YcpsqGBeCjS8FOhP9npUaEzZ6c7ljjVwrwiH50K4tdU+tgPhedsH9jfbZfYdfGkr1cjToI5sHB6nCqAPNBmz57CgA3U7SgRHHPx8fEPxpt5t84CChjx/5s7K277be6hkieG5f+RTl+qyC6HqBJ9F7b6kPf7OHf+DETBq0NhgGmPFSf7vlWVEDbP0uD8mg0JUjC5vChCV6Z7RTF7ZH+Vt57BImFyoTk+SO19DoM5En2NmOPWyA0sK1l+fTQqhXybHeaN4bPH9iB0HrJ7CnlFiIcWbq7YM7Yd+3pHSO1fmgH5T2NJE3a4GsokFTpSarebziG4YAqfhuwgfnF3s7aW9HFKVZ49Uvv5ZefNEsn/sQypeYw/oyxRtCZxITIkruTfSfiuWZvVptbrG5fG9+6pSnYNunsfB8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mattermost-pgsql-pod-env-secret
      namespace: mattermost

