apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mattermost-pgsql-postgres-pod-env
  namespace: mattermost
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgBT2jusaHYgVD/hq/lgZf6Sku9z9qpyYF45cSwHCn5fFrkxAKLVXvgtSImVc77a3mVTYed9Kwf8JQGzYuqXRfyZR+uKIzForkuVrO2WKQkBRgxRargQS/MVDHGP5mIErlnoFjPf7X4dGj+wDv+S8xfuT0Solb7bBeocfyxTyiBFjTl7QTep3o4JpPImmLSqdc4ITclRWYrsbh4JuLtooziTOVvD1BRzUspiUPV5pEGrBe4sOg6bjjgVeDal/aqZFVnuIfmTsgigUhk6bLqGkWxU5c0/y3S5wGFChUuETFdYyP6pY36IYTs2qoSXUqpYcf8DQxUG4a9i2M26jBC0pLmLekDOP90e+Xj4JTfCckS99DyODaqgRXP1zC5HkZFG/bq2gq30TQQarlpFlWrrmgwJlrYCVhsoQydRAV9jqpRIG3mzX+aQv3hqMu0wrRvpnLvEfGPWUfasqEmydAs0lwQIp+oJlSL+7fCazOfkbMQfe+VRnJncNRqaBFvNJRXNwvtWpDXCTprRMa8kLkfymzd03tK4QQ9qPMMT870OG6EajgEe2lUq+yIsQq4xnEhCDJSOg3D2PWRRU9fVgZcBOgOYcPrxFitRYf4vv7qtMxDvWaJ2wjQTOHz4YwRDcp03YH8hSX/9QHK9q/i121jpTN8AJO4A8hVuAL69RS/ObHHb6t3g48p33BxrRyM4oTbkIPHeiPBtyBaisu19AWFsxieIAJ+mvcI8FWs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mattermost-pgsql-postgres-pod-env
      namespace: mattermost

