apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  destination:
    namespace: sonarqube
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-helm-charts/sonarqube
    repoURL: 'https://gitlab.enableit.dk/kubernetes/argocd-apps.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - /tmp/https___gitlab.enableit.dk_kubernetes_kubernetes-config-enableit/kam.obmondo.com/argocd-apps/values-sonarqube.yaml
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
