apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: obmondo-website
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: obmondo-website
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: obmondo-website
    helm.sh/chart: obmondo-website-0.1.0
  name: obmondo-website
  namespace: default
  resourceVersion: "17553008"
  uid: b22b1dd0-fc2a-4b61-8277-cabd6df84205
secrets:
- name: obmondo-website-token-kn9tb