apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chat-token
  namespace: finance
spec:
  encryptedData:
    token: AgAbd67OY5kgqF+HjaD9bVpfFECuDdqYApX/h4p01NmWwWuPZ5vewX4llaKJYYOaxsB0Yfaw6ngq0jPhZr/tQ4RQKYNrGrSL7cL9J72xuNIjrSuiYBy/IWBVqQyk+t5N/5EO0SEsdju78Vi+Y8Po5qh/5ia8filWCiV2IZy+ovAO4b7KMjdQDL/MUAAZ4jS+RdemSiQa3Ktx+yOD6LVyRQqJ4NMFoZZkfzgvMiuyZl5tGx7ujKSX6Z7kxaH+qk3SSEboT4ss2INgWIfQWzRU1RBy2V9XvII3FF7TzadQijmI1v3CfAMeQ5R0ZQU321Rtbi8awW8Y3I0TKdk8KdvLTvW9Vi9aJSJL+2cVl81tGlhYuzNRwiCHXgn75jNnfENoWto4SXkNOX1zj2eSXpjKIF5yevRmnwtDcRrPzkpRDOiWDQVHExmGpiSiKO7Z2Fynv1z2EsqtsUpf/60PzPPwtd8wybIy8vI2Mqi8Iy7OLOy7IdIxOYtXo6jfuJnvpnJUuOsDzUN0/wVZQXsBisDNIfyqkDhkC5bT/eMpdqLo1e7GREbxPLXSs7i1f7BN85C3NSbM33/FpH1mwR+RkBIYJ8Kguy494BtTLJeOcsb2YLOHTh1XxsjoVZrLxtYa1CcGLX4uquMyFNc1601meuRqyOHiKD4QUcz7UCpqJ0nmW4mYKYuhBw12At54FPMUvDUi+92NpcdGCai9F/+iSFncKWJDdIme4IAPQQb0
  template:
    metadata:
      creationTimestamp: null
      name: chat-token
      namespace: finance
    type: Opaque
