apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chat-token
  namespace: finance
spec:
  encryptedData:
    token: AgCLlyQldMDEC8XThqjYOVWzrOKIHg9P9Ujj35ceIbEYPHA+xQA6FcEOGoGllGeQmn6BDpgOkpNpusxPqVU/5GfywZawG/nH4tG4ytfdxdTpLUCyOOkH7z4bYeNUpXAXlRHPH4a/huEPlGTWoCkMc37gvZ/EcI2GI7bBqZ1IVbJSJ2mAPZQu43D6N8RdXvUr/Vr7gE04V3YOStqK2r8XsJaDO16KVeBAMI18mR135Fqut2H/9Lq7spmkUzEmT7IEbunpqz2RfR7YaHKzVvO2GEpSrtSapUIn+wj2F2WTqF2GYIQPDs7T6fy4J2kG9pmTOLkigSO4qlc2DQYOYOwVvimy26CtgAdZeZM3i6i2jSB9dJWENdjd+pecEwSeugyFGS0ZJxjQGJfYhbrCKd2EfPDhR1DSod6+TsWOhOnw5Uc2Q+7Hhn6q4kefAlvmDBVGS3BQ3QzKrvlyiqxUDkCykw9wddNufGm1QW2Wx/Blkcsy5lYV7H0Rg+ttCWzpS80E3ZcoZz0Wssu6QjolYHQYBSZOJal+w76VcnCcjuzaoBZ/HdPaeuz1BVbLxtnmKKsJKMQqUFUZ9GJjcD8/2ByDAbvD2FdlxzwXqQQ5v7uyfYpfbedSmimUgTcWDz3FqXy5bv8c1RIyxE8HVkQMEOJcB5a+8eijzQ/fGjdUizIqrC9ORpKECOM1CN5Wycm3dlLaoj5v1LhvrUSN+ggJQc/2bT6zO88QRYn3OgtxfQ==
  template:
    metadata:
      creationTimestamp: null
      name: chat-token
      namespace: finance

