apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: g10k-git-secret
  namespace: puppetserver-7ejidqmfi9
spec:
  encryptedData:
    ssh-private-key: AgDV5K9K0PH5AYRcSUEtsQs3v8NjBbSLmaumCX30DC9xXGb6SMcfJiFCjD/VpixAWcfAQKmn0H7et8rrtRezClK0Ljs1YOGUE6gRB0G6WHOLCf+YEatQJd9+4yWK/ZmUzmgfzcsFol/cmDpeAYqslDiuEUIQDqKlxatAnR0+srdR1lHXIHW5UmcZiNfT6AaG1OLYR2/ZKMfZNLezmnO7gXS07sHq6FdqtYMvIHe1GQGKTsEUJplzXjokb4souoVMzqdZSzLJBRO6tuOUJthGTm8pxSqhBnrwnKT7kGxHd50Ibsne5+P+vox2xe1hnW8zYzdpXjHERpnqaSNEYFh6o7rPt/AEo0MgwyHUlwuYmTiNoxac3f424KTa6KQxL0ZEj83O3ZLBr8nbADRq7EzI6OP1IfWaUHMPm+yyTzFbhDUCTZmOUHWSp0VsZxFVsQeQbTqjtw74ZkU9m3kMoP39gWfOsCSScJlv+BbrbRgYPLfq9NX9lwttX0BrPCVqJBxP1AZuwmHUNwkjqddKJ3pmLz/tzyItKcT0y1mRzdtQc07Wtv9gHGU2hpO1IrSDTb8HAl19MmSmYvh7JWoUM96RbJc6JjevdBWbCvZDLJgGjZ79tpH4Ty/lDM1XrROvUQYlhPQFd93LR24LUQxg9SlB7a7rPKgyg7Wui+xoX/j51NKd8PBI4M83Nz9MIuaFexaAZWvZlujQAhNsp1uouhy0GBJeX/2j0/xeOzhXBQpd2khNvbVxteF3qagDT0oZ9tSNr+60oXJvJNA0/QN43lmntxTIxsxmluvmTA19UdUN6IjfVt4k9GhsagUvA5mQJGKG/aKyLWIdIBA/B17tYSUpFk0hVPWQ9gFnH5Kay5NraW/DYR9mOl5iiiHFCzs/dZtZubAZYdToU1sgBbP8q56f42nCU7zrYaYW8eLOzL+DiuI6SedIiup/QhbnLJ21xtRV0m20Z/qWJPMADLAhooQd+kujVuRZoFBdk7aP8lccYW4a6G8gVT4rUGGkNK9i2ptRy/w+yrJ6VtA8kjycveuCoEBKy9+I00DjWMgHf3lqtMl3gmSyQ4HqvzkDq0ncw8aoU/VGrMzMx1YylBHFlt/IkBoQ6VLHYcM/bptNfcUA/PnTt9vypabro3sb/abdp8TKTjD5+DrC8s0Y+gfT6A19qZnofmcam+v6RdD2S0xX/MhXpGjFHR0LZtXI9R1RrWPxpZfjj7bdBB0GQZLglosZrGM7+KpeURZCgY0FFzg=
  template:
    metadata:
      creationTimestamp: null
      name: g10k-git-secret
      namespace: puppetserver-7ejidqmfi9
