---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgDS1NEyK+FuWp3dYKan66ydzOzdaDxJwbZYEV0lMfNq/i44jo8jz28Zo8vE86KMSAJ3wFW7gPEn9x9YZlaK97zBkIlTPlUDjHq9PP2LdPBLfPpKROhYcqEHzfn0sNAfW6ZFigzgXr8uCIJfEJicLxQESXcc9cU6z78KmVzEIkkt5WmZC/l9A9llku1mLU+5GD0xlwe/L0qTPpOwb8WZaocdUCZc7oG7JWIQUiGZl+PPd14vdwxjbSRrroeC95p6jIidb0TQlTh1q91o3IYDhAWUwQyMWG3VN7tUhaM9bpWk+ia6gUpjCZ5bGLa6Vl/QakEgWWH4IVpjdiofPjq3Nva48mTWYQfCCRAkJA9ErMfuXnPCDUkUhkqjtBt7UQeoyPfMkbyiheWer0PQtOFbT84yAhG0Y+bx1GQYR9wp709mMkcnY2bBF1jG0bpfcRoaDToe6haVSsLD8sNCuUjw7Q9QJ+7x97M0TFu1C6htkcFEs1Y7Q4PvGJQY85Sz7m5fh9zXSF7sNqsZT1IuuGnZmzjsm65tU+0IDdxHhl6ykUP7krMpfPyNmo5ie2VylK01pPgxmpU0eIgJMPQim3XmCoCssdK7FHzGnD/R4/OMVsaJZ8z9TLKE9cRyHa3pkmqPt3s0gB/FG6+kwcaMWsYsRubLx2JXvDaq9VyCrCe/pbs9RA6AaJ5mTowRDTPEWmyBS2xeUyyAZORubga4fJc3qQ4FM9hyKFvWUgJqQ4FDWut5AuNxkCQAUQ7OsOcrH9at4KsJV3tFMo+GwmZtvZ4Lhg1Q
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
