---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCMIt1//wB4M05WN+caXJkt7209kzl0RHmQ8/NzNY5bCx8UopftHdKQA7E9TB41v8+KqkwVVnI2GPSVCIsrat38t01U+im0bg1+AK6E8Z9/+l3dGPfWnRqGCoo/qzKm6ZVE+xybsAAQ72lut8a+2o8dEdwf1FcLgLKh3FbqhguOfXKehpyBqUUztPYPLCXii0d3peYrUFZmCMejT/h/vYInVf+qNKLTxmzErpb+RvrMTW7LN/c9vBr7nilUiSvGUBbVGhA+8iWA+ulvBPQasatIiCEnKyIvSf3wEYfzorULtnoltj/58xZYvm5JD09L1hNlFxSoEMRnrV2vnwVRgq/WGkSo+fa9zqFFVj/idGLxzD9S0LoLm6MiJExGTw2lLwXFcIqPG0w1MulhoXiOdtDH2O2Wq3yrx1ukFc1KbKHAGt7ReGYEKbU35yZ3Z7QNcHmOpA1twbASp8i/Y/fdae9mb5ykjYKNp8S0O4aWFa5X7ud3KUhzBiSRAXdaOXY+NuKu1SIBXE/oKU6xEjzSdreC6OuE7v1voZrENIo4N5u8bmWdu+e+MeAVgF4Q+rO/dwFr6RCRvHCqiBAi22gUhGSTzxJyuIG1Et2CYs1AJiGXNJyNaBZ64gFeOyFRgm73sYcBS7ibE7r52fqqn6s5e0+coCilOgoXIGVwY9A8aKoBezltCw4Q167vU5jwlPAbmE+Db3FSMaaXVZ9z/84ihW7i1arOLo+2UfQZQquyFxAtThMULxCnfJ25tJC6PMvc1GVW3qlwDcZerEe6WPUBuJY3
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
