apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backup-sealed-secrets-pod-env
  namespace: system
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgDP0pQ8sqCIHXU5V55Qm2NhE+gK/3Z+vLBgahH3KV5TeuAU/JE9XvHwumUTmFtSl+Dx48uMhAZHwl1QCES6H/kwQuFk4VGQLqnXKz8AcHLQDF9iKSylvSQdSAZIvnXh3X+NB77bsSYQNMMPVk650dJU3eGMhdHWxLfYfDkuMwUJfMGQdg87tZ2NesaQCKbGzva2WwuzUMz5GIt8yzcAFPpDzzLBHi2b2y2WwzsM9uNUXJigze8cQNbP/bZltHncDQKGtSb4JpFSTOmL6y0DIqen3DvUE+jfmSOKwHNCnKt6hX894SCOtZlCt6TdcxUEQEcumVegdb7HDbhSsbpCDraJYlwqH2bggolQUDJ2QvfppgLPd2ZbtrQeHV9CkP0UqPEqyPt7fmfF/IpvPHpvAyPCDlU05O99QhrMoE1nOfzDQAlvBmD7znoaDag0+81rvQVKy3FYknMVZet/mh4Cb3hxmkzWDhB99Ih/bliO0lETHXyELycXZPDT07nTQ9x9bwuXefXGFfCQJF9isL6dtmGnOU1tScdq5f3yY2/+Cftt8roIQTtB8YaI5+zc+PnWwtn899l59pmWfKgL1Msem/nJ9Ek0NRtT3SwcmTAl/hnGWfiivawS2zsKyZklDPrmMDbTUJ4zIjdTdxWZtbaKt4cLfd95gCy+/Vd1kHuLsQuF6ZelcFZg2/2ykWXzEP0IHfaPLOufAWUPkml7q8cnwwYYcF0Jkg==
  template:
    metadata:
      creationTimestamp: null
      name: backup-sealed-secrets-pod-env
      namespace: system
