apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backup-sealed-secrets-pod-env
  namespace: system
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgDkL2/dFfstc7anDuJ0wKrXW+kzbn5sWvxkWsOOgJwoKPT6xHFGZz5+Vysbsv18Tkba1GCU9kJC1miT64N0YYqLeDKQtDa09GtDYUz2K1adaG8SpJuDIFCOLYlMj4zDO42ug4H1BlDRJeN0SWyxzt06KBhDqvYCGGLs57iQlQfSPPC8fYm9TpyxxvVv7KvddvVDw+gWKt+B77WkZk7bazfsvrOHp+1nZwiLBulzDEWdESeaCn19Ysrrgnfl3XnMYnD+cVeth+tFvGqyuwV1WKvNt+U+/IfZhmmxJBoB0oPozSJyy60wemfsiABsdD1apV3lk+8+ZHezATFfFSbqct86vhodY7L8UXMh/2kpBEfwCGNQPxiEA5q/TdoDVsQwPNZwOtWPoNTfnD/Sgij30Xpr3N6TKc5yDz5VPYidGAlhB3HEcOdFGObebgrT68MZ+PlWbq2sEBHwN/uK/GnPN3aTtPecPDEl0lfVXcGTkH/fs3RNmaS+VZTp8tIvkQkgHoVqfHwnbbywovET2jnK5T/RN1RC2r3vAnvmUFq1JcSN9BW/bkL2fSxB6vBt24Lbp32Ez9IphvJpFjCqm1CCD3vhLSreQdGJHMUQnXiLtID6Ezzb99A6cbOyBoaQPBc4DoxmBGD1WunofwupIvW9JyAJHZyuCsHoOKrBz1H7cjUWxslwEmP/Xiun2xVH3L/CKLzGV2lsUBbb6ABtJFJ3vTotMTM1+g==
  template:
    metadata:
      creationTimestamp: null
      name: backup-sealed-secrets-pod-env
      namespace: system
