apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obmondo-web-app-gitlab-registry
  namespace: system
spec:
  encryptedData:
    .dockerconfigjson: AgAkZ3uKI1pSgXpaGvFhosznURs2C39sXYusepYNAYYGyljq/vQVJlYKX8nvmNWw4bqldeMx8GpUP14tjBNWbDEmY6a7w0+1fjzH25AHguQ43FRwowHw2BQazXUjgWgPI9Hy9HpWO+QsF+IITTYJItZWNupYUA1v6+zjQin/1XI39pY53/78dkge7eE7FQh0+2QZBLB5K38WA97NSQsPMTNyisUQzzx8fCvUZEQapO1F6f0vqCENlsY0X0tlSPrkcTSND+8H5VrJxqTpv+TizfohiQvIH53mRylbiZODZGO1BCYkP2x8ODSsfa+UrI5u/7vvULJuK4NI3+WorlKn+vJcMGYNZGIbFxfDw0VetMsxFVAUuvt9rfJ9SeaHmcqDehCm4UNe0HTIJ5DSVgszl/wZZ9KboLNq/hUQQRbbaokwiB/6ZDmTgF0m51K+vp1ESzDFyWYjSA7F0Pkha5ymEL5z36ZWUEWOgJcIb1/v+grxt88oUx9yGAQeC6G8ithaiJ86tdJ71Bh5opCCm/wjLNwspnRTyGQfUqqc1K/tM34vc7YiVsTA5DrW5tU+GGKKEivAhzrS6LcAeAXlaxadXOxz/vLhotrS7zsNs0TXHgLO+c9BV9QkMRwjuJdGN3SmEJF+SMg3nnqmD8rv7SKFneNDYXPhy9vUavoaaU/Y2sZBwJuDEgzglUkPU8mg6HpxW74MyinbSLdXO0rVPHRXwUsVqdxPex2O+N9WBTWG6w4D7/PyDqv1tQHCUQw1MR2npou91mzgbKGwg5SgGkf7F1IzM20RXBQeR94mzmhcqbg9BermHwj4a2LOQskgYP8kfUju/iS32ukCktHOuF6ulJS1Ftdo91cc7C9xFaRXltmfLtvWzqbwXKB4MK2ui8SDBN/ghbBfjvVETGlriNIfbN5CWaXup0vF3kP96NPz0K/Wng==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: obmondo-web-app-gitlab-registry
      namespace: system
    type: kubernetes.io/dockerconfigjson
