---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAKcIuWzv3aBdMNuyONuEcmBZuHjWt8TYo+7i6KW3hajeOaMaA2VidkIXtOkGH1KEcwT0ofuKksOfJPpmfgh9Ot3FM4B412I6H7S5hXVy7RG3KtEyl8DHsyOyVpPLEVOlaj8Tesng+jWL1npiAFCMTnjpJj2ugkvI5H/FFpPAlrgLxnAPGpHMR4XFucFqMxYjzSAgknzX2T6vdFOexiePkZgwOIzJ7qItDX5TtB3eh68VSoFE3PdXtU1CmTnjk81vNVBuY2wvOQl1P7J7KOpq/u4p0aJuFpJpNV8KgFShSGvXCoCUebsx30obj10cRIf9se66I2F8gWFxha07xq2kmrxbrk4ZtmJ3S3Ds5dE0ucodQ/A0P0Oq6KVPWD0Vwf9kTInqaPR5l/GxW/WfDjeTre1caT3jq7CjQiOVEMVzpPb7UB8mya9Np+eB+5pYEHSK7YrFKRvBbBEzQAZyREFapoiB0jWj+E45ZDyRF8GrJpZZNob9WmKd0Tg6HiqS+WyvTFXXlWiQdMq77LD+1jDEhOoC0UuTj80Uqw4PLCW+s2W0/Qd1JzoY4Xg6hprfVSO43eY/4EVJ/AUzEqK9l9SIaR74hxCPYu11cmnhW7/KadYbNJjB0qzQrU1n7sC3Vf5pBpYxKd3OYhD/mKiY6CNI73bOhDJi31jxTRs8U+k80rDG/q/Y9EQYfNXOTBcoV/sECTD0yiyQWO5mObICIXzsCBeIalo6n7HDUrHDasgjpdp/WqtKMy/kJ8BLIuOoMYU8u0mybMu0HZxS9+4HruYidA
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
