---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCXsBkLFDePh45qqfhYWOUQZXDOTHt0SL6j8Cz/mXFXh/g/yDCFjOfb0F+WqEll/Mhypn29jg5sK2V2CHUGZk6BOftAAePYc3FLweNHVeZDvPxJvLs44Zhkjk2aAnQG2VDYIzn4twO2fvJSGn0qR3+22qSporKqRM0MTCBBmreSw0UoRFSTzbciWCwDEwm1KwxNVIuBGSJqr7h9M+29nMjUiMDCniDn+MQ1SlLbLhNwxjZJ8pJG0KZQuOIdgsQqY81w5RXPbSH36pKyNqor+sJXYxzSzH0chELEfUO7eVw1Wzu6PmfGj/3zKH8S1FA6jmh+6mxzrAfneMXwNOi7RZkynFtjZ+AKj4SUfwO6SlhMqisyRgHDaIcCJ80wNRDEClshdeOo7IbEnPqDmB5+RZ0ryeW9S1rV42bql5Jx3vPqJrHb0rVEKL4Z9lUC7HbynLVOM/lyj9NSMegWsAe4OA4RzSoshEHExBFL6wnxO9D9XvS64WqDUJj3QA4y/OgOo2eIuox/T9bCnApWvOyjkYWfMLrGzekJS8LvrNwjrgYbFcfMZah6YQN+KaNSLWKZGOwyr11qjVLytE9C0Ad6deQM4yzw+pPCK0pcZvIeVb6WqFTkd8vjwck6btPwXVatT5lc9+XLT/emLmci53alukspsC1pkuzXbl4/l0Hq3+YisqNhtraB6yDO7zUX0xVwJ8CdCcD65PmPeLyHvZQu9aO0Ly8mkhYYUpGlPb9B5UALfvWaFusJ1NpM98llrQVardxFSfqYeLUOznnkCyxapQ4i
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
