---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBaJHYvp3qoyQsp04hG4FwyqLb8FUuBpgRakYW/WoGIJIc0kH4WzgqXE2t6H5gOq4LpSvQ176+rc8qNDSwCVSNFHUFWs46o6prVnmzuDYxGfnG+ntWrJv0SeDnpZ1naxBLljUnHp1jexgtxNM8f3iTX4MqJC98IcB/GzV7v8FWPxK4Py1NYEZkd8/bPPTt5SeTRR4PTiLdClTcPuI3O4X0qj9V9c60UF/ttp+aMSSu+/wgVOCU2jBnWNzUWv/f0AVT4sVO/dvNsBS7bKp9vyh46cVyJWAB6w85spZxlm9L5tgjbWUFxl3ILhGgK3jrkZ4SlgLncdKCxJSBsp66OnttkIHIy/1/3hFxOgeC98JKCuqimflc9bl3UyGrjBSUw7D2NOluLSzsJRMTmeyS1/0GUKj/8nDuIjqpNyitw41yJZCOp7vv+eWW3aSqin5RHuLR3ls+2vRJbw9Gq2NDTuSyr4R2CR3QKt2cMzL5rZSiCIGZVN2U9Sivh5UJejtC0/1YqeSLZX+MmrL0vKIHfdzoNBfYr80uvkJa8Dwrr/m3ZEhBkEEGtW1TerhSLYzkOsJ6HI3/kqgP9cnMcx32zI29J4R2hHuuqe5XFAI2gnhhNnweaeWHaFWWhLJwOsjFIFUUl31Qbo5SSVNYcXCkrPlCwyy/dz0lFifpHu/NpurRkaVYyrnZjWZmFlvAHO0JE7TWKX853MTSt3IFRDh3P13/bkh+TQjpVOdEhwURPtpeZdQlKD4UrSgQvnwaqOlKoIApi2gs0WOa25EB5SWkCbVlq
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
