---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCqaEJtZDHnatR8KBN3KYwIUl6T6PM6oAgVG6X2dhcDHHfye2tXNjczVSD3E/FluMKzLsyISMng/EFC59XAmJlovtzB+ZuA1GDsIUJpbVy668dg4IDxtUlARTNSbek0ZvBE7l0uypRqAwYHatC+TgJzRXH1oBjgFwppnXiGzN96Fv+eAHIGPAOr+ZVcJT1kEeQPEnmGPr3sbmc3AEL9zlSoXj44Xvg+UBdd8cH7x+nETAHLCkmBfFQaO0ZiDOQ5ENaTpevP113ZnMsc7v1gG2XK9pTq5ge9Q0X8f7RSu2ReugmevY1fS2UEMbea3KcDpEIBI3gcxMBptYiULiUY5kB86fw0EGwJSD9zv2MUB0wyEFi1jyArfkYVZ6px8SlkPHReXY0AOxgNRRmkp6ROkraIC0n4NNUEBVIJvnEedhKTmqn6QXtNnRzvQWH/hyyPgwzGMreWQnJXZCrqOzydjVcJv5WjFAb5k2e61GvTNwTx5pAbvkz6ygMYgiyKMzIXth3zAaXL6gHIRezhfFCHlWW0m4wWfPLsYWEYJTon/O6DGu9OaBV+eBVATA/SwWB2Hpf4SjM9AUXhGh0FNBGbFCqBgs+X8UflyxJc882j41qYiEzFHe1I9qdscRdpTpqOALz+kZeB4J3/WV2o1tb5BMzok804qmL5tSRX1EDrLjA016Yq0WQ5ZvS0Alc7dbXvB39P/9Y09CHqOnNLhRva1bwWbTr6hkeKrAp59x254GYa5rqFZT8/IOfmwWDAWO2rnrXOVhGCV7kJG6O1tcQ5oJcN
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
