apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: monitoring-c1mdewxeah
spec:
  encryptedData:
    webhook: AgAnpixbJPeI+rMDRb1vRaHh0wO0o0ZwDp8NGsij+39pEIyq3wljNNsst6U7VR+jWsVQR4TSxTYu4bx4nFwg44xBF7R3oHSE54AnXpJazdkyVZ5fZpHE1l24e4bWrHBCUDFL1Zp2UvFy/19FelDWhs05aWLcXpZw2Dgz27uVk1kgdxM2mN5fkeVmSrR+EsxPfkSXbno+CdZm83DujrkZgINg6gM1GYtrRTW34Pw0SMG8scDRZLq+YlvaFB5XQ95MYrbbQyH0lb5zmdJR9tfc4xhreIXt1t7TcC1YQVTCOKev78V9xcZIh/Xb3saWVZW+MvwRVDiHfJutNN18Lc0Th9kExOPDfsE93r4+w4x2qfWuhn8U7H5iWGG+kvcFcq7GOAzLkt8HW4NYIla89yVBWYrj9HiPMTkAQkiuaXUgoZTpeKgqoR5P6P1WsUxFBT6A2Yh9ur5PLT1nzqV7DfOvMFrLE7gd6TDdxusHjcsNMxg0rd9cw6xOawuCeEvhSgfe/97nrgeECtd3yH3SpFfdA2F0rwksysrWvJDrIzM3iZRumiesaRbqtsnXON8gJSgKjFVRwrpTNUGHVa+vpzdKW0gc0kFvGrUOTMlhqlLK9DVmuSw9RVVxyKdEY8W1aY0AJs9AnetS5OX+ShLCojDxS4PogssnijC/vWcm5PQdF86/sscXgVHC8RPd7sX8B5ah3/YzOuE9INu0EKmILewHvRLYtxoQdMF8RSLG1zkLee2cws8sTBF3V8Tv8kPqGwOATIMTJNj64Es+8PM=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: monitoring-c1mdewxeah

