---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAtHW2HVzDRlLX/pkcHAY/lmQwDLpR6iO5KWQYwRLG1q0Qh3ThbFaCrZVah8yvYbcDXXSQaeup4HIUfTAjCaTqHPt3FtOMzkr9A++Zp4ywuT1EfjwQ2GOx1HDj95j/FuIwkH49kddVx1lFM1UWOQBBdBZCHCxv+ICh8/7+xk6GRz2WSTSE/J2RP+qB1N/+IZxPyRFRH18NfNbkgH06biEhUDIiv5KyEMsinmNcrziIt54LZqCT4eQSFluBczwoHWgTEeqNvW9MCJpuWQJJABgbe6Bg78TYvJglUkR2VWeSvvVKHsg0WxB5RVHbftx2We0DqYyvfOMmHx0ZrZjRtXtxJ65A267Lh8h3oSX2bXxohvKEJQXKQ0NbXqXyr4PebU+6RFYNnTosnMtPqf4WDJ6/fBt8vQfkiZuT8MOIw8GM1dS4gtFhhy4rVxBR2Y/3Esghe7RqDAamO+dpnuxIxFx7HQVwA4HtkFOdcXvnx7uMT8muqO6+pOkBUfwNwIdT/Tc0H8z2zgHWivQwphLhKLMNlOTu/3Ch4K2BtVU/X1lm76Yb1hZxGX9G65rTypWU7+kMhceVlouLZb7qvAOWXfTVyI2Fue3YrkKnf0JonKuzHVg0gVlck99jUppX/Um9lfsz4lGRF9/C7NcS0UPVbxvGJpZewnj9NCKrno9+8IoloSow4ZFYmQ5oqgdZbtwKhRs0LO7gPY1XdGNtPkZkr7Fui7sFHbYU2e+J9U6Y9j8oJajYlb8TY0HpUgiG6ri7MZJ0V8eutzQuO/wxmyGciGyu2
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
