---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgApquM60zqoeqU9S0xXlVyL9+Hx+quMC+oYcngmBzIaRr4y3nQCnevIzezEdtQgCdVjHFcXDsOPx/6mNptD8vbmHZPfOy8xfM6oiQTjGWrka9BgxMpJxAVlyl/sjlSNhq5edUXtmu1Q68lEOeDi4cfqbBzS9WTJZcK/VKyRPKODydSS5JhaYeoUhm8r9iNjyzR1aGyEsQ7FCHDYSOpX7Xbp0vPGsIC9/ibS5hCuuzNKIHdiDuVS03Xu6QerK7iQ4Qb+OYKeSAO7rbyjWoSekCOQ3dnD4ibR04DHUHdoONQjnuTC24ajxYyDaK9prRFdzpqwPMidoW7IgHu4OoLLzwpnwdouvNF9JJ0qHEv7nyiN/HgZteXkIte2RPkoHQtrGLOjaNP34gNNFDvvm3KiCxlun1UKreQD/KohYTzFXABgWnQQ03sdMdcF0nNO1SK5Rk12odpz2Ppfm95emAUoV2z3HFE94pJQNHx+2bjv6Jx17Cl2oycO+2Q5WlSBJ5cuZPtsDws/3d4br2SkcliCHk1jeaooLh7cbCITiJNmn1vWVXqhu+qSIFm4z8qCXM5mYulsUUCvGnUQLc6ayPKq7Ix/22BgpDRxINT/J67iuRBOt6nbQa1OBnvhO0mrvJu0x5KFslcie9K5JE3gKt/v/3IGI4mBKAtxPgOK/DtR6pKrqcc9I+SGnVFfzHhqZniGbuphPD+EHynr3YkyXPNr70ITJBOAMW+2ExrmPeMAo0CTlX4btkqC/rYWuJHSvAVdM+lYFcyCLngv4O12/FG9b7qC
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
