---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgASHH8FtK+PIQzJoFv+7xGtyShStzL/HqBc0MGavd1YdgyLa7+pVRjhOFR7SYbXyZUyIXHBgFCkmGvMDo45sLJ46Jiokth/r9co1dk2zxt9hfDc2MW/A3lG2xgCuHX6kXim4pmaH8jG+IvJAz5YKDuulIwOx+CdDKGNl1jOmIIQSXUpFE6KRf0jucACaiIxiQJnPOYASCAXDtujVXLkshlsdU2M2J+ktjD+fpFvrXfqw6VdLEnzIIjMVFIRM7zh50XEwVcbPx4G5ud2Q0lPFomABSxx9FznQqPYjQncdiXuJov/3+NaltWOPRUb87WN+mfRJPiKiKyPp5Dieexf5fBJk29sCX3/Jmoab9rLwkORBGqytklPGEaKRbXf+aK8lZXmCIQ8sqOIP/Oms7a9DGbOC9RPc8aM03KoqdvyGzly6gXEApTWzju9wR/dQJJSigtaNKqAXhKUzlshm6t3LcJgcA5lP6uy6U+F2pcbmUmAt+Vaf+S16qtJHWwe5Iv/tMmD6eHWQFHQpUES8R12Ygj71lrqkVPLM0q0gtqtQ/uhhOnSX/GZ/6B29B5HUsM+WEB4u/v9XaPm1vZZVN1WEo+50R4wSfg2AdwTsyzOzHk4zefYksOzDw+X4WCjF6l3ynQTPSb4jLPPT608A3l/hDwS7sW3uqizLFOKA5XKIhlb9XvLGxlpaesnz6sfBnw5w28zcGyZ8t70OZtqz75nrli5nvGmyTSG1/5wVv0+z5bRnWqF8QmP42ld5Ianbs4gY5hRNLQPQBg7QXlFcU/1w6g5
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
