name: K8id config lint pipeline
run-name: Lint CI
"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    name: Markdown Lint
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: markdownlint
        uses: https://gitea.obmondo.com/Obmondo/gitea-actions/.gitea/actions/markdownlint-cli2-action@main
        with:
          config: .markdownlint-cli2.yaml
          globs: '**/*.md'

  yamllint:
    name: Yaml Lint
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.HARBOR_REGISTRY }}/${{ vars.KUBEAID_CI_IMAGE }}:${{ vars.KUBEAID_CI_TAG }}
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: yamllint
      run: |
        yamllint --strict --config-file .yamllint .
