name: yamllint

"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  yamllint:
    name: Yaml Lint
    runs-on: ubuntu-22.04-htzhel1-ax42-a
    container:
      image: harbor.obmondo.com/obmondo/kubeaid-ci:1.2.0
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: yamllint
      run: |
        yamllint --strict --config-file .yamllint .
