---
name: yamllint

"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  yamllint:
    uses: Obmondo/gitea-actions/.gitea/workflows/yamllint.yml@main
    with:
      dirs: "."
