apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 26.1.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: hcloud-csi-driver
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git@github.com:Obmondo/KubeAid.git
      path: argocd-helm-charts/hcloud-csi-driver
      targetRevision: 26.1.0
      helm:
        valueFiles:
          - $values/k8s/hcloud-vpn110/argocd-apps/values-hcloud-csi-driver.yaml
    - repoURL: git@github.com:shubham-cmyk/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
