apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: artoo
spec:
  encryptedData:
    .dockerconfigjson: AgCXd+oEU/M0BcpBu55NKixdeoxisO3o1XUCWxRL/BT5XFDaEJ9fuFX/K6x3wJuKO/dM4QJAPDzM6ep+Hg7o6k/uwdGAI8HyAB3nbnPDEkhQYA3rvHeIzkwzyf8JKMfrdQWKI7ITG+9Ki7lpafBfVmVI9LADh25D9r5jbhmiMDiTAhJWQHArb9H2vXklCMwUHHjqJN2tD7S/4QjbRpr39uTjGBBgz5wLhpM+xeGWFoYNpj66rZZuDKCxgu7cvdz6wxDAGdbroi9ejI8DpYU/AHgw+nerKUKdR34umhU3Lc3Wis27U5pZSloKATP3pPJ1n0sWIWIfmnnH/fwG7teYfhO5mJmpJw8IOeUdcpio27CckKjqeCucMtGSBGQX44iylhHmfTr5Gcrxl8HkIn1Wbmi3RQS+DRRRpWsVSHdF1zlAy/PIswRwTz+UGrBqIdAPuOnOUFsOqJKb/lgDE64ZqU1o0TrtYjtRlPdNcdBBt3vRjlWIIBkwT1sKfh7gylci2suFY+nBsBPG18D/COg6O3wMe48ytn2bWYKcQQ989SffaNpLv5lhjy6epR8lqGRaXPQPMXlFj3r67z5bI6UjPJM+9xLou7HK/EH3D/jyU9gUtMRgLPltv39XmJ3mcxhLwrI73h7GvR4KHcFsKejBRbj0L3X6ZoapEphHFb3t6rLqW+/F5WAUw16SzsTCBYuyOm9iSzxwmhjv6GrvjvLzbRg8cO+TByA36yFDt2j1snoWYnkcwilR2mNL/Z1E+Gdo8Do8zYe5YQMnbxSuraogA1ovn0AEVRHtCXrIBQCTVO4czIOeIAu6urVZIdjmsnnvVJ8yMeMS1FgXgm9ZJJFzjbgdPDsJQmRd1RSFnsu9KgVnkyqLCYaeKvj1aBeNnIwPa17LgylDZhE0HYdE3QMSmQ2FumbaKXo/t46o3fgynu3mJ2BhZOTTFerSSWpT7ZjzA9hYG4GWIwmfOP553Sk+JpVW0A==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: artoo
    type: kubernetes.io/dockerconfigjson

