apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: argocd-helm-charts/kube-prometheus-stack
    repoURL: https://gitlab.enableit.dk/kubernetes/kubernetes-config-enableit.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - ../../kam.obmondo.com/argocd_apps/values-kube-prometheus-stack.yaml
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
