apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBxq+mtMXrr5S/4OIh93aG84MRqgzszd8jCJkz7Hk+urF/UhndyWLDx+jKLF1+dBX2bT/A26hnKGRSXK0egdd610mpR6mVfyAKvFmqWgNRVzLsd2odW8h4MIIHXQe8tGZqrr1NXe0S+RG8bmLD151st3U8R3MvUjGV+GrWxSemG1fpCpW9YFQEhSfiYc4Qq0UVKof34NvvFaaC3+edqRIDfUC+8M7hu7chpwZ7QGR/jhgmFf4Kb5pszeTcKy0L8cZBZBm5VAhhenIjKmB7tMDdHKr2G5wse+5Xux+k60L5c4h8BT0yC0keMbwFSnxBFL/3iTFNkTNt5AKw8Z9qLAqB6BpSBGoqLZnajMHyMwYlbV1SVJ0DdqVp1OrwPD/Xjd6iPkDDCuUtFx+Wd0/IduTCI1Vr264ZxsWWSEw9ByPkcjYduSyCFMMWsH4oT4bptyh666gDWs+IW/UBWq4tOMIF+8xoWKzo7/dxQZxBXTfQrTvxJNiunb01mvR0TaF+Q0srrCodwdU6hMQFRM5h/x5lfNKA4ERF0aAJAhs1EjfVl0iMlien0l2y3WdtMOBe54TaZRq+uceXEYatwWx6KhLWs67ces72nfbptRnY+lBds9+BSdcKUUXSRK9Jue17oFnJWp9QrLs6rC86hPbdxi3EphtQ1+1Q09SjN89rPVZuKaUO1PyKxzmay7DQdkWIzZB5nz/gV7xBdA394q94/dxDYHOLB9Y2X9bpvCwlARzst7U3D/J/m8gTf
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

