apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBtcwOWq0tN7AtGzdzH71JM4WJRHhVB6n25stTEwBKWoHUY+RDxLkJjmW7vUtSTyMCUsj5sXy6yOw4uNmgWgMpQgmELR2vum88o0O9GEmMONAaD0vzhzA/uuIo0Bo97Ik6AyLvLwUNl9YzFGmse//6/K5DbXVhLT1qTC6CXjFaXB++9dqWbn9byhf+KR4Ba9Pnn6e+9okdOwRhp7hNrJod+vsxyMPrIqNQxWx06SPtxSzH2Z/zu4VQxTIbWtRhVapgzn8NLW1e4X2x44DmgDY0pr7s8Kk9SzZh5ekP6U/6zOAgR7ywW4Hq/YwrJkfkLYxlprGusq1Cs93Gd75H+UpohLWID4EUmNRDwK9KqqLax7vfK+xhW9UB8LMymOvk314AbOCgBqcGABm+56FkqK+4ZN+ZiJbP4g95VMHfHCy9p9YZU9rsjNFyP/k17h3/ZzAtmXUJo3wgkm2Yv1/GshR4Xn15mqha5nnl2xxDz/yFO4gx9oprc7O+FtXfaemaP5o9CHxJrV8mrkQqn8DJSTEn/qaQa6DaHxLMFRqdqq07FGlX2WEQOhrUPkAYjxgQf/9x3qhmQ6jd/fQpVBcPZQE3DcSS1NksVEqbdDNYlz6xqGH+vuNrFePQ18wpqawVfMOlXrrkof7V/d4bJK7cWWWc6x2VYH+i062uZ+I0lIWaJNvgSUGqkEqzXdnWfcN+U+XYjDiF6WWCLrK3xry7eqfEfYnivhiXeBD9v/qIDszEeLB38kPff6LJP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

