---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAKWYSA/4w5qYHjwAq4m3PhxAwrSHkpAZnOUuwBKLcwweIk5CWlDZaRiiobJJncEUmxCoIRJqdLyUs49ruUhsut4fJX8EQwuRZv0xiK73nNplYQUiG5g5pEhobkgDkD0fyyE/czTDd8+ltpjmBBvFl5ePU6fciFdQmNefUjdQgj7trDMTKo/bENW0ONYqn+rp5bfDMtDxQ8VfQVMMBc3CbYubK3SYC6QExEhXPNKX0KtWrAgbkwNXmCa3NcRgpM5j+4/7/cFi0ePp1o8Je3QPVtSlEJWKIa/q2iW1CBSlhg3aKd4Pw/yUi9beyqrOVvQ4Xx7vZ/jfA79I6lGAs1a3PTVAznvcKuLdaQdGn/if/UTAvZqEcrRLqmuVVmMMErf8qsmKaJ0cgD6ZFbiUgxqk037Bzq0muZiilqJ0k896e3yJvBG7XBmASsNcnB/nvc+/du8TjCCs3Rw4bp/awD71Zzmd7gQgrJT5aTw9MVXYTOamw26WR2Gmg91xz84HNaWW3jcUiT2O4H3CYykti2OhV9gKqEUAs9hHjYVxIshrsxNAU/FYWHlWfoTiZpJasZj2JDuq0qrMLzTuzlygLPp639ymEKZvb5D5UcePFr/oRVSrqpPuxGF9McajresYQ+LPrKP6fwxu2gnLVwIIU8HekVzirG+m6n0Nm1ukDttbbOcqklzAiEVpaE6PxkxTg+5CTbWDfrD6Jzeqm8bRy/d7zALNFLx/LCfUiUOeFDkOPfQM54WvlIZ9mw
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
