apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAQBqqH/pK2YXmDm/pHNYdAMCGJLjorTREZ0KZohrdbpzQXgVudbdaiI/jef28F9RDsEMr156Zwi4LElVyqhfLx8WOOi36dJzEyA/HosnDZDg9s6x/3ldDKLP2XanC8r5EvqRk+Ql0eY9dl39YemsZjdsKTGDZFF9tbikP8TAvO9IeAD74fTi6HN6Gi33aS41MQFD8bUmuLSKe61T3WPxxqlz1JOIqmrch6f6z5qvx6qI3VxorEhv4DnZws6+ruH4FI9e2WOE380uGRi4LQ42UvniJPDsOJvtsltqR3FIDHTD9tTAC9qo30T7imGfRZWBkwT8d/pzsZITPVYI9QzeUrZk7Kk5kmK0hwv6aLGunBY/YVnfDcls+kDFQpj2wL2XFdsfYw2LmltkPoEMbJYKx006QZr10nT4MJJN9NiEtlGqbL+DknPFKnOsAiBfdbLEioYSmHXajkJ8kxLQMjGS94paQf7DE4ffm3bTxE7p7pdpnGkvDXubPvA92LH4uVK8q6jXdP4f6HvWhcaB9zCwmyY88QM+Me67ApVg4NZYMpQDCloycI87/Xq376MS/NN2FFHUouXeUdScXdSnF65drg7BqAZxnPMQkpOirv5bV0tLMm2Sv2RhxCUaRVeLrj0EmG44TDd2nhdq+EnyFmg5Qiqp/epYlNknCggcmIfQsrUNM1iriHW+a7/YIQCK3MLhicksad5wQx17Jztj9aK2n3OG+Hp4hbBxv0KITeWdCY4Hl21IbPB1y0/ZS5oCF5Gt/IKgqlojTF2hCfBhxYpUpb4Tsqr7Jeo0bKqbFuBd3r7U8u0QXs8EX7Agc=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
