{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloud-credentials",
    "namespace": "velero",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloud-credentials",
        "namespace": "velero",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloud": "AgC+QV5F+XOLLTLQASebjv65n9t6fgtM2IGKNOy1g1yav66nho8QjnNAQVVD0+/cCLuRfU4dLM8S+uoDN8drFi3kCZ6NFCAGh0yRj5CdvE8vepebUfCEQDEoLKSqF2mII+B/eEwGmJEsY3e5rPIZMWiJkdr1wGY/ZkmYt0Qh36gKeQ19dH9rjh41ly9LwB8Rbx8ndklEB11i2BrX0sbLcb6Ws1/wfcPwRIaV2tlWltP6vpvxDTxboPKPRzxN5mJG6rES8TNB4Sph4kluSmeneCNII06vXgNVCSMCSxM1JaNf7qY5PCwoKExkHzEdww3BttKl0J4gMUrI6C1DTn59lL6awEmaBENS6oi10qqoKK8O197B1TTrrAPjD8v11Dc5lowUz8VFGaH6QnXD9llEaZXikUe4u6bZLOM9OsRRW9hFeTgWc6D17XmnPG661S4/mlItHD/OE0vYW8r5wgqJxf17VkQqEo4ClfKmzRLh7lU77e9hL9AtKjTIQwjggeW8xYz0vS5D3YzrSZPd9N4uWjOreTUp/yFlcZCwF357pWXyFi7HVqjaS8WNplCPJsptzwOq0dd06zah23iYZBFm3CTyyFS3mHK0NIpUCmKeWOETzZDy/+FfFxX4WZrb26yrcsJiOcFMuUTOhhjXXrbr5FJqpEwzz83bDsl/+mcgKAusS2pfVOvIwmx2f1ERNG6WvYwVC3fzJfLEUIQOq0ti3YyKQObZQO3/CVbFIXjsTcY9jZz/IqHRe+VxgWiL9SdXYaX02+SwaAAfHBsvHn2CbhwW7HBv/CnuIbpW7Fv2eHMoGDPFxEG2YtZn1Ro="
    }
  }
}
