zfs-localpv:
  zfsNode:
    nodeSelector:
      disk: nvme
    tolerations:
      - operator: "Exists" # Daemonsets can run on nodes during cordon
    securityContext: {}
    labels: {}
    priorityClass:
      create: true
      name: zfs-csi-node-critical
  zfsController:
    nodeSelector:
      disk: nvme
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    securityContext: {}
    priorityClass:
      create: true
      name: zfs-csi-controller-critical

storageClass:
  enabled: true
  poolName: primary
