apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-web-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obmondo-website
  project: default
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/obmondo-web-app.git
      path: .helm/web-app
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kam.obmondo.com/argocd-apps/values-finance-web-app.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
