apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail
  namespace: argocd
spec:
  destination:
    namespace: system
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-helm-charts/mail
    repoURL: https://gitlab.enableit.dk/kubernetes/k8id.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - /tmp/https___gitlab.enableit.dk_kubernetes_kubernetes-config-enableit/k8s/kam.obmondo.com/argocd-apps/values-mail.yaml
  project: default
  syncPolicy:
    automated: null
    managedNamespaceMetadata:
      labels:
        kubernetes.io/metadata.name: system
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: v1.24
        pod-security.kubernetes.io/warn: baseline
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
