apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: puppet-git-secret
  namespace: puppetserver-enableit
spec:
  encryptedData:
    netrc: AgAPq68nOUFnT0hgZb6zXSfMPCIGz1adf4bAyP9WyahwhIPROxhMxkUygnNKs5uf0PXcTIUK0IlzCiClLFrLlhWY9ekCKby4DxJvX2KzJS7I2qiZy2YoGUz2aGFKjuQB/WUktmpWg75D57ZKsUmdAc0whq0VUx4xLXR2J3JW1t6zikwGZGaoLgeo4ZTJtWIDlJOjP6ScLWSJv4yPS5Ye2RBxkxCUpZL+mrpakPwoUyQ2ITsMhoFqxTZoPJ4O3tHNBngPNj1jblCy/L8M3AsuhI1o9WyZt3x36DB1gbp5np4xpRKUpgeA7js/Rc8Ocoi3IRBvIgXFfyDvDJvW3ytnPicMWvb7QsIa/t6CWwQUiBuXzs4js9bE0XHvBqUaoqtp2B7fSRKUkwl5hzilpU6eJXkVQ6sjWyVoawGuhOrm/9rbadwBE3u2vzddJlaxeN41b4z3lnYd6qRpbpD1GmOoQiqp3l7cj1F/bSz1OZRSrSV6zBS28iLHm5y9o99wy9hP6d4N1ORBHCi1pSGY8Jnd/LTF1BgdL91cWyRgBc3GwK5TCPy8iX16n1crngYsVl13x4bQ5kivbD4vEAKJiUbfw1L6cDdAzK7ZfzH/FTASFU9EoxpbAMXIzLenMaV4vDfMHhqbQw15zSVIshbyUG6pHjhCz/ubfWvkD6AuyOU/ivcyb9UhMG+VTZHpWRUK/vFoMXz+9SL3OA4f7jee6jvwqHhx6gIZcB47lOPUf9YFDhoZCUbAibme+9jIbiDT6lHLnULohbytVq++wtBKPF51zIPFGxRATD9ENTOvAGQNNqWnlErYJhVnnj8PKHQ/ZDC+5IHalnyx
  template:
    metadata:
      creationTimestamp: null
      name: puppet-git-secret
      namespace: puppetserver-enableit
