---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secret-token
  namespace: obmondo-website
spec:
  encryptedData:
    aws-secret-key: AgBH3jeuixyu8fF910yFfmyGUATdRz4PokdqK+cAtqFqVJybBo86f84WZtXMX0nwsrlZrxW9oQDPFD2yYddOYZsHE7w1Gn7L0CmUSavCwvKCPnTiQY0nrn0HeboHxlHzNR/8s9FAdkhyvORSRqhYa9VvE6NYI1P6WrmL23KLdZMP+waqFA93B2fnI4zLEZ3VByZm1fMoqziNnqCKKVNgAmGmSMrDUQBObHDcbyRRH267FkZ3lL11IBY0GdHYf9cIktpFh/3Bqt4xxTBK8/pp5E4bNchDV+TuFePNXzQHwCheIkKnEaGVIzJNxdL/AAwPpNAU0bFzjmDgHSYDQdqYxYAkISaTBkij+QJy2+awDGVPrA440g/HkaCyl+teTFOmi4xMlE1TiTYCkuD7taLGOdE00DR/cErSI0FFqqTAqK+6AKyQg993jUkLepAKJWVfrJ5MQeho3QvL7W8ukMGbqCvBTWZ9hezgAkKrfjY0NVsZScwPShVti8Iqk69rJ76zwv1MUYp9XVMSNyg8H9Lrk0wF/bvchzE98CqukFpqlevOPP+Nzi6GwuLyFpF0Gb59AUTi9b6U8d+TghhpAoUVPIMWvCbRj+1cCKpgmYA/TIJ/p+Y81bJia6TCgQCNWDmDlb/rvVMyyDv9jvwfW7CI/fNjCNGI2yZws/1HwpSZGQkogU6bAWxq7w+d82ytZUeK/ivTaJYCTB2nb5q6z9GWxDwx9wfGMXjuyiI=
  template:
    metadata:
      name: aws-secret-token
      namespace: obmondo-website
