---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secret-token
  namespace: obmondo-website
spec:
  encryptedData:
    aws-secret-key: AgCM651Uhi9z6iXN4DtKh3eqOhh779zz5z/nyWEx1nNwcU1sK+514tGWeu2vl0a+HzZ7WdGWivunRdCRK8Nr85qZE0wveStQh5IXU0Ijjniv0wqQq00rIUARovCA209BIURPStX+9RHJosHn0Tcthqku8zMU3gacZDkuYLnudzXYzc9k+DZANUPVo/g6v/4b3yGN45RRH7YOkjP1ntATo36LVta2TnumN23SwZJiI7o15omP4uDse9StY34xeV5ODnuKuME+v3nAtfDWnuMAtBXZB3Vjn2ds+feKAjYh43wF9+2BoVvrw/re9cBb3z02feEMs1dy1uTJsxj0mipv85nombgIa+jeUiDC1Ip7tVsm7B0TnZum0TOZyce/KcScZ6DBJDWqRhXPfGTDj6zYE+2Gaigj87it1JD2afQM4ckZUDOudCsrzGytfvjUIAGi9i+Gw7UVi5dcGuYLyKgEPzYbTyRVKv6QTPpzaWfD+zTbpWFNoknEVdc00jWGDbNH/1uUYEg6PyZmAzFrzb0qTPVpC3UjDEGTjasnjsYx02HlfDw0dlI0m6lGjbZ9M0GfvP48sH5pGNnYhS01fCIGF0G99vmZSkHIt/sydFFjqtE1Hjt8rAMI4/sUFxFN46BaB+qXrLZkZlbZVjVpvy71s2uocHRrLNMsiejzk9bd2aFVQZ4G5VA4ze8GTTIeT+ZpjRHDVFRhiSP45mJ0U5u1YHks76RbLn0I4aA=
  template:
    metadata:
      name: aws-secret-token
      namespace: obmondo-website
    type: Opaque
