---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-registry-secret
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgAslxOcfDTGsVmYJcoPsT294Jdn2ZXy8SMcUdL4ux9BzhtnMsSUnSdPvflqBeHwZATF4wlSEZcobHV143F/vvZ4k/kS+TJIBahjMCJWh/cuIovWsZIXckx4LPPRLdKTzzW9+WYolRtodvwAUbEyRcIWMtulsJ544PkhjJpjHPrP1skHdHTGcQ5b/c07Uv40vkhkSuOpujiuxuO9wOskgTZiSFMI4P2rJpfZMKFpgmB7SRMznXkmytf/Evn/AvQL2dQns9dIyg6b1Tu8nNDOw/09YPmK+WKt/HFxaS2fXaTXzclJgv3zMaY3mUyAV388lXf3ll6pTuJyysWp7p+jH3WsWw3+XzQOwDnViei1pLvHCVqwrcfm7KqkaT+97G9S9Ar2bPupOw6EpQgt0c3qhhN6vbFECdnS5hV3iTbSfGZwDSb6LlitmnHpaki46ez+7Kv9VM7NWEnWqp76F3YJCz4XMLurCXWNtE/nLQYLcvp0FajXKperPEW1aZH/pmIqCoLR7W2/UkW49OiPDVdlV5nXESLoYv5BpCVk3PNucLaNV7W/v+tMzqZwltkezarDUIKAnA7iHDYUvYUvIqpg8WN1+wV4hzh6R6FiKkM0FCjv4cofmhAdoP37VQpUBDhtzURTQnRfq+jaaWxo5hpnQydy4Giq36YLY1TfT6yfsE8J5gYzjaUsfpa4rTC6jD/Ss9PVnmacPWE1H1ZVm3Y8UDQei3UP22nz7VEKPX/bxJglqonHTeML3bATdgDaUE2GtgYy4tQEs92Ne24ZPLb597BopFyndL0DuqHFRl27+xkW4VESE3+FScCU+TTUVSfW38qzjxijMqGVv40v/51ukwMfCnlqu+kwdlg6P92QsFh7gG5paXnDXfg06hSmoQKDT0iY5cXkILqQlg1N9q8PBYghCiMH2Fy/DjZLNYLdPgpp8io23jv0VK3+LvXTD3b0ihzG9Ws/9hJKTDy1T47jK+CijA==
  template:
    metadata:
      name: harbor-registry-secret
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
