---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: internal-gitea-push-key
  namespace: obmondo-website
spec:
  encryptedData:
    ssh-private-key: AgCyS2dVFD+6lcSROpphJFuVwm6V8vIU5Okki713L7HEOdsGXQHLyNm1aW1fNtWH9a6LcjZ71XDUrMlRkDpdnqs7pWqB/iB2WouSEhjDhz8mSHcETaMFy8J2PekIsxKOp+DvQJSC7YKN6f0dg0mMabeUbKXdR4JEHruDjYnpIW16/jyH/f39jEkw3XdhLhumtaIZSziO9oDBzwRzba4JQ90L12m3PTGA9I3R/dk7WAodvwBe2MUE8Yu4ko5hpI6U1G3WFYZuaBNJAtbf98TogCSnUQMD6zgMaq/T3OY98OtZaqPnZit9yDp09MNBmcxYgfnciq3SYu2n/NpWou0t7QfO6WvR9zA8IH1SvmU5aaLRq+il7/DNTS1ec+bUQICgUNEZJW5r/X/6GeOCkPPFiGFdxZS5XiysWFnTmhe+SoNVlLIt3s9TmiWWDccHlVsSp0c/dDHzXQGYiyKyu9ASnOnabpTxRyTr4VQhRpjwqbut43RQwiB83655nIxEGMn04r8B7CYYeoq6QIWV9Yev62Jmcylj/YlnN3C04sIbq9aSu2glBmDGL1WRWSJKwAaUYv+hgRDBE4Is0NQoYwb42o+moT+EA/Iypg7W2Iz8ZNgT7wkgloQUeocWKOyatdbKqgpB1Br117nDFRv+5lGyZkVspcxTa3kSI1smKtHb5r+c2PmOw0xeqAVXYFIEtgcsdWhL8A+tF/HewNwReECFKQVTkueuVMTZu5PCBFOGxzFftRm4cGil1GrQ/6x9IptQWkCk+YSfDAMWgwEZGMz0szoQR7FcdNAaKe3zssuCnhV0pjxXA5bjapfGT6t41Fre0AwDACazhKSsrQsCniT59Zw2Sx8L2VKrDBeNQz6HTDHWcSya8ZQXzsM80bKdrrdlWfyO16YpkpIOpaFbfNQW0DIMsoM/eR/dup/5o2TY940LV1YcekuR57yq+ouOCOj4pYzcFlGKyv64UapzTvMi/eJrWQ86kRMqjLuBo23xJKV76nxEL2zknN9yawubuQxm9jY8jpgI/u0i9ftKltK8mljbraNQ4Rds9pQm5Yy/j7biowfK0U262krVAXuuEOD5ovLZtGujXSxntC6Jai+mjbbd1URMKP9oDi8SN5Chk83WqF/FTFHfLaYloFw1+kHuCx7zVNkuOt3/Iz1lv197Cwd8eHdoBQKqJuyzFgzkp4B44qeEa1idxeQzc94jOUHVEI5YbAhzkjITWvlBOlJ+PgLPOZ/olMf25bMywdeRawj+W+wqNUvGwS4NaMPQXB46QeXA4exY9p4D6BuJNAn8olb6uLbFvenkuKiTwf2FHDkTEg==
  template:
    metadata:
      name: internal-gitea-push-key
      namespace: obmondo-website
