---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secret-token
  namespace: finance
spec:
  encryptedData:
    aws-secret-key: AgCpe0iP6f9wtBusFKdVOwn675KXuo1GuHYnu63EKlFn1tITfYG1Gfg8NSn4MKH2+jRt/9d/dhyFygy9xWtQPUeZhtnIhfkw7qGWZWfHXqj+HctAU1OwCOhVRn7rhMSKdV4kNL+Y3MbAfaQlFmGfPEScoPCJrmPw2QBIwIuxXpdhhMNu7RGngyEsq/EhH5n208DQOi10frcz/2wlWm1hGMNhbmRMynlws6FdxNzavw0r7V0L/17yduGukJ5qfO3W2u2Ctau0jQDblqQd/fDXBu+LZVOfT+gCuXr7IDQD/PW6RsWdCOMmLat82SWav8KI7DjnjBphh9Cr7QcdtXwlxdhYM+uSrlZZbZ64liOR/i0V1/dL19PhybRqk58W6ett/jBFUjvGYWb/EhcqobehZ/w5Hssls2M8YgWnVf541dLEP0U5WI820u0aIR6ymCIHlv3dQLgtkDrtexTmDjr5GmiMZW0W3/CnDxj9zeGR7ld/WoWKmv70Ma5l57ozSMoRwJEfIDFHgH8VJTW1/Mmp8gukaIQriKQCgAqTryJakbNaHWDVWb06b0DsCMgbCaLZz2nbpKp5BtKKO/rS11eo4rBexTdDg/QVneCgeypcUWGdnUizYQ4CthrQuiQiDiExvHrkAK8gG+6yWj/txuX2ZiAbnM0DPOY53rT+dqPcr6ao9x42ZK6O/3XMtPnROSnoJphOg8I2Xvi52IxQAqcsLruwYGCzXTYGzts=
  template:
    metadata:
      name: aws-secret-token
      namespace: finance
    type: Opaque
