apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBSdeoYvPz9P22V6vyfum+EHOtjVNBra7vePrmw8fhUPOUvT+oHe6SSs+TxREYTXzHcIJcFQcmL6cYYxand9g4TGzFIxtwKkLSYRjJ4C8C16XC9RHCXa65sGK5uKjnhAWclDF9yeD5BCHMdgiYXtY4XOZ6wg+QbFroaa3gvA1Xk6d9N2XGJzYUFFnYZjvIIYyYwzGC8dZyUsrFR/Td42slj9+xE2Ypjz3tvtKzc4wrT3n9UPGa2vI9Lr81ZgOMxuE7sQe1/PmL9O/BCbvqM0HTkx8CgMSCAoxylDvBTnN86f4g5uBY3wam+dChI9NqJDU5ZaAA1rSE3kePb6VwibXP73fCEPtkUcfuz6NaWKwEdVhy/b5iZcv8tMiBTcEZ46LvxquvFw2Xi7K7rOyHrzT7gR6O6euebkDRsvmtgPfhrTeaHprkpXFK6dMyvM/eInrW7PQLRHdORiIgU0t7KzkFK/aExVCHy2SHL7p+0hd8NF8nwt/kOATmHhIFmQ1vj9DsgduVDGIsphiirFO24wB9fmD8LTcSS3OOKUgrXzFhLiimvgUQHoQcSENtJXgemQdWi69Qv4fIl+TAuLgX29/iKl5DRQByZHMw13xwGORwk4iMX7OP38cHvn3mUoBttoTPBp00eFyOqUlGq9zf9jCJRLBle21jiUx2iOqYSh0TjNjDExYLHBXEIHYpPz1Zobq4AwhvIWwS4FvwHhg//XYwev7Q2QzJRghKvkO/CC614rpO/9KUQujL4
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

