apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-webhook-secret
  namespace: obmondo
spec:
  encryptedData:
    gitea: AgB8F/U4nrF/UGTxHLH4u2/apTMGciqxrZV+DEleccELSmqEBteIdk1cJu7RY9XAkB0gu0Lq9DyGH/9vTP94xfWN0alDBKU19QzlPdwuvfQnzvNHC6S/Cr0p4tb/Qm3ybdAe9TX3YRYLyASt2r535YgcuGDd1jXVwaRZh5rqVmqy7Ay/FE0BQIIWI0XBIkAT/sTIBKiOqhsvbM7QXQpRK3snP4qh2PDwGq+zozlUP6K/L7woWJztefODvHf826AoZIDxaEvdESHr/9nyvbc9L4QafJAd1G6rYAqg1t+Ta0RBhuX+7i1v5M+vo3Lo2/RVnG2GIeCca8V5Abazv3TwGGypGRGnAoRsT7t/JhCrU6Wldob4kZ2xt8VYDOJDK4G6Yl4dVOD6kxJ59thxqvfZkuW7kQEJmKCXUti7gY9G7Bl2PEXf+W43Duj+N5qtyROpa2R/x2gMxCM5ZoduV3ztMweSgBOzVy4F0wrNMrk5fVhGALtepGtmo/mzsamlTeFWTFfTuGUKGZ6s4enCobMhHKV8DBBAGC5/f1vHjT4Zh3an4UojxZupDr9SnnZ6YdhiZgXXfsTN+IQCln2Mkk7AvjmjpSoSB8A2IJ8bHuGnomBx9q7jibS9ZvgSrq3ZsNxmZD+VBVchUpAuIWJ0i1toY7O85h0CTeNg7u+Qw7phQJXWrmr8e759z9iETuwzyA6q1ti+Y4VszfkfWFHZphEw1jt701ivXOueXc8TcWTo7zo5plc9Rknl4oS3b8ehQpBuP4DcCg==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-webhook-secret
      namespace: obmondo
    type: Opaque
