apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oncall-postgres-pod-env
  namespace: obmondo
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBrvWfrk15d9SHG2fNkbCwhJGTRfcqBczWwu5nnVYAZHAfnI3LEGZgWaPjLATNbe1tLx72A4ish9CgRNXhxdBfg1ppniJhI6/yyLmWaKdXo+CdV8u7e7lndaToWE7pRn7G9Dq4P8MrJoPNSlOhyhFIli4pgZYj2v6HmP0pF7TQ0OD3LhtlWX0wXKZW/UgCqP/8xIGappGjzgOPA4bASPDQ85HZP8dBd7kVH9/530HMhPVZwWoFVhjiE6xekabuom4nPezrY5lyi+9HZpvDc5TrkP2dawr/zlTnO3QVABhTJstAYaUpxPEqlWLgOgoqdEAU4tY60UNxVCx/BS+aQbbTdOI4bhWn3vDhlBNq9BrWox3uT9nzu3G8jyk7rsNHKMolHGILjF7Ny/Bq6kiJEnX/7kGP9BkCnHfd1sQZq2W44TavusRcES/XM73UwJ5GSPu+luM5woJNESG001c26Nubl5WBEpJiKvVq3krhxIBQBNhbr5WTQeoB5j5Vk88BAgb4T19zXeEraEQzqvtARaklTMuR/Gml+GcYgQx4VD48jbroxGuJaGzl0kFXSJeiymFx80XMNVxaxwtHTf6FE3+HBAwOgg882Ke4sY2GHsCsVZVTT9W7R0YlJ7792qDKfIomgSqw5FBO4awbx7fC1iHwhFm2R7hvARFW2YqJA0K2LPyUe5emSeJISWZi42iIqpdxQ3jg=
    AWS_SECRET_ACCESS_KEY: AgC2yckmkE6CQKnuAwWYGB/+I/ucX2ArS1ibo0uUUbWXWiJ6hTfPl/pU3/9OaGNH5cWbvqEhRQtidG23IxhKIDVEM2JhRBNZuU8LxfuON5L5J/e6Sh9Io516BNeTrpzmD5Nm2g2PfkcBKMtJgodI/zQTQLRTWh2uRQT++D+1MWDWLMDgp9eRc+NKH3E4d8E25JYX7Lp4lty2EDGMK04QOmXt8cAsr17e/nHZdJoxB1ziKSPaEMBnztI7dEn2c/NhFvNpn/pLRv+1DhXc7NFrzDSR6UY4cNbAO2Wi3YXeeEtKkcokI0408EubpnEow8FhF2HccEBoT7okrBo5vaRw1SLIixj4Jj88LdRyDC3vCPV38876kHjtMLzFo7wsooqSAN9DfT7zqz8yATn9OYznfOj7sV0f8XtXrm3bzJ3LtITgb7twojQLSh+ASHDiAE2xAr3wJXTuZZOmxo/ttn2CaDXdk0ZN2vlcccoVHn7Vemav5KoP3DnZe1YGMyavxMCPffcILZlm4+MloM3mMm9AiVTwQHiBtXCnzvpiMf+eIRVxuqy3f7P/mcnK5FnEoDhIUmdzdpr8nauQJT3XS/2ifj98NxGvyKN33HZhcTSWym97srK9NVKYyhNFdWncfKEsxIFQqoh+kJr7Crlq3TnDEtCoG1zSSupepcZ89FLUIEXmISr0pG7fFFpA3d6dyUUdvQtoh56//WvZr2ojiSvee+m43W7NJYyUS/s=
  template:
    metadata:
      name: oncall-postgres-pod-env
      namespace: obmondo
    type: Opaque
