---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oncall-psql-kcm-backup-creds
  namespace: obmondo
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBd3nTk60g9/RaheMVodxRh6g6kLsUU8AhhpT0M8QjxtHYwg+XN1y5cwZmGZmXPWAZxaX4of9WFi1sxlw2LIYKP51hnK0N+gKfHtnU69SRTqgYZtTDqgKRC9eBR5JBg8zERH+kDVvnfZEOQr+k08LJXkjyhlrTg84MIbkIbk6X5XHPi3kVA9YjuC5tK9KhZBOkoHRhp+uu6aHTwJ1ouKjmhy1ZympE6hPS5crGpCQRLkckb1Krg/4b5+0tzu6vH0LjqEudOCWVqQh1sADpUgUh2wuzvK4GW07Rk5/dTE95Qt6xJzCBz9Q/FmSQiDFgNO/5PMlVwRD6ZZTDOP2s8KoXx3Be2jAQwTMSSbpVmAPhODXvh63hZ9YcpCXn8ETVZ52gnXhOy7TZrRG8qhg/np0S7GHgbt/ZzQafvMA5A5O8LTN8h6+vP3uCcSktv7xPiR1nVKF5ZilpeKtwHaOEVbwLK5jZk1JMFT8hqH8sLc0PV7OCzNdUMUv20njlgnWybVOzMg0uDCkO6Co5tmtbf5UQ005nPiek7VCVRylnetVtM2rSzSevl1f6pvBjVzrjKNcZDOjCEkg+DsZ6HwGZvMrIm4cR4tgeD0l673zl6LeFBcZKvy7wtNyUCEmoVLQAPbmWM14aevO7/Mf65CJ0bMsDsxDJqF9uwbMwlMev9LHz8l83jSm7sjF66aE7J6B4QSR56rmI=
    ACCESS_SECRET_KEY: AgCEupdDIgoLdR+XRUC/rrwWx26Dtjn6x+cA2wVj47ifaFRzB7rPJIaqYd/+uhOm5Xf9KqHjOZ1he+cbdSyCC31LaSQcfm6lRmcnDcV5ZDOtCGuF3akeWsmwB0oVk+5n/Rb071xg3SmgGgFNwlKINBfiLUgy49RgjrTCUVRP99zFEqaqLTKuKmQQ3V2ss+fkoP1BvXwxKZEOQ8fUfvOTyoijb2czlutUApIXGeu9rm/4glGXPl7VuyRapzd7VnVqjvvtCtnZ734rjbSvhtdaabhbBYevvvfrTgMIVcpmp/LynV2Pq6psVE3BKzb2Vg0JCpvAwu+PM9X8qpwf2zGLg7ikiHk6vDa1KwqPHWQxG70Ev08H2/YRWf54ua/PZYMY5zlSGc+V8W03HBz4pdIsERwxpYGuowZS8is2uLP3Vzo0YJG1KydxusR5tI2ukSU+T89lHKrK/4SMJHpkc3t8+Ack4gLuTfxYWq0FcJK5CZNJ2dMYscq9XqEQyW1HT9Ng7g6JYFHqArgDYZ1z8cqpyYQlbVd3MF9yC49KXbUX28fl2KwyoYPuzRoOMJ9sNzmiq64wGkfsGFKnTfGTRlAf9gZ/Ko4AUBJ3p0dSI2TmVZ8DAGefHgasowxmz9JQQ9lmd3mdqzmZY9hyGbn5mAJoz4OLKiwf0aGqo30rjx81BDzNmsTkMkJSetpK2EPlWaTmYA6z2C9tE47fIQcV3fhtr2pkisjoB7uh4cI=
  template:
    metadata:
      name: oncall-psql-kcm-backup-creds
      namespace: obmondo
