---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: teleport-kube-agent-join-token
  namespace: obmondo
spec:
  encryptedData:
    auth-token: AgBh53XNx6JD0u5CiQgI72XSJMyl9Bqq0hs+KNsecyCBSK3P3rcvBabzDPpBzUYvxhcO+cn4Tnipz9snrOVXJB2ky/7MCPaEckw1RO7Bq1yvON6VEUZTEK3mZpuGxzts+9lvPhTEt9y5fGESUrfeHKBt8Jp8RTa0c+jcJLDCHoCBnmlRu3rA0tT2v7ARsIxrrt2My7I9d2iyNHY4mKPMy1bgqylRCB4IcZWx7D9qy9f19iLlggqPkVwc24MFDQoVog86q4MSAJs1jKemtF7Iz1Cp/OXbuMjetRKACXGxUy6tbtIWcmBWcSQBNg9W/dhNGuepTdIQy8eWbsxJ1oiLJksy9lp2t6gCd58n2MjlPYVj46LV8a5xajT7oc5cFIOI63cUwkPU8JS1DI8KfudJFeaIPbG2l3y5wprdiWxt9lfv+2wTjsso7tf6litKZiIB4Rk+Pz+Ihd2inYh/xVFRnJeUIbIq51/UsFkvGlX8NPgSZmjiHpgpfI7BuNndzdcCztUn+ifj7U2vhNmHNIcWI6CWzW8OCPpAHgYUVJJ/KGlh06kJFWsPWPY9C1alKHRv+y1CZGG7r+at4+DOiFlunKzmN8TwKDgq8eMJDk5Y6VWPWrcbTgCVI5vSTnd+tf1RGGpggKAJE6mfMmKyxQiDrtXN5bazjFVEEwd1MMPUg1ggyohCP0oL0qU1/5ZsC22rC7RSPhcYrzbgjjWDQWLMjC8FcetQHCpK3SGd5Yxwb/3SEA==
  template:
    metadata:
      creationTimestamp: null
      name: teleport-kube-agent-join-token
      namespace: obmondo
    type: Opaque
