apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: users
  namespace: minio
spec:
  encryptedData:
    admin: AgBvbCWzC+35aLZ2Zt5a7dj6HOuKq2rJejtmkhdeIznFWVKNIMmAGE0Sv5d42Yo4kIZ6Av9YcyDxZEtc3IgI/hzU+AEtPzUub4jVqvZElikHQlIAM29c6pQ0qQyugUEFMGsWEyN308ZXupBYnb46h5Sy1TYO15J0er2SDK4Co6LlluM9U/L5eLUqXdv/yMzWqEdsGNlRPGHh379qT88PTt8Kwu5L6ztucL7MYuBvYapLGwqP9+W7m6z6d5tLHsRS6eReSDOIlrrjxVH0KpsHFwG8Zl0jbh17SOW2dLKal56Sxw4PP3DAKbwzKutLC72UIN8Wd7HAQMDueIjbxH0qhKcUtUEkEnntCKq8MAhbxsgkW1oMTxJGcGNHa2TTxL5jcYEa6pMXc16J5ge9cMH99II/vu7vrvuOITpSrPWYHxOK28O5DR9/n/r7nQopXH7PQ/Vv50Akn4JYrTW5r3QRgE8U6scWGoLnKaV69Cj43q1FmX5+00SkuaxxccntDpHSbTr/xTZXDQq7Wib+2utZ8GdTDekzaRjUWShRjWwtpj8z7352NsBa5JN9NqmhxG30j0fpmVJGwCn1iCo+Q0wGOHukt0ua+DyLCqqt/ChCDOdXqbBnpKb/gYGKC6zw0CggpIDSPKNqqlFsbVA9wtxPcWId+Ho08WEmTpe/81lAPop2xcMdedCs9w4i2dQQ6uDfACdOhi8r975PUt68V1g=
    mattermost: AgBSkoVOs319NqjTz7I6pCRWdT58ntPGR9b22FxuEHtjXyqoqQDdJmJhIHU6x55m/GKtmDWB0ApjYocjPxa/cTv2dMFHZf2RR81FwaQ6xkV8iwvL6TqFWLZ4r8w48P/zTRFLZrgLxrhwARVRkRfDbv9l6SVL4MLYSbWTaF4mX2Lp0TJQ9V8x0jWGtU4QTLSRrs9F/NEja513ZLIADvIM+eOyZ44qsk39pTo5aUR4iLDJyUEWYlEzNrquLwoCdhK9nVBGgTi4k9eSXpftjRvWampLHJgxd4/oNKa2+GfB1w5F7KRIhEnwvfaugRBqT6xyGrwzje1lm5+Akyt6IPK/do5sAULjSTpM742m9vdXuM8jKUZhjwDZx8NmTZIp+6blenZ1nMh1lThuMSk6dUsf5W7pigpRUSkRoQaotMx2kEuxsDk7hA1EpTluIbKBmWQKlecYy7Vw27tpdGquR5QQjvKYA0Gq2W5NfDCbONEiF12DddkJ4hi+S82RYMeYjeXj2PUz4i4/g2jVZ+XFY83NlSYH4rV4tjyeBXkBfImeEz7hZTtvX7r4uK7eu+KrVNC4MlYoDsFDPUyYqbBOid225Lm/sBmxlKPSkzbsLbQTGirMjCYakoN112EIC//vMi6nFH/zSNkH3kjzAZJjcViFpQnpcR8JLPHOuVSTcKw3P+bxOIpv55ezVowcrN8jYaG1hJMh387PamRTq3h65VEyc3A=
  template:
    metadata:
      creationTimestamp: null
      name: users
      namespace: minio
