---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-pgsql-backup-creds
  namespace: keycloak-staging
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAjCBGbLzWSvw+1FQey6ETYMxJ20gccF5DRthGTRKJdkhGSg9satVf7JcBDulD0Rga3hED1jMFsvXp3U+BLMeykTswe8TWLEn0pBo7VY90yAaOnfSFsubGWg7O48jSKA7ro9OV9tWefaUjrtgDxaWqu3kzLsRxxdKZk6Mz3sFdZFS9ewx6oS4EiaAaPkuxGZKcktrlZtjGAto2nGxVTqs+JBssXtimcJiPtaRQGyikV/bkuWQ/YLYXnAWYC9CdzsdI+vSz6nGiMrrpLdbBQjgENJIxn7MF1EEOsmLdK2TY9guqequPERl0GPXPlAqIV6rd0181bLW+P7dOWvD1Xr99PTQe7YNkSLWBVvYbfeQ94hXfGhPZYpI4SH2r6VJCns4cVvqoC5kn8ddmjdWZfonu51/GfNcui3lxqqgGW6+qbYEsuuV+8y7Vl45rC5CiuoJF9rN3LJO4MvuhE+RMwnADPGlUtXH5taIBxTfFhVjzhMLq1cWuNFdfUl3pEvx3ppelRlWcm3ciq07DYUMRNhJ0pxOl4daLCY0Xxxrx/apUu72LDPOPB7zztVad5SNlyYcGhnAqzhI7KTXiRfgwDY4sOtJP+RK/4Rm7ZN1Ezpvo70snK5g3rZYekunyOm9ThJb6i+tKgk2AWBNWeIlxjjreLSgA7dHmkBG+3KNO1jqs3iC3qX2L121aJlWNKeg6VxbmQ6YI=
    ACCESS_SECRET_KEY: AgB/4hsIul0xxuNlDQYR+tswLthzhi/+4Tr5EEUthDGeQ0nWjoMgECre0TVPm6a4yuKi1sJamjqlosuLkZi1mOxx7hFDaHsjGCNCR5AyfCRuX4DKiM3nNKvFw/4hqiDEKXfu6GqVbSOTLI4ypfnuns45G7So3ozJwh2ATFeh2NqQuPG0H32DtjJSxQxuw86jY4lFl1aldyR3de2vFAjWd+D5hfF2rlnMcZVuBT4t19mES7yMZBHhYOhT5ifAuZ/9L/uR3nhJEiIMsdJeL9BXpf3F90PBJ4MSxHzGnVCdONfs/edYsMdHwKwtpFCWLD7aWcHpdNu0YOyqBt8+Z1QYGhGDNVsvitqK+k4+qFoG6xwoR4CyAyjsbE+PP46BYWAhwcjENGXC8BKa/gOVf5Y1yJ/ztEvBUYROA0ksLRI+391FqUUaO048BqqIIcX4Wc9b1l1EgXVsBap4E8LiLqt4XfPusXFdbj37VYXscJsYruMKkQDp0IvTk6yTjnrIG2bRRgChc8f8x95ULmhX1Xc8MTVTuqXqQDG7rh4/TE8jLUMiAJ69u9OstjPK0lNCQ6VocCJ9AaENR0NBVBpB+y5fJGotZ55j/2d5wUiCAAO0hXOkGq2i4IfL6a2AK50LzvahLS1TUwxziDCmA3dWiBjGAF5r44eIvRwCtN/ll+grb9pEICs6lfQ2xrqOfmejPWdRPPT8kUdiaFecPgCT/EM+BtGEFD2KYugmnx8=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-pgsql-backup-creds
      namespace: keycloak-staging
    type: Opaque
