apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: errbot-gitlab-registry
  namespace: mattermost
spec:
  encryptedData:
    .dockerconfigjson: AgCfxPutGUdSURQoZPr8uemgVNv2ascim3WrLtauWUg5JW/bnI6iDteTVtp1pwLUBv6X8+uqo/LiGwBj0wTjCbMTe7fhWdu16gw55m9i9xAR1Hhb1ZksrfK0n5cK546rFCIZZImChKCYxyrlhhWtEQ2WQ1yzPpjbl8w4fXIW38vET87zfhGY4GsOp6mBCVCII1p4ks0FYCF3UJsUN9ohIZKl7LPsqNn8DlSkL5pCIBloD/ldGDhK3Q0ECA7lMnSYuI0qTciN6bKtQieuU8V0ovHeTTMppZbJqisAL01TlUxBvkg7TZZctNgSiWY2lCWOHyZdnEBmhRAJWzNExyQck7yZlGC11HnMq5Rbm8t8bVQTcw0GBK0B2LsFKSLjmLFw4cPQWwdnLWgpgHCsfH4YrYvOAy8qnvbR4YlkOJTh+sRrkErsz7PtMEIzMRTtEmPLvVFYsdOs+bcV0cLwqgWSes8lwZn7pb4/Vet2vmRuko31KMb3BbMPE1Sv5sK/U4xShmG4d2HoqauPflRGjh8V0wvBGgslUXfi8HbuKbsfz5ARLiiD3+JY73OlhyuVdvD/zX19GZhBhQXYkk1MdBw9BxHn59vHARBL57vJjK7jON7MEs+KKATtJNQk9YLKuhHDyfjLKC6fXMXiMJncTcaz2HRT0fxA8ffC6O5byw1RvfbhC+tkL1emTYLVfFeDBgi4Aij/SwwDOY/htEKtLVfIyDAvbw/xb65XgJ0CKrA99p+Sd6JXXmePeSZE6OXnvMtOWvl+lGhmekNMzoCKONJG0uZJ4l57WkeW/QpySHXsAt7YwtDYPa6ucbdsk6jp9S360ZC3NgXI/P/jTHnmnhYS6y0sYf7TJ4y020oWskxnzAWhIlibVObbvR+tjFb4jz4gA7Uc+uP5Oim3uR3wNGQszCT5hXp8P5EFOHMY0rGWh04q8Q==
  template:
    metadata:
      creationTimestamp: null
      name: errbot-gitlab-registry
      namespace: mattermost
    type: kubernetes.io/dockerconfigjson
