apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: errbot-gitlab-registry
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgClM+4Sq4ueQOcH+412tm8KBTiYi/vhBzd46k0jZ0J3o7a7R4+zFpFnrWUced3AFNG0u5io92ZecJPVkg0aKtwquAGDHNf+M0g7capuhXG1JbVhNOFZOBGbTqvifUTLNpApoAPxFhPiSCHeWlAp0YNA1vu6TWqk2bd5po/5Lwhrq5cc3Cky+DvuhhxoOuTsxXLmMGF9V+ue0c2A1AV9OM+f/WBtImvJltO11Ix7WiB5gYloPiVRlppAsFi7kKQfUnW3IAUcNvKfVN0FjT/qVBwhV47JD6ce7cKCxwc6q0XSc8d8I4DY5ABSTfd6Sp3lplo+zyLRZQrKxMdcAWABFzdiiS0Dl+01ytVTe0IlsoV9vEVUWVywKwFaFHpIcOBnBeBp75dmkeaMIFv9SJZlqlvJrA0RpUJrKh6PbxhiNPoA5E2WE3K/DX/2ASY65/nj++zymxZGvI2bnaNhq57hK5KBCMNt72WIpILQ/IKtZ4mMNNxEDGwELxU5/iwH6GQRpsQkc82IF5sJ9IWnI9v7TszyN6YT1bUDYNGW2OdWlViuCtJYP3ercjkISNcA1NoGDiak9OURbCsO1cWDkR2BKqBQT98oBPJWm6Jp0sGN3fNMvTFD4CBAWwJLkz2BPw+8ipYHLjAxXtuR6aFJHw2Jtbh6FRNxYfkipHMPI14qP6qEI8XDs+AD+HUwn3J33oIs4zUj6Mu2inaOBzS+AdK7sjtixkO4YwMurFBN8l27QuSbLQrCw8+2DIF+1Vk1cbQpjjEUMRgAic9ln8ktm9fBLVS+lrSY1Gd3ntJ3Qst3T/SnXqqbfUdk/Jho3RCnMFSYrBtjEfQy1XQn4bLIR5KkzTIw458RWOTjIDW2z0NQ6HX0s6Cs9BDL+sK2oJjy5BSzOcg3WeEJ/Bwofsxq7YG3rayXV0wapOUjPnQ8qDEqXTHJ5A==
  template:
    metadata:
      creationTimestamp: null
      name: errbot-gitlab-registry
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
