apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: mattermost
spec:
  encryptedData:
    .dockerconfigjson: AgAKyQrGHQmtjbSMiyoY+qKguuGJ6Bf9FUtv8vCAUn+7L1/Ep4gYgxgfJmMYifhCZc8ntyzmRA3lpktMc1GuuW4d0anwPWiCn19ONmqumo6QVedEHqwXLFFS87zY83qWzDIc0b9P4/sF5uuHtSA8HdzWU+veOkZH69Dq4W6Cnr1RbunZgS4CnrONDIMBoza401GJorU6yuikmgBs0A47t4yQlRAzJquQMdZ4XFB0P4SAdGfQZQo/+nLb/O+IGOQ68sYgvF9dkGECxryxBGaRYR15p0ODH35wFOGfGnOHGJ6TFXpmaOR0IrRFf3RVul3NuSCfiOTYP+78FVMiXDDn/mWG9X0fVt47q25bzcQCKUtIk81lMGVOU2MjEvfEiD17kiGnPha/Q/kdn/L7t09zENdoHVgBPpkRTzMM1YxB5ShE2ICBJHwuOylOxY/tiOSzb9ETcatQDWYIyj4bHTquCI4eZ8cHA+fJxwysaMyMKUcCI+eEYQkKFA3Q3hyF/vrbZ7nYbaxu2/IK+XZx6T6ykhZ9rtGm5mjmVJ4DOuM5YBp9O4d7RNXJfBbHsHu1XGQSkKLD19fUSgwkvb1ThEv4LAI/cQfsTcEao7gY48ASGc2b7lTRhVY3ZtQkNbp36y9Mo+YVNdL3fp0Yt42Q9BkS4rvFtwVWdeRciGtN57yYKfaTXMAMp6jss6ZwAhHVaCJPbXyuIfUF1h4bwcaMbWvYgPdiyNbx1QBlOpaH03mbBD9uGnWgR4sjz89s+VOHD+1dz1A04L39a/c5Jev1fAEeCW7y1wxF76VKXXNFP9yoabv435eHBqEEhnnSqgcwrkZOX80qSgxCypXtYv1eVtdoCAztvWbpRMuP8agOSlIhU25t1Z6WgPVQmFQQLWQR09AMHpC7clAftZ66/0rc2yZET0DqrDhasJhMWugOUjxLMuBi13vOF46AkAk1w7/JQdvSotwiMkQTq0sYeWL4tWkLuyfKXw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: mattermost
    type: kubernetes.io/dockerconfigjson
