apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: mattermost
spec:
  encryptedData:
    .dockerconfigjson: AgBu2qI/ZDtnlJapjm4bfejM4lolYVK/TJaKxqL0j/FukpayzOH9+FSJvgxTPuq20vAEmEMsPV1G8Co6BAidqSKzKXA4a1wRgOCEoTuB7gPU6sqITCozPCG9Br8T1dREC0P+dzMoZuBPiVxFHIpdTR1iTysQvryudM1ObttGN1YrV7COSxEvASd/kFUn4ph/mK7IdjvgMw+FqVLBasBaT41/wiI0aOqklRxX0MpS+tfPHCvisLJi6Z/cyH9KD3TzUZWKXF7YqpmeMcWgM1I1e8uO3hhPK6CNUwyqy8XCaei/Y4KbEqck+IcMiKpS/sJ3O9/jUqEk6ll9PMOd/eRfS+YIQJi4fOA4BJw+etzPkJpVmyDYY/zb+3GWAPV5rbcBBbXQlkxI4PCOfcdFEHGN5oKGeU1mNq3f6+dTKidPbNKeAAxJ+9yXY9c9V++v44YZW56uYTEr17hL1qRsLNs57aKyWlqd+RiA7ZeOEPVguO/jAO6qTNGpd0ZdIBalFVF50+LwxVMoLMVBK0KF9rkRdfwoeZWQ0AE8JtciWrGLuArI+uheGpYvK8oE0WCZx859KsEbghhZle5uER3rRM6BbK1QqLNSp0VVMKtHfyKYj0atujNMlKB+kCXkqA9I4bRtnZc/lykdDk4WcDw9ZDVd2nHdJzQ9tNku2eHtZqfBGoSjhemEsE+JtxEKUg3wgVtM7QO/bvex/Xy2grcL8O1xe4lT21dziWvzIrq6tTyGmU2vZq4lhHcXVqOo+rcWRH/YRa2dl+ejmgbue69ECaDsvet99+fvATCt2KCuGQ3A5uH2QHNw0J3S52L+sOD6JIIPp+YM7Mwc0pqd6xPgOQHH4pUqY9Dm8G/meMn0K4DE/nwQA7u65OXZGuZd3miG7IbtI5fByvCp8nVjyIJMdtjI0lCOvdUM7wcb78PaV1f4WapsQ9/LvaH6ucmMHYJ4PXQ=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: mattermost
    type: kubernetes.io/dockerconfigjson
