apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: mattermost
spec:
  encryptedData:
    .dockerconfigjson: AgB/5ms0jhkXDdO2/UO6+LR3q/HhhfmdhfDfy8n/SGFT0dkQpCYs2QQ6UKkU/vzxYrQbujGZo4LSM3S6mHpLU65gS8pb3TXQzFgwYICeyVRTujvRLYUGgwVKPgjsGLiPaXrMBxnhhzc4lLE3t4S2R2uxUof7uGgRIW/mo2aWWhUMnyRghMDHOy2p0O26vzOedIVE7RrPOsPNdRi0aivvOMi5fjdeFBnuRndOhHWpPvp81XjaTpNvi9er1f/bVH+onDk4SDQBGU/CFJ3g+EDfp+MGsQSDqM7foWHtM+LkfE2wuc0HBpcIfWk1ferr7cBB+6qQzAuxwEoMzRkEsZ0mBvWaAN9D29rLcHCT9h+d5sC2CTFBiIxJwG6xCnwPmY9lt8I48RVLynxyoFkUbrDbTo2G4QJdXx68bvzK8NlGuAjCoCHVHOKxiqyrHtpuIAK/yF1rZ3u4c44wagTFxIYZ98YwhhUI9sCIHKbST+0aExprAMhWAzLJUNGfdCsfZTpjddHUR73GP3LjSsmE5DLKbzkTnDwJWHBXiV2f4TiTK5i/IEfYY3SIrdhVlncE93DLv+4QcXjR5znlRgsbVZKkC2tq++IYn/+rTXdeXx9U/e2WDLkvz36McK1HzfH+P2jz0vc06p6TNqsWEQUUzT+Y4XovfG7KUgMxML4kiJJQlOnS+XrmZbCiMQvgQQOFavZWnS91xBMFoMFmxYOUf3cPb3SzWHqIlCmGRaTyzr8XYnVv8tL0WuLPqmJ4Uv9wii/s4li3FdPqqlJ8co+2Eb6QxjRb/IuixWHyRnQBSEZigHfHHX9QrLCOk/VEc8rJbpjF9p887//hTCRrcJaoyLwrhqe4ljQzLM7AR+nT8dIRDKO8+Uc1AoqI69kWXLkulcorACt2a01w5xseSbYkxITOIV/hhwk95pQGnGfq5BATB8Cj8YyIRXKC8CpUlZADOuQ=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: mattermost
    type: kubernetes.io/dockerconfigjson
