apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mattermost-pgsql-postgres-pod-env
  namespace: mattermost
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCks0iA6DdTn+kvauz3QWt/7KZ6AEtP86Mq856aqGxtQli96nLIQT+dBH9wNnCjvnJSISDxvDEgZtffCVApH0JBzJKLbF/DdnrZp3rP1gD/3mDRMzxDOOaQThz3vQh3p0KMxNFz6ne+QIHDI7bPXAzIh0RynjxGwlMvim75/NBBiRlQ1qPC00inE2jhCotObXv/cWMKoTKf1fKtHbaX1/6IapsQnSvqegiSMN6y7e9KTLJvzHWiwRY07Or9bgjbbuDGHmb3HrjlBtE/O3tZEVcBMyU0Mir8fdIKVJk5WDXS3kzlaWR8pHdY30w8uNYsPJOdafSgPB3UW7SPVESsOY3vWLlWnNjbOQchzSneQA4TDyjgtImFJagk9qhvq3V22UB6sW66o7oNIvpwFh+VMDUpH3nv8t8xHw8hPi4g143iHjimq7H6QqGS2rODcyR+rKLfnuOKRyPk8QqmJp25U7oRbpxOK3afAU8tUGkPtXaIM/au8k/8u3ujgxu4OH7ATy24Wr2cUNHzpldBHiJA7iSHM7ASKqrVnVlGQrrrheY+TzqhIIxPu5nSItsZIvcPXBHtgr71WRkiw4ER5SZF1iT4fWMbkDCpb1fLJ9Jm+wqx4swQIDNXi0WoD9ETfxOiJUGJyfFKy6EwB2JfQs9GZZsKu2Lm+hTxwEXOMmgedfuCOjVcm5cgJSfrIQALYTqvNerwazw=
    AWS_SECRET_ACCESS_KEY: AgDSxoORZJikP3wEDi0hCeht/a8hmUf5O19zAzBFP+NBrG1LJ135qpt87DMwUOwNHVV7BTdlrdIJklihp5a2I5TsKGihToiNmq1YK/R3La/oc17lD6Yg0pevsOSf9jnNBPxwuACGn0KWoQCtS5cp8PPL1k635cM5TxNATyEFGGgi82IK8HuwSSfdIEi1tMBjcbTwpICTG788ZNQ2+Jrd8zUUZ/OtSU0IAVjk3Ktn5ai2XSQEdcPlfQ15iK5osJxi6rLyVQw6Cz8iKaLMCRwwnCDgdRqs79Bi1lfg/CSrnI9yV0QzFQU8uxNs6x+AWcwusgeVSrWR0h4rSYAa2kDkJ+CtMDVBjBehA2Eeb1JtPF07lI0KpJRF6Sxb5JebfqNrOTaT896afO4fv7ktfBGdcfHEyBEznG/IOkP9hjTJryxOtEqMGZxwCAN7+4bgMaUilkmKgc4CzMRp79kXVZfSOSX5tLNzbzFlnFj7P+N4rM5XlIWyB07+QCVYeBRclnuF+gDrT+2J+5wZ2Z5gU76RFmWBLwbpgVjXGnWEMwXE3IHVnc908g1hM8jq+CriDdJ+myw4BTb6bBwKP6C3vF+qKQY/SojE1/5UXeROeBa1h+chsc7ZUQ+obKF4P91hN0H00RHpsXhRNi0Ls6A2aCNyc0wHMpDJ56AquqQVH0PeMUKYsZ+8E8qTS41Dr43Q4X7cIpIK1vfFrSzPVjb7a30Ceb9VwCs83ST01Pk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mattermost-pgsql-postgres-pod-env
      namespace: mattermost
