apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mattermost-pgsql-postgres-pod-env
  namespace: mattermost
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAC3ccCeLyHndUzQfH0GAMtHNjeGqcClmssCH3CySKW+1mwNyHIOFhgSsAR4DGVyDThvg7gjUdDoWkguHegJb+NeNlJ6r2POYUMmZdvJueq7uYLg2bewMabeD517QuUJJFao4ib/6ky36R2whCbCcQ4F1wDiox4MDPp6Df0mgs4YfR/HiQqTH+cze9MgSNE69SaEVSYTrOBkD9e4ys9wQaHfMlGn8Unk5delTjS+SA746pMv/chW3WqKFY/7FCm7eUmvbgm60Cxvpxy26mkwuxo0YjLu1vJGLGdjYEH35BvVv8mbzuBCtfCaM81U4iTT8xi6HMfo+c46zStNjcFOx1jfyspBHJK/pZDaKwGG4PxagKTTlclbmVnCcZvCN7KWlVEOlAxZ6ZHWxuFo9DZOqhSM6lydoRjTarTDJ9PblrNAusLSIQp8FKC5lDvpkI00NxIzjRVwrdRqX3GIChAUl449C8JGwKD+Tv39ds8vjEx1ND6tBugUGdA/tYSzEovlpRnohybP/LyJMjk+OH0S4CSDVDwy1ojJCY8gkMlo0u4ofUBzXcx8tWDBfm0T6wfLUsLXcBaZusvOBBKHuSkWkuXaiO1U+xakfZYarV0sKEuXln4cRLEpprh5HLaNna7G0HQmtkflWp16y6MfkhlH5ab9vb2YGAS6X5pxAzI6Yeaq8zLSbCJzik2DpIwpHQmBnsrgHk=
    AWS_ACCESS_SECRET_KEY: AgCwxflYyQSgHFLvHCA5EyWgT64+Gwryq2DxHmi68dNEdWw0blEtIAZ2jaVKMvigdQwHTqSPLUA/Td+0Z+pZhD5JgHVg/SPMIcQWKXKmipirD8JuHM/yV1KGDENfP+sluPTjYjgvHdPG+o+Lf/Z7Y2Ucb55fVV36zhJ71NwX1W9pL94WrBDQDDd5GXiJFBdKoxIhvREuOY6wL7+ivul6S/LytARCyLmF7Xf2nzSY+jRjmMYE+ym3+/fGQLSs0FcUFOH/cjrA4nAubXFDpOQezrgi/ZLfyJsZSvscfn/5pU+JA37B2PFSa5ETeMD3TbzVxUXxYmV8ObO/6QmEW6KGx/ywTqKR4d15+ikU032uWlQNAFuYjpabGp4B7lwuEFx4Kx1CpJpnQwLz5rurws0DOPIJJR1VR13iTSeQuMQuanxSsyzYSQahrYuwBCgc7fqUldL8iPMVADI1PiwlP6GalYn6jZ+mQS/S9cuZtAD8TsNtaCgzwZxJeTsoGkP44j8LNmZ4BHtiQCGZLWYEARv2yt2EcbKHA3CVf/9vfAe0MQSgr8WAZiZsfz12euJilMrN2MmlXYtyzNOlT74LrXgyf3AnjsEYBbeR0xUCfro1AU8d4k4mbKW70pUiNV3gWj/C8uNpBA4sO73nTAz3JieNtabR6tYrUM/c7PVn/pJ9Jt17FJR2WFGmvyrTh9yctFI8ij1Kq2E2MDoyZvuyeSg0indq52TLJVpT6wI=
  template:
    metadata:
      creationTimestamp: null
      name: mattermost-pgsql-postgres-pod-env
      namespace: mattermost
