apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mattermost-team-config
  namespace: mattermost
spec:
  encryptedData:
    gitlabsettings-id: AgAA6eZ0Bn3RrYY/3v6WnLfKx6j9hwbnpOho1wUlO4ZIAwHBJqnUFniMdXm2TVW1LaCb01uRzAHgiZN16RBSn4Hs+fn4xzjQ3HdTwoHe2DaibO+hFUAkRN4nyaVYJI+hrYWhCDmwmQAxLFXyS1EYyJ24hMYtiY3sy+yPLILeN0W/aUzTYeN3Id+yTwBUHGsbXi2coogETJ27jWQiKHLkjK1S5N3MnhxlOWioJhTB5Nv7AAlVGNekF5xhkj2P0c2chvfCQzQ1AROpz7QA0cVteq8MLcas9Liw03M4zF7CdratpAqJaMmgjhlItnEjBaLvzW+iYEeUYfSeQryemn9Ivqk6bVUxunRG1VhIZ2TOzNMUbiZsTnbsDjQcZpHdI1E7iGcTSc1xdNaH+bF0pwh1c2rdhGCKvtFlrRcHFVaLxGo1RT4yaTANiqgm3ifr2uD1Ho7NsONrrjivQQNiGltVZypzhIDfFz45D7DID46AAYLcbcv1bzRmivl/+2Nb/ujYq1EqY6McfLCMDVUUVE+JFBijqRcDP53V24vKhhMBpGIyQWiNml/Y9s2OfYU0gaCVI7c0s5Rn4p071O4hW/zAuUbv7sOMfAAshFsiS9wNk+Cq5S4+rON/uGOI72h0oq4VexLZJATWln+cIMlBKBFrOOoeJ/RVJhMpi+AoWmAYIw1fJOuh7vFdzT4dDWkkbwLdR7r6mKO9UvKFsrb8
    gitlabsettings-secret: AgAWSC1JsYhzjRj27vji2bQu1hnQd+o2GVDJK/gqx2eZxnRE4A81fofiJx8JNf7uFj2iLW4C8L9qxd+IC0a6/DvztNun0Mp9EaiDmtQLgncSWItOtne119PIvAu1gPCmRQ7zq3+8JGko7Nn5ebd+XHViJEKOfMuT9t6WD3PsmXVdtB9i9ArMS1TTrtTagZddMAiJAyZeMCOOyZib60K6cpYn+lFVZy74Ok4+UpjLdnTBzD1rLMOmcQTcAFvvFBvLDD+mWhfDeCgOi6A8Zu+N/MVC/tSt8W5TE7xi4EaVX/Ox2iZpImzSd4fkdKZDr4NTUk/g32m4TBRbUkvCgzdxA7a/D7DE/3vvoygjhIA/G30tJgSAYGSNioeuzeRJj8QL+rsdgBgguiMY6nLc+44oOy9xBoeQyu0hf8elGv9k5caVaLsmNVixpTTz+/bhrEyZ6JAU9BtNlcKGIJMUD74CoNrHSHOxfsjlsI7hCmmTY8afJBwxT+OnWWt+KYukgPLy3vGgEW1Vf7EFULZ7tJn6ghD6Tc2ge5aF7Y3lOwoCZYm+t5bsfKzQSz+UnhhFxiRSR2+duVgCVWxLnjGITlFwMU22AyAhIAwriPv0uxdeWjDFdhJwyO/JhI92pcJmAZzpxYj69MrUU6zlxcvs027+5X/N+06EmZbgwbzbbSEehlE66PbFNLs40I84bnwXioiX9RXXfC18uAGwqn7VYJOM6xSAQusMGq6nQpyvqs3opMtdgg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mattermost-team-config
      namespace: mattermost
