apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgCvmbgEfkj/8JQVpoyHq2V03glwC1RpAO5tjRykPFPJDqR+EX/2hOa0htAH1vMOzi4l8DbrHNn42enjoHQalIaaZMAlwx6iDTJYFMpNvNPmIh3PiRS3POWT79XkLL+WUPltFSdduITBOm5NL95lAmDTkseR3ep7F9mZHaKcFoL8YXpsQm3qFGR9ad5xOcQV6L/jXwJjSH5k9JFZJWTke2eiZo6+LGGjc4ezdS5Wzn5vqD5ewVhcpUwjXp9gF617Mchke4Hn6QHeLeRHgDJ2TP8qiL1GTnQ5dg2SFZQB13ErClzukiXE4U4yJHTii+YsRXxhfTwIKEjKMHRlgn2X+2V16jhfyQRDv2HE6jDcCLvLX3iP9SNGn3UDwB2cFeJQZYpnGFdZkJcf4BTirxUWaIz+yQNV+1rolu+zt2yHEbxNd1PAEJOkQuGuN42IpiuPQf119pwNovAYQk36NKk3UYwfHjbA0UzKoCt/c1SOqG7ox9vPMsUciMiI0ih6pGzMSRJhhhXAbpyQX1Pe5+yYc+p9jZyRsv8NlK/bZIYJMovK2qT7Xh9X+sVI2P10bryDNgQsaXhMohY88foMq1dY2vyuENEVUe1+5tsgDSkb1EzipU3DIv6FLq8NxneOM8RNAGqzNdo6D52Bj3XEPjwwjXcreER08nXBoUnVuHVaPF0k2911nn3nR54hYZM1L3WcNdEZqWBigSgTfP0gReKY5C3UxXFJW3vdsDQRRXMfesN25FwEZjKq/gPwIS2O5sCcrZI9buhs0o3/3WgupKzOgayCkXzJQ8TJngarrKgF9zp/fuiItUrJKMIWt+q3iceEOW3iUFR1zXi0D/RaLdp+CujlP1i6YJ9pVA4Pb4R/8gEzW/LgTBBpgpQCW/rOv9bhUqelEIaFf239XYtGDotfzBvFsSAeON2OgGm9XiK2/rbfgd5JaZ+0zKvnyG25m5BD4ciPz2SkTfoH5kz1ptfVcQL01Q==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson

