---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgAMMwvNgsRnmRvTLWCq66uTdCH+nf/BycO/YBzIg2TBzjrG0VKbUZ2HY3I1sAHA8EyrFa4o4OIZXN7yO/5p82v2Tgd7vsY3DFh4PyQjo9WsqJ5RjlFzVftUfV8cNoGoBTu+9pkjkz1eta6tlGS9aOYZcRZrONg7MGwtRc9ONwcZLd1A5VIWO7k0v4zb+iejTeO6/+UPzauLjcwfHMTVwDMy+yfEBu/w54lh09zh6Ju7ctt3Sdih7QfNn79CyhjJTNCq5ef2kZ8UDwhJKCqpXMo5kvkc1fqpRWurpSDJkiwdIX98W2/JEtih4FSJkR84vGVaoBN3MF0dvrrl2gdkTOxDxKRzAehPqh+2UYv/u3h/fMkLdNCeYf9ZdQdVnA//5q7Qd+5Qp0ycv51/W1mlqx0o9QpxyZ+aP5lWebGyranuYmepBHwqL/EL0w8PFoK3K9DOKhn91veat4WW2snsZ4FJ88MkENx9m3B2XZgi5LdQ6zif6Rx+1sHhPKC/m9MJxCSoAC0cHuUKUd9MUb7LYV6dbuzOH8w1w4dHEe1/JHgSCOVjtswDTz7c6KifkVCwnrum0n6QXG7xn7vSzuy0Cdxl45MOo03EeTgdyLOut+bfmzaVrM6GdrB1HlF4XwsFb9BMFahEk8WaU6WCZsiM/R78iPjSawQCsOqf+tLOHEIJkGGoJQdAq1ficgZpMXUiP3SNMe7p+pdPigcr+esOZ6sLeBs1mNwLLSYoy90dku7DLvNeUy/8v+BQ0VfORS0Rb7RfkvbQqEGw9MJ1/Fsq8j/XjuivlnY8q2bBVpxE56ZNOg6p7+J+Ut/CRIj1AzTy/k2SWnNuCal3i4WygJ/ZYA1KNscJh7aYxp33lUV195ZkTG0K7qd4iLH2338/EJ4b+4NOnxgw6VaBsB6TNKuB5o9L+tnqbjkwdz1jmshy84z+d5JrprrIwbpJ4usMrYiPPdr3uZK2ad8DiotXHllfxYGmFEL5Kd33aqcrgmdJ/+TaRwhJ0BiWBck5
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
