apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: totp-enableit-api
  namespace: obmondo-website
spec:
  encryptedData:
    k8id: AgAZemLcTHDeoY7Zhx+1UXeuBQJ35CCXT77IAlfFYUccRioOU1yphyuUv72aU0Nu+1+kfuNRHc7eUHu7dkzcGxUBmxYSi2T7OVzPm0e+badyDN8wto5JQ+B0FOljcDZtsUb5dBKkXZBEtHTZlJKYVSpMCsl+iK1JYBzZFmpWBKa2i6+T5HpIp9i7B7IT1GTuxc14zAXsDkN/eODRiRqd0PkFEbKQ3tLFyLuJRDpIIq7CuNwFxsEILCEoOogg9lBEqfngvKLHTOXfKEkCDK/L3/S5ixbI7Js5pNlc5lJnWoTmbSRwVg8bNHRDB0IXEUMti/tViGTMVImliUBw97/Uc1aeDcvvrV/ifsqh/0eXPWHLDy9sXTEKmYIujNr1vrJXWKCzqYGSCKkHa5HyZVa1AeRoGx6sH5lyzKqROQA/2CxGaV9sdmLYvDOKvVnUsGPOKNvhT63I7tQEXPPNKgpR47kyCrnaT8t4awTPxJ8iVSbIlf6uNY1eQt/QS/wxCTj5Vk56P2k+1S3k/gP/aF3f4hmwXw8hlUcT+WfrE/LE0OxKGU0pRV1Kj/75qNSgL9o0WhWaEDJyEAEQYBlfjFLEDT9JBIMCe9ELuA0sNPX1JO3iGm3c3fxtHCAxX2PNefyRTkJOfy/CkiDjyG4SV3246npgbjgjRjpKZ9nNMs7KR9L1hNrf3Qq01aICqlAxBbqbAwPPqrBLOAyyyW9ulTQgDqEh7UepqhS8HOBfBxqS0wMcqA4cW1DzoeZ+
    obmondo: AgCFqJecOPiVZU9uzEw6iW8GHz+rFYlz+jDp3LErePeVTvGGNbhKxSBWxRo6jvCCga6q/19pH8NCbPda5zfQAhJN31JSalaLhuA39QZf3KTIuOyQTUoJMKcoGszX+gvtQ9ytim0xsxkPb9rbO0m8cn0H4TF9BafmkmpfHT5h8smHYyhD7pGxuNSBgU2QLHsP3sogGBXG23EIxPXDYCsd0JJNeVeVRRLNMVGO3CazlLzPrzUSv6OT63iZreN7QQXozQ9iyF0SgQ+/W1TcaLDpjPkBrsP8t8dKSnfNCCeDlMr7Xer1MvjEB7iLm39GeRYz8i8rFkiuLlHaB0gpUpj9++dmvDuIx+Ne/EnMJyXPxvvrUcrQbXUeMfx9e7SlFEQPZBzg8PvUf/uilhR/qgMvWs6o3SR5m3mfuceBAxUFsanWfUVzaF7Jo9vr9ezZaUmz0eEK9HU1RyAksa7gy+LPaGGzHzZh3y1UarKDLFgE6NI+WzoKUdBFna3nUJrX6P/h5l8Tq+c4dqZbjoWbQ+roU6+on8lLoUUltKKWHq8v9LQryiX0DNBcfBF7vTXeaa4KzTz67YGujDUCgugwTOngsefvNumadvoKNtUnM0GP5W5NRjlmwFEx2WWZ/I3aydfDYrIKwDB12zDC8WYCKBjfU+Tqk1rleQtl7sxMNKSv+bQbrsuhhFWt/LqLw/llKddga35AHgqaBFiqI8NJ9/ewwwUQTJ5rHyUBZnTP47uq13kofTMROGoE3y43
  template:
    metadata:
      creationTimestamp: null
      name: totp-enableit-api
      namespace: obmondo-website

