apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
spec:
  encryptedData:
    oncall-url: AgChTLCQ/fhwvsZicJtEiw1xRoOTBCZ6hS8UHr5iEiJJbgDzChtVclgp5Junylmj79GgBxtHsVutHjA4jU4fW9Cn8HgOo2/pZcZaHiyo6A3pTwVP1T9xNzTr/t0m3yWGbox+h2ht5pbtepGmcRQeDjCXK217hAVW9lJgauJ76P0qV9ItVqeQbUGIxTDTfu6GWJcB7yuroT5O4d1X7U7aHHdhp3hXF6LU+b2l9DU8/04FG5N7KoKR2w3H5i52BVW9QFR1Xb6yMv6kqxUxVclzyXs0kQdgI6/S8E6rksuUHcdDGStHHnbbcWynPeRi05FnTxjC1ZuCSxOsYKltu3Ga2Bd5gjnv7xT6YrqLn689LYvYEcvFXtBai9EE1clHzdEQL2ui+SXmPr1CfRi+oVd4noRH6hBPdpiZqzM8wC5Ti9YJdoBl89rMnAMTSe8/LXNlinTBimGVm6pRyeSr/QC0JmYWVg4nQ7KTi098QiyfCf6TZHKZoq1hQlxX53wewL/8vSMOTxBGreuD4msQSd8EqMpS1nrg0V5BWSvIXVNv9jSoCXyJH+G3sTIIDnR/hXajKphfgjq8IdH2OobOAhZQsdxqcXQyvgPkp3VA09cajYl2+h4qqFRTY3gZMPQsLwI2FZwpF88b7j6x8qJvd1r8tfYe8QCVtuZGlOE9OYac1RcgQjaRbx+nl7zaCQlZjGydMipMtjdPaDly+GuygtpFj5T/3cw4sdtCr69WYAIfMdIieS/ei5YYEnCCL2hRQDLh3tkhAgFMqWYaabS3/2Nm0sxm/T0RUuMmaOj/oJSuNjP24qNdkUKNzw==
  template:
    data:
      alertmanager.yaml: |
        global:
          resolve_timeout: 5m

        inhibit_rules:
        - "equal":
          - "namespace"
          - "alertname"
          "source_matchers":
          - "severity = critical"
          "target_matchers":
          - "severity =~ warning|info"
        - "equal":
          - "namespace"
          - "alertname"
          "source_matchers":
          - "severity = warning"
          "target_matchers":
          - "severity = info"
        - "equal":
          - "namespace"
          "source_matchers":
          - "alertname = InfoInhibitor"
          "target_matchers":
          - "severity = info"

        route:
          group_by:
            - 'namespace'
          group_wait: 10s
          group_interval: 10s
          repeat_interval: 1h
          receiver: 'obmondo'
          routes:
          - receiver: 'obmondo'
            matchers:
            - "alertname = Watchdog"
          - receiver: 'null'
            matchers:
            - "namespace =~ testing|obmondo-ci"
          - receiver: 'null'
            matchers:
            - "alertname = InfoInhibitor"
          - receiver: oncall
            group_by: [alertname, datacenter, app]
            continue: true
          - receiver: obmondo
            continue: true

        receivers:
          - name: "null"
          - name: oncall
            webhook_configs:
              - url: {{ index . "oncall-url" }}
                send_resolved: true
                max_alerts: 300
          - name: obmondo
            webhook_configs:
              - url: https://alerts.obmondo.com/hooks/alertmanager
                send_resolved: true
                max_alerts: 0
                http_config:
                  tls_config:
                    server_name: alerts.obmondo.com
                    cert_file: /etc/alertmanager/secrets/obmondo-clientcert/tls.crt
                    key_file: /etc/alertmanager/secrets/obmondo-clientcert/tls.key
                    insecure_skip_verify: false
        templates:
        - /etc/alertmanager/config/*.tmpl
    metadata:
      creationTimestamp: null
      name: alertmanager-main
      namespace: monitoring
