apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opsmondo-registry-secret
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgAYoRH7CIR4DKufRcLx2J0iOFfmq96EZ6Rh5RPY9cCU/rNVOVLcKZU9cCgcCBSRTowgefeNcAIdkNo/dTdKnDvWdap2i6SR1jFZnuC+idQxoMQ9/9vAoHIwWkRxXO+28PgwC0FMFe4AHvM1iM8aqgJW2Pb1ezvDAm2flI3IjGk8nk9J5igtfZVpWoHPUEb7G2zGmCQGe7/QVKsjyUXRrwAHDIC+vM/9AoAwdjwTBo4s2lFD1Gfpxu8s62wdC6R85vOBhanglcZEnWl63I9G+xifjEmqeLE4TjmKQ+BlpySkdpprsqKB/sEu0yXFI/KcYmTv3UOXioSNDbpTB8XSCGwpfLUJdUMIkDTeRxgOGBcam+kiE4PmswI72mRLjXP4GtWeCXFD2qW4ofL9fJDuylhYskgLT/bWoeF4O9J51rLjNDvELTker4+ZqI++QD7FNOrawZXd5gIayZfn0s2Q6lYGH4o3m7Ysr4soFNaa185rhmeVZYI/o/FUOPtLuqoTvIcSlOyauOt4jAd9vptNVVpdOv0ndlD/8bE9DpoGAO/CUhNs8EG+yGbqz1tCHNNcBWFB3FWDNHlcGNJ/X4AoX0bgdx0fOyHozlpy4dmxqZLF++gaKACU6ayjc9Lb3oBeI/nSSmDoUyLM94ABlfMVv+v3hgTIFbAFS7jg1xq691QqAqblRAw7Wjfa8/Bx9YZm4skLupQDDJznTvRP7gTXnuSOia5YBqoZ7gNlt8YHmnKBJFiHYSxa7Ft19bo2NdlqcV9OnKOgJL2aOyLJ7L6Ws+huK4cRfR/Vh7dsUwi9AGObscef4d0BhY0giu7acF+XWjqEUeDv/AAu8eZe0yKJoPZGKs4Wg9O2ZXAMxAv0OjrDDmd+lbcF3rK1avpZ6JThxEkY1yfMPEtjjJtcgym+JcnsTVYuhNEbs+s9zzW1hiVFo/j2c+ogW0iNuNvzZoQe5N2NpyU8eeBBbUjcXVboIIzWdQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opsmondo-registry-secret
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson
