apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opsmondo-registry-secret
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgCG4M7VyLoS+UFlmaHkKe34BiQzVzdxdeOFkyhOtAdycyR5cppvHfMjIt6ZXdtI2K2zxVFTqEbxCOSglzMfBV/3699K1sFrShxbaRqiQo2Q3VmskVEuJ/h6CelpoutLYk3cDG8e6vjEujNDpcPVhlnNGe3L1UyPIU61GTPsiPNxVlYqrN9mc676UEUhjyBx2q09/DpqKJiXu7rZJ+4XLMhNw6JBRY4iYq139UXzrD/lU43b8qUFLcI++eKC+lzjoBvJquhn4gWK008ErBvjCH+4bcKixvlpljhAks2rwJL2wIE2KEUNnIhbIklftFK4OhuViJoOIJr+BTJZOw2ACqPW8fmGzED/UuDujQiSIyEFJIwd78rMFVyx8vXjtegN6xmVKV1x+T7Q9+TPdW4o+heJz0xA6F7svp3qtTPQ4Eqz/tnyvH8u2wiqo9aRSbH5+JPyxvrsZ8JTFBWT1YPl6TjMyFMVYsMjKtsd6sgyFtj2NVdqIyR3bytMrKUFb+yZitpPDVEnZvQYhSGngyN8nInt7puUgdRXsyu5oFZBpPVYP7sUo2mVSI4iKXWY54v/lavGS49yYsskoWAXW76X9F9wXxRwk8UZuDMF86BcoUdQXXmgXlW1MUeJHqcLNllYyRoLUgX+PS0DM9L2T725S4yWntlMIesFuXm7cW5iqXgLM83kRCpO145s4mI9TxBl7qt8Pqdf7PgGeLxMA+NseAXi/NIJSbd5zkvmErPXWlYVXp4C2d8y7ShBAJZT5Sblkg7fIlnne++Ide6oRja/26AYJzPow3vFg10B6gAWfyiSbOcuACufuGWMKAefqacyHxAmLSDeEGFizYLJo9ZYX1/TAO9ik3rkBHwuUYoS7Q0G29zCpgUhQl2CGTfsrmGHeVEFOLqiLOiMYMwpymxafKlwDLbiRUFwOFDGNn4SYZfSHW9KmwS3GL4OWouvgA4ynWWGBjYFo825AudNmuJ6yuyjlg==
  template:
    metadata:
      creationTimestamp: null
      name: opsmondo-registry-secret
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson

