# kubeaid-sha256: 0f7e54c62dca7269d97ad1cda01be4e1d16fc0f2301207685dd736323c2b6b65
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbird-turn-credentials
  namespace: netbird
spec:
  encryptedData:
    password: AgCKNnErvx9Jl+g3IaiRoFGAF4LlYSI0eJiob5M/qmReR1xor0CCHg7fbEhAgstE1MdkOopoGMX5S144C9lLxA12GgVLiRQqWALuZ/layStYE6G7uLCaFvw35OE9t+8srJ9hFcUD10pj+WMT03bfGvCvsWez+Az7MmqTD8YHssrSilVXPMKcOzDRfuEvPERizHHis6RtW1Tn6yU6TKpaJG0eRPOhjWmXgZMlwaUz4GWz0AYAjZwCoBLxdbUmDZ719egKOjVQ4yW0PAAWlbzObcJX090phFb285hKUrjzxGixDYBwRbfR4giIyGR59enDQMEqUhDdtzSRtKYqwGYfK0j+Mb9Z154Zhow2TBzr3q0bjxTNbQwKoe8p6V69Eu5/pTt2gPQhFj3scE3C+S6zmwsDIMuIxtqQoOoQWaKSPFVTjsGS+S5Kz7cWWYXd8R916Be8otpSfs4pcOxVFD+/vfbMrGi+AoCa3uHJ6aSWinBmY6xuwYWAlT9WBA8RvUBrd7MIVLV5iVJqGP1CFf5LexKS3KjlIE41CBCT49dkfnUaL3R304rsEXkcbI4vE/i670AAVOjZcZelASCHAnQohW4IzKY1eZq2s6DXBQW62tiNBRdl88G2yS+y8g//VP6eW1PN+BB6f63071QWMSH7bCTdwJMbOLAi3zjytMd5hEmi7nFcwFsX08obikqHfxEJiMBZhSYB+wFlh5A0P853JoSp4isBoiuRR0ZYBWxNXQGapw==
    username: AgCtnZSPZIEet4jlCAJdTD5vQOmezOD7jPAryHu0Gt26QZjJVGaUpeJbTYbM5ATsXeCCw8BJivtJTfHgZlhkybX+t1UOy32VrPAm89sIDZVmKZFETviXL/ocXcEdJzbU/+JX7lPWZHEQZ2SIt1MNZ/rvUzXrWet9lKCYwR8p02pIcY8EWLxi6JwIZ94pi6oyHglwDtAgtbOMxAimewTlCKdET94ff2qpztvyLGqgHVcb3eq6nLQvYPx6qjEL2B7rfDNnoHySJLA4kd5jDClY/eTrv+uMVL9VQ8fvw7vma87Hm/H1EAwRnJG0ianzBHx65DxUO/Od0Ef75ezIEg3Rs5m+3aVMy7XxWtjJHZlQFaeSmZnbG9/i9WUCwkAdHb/ZI5058DsG642HstQ0eETPMpQpX0W6ty7OyhA8ZkPlSadU0PzFlNeAvCH3hhsB6XVPsGGxD+42NxaHzrzgIup9UEZ6D567T1JgJUQmj0DBlr7VS7xO1MKnJTOXUmXbcZK+DQYqbBZvgW7Q1VCCkqc+DiT5gDzRfe0yBZ6hREjSFVd9JQRzFdk9MYWK1rFGR+SG+/gDvsIm0EPvpok8WEHFmE2MT7PdYxyYLFyT9B5WvvKgv1KjiHA8eq2E/lg0dS36Nurjhcr234Q0o+0svyXos0BZBy3+VyfunyXDgHAiUMS5uG2w1RFlSRJRPGE/qmn72cmOYTBNyVV+
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: netbird-turn-credentials
      namespace: netbird
    type: Opaque
