# kubeaid-sha256: 2a30885ed8bd5a9c19fa7a8d0e95b0cd3dfc8042bc86ec5134db576e501a2bd2
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbird-turn-credentials
  namespace: netbird
spec:
  encryptedData:
    password: AgCjSxSuWwrKYbHO0I+qtGW+mPnMa9AZDE0qETzA72lNcCLNSP7CK73oSPYlSb9HThQrZK+lzdfqq/Jhi3xALaDVGMtLS5dlcLZ1Pw6M06gOUj+rZ80P34ce5Nz8SNgsrvlwD0uCyMabQJ466alUIi+ngOGfSpdTm/8nQ+I5RwPGFpHtVBDeNMtTbmLms4OHbU7e+NgJlvJjaP9ec4GUuY7Y4iLqSR2EYEQUBEnByLPGKjDX9qVCpnfSZh5A/0OIeDDBlPk9Tv4y6mJl4Oa7wVBb3dGXhqQ5GnbmDydGkvv0k32+B6XRv8LDkkHsxtVLvp9WgRa4QC/3A12YwXDfXvwIgohuEZ3+zt0ncCtNB8u8Yt3T6uq6NLw8cfaxedyHDu8U2gd6nyWM6+ZNRSxAovzdVYwkgo4Czwl754HTyIomZ60zOb6MszuNVU3vQVVB6cRKVrPXGISwqvmhtlzRadykC2Q93Z9S6z4z8Q6B+wnNp3J6NQtCQm8Fi6OUlaQbzdLWUbViS/BLFinL+Ml4v+pb96FkqVKZHu37jrbjVe49BI3fEwp3dS+cXqvslt2pMsW0UVDGwPT1hPcwBa0G3jPQaFnpxlMfBCnTcsHlrKS+je9fqztHK12u45rnAeihd8W4mT5PG9qYWp1FwCHxnOjxSBzHZqF9A0a+gr9807OFIofMG8GsPSdqDyowcmnL78Agxiob86OWifhSqds8Da4ARX2GjUjM7Q5prB53ImwXyg==
    username: AgCoXC/Y2oYLjvk72xRHGWPO8922TfKZ0ETN8Yn05MOO49YkUNxR+7IqBc6WlXuK6Fma3x9f5E1xlo0BypNFqgWI6dxPttnmutzOEfLF4TgslaEIpzLmZRY0XzRI3x032pa+VuWDrz86Pf4aPbzQVa38v2Wjl6FvR0u8Xurxa2gniXjb5m3bvyohEK9JxZ3eRUoVXN7T1N+598m78xBv2LlbQgVEHaT9/UHB3kEfPGUPgJklRgHvzekOGiKDLscKaECMCahpi9nZwAZhq6d7xYtNrZSAVutEB0uHrIjaUlXdNr40QFRorpDYQBRl8d/tDadoPVy5g1Ea0fdtqvwKGNHRHRocJRtjzaX5LMLL0xvT/UH5h9TGUXuLkzoEHNzdq86uRzXnxV0tXl83bUbWJnnWPHltokrZFlAz1MtLDa873GRq+5siMezEFNqjH8rndgtPBuChj2+7A/E7uofh2nb3pRus18wpVc6X1TgtEejEZe3Z+WgXPNlMs5UGZwT3YFgdI3uAwxhXUwxFSiBgOQ2VNVaXvHyu+ZN5KlXGFa3nKN/z13x4KOElhn/N6YFcUDHzxunE6w/aEvjSRHjB8GZDFwRGGvBcOM503dFtvCte2OEi9QNrJD5x2Qu5Y7xch5H4my0iwPmOiS5X87ReBrbfmZdiXePFY0ElO9HEYQGqjGdcI/Ek8AHs+tWpi+oxd4MMfKoWmSYk
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: netbird-turn-credentials
      namespace: netbird
    type: Opaque
