# kubeaid-sha256: 42babd6c089a53a30c51b5098a48029ad17b5b0741d8efffedf913bdabd0814f
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbird-turn-credentials
  namespace: netbird
spec:
  encryptedData:
    password: AgBLK/2P/0F5AFVnElJUaBTGwqj68x1a1TbCPRF0hOXUALSAH59GSHfbU1LZabekJT2PUhwyUv+6MG5st1VN6S+FXNme9r+dfRzoUXvYvpMi/4Aaz3NGk+zm9GxE5uz9Os5jY2pTiFWkGM0ojZGkX7wJqguIVyn2ffORtdO0mL9HAAaWkb70C29gbnsA0XkXMEmvWuCEXwjCE/VTIGWsuqdHax2m+wY+zgwP0nq+BqWM1f84zXnDOfgIJVUb8mclfAMl7pRVDVYM3arGWxSzO5cECZnaOEVw1jA5aTqP8kDZJKNDJvfQGUcNxFksWRPplC31G8djuu77e876n2xiHQ4MCB5gp+juHqiPi3DOW2lzGn+GHIbeEyxW+pYmcd0GuSWU4uByBXHuwmiNes7xdd7/YOnTLfSESejnX62XmSAVav3DHAloycjhBwziSuBJztvVcFwF/hL6K3KamZy/R9AuH7fy5KcOokGyZF8wMF4JEGzVdy3yh915lk9Rey7f0m+xVn+3MFD9vG4wWqzsSwM7napARKepHv1UZ9tOlR3FN+4+dqKO58GVPDYbMhQ1zLmm4ifWNau+0XhHkPnt6kX6EuImPNxSPEfXqG7DD9mARRVH9t1kZ/ycvxUkOsLKYwBWLMZHG4ehZ944DKXpP/heHJvhksIi8Gu9ICjjWJyerWxm2Ju/bdIzglDgoPfbdNfcYTjO6mjlUVrwkuWkFPnVOnAkYzRVcT9GSV0TiXrF2Q==
    username: AgCIzhpRvEbb2wUqe0BA5s2VoIQKweqeME8/+4qTgi/znvSIcJb/T7ae5y5V81oHVGbmb5cAK0CqcYPPATzEUalj472pliztwWzXNgziCAsmOTNiiCvTboHsOx20T177XACOc8EutM0BcFxQfgSR5rNHYdLldZcnGkhmQcyxS7DL8ScnFXssZ+djFHxIngSznLCq4JJ1BEw0Gi5HNN2Z/3NYPt11PKHoKOymS10gbhPg8jyj/r890VytSo3UIAjdH4DagHMqE8ErMkHYS2+D7HbGxLLEMc/+AIARPpB6J1ewHB2wpIMpK7NhRoHFc3viBuCwUzOXnp2I9dI+15rHxArz5QAfP3ygWJDHPgdzo+b5M+dEDymL3T6Ug6s0KF7WkqvruaUiv3x7rShRRocR/P1b+c13XcifEIJyf2A6WehRAE2O2K34L+i4Qpj8CIhTypmkbhZF3k9bMnfKXAm3Ld4VLP1COWH659gLCnowh02XcxEL8Z8EdvIhwtJm/9qSh8eXLSm5/w24H4C4rq7x3/KJ/BoecXtXwtyjFJawTgYQldqWqeqNrIyYdc7E+GRZMWJ81LkR9XEMRi1X3QH7dyobT6j46Je3oux8whRB/MYLcYmtXCGKBWx3Eqlr2B5Lr+GtDkVZ4fCLPoNXMAkzjEt24sryvuan77S2P3GeqMG6ShCwd255e/NjHmkLT5XrdkRJa1CkL9fy
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: netbird-turn-credentials
      namespace: netbird
    type: Opaque
