---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artoo-tokens
  namespace: artoo
spec:
  encryptedData:
    GITEA_TOKEN: AgDMT/5BckoY9thf97L6UXUEwAoOrdVDi0rWq7LBoOPU8DSBzgjh2+Vrn5ua00YqITE95L5E5M3rw5S41oA4tGr0nsNRnY9VyvCNd09t3nh8X9qwSFGMXWT1DTT2K+WkyUZUuYKi0t7hiesn70yB5TIR1Nrj/GUxjiz/Me7XusuGIz779/YehAQYk7FwpBkAMSInDP+RB8Ite5anrBplWBSeYR4uGu4BGN92vYT6u3XqR1o6NrIe0Uapj3AvF4qw6ccCieCu83qjqYaVrs81WhWzQ37ITV6fc4CF2VFjMsVLONWoIyldk3ZDdJEmgzzboENrtIdZKASqiWg2btdkSjPft3Gr9i0msJclAZvS5FmpWkMOfAVO2mpnv61ExtlNP/rNUHjPe7rZqYF3RGV0E6A4lcYxcvyRMlJ9EH8g1EkqwFJzhFfBxAE8Ns0PfUkL8kX5bQcFKhHPS6OzZY90itsjjwWOI+YZ1qgTu/pjJmSMW+/Hn0VUplsJZZhmpd2szajrshGN78fXVGQYOuqEGZzJL6SLKoEkz/23KqB8zgKfwq+84YXyOqdmn27XTt5ei0vPsLElyPcbXzPMIgU1toINA+P2ufNZKMCzE9b/52H5VIPRxoghYqdjKv81nmyOHOQ0v+SgMDDaM5kdLUYWRxYZNBYMraS6Hx1/r0YL+OOF34zJ6j/lO0KZFXXmBf0bJuS3ERmj3O/PkIERVY3sctj/p1qGVJziK3jOOey9vwAQNpYAeXltV0nN
    MATTERMOST_TOKEN: AgCGpDghGFRiGRDloxS5CxRQeueUW1nqgX+FQXCq7IOCNyUMD1KiDQ1L5Bsa9d5wdeSQcQ8kzADEY4N7Zo50t0HUCJfEqGj0iDl2/GfQhntNPR5xjlf4tN/RTADsxx5Dmt35k1sV5exrxeQr3p7JlMTm6VN66+1VysEsBX2UgZgY84uCh+5ZDCVidVYqfoDq57/YW2/JozCxv1k05hfD0Ie4f5nxXg7mGNyY+1V3eI3v2/fI96mOOFeA7xX3mLdy/B2dogvgYyfB/MNXjvBZhftEwNWfqfRiVD8TeQNDuF1nZ2cMTQlqmW4XIEhAxBW8LzFxMmv14F64hSft7E8WqsLlyKKMXvG/j5ee7YY5CBc6ppmexFfjJRf6bqf6uXVIEYsUXKYPiyLmoZ8yUez/VIpQTOs49VxfnTAA1SHpZgXXSvfzPKxeFZiWsKLJBH5xDuVwZclYXfNseiT3M574ekvTOWSHNzoMFVUt536iRoTCoohj9ard+b4bsUK+hc/aj6BMQI7VWKpxFVuw40IDMlt0anlGABpp5yBi5GQFVpic4dw26UEcucnh9Du1z3/DHDoAQ0rGY/e/VgSiAkCWPtZpbS/PZ/FZcy06uNSveGvbi5pmMycqUmJiJi8m4pjyAco7trEVOxRCgvmk2zSBpXzyqpccTIeBjjZd3g67A5qB28w6g9OgFy2E7GLMQ3xXudiSBkjuuZYlzGa8/LRQqBeuzNyEE15OO4R6Dw==
  template:
    metadata:
      creationTimestamp: null
      name: artoo-tokens
      namespace: artoo
