apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artoo-token
  namespace: artoo
spec:
  encryptedData:
    GITEA_TOKEN: AgAUdRHO4pPkP5U5hWjIcA3Vrtl7tXpud5pFsMW6IIzUAmLRHM14uSTFPkBmAOe93oG55VjOa6Us2WnX+OLfphZnqBWEsCcsvqwaVD0lSAgp16D3gBcUcvvwa0QAcvpoGFDT1lBRpQXqWdod4iIcCZ02pM1/PrtagiqomPqEZ/e6LVp3sf7YhOfYhB9C73Q8ptB0jRTXq2VOjXUa4Hxrk2s6PHk+k7rxRu9dbPBSBXNhFSYtcHaIBInSlRmlRBowF/vg58C0FVcd60N5XNBrAQNDjArdp6Q5iQAVK4nZ4wrOoRSXqpgUYQbOIABXvZWEfMXKeYQb++15LTkQqAf+iJATH9PVGSsoOOnVsDWyO4+JBq2tbmvWL/QrS/ehzxjQ3HSsqdX5YlSXy9L9uZf4gJ+9hY0BFWzs5QKtVBfp2LT7lToDYo4g3z3SpLa5y/2/c1wZT3E7CSUCeTULMvf3tlM0FyP6OztwPVkFur4cmG1J7upzFKAzCh3RYCG47c3fD0rHh521Keecv0Y+dZ2zBV4/JMOUwVmEVJ0dkMT1PQQpsVtN21SM1H0EItX+vLiTs8OvC9X4xQZXiOsKT6LEQbdp+2/IGoTuhtc6XxR7hXmXJBbhnaH7LZogCSSizs0P89SpcOjlRYZ4GhGlBxEFICk/VFRfP7p7eODMs2X3pEYtfgSJvRYPjza5pXuKV2SrUxkIkK8GQwzq7o4QR+FtYFt+z6a3BE4xN1AnI8vwQJ7g4U9y2Q3gIiDz
    MATTERMOST_TOKEN: AgAAtzuqvB+bCJk73LCyZCgiwW40QnVxsnZUaOcFu/3IDsV8mOPOas+zUNkZW2iDZQuJyhXCmUJChJ3CatkiYIhs2YXIliNrUrlFu4YHPMM3s7t7COqdoFvFTuXdBUeTj/gxJka8wn7pyr05RjBtP8+oxftmcO14e7Dce+LQwCLuZigj/QKKPH07jyDw8Qs0Zvl/uRNLd0Jx1aWfxRvXJx2HVqaQq0rFm9P09jve4uWOrvZPSqhV/7ZiNkUnHVyVTcLIfR2LLVF01HzAt58OKcLxxJBpihx4oTjaJ0PrklQBYhJU+YjXLBR7oPUdhK1urqGNpV4aw3CGygViMfrfMWZr2KXRI7u9hay+ND+FJTRZLYcg3uF3StdVA36Vk125fCeL6m8vh8BSZX/4fhXZwBsKoeAmCh7iKUaNpWxnIm4ioAeBTxR8GwLMIsIg2hgJFXuIbcP3fekkH8r/vy4N5LQ5yy0Md/8RNDtT7beryAP2V6GtVuZ6s1CfttiXXWkOB2vZJwSy5mp/rieiQc32j1B2JODIL0QhhZ5mfZYuGsWlDC0oGFcU0c9m7RIfqCPeeh6q6S0efksUigdpjzY1BoVz69FatZa6lzvRn34xfqiJBq8d/QFhFQ1ehXrC5nNWpmtc2LPZ5nr/Co9+9twosh0W3JZi6fQz8P/Dhn1tdvc8IGn4NAdJom7uyZDcgwm4JgFkT0Z7EXbqiMz+W+gXkOjrMD2nKbjgY0PcmQ==
  template:
    metadata:
      creationTimestamp: null
      name: artoo-token
      namespace: artoo
