---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: artoo
spec:
  encryptedData:
    .dockerconfigjson: AgAaVhHfEkQjX8grTwKjbnfb51yToY01gAylRNwdkEPnid16xy33en/mJgXZscCSYkdpYWs8W2dBnUBqHaP2vZExYDolCvuAaOLtD1cEmTVrz9ZkcaDqEObsqMUmjz8QsGeQUlU4x0UV2dVNxzbOKKgZJ498NL2qne8MY1XsOagbN9QOPyXnERCoWIf07/ZbUlWQ1CKKeDHFZxjOoOyTy8UvwUNVoVKR4cXtGktr1hxbW43E9RXyHSIj+bKH2aWYy8t0ZQltrzmKhuRzyNfJN1omcttw0RGQ8w8n6bknr6TFT7BDvdCLMix6wiMIrh25MsIVqacyBpByCCxBb02bgQ6IAVibQRk4B0x3F9RytHd2MuJx+v0whDsKZBJhlaCgx0sqdBSwlbD+ULeoJ1DONk7kmW7JuuK71Ck7nHKMh83qD00aw/SyuU/Mo8NAsfbklpGYK/BIQfZtaCu9azXWRgnFaK4IhVWxOS40DAzZTq3qagLzteCGipQ6r2j/OtpRO4FfRolJSjwTYOaRRLbXfCHa3i1sweNFF8V7jMu5FCXkpHjzlCd1FGcdi9tPdCoEnsU5Y+EO8VX8ifFwWoo9Em0FmRMlZ9W/CWNcl9VsI/+qV2gpBYAkPtj0s1KBXUlsQZQcTzwJw0z6tykMj8CC7OkSdqV9U4BcoB+u4LhZA7RUa3XrFG2JOh8WNs4d1zQhGJMvnVIR9LjHC/Mdn1aWnZUR1zlnwgD5zRpzogI97PvcTwMpshbVa/oYvqvV4jqvXBrRh+Z7nodX/hU3c/FDMxGhpTCrX+AwdiiuV8xxtvfYA1sXSbzzny4FIdXrQxhJ7j4LCpOz5owiq2HNNvTdzZpFGeyw8iM86PDWGLxYehInnw3+qqyA/HTEQETctrT4iM5UBkacIxTT8nkQcUEvlm91kbqK8Xm3SevsstvPKJtF6xmM/7Ej7PEC3tqu7uA29f/PdYm8FFIp7RJFHGEDLiM/Pi1SIG4ZYtCvCRWc3CZws69g+9rw29H08g==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: artoo
    type: kubernetes.io/dockerconfigjson
