---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgClj+xuOUAQ109d3IAB2+LtI/aY//NGdTrnnjIsIjAsyiCEsfP+LJELjexHNlycvkOinI0IWbbheRwn/i099U+pmsiGggaooN6Gf0IHr4h7J1190r19nez9mzQ9BlCcNHEyaRsAEA3KHKg/IKszwEYe/LIElnuL7BWiSrRhtbS5Sb0EDvJMGvqEIneXw61XKmPx0+3fWU0FUPTvzYoLq7+0mH6wfWjRsfHZEm0wCdgruYuDw8TSrTY//t4v6hwOOpxKPEYYKFZ4rbG+PPwWCZYBEvbhBySL4x3JRzBS13StnuZGlJNTMZFlxWH7ok73u1+8RI+L++fET0ilk7w6GT3SGMGeajrshRkkgoy36JWwgbRx4tkVgpqCHp2IVryLPYiSmd7kfe4ZV269Os+CYbPPfoOO+Aml3zlXkk9hPNpC1iepXwrW4j47J96C1CUV76w24PEAp7w1FRcnOmsYfcgs/e2G4vfk5AMj245jZbAW82V+Ke497xy7N1nIJmdb19uMX1ZnbZMGiQJQL4zFsIm4DuTHMNtFBfNhbEFFXN98SyJ7YUEWtnKiVbdUko9ajPXr1fAD8TEbMgf04rqDQ72sfNFGy3YEm0xQlKz9/i1+3h9aG/II1MChhJ8lEiM6f/sU/yYMtj900tmra3U5HcoaeuVYmZBQnrASft7oKrXFcTdCw4NgkDUgMIboLKJnu8AhLED6l3jm56WjHAw+2Ntm7qMBdbkf8d77GmPCYd8X1vZey7S//gHA+i3C5pctx0GJZEq+QwRei3CkKbJk/s+f
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
