apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: enableit-api-gitlab-registry
  namespace: obmondo-ci
spec:
  encryptedData:
    .dockerconfigjson: AgCDbXBow2VaL3yTcgVP8qdJ9BE76qh/hUMpr3kRNrtYVtJ07VKNkm3wT0hHsd2rvK/CWn0fYymIfcfLGchwh2/M3qPuxdPGGhVhLQvSIdi3qE0+Y47IlQF5daqIuQqPsjkgg1neNOJUFORhL9qWLs/aE+eCxtxBXHPcUdwXq2GgpSwLhYFBMHeB/EkKR1Vxwaub36p/OqdcR1qff7i4/ES6CePonPQocrDAPPx5rVreUmWqGphNHin3r26rJveBVbd1Ff84x3lIyEL+woJ7ix2umc7sHw8ndtQ+juqjWS1/fuQDNWkDphCJTetBODfpg70dv5HzAIhqoU6cuSTibmsEmyotRoKxM73hknMjUmdBxQEc7zFUznNyXhHkmljDcpRn+a17YNecppmCjuCaDUl0kxG8RTMHlLzBeRrQPSyNr4i4hWSK0qNLH7cz3QuFihhwhMRmUpMrGFlKQu/sgNBjNoE/hQvXbjiTHtgCacXGUVCWIJIAuuoju+yn3ZuH24lDPKgKf3pb8+0eMkbHGc4vAiR3Bh3PqTMHC41iRspdnp1dypmPBOvZ9NUsPpjybnDlMAnWkdUllrm1XViRVAvKL/uVF4nTF/uusZTJpHsfMCQjLRLWcxLsP2zzoybx4eGSm3wPBLCLLGNq8uGx4JtdY09AMxIPVIRsDVFMstP4HJz8BKxtAdWlzNhw2Piq5barALeWddfwc9g8ZhFAndYJkTzdzQryJigKy4KkrtflsY2NWV/1bHVN7x7L/tX1umxzyf5IXJ2Pdaby5YC+x1Tlufn68cqUvunlc6yvn8KVohwfqacSKG6tH6L1fn7I/0xLAxnEsTr9tA3c2lIaQHSm0qm2rYaM8RjUOLjWKcgIpCvZp40e4pHbIS1id0Q7CH8xYdo2E+Hwgz+OKCjc6AG90JdF3VIUuxUBo3wGHZqDMA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: enableit-api-gitlab-registry
      namespace: obmondo-ci
    type: kubernetes.io/dockerconfigjson
