apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner
  namespace: gitlab
spec:
  encryptedData:
    runner-registration-token: AgAd5DRwBsk1nFc0oatXnJiJtdvAaOMGooKIVcf9MtPTwwcNb3s9twkqburBQlBjHmPyJFFJGl0VOPlcGV+jjIPsk8H5t2gC5qZ4EO2rCttiPnuFeQVT1B516ge7LmuLOJI8JTfwWvc12Z5gXA8nCSSt15O0+oRlKPKTFZByXvhwRk+BAdZx+tJJU7MogQ5UBQXZSYXSv4ejKVM9XZn3ZVpZF6oN6/QuWbPmkb3mMIesnkLZ+YH32Cc0yKq7tvLsJ+vP7XbAuInvFcf67GANrmNJCjivUtXHM5G8POnx/YEyvgNScECHx2oit5NEK08brkbulx4QNCYGHHXtZ5PRAD2o9LOFh3H4bHdxFR5Eh+0vEwVuR08unDLIhsddVi6SBEDzSyHFUAkqkr98+PCXkSOwGWZx0l7gj6BksnnYIBZKnOcs17iAiN2Ma16HT5nAtgJb54Iw9wDuoOME4sw2yEk/cZkXt5gZQ1+2XZxUvMELfvniojYnTRM87T8w3TJ6gjw8ziKBKtJMiRA/4i72YZObVioqSMGkYlowrrdcBdR1wjvGdngcWT9y9NzyJXSfT/eWvpFNZlhY8cwFSJGjMu/2gZDGwIwTXXP7qxhfg4OYMOIKddkvRODVIyXBWPD5HDRLH/j2T+Ketm3Klz+3DZYtAD/TAHUbc4bClZF992Z3h/2XbOTtynBqEMK2LK9fnRRI3QOd6pSmBGVnO1tx/1lrgKGBsg==
    runner-token: AgAnHeQhQmBt3SV8S+UUxRoaVRLdcNaDywr+9cXphP3hEIiLlmyBumnz44jAQSeQJpxPIDf1GkgA1R0hXY5Q1wAgtCWGu9A+6+SBJcBG7nsEF16KbznLmkQcilSs1Lhp7mTQiVCliv2EMMF3KdMpy0He/7n98tnaUfBEFu99wYW9PtNv7rKlFcqzXXfMvHVDY0bGIQ82KbAF+v5qG5FHQtNqiFfgM3hubcRzlcUMU20YGemwJhim5EE/4uldLnVtyH1FxYpAW9kISIkDK9cpWMYbQp0bIApi39shpU45uD0XxG2cw2urT6bCuUWi4tsqqUz2BBg3Bqmcyi1vjWNhgh5P4m6h/6Pc48EuCwUcj57Tu/InCd+c+9rkmxDwFjPqGFQGjwhXFEP3LDT8HfIOll4HTYliPckUoTYqOtyGIuZj+N1+Zz49lG/+KvOO49EmzTFLPbQBtO402JDHioGxHRnKuHQNgse7UPkGPYSkflFq2kc4xvc88nRO4NqqVtmkvLhFEb+LXBX/gbroqRS8pvUilf9Rqnf70WEgsx1gDQrZyXLaylcXrZD0EztRrejepFonG7fDi0qfjKUkP7Qp01J6JpcMJKRaHqdTHDqTi0a9bEry26AAK43gOD1oLF0p1scA/UPSJro06X4oic7YGUgMe182dqYKvZ8VLRIHD6q/p8jOvRsC7XOElrgxs6hpTGc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitlab-runner
      namespace: gitlab
