apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obmondo-web-app-ci-gitlab-registry
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgARzOZyYHMDVjJ8hEBpz/dUToqyhhRyX3AU/gBXBPXJgKXANURZTrtShsQlNVMtkf52F4Go0F7J4SEctLeU0GxjSOWb68bpL0pyB0RRIMDRafZexIf1A9gvK8B9wbLW81nYwHc4dIirlGJa4pt30A9UUQUimk5EzS87t9IXacqQHaLF85nRXvnzgA+x3zthbEb+ffXZWcO2Q+SkXMljxhh1hGCiwU3w+IfXqr869IP5o3yQJGTWQud/Ecr7NMhUlfe7mBVf9AYI3FqVmrEljnFLOrJG/tv06TFElWP3xpl5wBbPK+3MHqyWuy2YRO40DJdN0UtNITcAHVZDIYyPcGhHo5iHOKxPJ7S8Ixtcajbj7TkXpHN+3SAbOL7Jhr5cQi5nbMUybN/A/IUCr/MbRuT6A9v4GQ/+mQmBNCVViKdMZ5zMRX3/K/8CkDo/pwVp4mKH/8Sw4UpRGNv2gl5TEhXuX9Nwk+KdWw7qz7939lpRsbhNNXUbSz/t0lyx+je7rhv00r+i/HL3YS1wN5SZ4wklXrcIhfw3BG3BRtya6ss4XbOINEZofiQucA06HAiwauCeQlCJKfEuokyRLJwUbRRuoe7MCVMyJWBYb5imWgT9pL+23YGP6novHZKXPlWrSvlOzoOF3/+NkAKc4XBvIUZ3thQ5HyqGLJSVeOATy3wthxkQMfdKXEJqMewZ2oguy9mNNC2nNobjzsEYfUfSpBWrLRNI4hF/mq/Li0TeVyGpz4c/1nBd6od7ygSCj+BQ6SVKjlKg/6OXcCczRB1IPX+GIANip8UJip6aZlmqHtJhnl4/EWHvG0QX8XCjkKBJzCVJGQ2R2auRVOy79SOFrQU7LiO8GjaNvUe3i42CGB+lgjUKCl7Q6CL68og0waFcX7EFHAmHFClI4Xmh4z4I92WkMN5HXu8QX5kAVI0YJJVnrQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: obmondo-web-app-ci-gitlab-registry
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
