apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obmondo-web-app-gitlab-registry
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgBQNr6OUnpzHmj7N/zKo1+mw6QQPpyRoY8VTFunk1KWcjO2VauV7gL7wBOUWIOnn+HWcCNSGsFeRvIWIyqkPa7PmaIuEBQMkBJrVIylCOtmFPNlZzQaoZTQG1jMYRjDEpHHIgSA97XB8eDdzWtoGfSlEox1UeKdFCUs1PsfvTvaMNyvJ4YdlJK5w9mupvpeg5XyGBhAP8ayMtf/M/NxonPOhMdKIli44//qLGS3w61J44ojZGi+TGU5e/nCf7en+1Rzn6tS4aWGYAyw2KlK1xMKCEgdiyXks04+ZL0Qgt10rrcDxIv+m1+fErJkxmH4n7JYpTqM/g9xYlwmWBLEKk1r3WtamDT7OF6385lCC1u9G45vswv079HZazOfTEyIt+T8EFalWMbIozTPDMh+4XtjBWMDhvgg5q1FXx+7FWpG7wQ70Y3VkqaYqxX5E4Q2GuBykfNX3Lr/xUYYCQcc3hLjvMceg4udHuSJLSkreU6ztcokO61qSP7SWYq9Nz2ilE1OmEC4ZtUsmgECuyYe2IzvO8tVlCDhlibwIiTrerIomaZKGkIYsIDCFEhz+L0JiR/iXbZ6PlA3F222IBUMdpK3RcqPFKu0+u44JtsGIAEG5LR+QFpbZZ9Qlb8vARBErr92Mj2SONd1Sxgn9XG4akKbpAokwsc5Q3GnTl57mCT4hSQldIqC4b+ttb5L0uVL/VRQEQYHyhCxUYo4Ihfm2q1brCed9u1/mnX1RrHPmpo0XH1JbH8ek5q19zvzBeerzITTmBt8fnY9k1KAvq3oOWVW/Ii2HvcaE6zZaLe9yvr+5NUJC+7v3gJKSxJk/+X9xa5ervKLPwk9HxYBmOUQDBcydleMCHmmHb/kXHgEo31ajbyUIAI70k4OZ55EsJl/POr3+qjM89aaiqKyMX8+9knYueBUQFnaHqkiwjMX09K1cg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: obmondo-web-app-gitlab-registry
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
