apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: enableit-website-gitlab-registry
  namespace: enableit-website
spec:
  encryptedData:
    .dockerconfigjson: AgBY74fISFgq/zltj6LLdzmRqy2IqiNuLPt0/k6dpflol0tyhRGhNZ1i9JlSTB0gqSeCmrTmXsKRKuUYn7QPgkJc8xE+txXn24vTNVUgwg1R9aAtnUK8EUKeRtdveihY2aGGfAU+p+nTC7dg0q1M5mXUu2GXm+pE1VwmOyggtVGEA3dNIl7wNuXlKJKDyTbl+zYzucFlQINyWGO1N5aP02F3POcBTLJDH1S/uVkFmVONoD8Rh8oxOWtCFVMg2woAlPMX2wsIH24TEzrL7Wk152FvJbrCr6Hj0D7FbwAePwJcGjUbrQpheKyD0ODrPHLlJNzZVKMKgE8eWMd23aY1cT9LmiLF2C2K9oga/U0PJzd7cW5ETrMt/tWE78wWeAIxp/AI5hk2QYbeaAAvG3MO2upvLj8C1KhDxmy3XLEIAQ7Wc/Y2w3WfxuYwBI7PJOUkVSot2HIgk+X1V+SOKW8yguqkUwZN+WvP7IjCYPH5zPC19WRZ2AEAtxZ1z7gMkVv2MCFqj2FTZvNkvT3bHNjzLZ3/2bUeU8CNDUDRyns47xQJIZV4Gw3OCX/XO1pDiOjAlf21h3LotGX1I8yFybwHNin1GZL0ClQZy5Sbg5+8uqVoSrAYcaQNn1S8jOqlGePCGPlFtDzKEB81rOu2nh5RCj89KLnRr/PxOQeanKvem4Qzf7x1iBS7Yp6YTAx4T4a/6xKDPZz4YEiZZTnv1rGR36KRb8yMzrVeJLFSir98gGpncGD+vkQXSCfRUWzBXofOsCmRMNwhfJwfDU7RM4EVi4EbnRdN00IoJLqGu6V815UxeSQz9aQniH1I/qpbt6J2W+w9j1e7uCFpYwp0fgWlQNdCAJwAF2Wl1oi7bUWTSf+J2g4vD1w8/up7MTN6GOaBmMeRhvGHb8nq7qJ1Q4/EIgT31/u0UdtqI3n7SslVR2++2w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: enableit-website-gitlab-registry
      namespace: enableit-website
    type: kubernetes.io/dockerconfigjson
