apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 29.0.5
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: cloudnative-pg
  namespace: argocd
spec:
  destination:
    namespace: cnpg-operator
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/cloudnative-pg
      targetRevision: 29.0.5
      helm:
        valueFiles:
          - $values/k8s/netbird-obmondo-com/argocd-apps/values-cloudnative-pg.yaml
    - repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
