apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 29.0.2
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: hcloud-csi-driver
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/hcloud-csi-driver
      targetRevision: 29.0.2
      helm:
        valueFiles:
          - $values/k8s/netbird-obmondo-com/argocd-apps/values-hcloud-csi-driver.yaml
    - repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
