apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 29.0.8
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: k8s-configs
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: kubeaid
  source:
    repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
    path: k8s/netbird-obmondo-com/k8s-configs
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
