apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 29.0.2
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "20"
  name: keycloakx
  namespace: argocd
spec:
  destination:
    namespace: keycloakx
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid.git
      path: argocd-helm-charts/keycloakx
      targetRevision: 29.0.2
      helm:
        valueFiles:
          - $values/k8s/netbird-obmondo-com/argocd-apps/values-keycloakx.yaml
    - repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
