apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 29.0.9
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "1"
  name: root
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: kubeaid
  source:
    path: k8s/netbird-obmondo-com/argocd-apps
    repoURL: ssh://git@gitea.obmondo.com:2223/EnableIT/kubeaid-config-enableit.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
