apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hiera-git-secret
  namespace: puppetserver-c1mdewxeah
spec:
  encryptedData:
    netrc: AgBxdgKBK0CMpud/MloTRWl2C+hJO9vH63k3OHuyyNZQzoWR81o034rIX6pvYdUldE6XIh4nYH18Pq0ZuASVLjuBLJIqLgnnUt03znGHweaG2FtX+ANQCK7dNFqcHamkn2LQzUDc8l0Spje49l1ZVHWzjPYayHzEFVRKxAisD1M9Zd5yLspWsxk28Xcu51Vy+A+y/drXV/26+thZJLOl5rK5dKKNfzLqFdPsIpo9qWGa6EQSL7QDB0WCLd0x2KVUs5wqOGn3ozmKtORq4hl4CojV64Jo5uVH6gJsWutPzAKaDNskFIUBUxx72K2IohgWqnJyxt2yk+JNDtsEpSi4hghR4nXt4b4G1jv19Mxl47s0sUjDkuhdL15BebzToRj6xMBe1xqx/VUQJsdmzX4EGc2DXuIic9AuVUOz8ZgI3hLG3eeVuN2JJv2dEyxN/h6Vntyeu0rTI82JJb7DNqJKTozGGUqZhBwLttfG/HEOlZ1R6q4O4eZixk3c+MNzh6Z4KfFHHAC+KeIa1MzyE3AJqV9M/EWIaIsBBFx6FFLmHdYvSlLZ1Lxgpi09t5d9VHQlyHE7aWtC1d9YdIGzKj9Ptxbkvw9mSJMhFCHErXj0xxlWsgRMOfAnDe01XTueBDE3QGkuNJW8y/BUa8c4qapVHYWlcgRJyw6xMT4OVHN7SuG9SPaf8ePYUtdIoC23nI1rcN2obUWWIfPK4YpAT4bqHJnw9uxXETiMwH/wC/a6Zp8ifUxyi6lukCyUFk5EEJiNAv+BpM9wZyc9rVxJ5A1+aBryZOgNjeVLkSskFiMFyXBmgm9S3OB0uK0IGy5TAJyxQ1OShXq0
  template:
    metadata:
      creationTimestamp: null
      name: hiera-git-secret
      namespace: puppetserver-c1mdewxeah
