apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: puppet-git-secret
  namespace: puppetserver-c1mdewxeah
spec:
  encryptedData:
    netrc: AgA3ksabPZPglO02n4v9Z0BN8GNRmTHSUEJFc7QK/A9el5888cixcOeqeDjIDbJXmIDVnYT7UAc0XwYhy/ACIorfSA3HLb+fQQB0KNTW/CVoVS1wlC3HdjjYIjyAyiqWN27Q4bEiRbgxvlJk75QrY+1TzTXRSFWAwkDLwYAkIXe5Rorr3ymoqjb9cf0ZbV9835wzsU8ZLi49e0WeynmyNSdQZPkAsEqtPLkjkSArMR3kx+zVc5tdZH+NExoKC9DsxwdPcJ1ASTxyNkoZCU2FY+gu79iGzNjQv4ywdGWrE3Tw3WukHIKsNgz3573CBO2u0/hMu+sjy9vR3aTqEtSmYT/cK1K6OzOtutkLFJnwjEDAYQGvyNuN0OnmBL7PR9/3PdzXEDTEX/cJDsmYLkpKq+FToTaAMvLzrFd32VRBA5aYUDzArRN5QENdvUp/kb3z3LOf7Yrs/hDdEFJdHH9+Vh2biwtofu4fKdUgdFg8iKTsNyc6C/13g5cDUPul4SV3wodYa/FZ1q8Y7Drd86zZEtuVwFZDBzxmdRyHKFR5of4OmtOsb3Ftb7hsSWRj4DxKO3rFXgUkTiudPyMnHkOX5jiZxfjevG0j7dXVeHLow2yGkOQOBf7F8bSUIu4ULz3zGHlcuMb53zlkNmOEAPNRMT9AciQqfdwj3CLV2QC5Ge76f+FEx1dd9dwejvP9ed+geoWaRt/rHruGvOy2FyKouWQ+6Ia4rymIbM+9uJZYnbjuapgBaETiGF4Ka+zRYIgIxffB2M0TIup4kZ69MntzoP2v3Soj7UPVSmsc1ON/yKUa6/YJNGuIhNTUx0UtOQIq1U0kTgUU
  template:
    metadata:
      creationTimestamp: null
      name: puppet-git-secret
      namespace: puppetserver-c1mdewxeah
