---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: mattermost-operator
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgBXmJHxpJelAch6k3ok5N9AYZKaQvN+aQlZyyx1+oCc7NIzArh/W5O8EP4r7BT/0ffUd1YE6KwX93xt6gxFaqHlGtcR1WhrXl77TNGRJebUQDLDyKvLleCgyZoRDb4Yh7LaiNllJSZlouCYoTX5evVGEy37wDJ50Y+eEjwTJDQ6NPMuCmaS7h8VnqwldyGFeSh1lW1Ew1lhIreFjlNlIAER3NWlPw583gew3tl2fDoWv1V0Gkg5pYslwReJ1562EZa6whj/gkywdVZaVg1DLkBY12J/KxBOamoKz+lU+5fx4CF9s4QnA4YHAC1LWioNjlx9FMCMsDLEptVIjHuc3+oucXJgDU5caf75Qi8MSDsLooX9FYMIetSyw1oTvxOKf8weiAMNI5pezhORrifUo60a5URCY+znNiCHWjXQUi01fWCL0dh2bBVA15kHUJWxVUAvtpZRmMQrzopvcNmz7N+twb5tIlMSmi+9tcvUMB4n4wZUVhzRxPEq7DLb7Eafa8w4CZTrWP8RolrHbFFPNx+FCI46vvhpO6a0S8R3/LCDCVFHI0gv5M8t/aaeR3xpALfGxNwoAeQsB4ad/16CS4XCm+2U1p9etfCvU2DiSgums4CFuMbQJnzKRpxEC40iFX7oUCi6sIvk/3AHfYli/0/KX4b06mbiSiAMexWucr80OEQ6Atg8Ke1Uabs85KIxc96tL+cTexE9k9DIxsGQYJn2TBAXqI9Til7S48f1nrSaVi5HD7+/JzvC/YBBkGYVFFf1BKnhxHLwXc4ctMTxNcb6IpQAYkxqsW04dXDv9YmRp557ZSLCmv3+jKEClciDYGiRRVcKP80CPrhObHCZpmFSDBVhxz8G8YUUf1g/8/pnfAZ4QKY/xMm9wzwD20KK
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: mattermost-operator
    type: Opaque
