apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCq3rYinwF+mNZRUssHnRSLBB9QoDIy2ZGJEDg+qNjZw50Et3xPx1cvigk8TBZLWJZEtDkzE8r3MZlWhYvaa8+9asmpp4LHIe/En2XGL45vQHDhZcRujRoD7IFVtZcHwJ5/4AouULPPXBfjP80pLnyEHA3zxoEiwDeUrRaPn2BXp+sqRVDvZT6pJ/TtEXMLdc8VDLpjuMD7vNIgcJQDVlq08YdLRnUrlLOW4Gf/NVpVBmMmoz0/pyBKrI3BdxpdeN+drCwZ/PRpFVV9Ff2RrV7auXbp58YyP7gdlOK72CqQu9OUAqqOU7DoOpdlSoJSOJq2zFWVqZzhCLIffkUE/FsiLnsPmVjdFDP0KaaP23GSzZwNE8+OH78rsgvxV5/uNytzIQnr4oY6n16pnOI00GUhPpjlUt4QIjJu/jgraLgJHpJ4no90JA3Dh2mt+EYNEcd2PQDRfxTTSMNUu9SF+STPJxGQEezEFzgRjsMfwAIuoAg6pdXZckh8F+gl5gtep4kLWIXbdg8yBQJYZkHq2wznB5Urw8lCwdBYtr4mFJ/xGTxvkQkNVeBIM9ucLLel7kIi9Kmi/mOr6j2seGyRhX7S30ms7xZma8Hzy1DXeetg/p1LmIu3RW6QhrUdQYmmOeJhi1Dli8E0zv07D61GDF2jBK56uVtJ8WtO/T12Ol8fsnM4ltB9QeKVokBdgOnOwlrAWz7SEUxfSIiPXaWLJ/ykuO88xx4/E3etHkJKftcoBV4bMwOAdrKf61//d1uYmstXrPGpZBTsBd8BushImxYI
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

