---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgC7BRgDhe5GTkIafpVc0JVvTPhhuu+5ZVxL2rz4aNMnCwQ6wLRd9TZl1MXYL751fbCtvLGifIXzuXxAgqZY3b8FVZesIya4aMtxJp6VJeQCcMYSFtluPRW+jgO9Nwl/mn3vKYauVTXfLZZUBjW37PTCNKocHPqaUgmX6mENsYMjckmuVESJpPTqgFmNYWgjsClH2DYvMwBn/lyAGv78uoQwaLB7xp+pRyKONspD7YtlXQ71QYtzaSlvW1RI++kfhFafTXwOtEpbN4O0z7kOG+NbXVtzfwzQ6ZtceMWlCJVkDFhfzI8MvBQnjO695pzyOwqgFrBx/R6TAZFwNeDJFyO/Nc7cKX17aaVJko2qfE1ZqUs/uZOyvgFwRVW8YQTiXp0j34SHPaZt4LvnqKFE8+OzlIfhSRi+Qe3CTbzcGSLlda7rTo5fWBGiSaxG8UoZiLOKSjW76NAAYCxT/rwDA4WuHFj+n4T5T0JF3BjsvoEc8Yy0oiH5tI6E/5SMj0gOwGxmEnblNmXH/2MFQwOpPl1E/0Hs3eXLE/O5eN0ywpoWg7ptAEPXgsTRv1hNex4sW9KMU2khoZ9eX/0Igz6buYWkS1B9Ij/5UQZC7AUyr/Ha9Ro/63+OzHZaUqO2YcXHznnR/llyCOpX+NEggfWMW3fdPFhYZp/457STjqfYR9l1r9RSlE5wnp/1rNZS6LAsEsDQMmIGdCxdqCtV0tMe1OE2/paBjnwYbT7Z54+BQI6jEhCIRBYNlnWRlpnq9Hd0oMsG9s+9yDJ8GzUPvEcskdK1
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
