---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opsmondo-registry-secret
  namespace: monitoring-staging
spec:
  encryptedData:
    .dockerconfigjson: AgB7ycyAGopVL/TO8RUQEq6JNhJv4wvoWmb9UPKn8EV7dRdbDdk/R3tw0n5Uz9QyYJxSiUMvj3W12u/ThYL/V6sbqpbceTMS2L52TBz6fNgPFY55oGMiUvQGn/VPkSx3RNU/Wna2bx1FhSKc2oO8morL2mpQpMwv6hqQtXuZ/PC3YctZOvQcZmCviGS6zNfuXdRiI1LzhuHmtYYeAvgjQpDAitZZgABOyGSV+9qgg+UR9HLv6+te3lhSqeU3LjPUVDoYWVR/mVKxVsiX1Pqf4SvoDo/ZNdqPRf5TCEiDq8hT/ZFPU7aDnIVIREDHJ29QIns4NehOBLYfaOZWgk4s9gC8Ww7ONmoRZyXBmoL/6IbK66CGZeoF2NJMs3CDJRjLL66xA73uw6Ix+4UDOBp2CVZcUNQWIPdSw5z5x4kghohtdQvKz9ap3iW+Icyq3x/CDUgTi3ykQQm+BgGfxyVdpkMqz8p6QLWrnjKAFbRidkdTlhEtN2QQPSZmn85dgpcxSfRZHbf+4RHPI+2ka+L0tqEbru60kcj587xC7DpCruiqOmRT0uKzldRl593gdxUyisK2Pczp/CGMjXVUEzHm79tc3Nmsw2pzkqSJoEuD8IBkGZR1GOqus9Uu99cfjXnQE/onPzNom3Z55M8rwsvpYWFDAAD+nEK/W6gzlMXnpBqlOUAvRfuRPqhaJ/q9+H7Q4DR/hmJoUlcn5jcEgfZOwCgt2fe9HNxl4NcG/RXhFEy/ptAYVPM35qLWhY3YTbp9u8QoYl3/KH66tVFY5WznWfniOuaLEoZQq20grqjdIQJ7btDjtHzkFplhJIAKJ0MWvvV1owdBpXFYfIdJUBdYdLryBsp73ZzR4X1070oCWWbXOZ1+7dbL17hrlu1tZaziy0kEuXXDlGXmyJ9OVDfagr+ddktEAY/T6iHswLJluGlADVqoRTLziR5xyKWvIV+bIzJpnEGAqGJs3jHThv+NG+3PcHdRCR4p3BHygDdw+pnL0LfCRqrh6P3A
  template:
    metadata:
      creationTimestamp: null
      name: opsmondo-registry-secret
      namespace: monitoring-staging
    type: kubernetes.io/dockerconfigjson
