apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opsmondo-registry-secret
  namespace: monitoring-staging
spec:
  encryptedData:
    .dockerconfigjson: AgDA9ppCAb4hHQAHmE4fzAuXgxtpQm8aTkcLNi4nzMMOOaydJb4ILwXPNsmk5kAI3xUfi77daUzSsqTIIDXGVFWrsOZZPSrzNBhqbVPiylOYUidczHf9UcrT7LdagLRSM8ara/0F1JJUN1NOegjyZdVCa2SI5IzlfWaijWg1ErF7/ejKauqMcqr5weAcEyTNe5dcjurnL0kHeTCqE7B5X8pt6StOdo94DIb2lsu0/v30oAR9opXSC3Iewm50an2Zd1s94y4Twoi4ofZH9Uivf8kMeB/kHCBa75OieqtsJJhSiYZVOVc4UOE3I4QEOTl22J2qHPVoKjmF7xF8qJ8xclt1ZRXHUfmBH1svr3AGENofh2LU9VQtdZQzl0o7DjaPB4ND6PCN6BcXzUN8+jFqcx7h6LXK3TVnxMOs+A9LGjSNHcXWueu+bWRF31L77jQmlE2M7hKoDWxxJ25n8TdXp2e706y03k5Lv2DdHqMn9lxfZDxsRbA1l1gg8qJgjOMmmJXf9wfGBo31oBFTqRgVjvbT9Atrk64hs6kAAsRA5MiOzJBcGKu3AHL/JxWsdxGO/6MmFi/YlYsUbSQbaWmypX591asCHGv6iUHkn9kIQBts/rEuuSQ6ezPpYaa3rCRuvEkTY++fJtUVgB8SbkVh8M3KLIuw7Nh6REkU8weGUipGmveHAugaB8fj0NjkLIxir75Sbfli8UDiqld7n+CZkhPJ9Lz2dt6oj1tetCKggpNa/iANwX9ZMLn+44VwtkMQ18S+FDRm5RSSpSjypMb9p6qEAC8y3JWKwqKYuUKtySMHq+bUsuN28m/yBNQXKvgXiJeqpRA2OBfojuaflw727ThmrA1qO147MWM7BpN5snzmxRE/hF41EAuGUxlaKVHwB6SqI5xErgdEke0OjKgEISBzzgmTDekXcR9NOKbf3Tki/sipbHZojlYZmmKD1Hk=
  template:
    metadata:
      creationTimestamp: null
      name: opsmondo-registry-secret
      namespace: monitoring-staging
    type: kubernetes.io/dockerconfigjson

