# kubeaid-sha256: dcb629a23e687f29bed9bb57769983047656a9736f5c1ebb8b689d6234ed01d7
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloakx
spec:
  encryptedData:
    KEYCLOAK_PASSWORD: AgBDsK+5h1sNolFR6RnAU3WWghFNku/i5etWSbTc0+s6tRGkKrVW8dDG7HCnBo9I6p0uayUZlakUP4lrjYJ1Il4+qu8psMLweZRTYIHqT3L6MZqjG7N+cNlE6HtNlfLxcT5i3PO8A7dt9CifdQo4XbZpSxBP3qgaZ9zEfTHy95u7l6pv6MWZWN5LkoOiQZEXlheYpfSKyJtIyXL/4Cd1DgbLKTbzxWaR5jzDbbx16f4hPYEUIKASXsddaivfnrsAHzS0kMLQzzr4zfxJRQPUHpkOAt1LLZE2UkXKVVC/SfVU9z+fGM2BXTKCCrthTNNN/6MKZdPRDXtmNasLgNPdwRtf9whQa1sUKJ6/cgv/y8NOWzg5xCzfJfPABMNPnjFMKCY9BA4dOhg9ksJQwq68dbnTNzf7O770D9kjClGRXxzgxZTrjtBqkmobIDLQoINenyhH+qGszN5IKFjI9+E49cAg+Pyp8yZQ8uruV7xf0Isr3D568ip7xlDeC2y2/hWgpV2djtzhf5QDG+krpEiEN06CoLM/HpDSuXCRgKMQqFj20cx50hIgM02PnSY2Lqfqcom2vhdz1RiGFQ5Wj2INENcH89xf9R/t7fyL63A4/UsSKjb2BHIxpD1M5OHeKLhniOQP3cA8mLXD9YjjQCrcozmXgA9vakFNCmXNku2iCrHjzv98J6ibFsIBgGmtAKM3mID3Om7BjPFShA8+gKZ7s2Jbo6iILVLYm48oQI6x9gXRig==
    username: AgBNiU9CEMVc2SxPPLaJYZcsN5404u7Jn/IIKEg2wnJRA6+dx9S4gzWyLGCfJZPfP8PtoETZ9lxVo5894r5UjMMNx/YUksNaD62N0mEKnC8JzLNDFGq5Dd/EL9BwWS/8RYJX38AiAl4yLvUoM90v9+5rhSy4XDsS3D1VW7RMFvuNjXLiHKVifoI71fdKIAkoizX4zmxPOHOW6AaNRDdxWG4DC1lh2psFrvwh8rnPOJK+Hb9evjV2slij0ESDu6MnsS/ODarYvbkIGKMBYbhgFfA/YK7h7mkdXlms0cA21JEM0WTdGYf5M6Rx8IK0nRNguN3vf01Tv5y9CmK+sW5qG5ZiqIDUUiFrW0Ds1pJcNdo7eCfYeRYasnNbizk6KTuQjF0DjSkoDW/lWGGCyoLTA1sWYiQyUKIdNA6/Beg05VvrgBQ1/fQq2AqSrBlxsATBehfM+tm9N8auFePWU2Hiup5wd5p5Fdw5SKZbV+VCUrL+jtF+RTtWLLW3MvsUcqdtyeFE6ff2HQCay3jb+mnihx84c3yXaQUeE2KE6nluB6ZPZrW+nQAp7AqZmimYXoJdSCeuEsbsaErK27Q7VLoOOGAZdvbFhnlVxtj7LwaCH5ip/tDlOIVqq5nshIAzr9TjI9yrDMTo1GRVov7ut53iA2d5oelGKgjp5+M1DRYBBiP3LqQl3m2SdvBvXaX9tXB9XFrHAWEDQg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: keycloak-admin
      namespace: keycloakx
