# kubeaid-sha256: 47a488c8c1b2ac4f072f46ce49a6d2edd09a937059ba9cd111b423646877a41a
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloakx
spec:
  encryptedData:
    KEYCLOAK_PASSWORD: AgA61GoVe0kQCszXk9TyzykftsCDHZsU6c4VDYZsI85Fgams+inuEuNQZTpiH/GviQ3zepTweDz+VwwEn8D1zhRqNWmZzUHIJsAo2r9R6ICr/2pAl9gyI+I4u1jEtg00Tpf+hQL0zK9Pd7lN5lVcvj/hvAw4WwxG8nElv8dV9hKCHiMYKkNMtNQv5LHzzef6jkAOijYeoP/GIMwaF4kQ79XpXwo/4uOoXHyr0lh9Lo5OWWggpwj7cE3fShor0SscJM7hEG9TIXJjvvgF6IjWEGEgGl+NQGCUF8cXs2OIlpTUQbMySeG0wFtgyOzC94hfzTyUvAkJK4oOl/gO+y1WCVLbd9Mc16wanWJ/Cys7x9GlxzxdWbOMKxZB1hl8wyO9fczluD45XkmDslJR767H2fYOusRGTRPjqCVg0coAcSPUVmADzFPWkHXGqO8xt0TJxGtgThkAVUFWI0maFq+xrV7caQYWAt6UEG2Uv60fmCWTYjE6AwkeZg7nvZ4xMEOz9BVu7GLe2OzIhncqRztFXeeLzqAoK+77hnOE9KKHxjRHx8/y2I/LAyRS7dbYXqHHBgO7KBIdvlDmqn5TFKqNY7MdDQHhFTIHJ6Yjoh2rdHlwXyIlSqDfpBRkhPeCbjWh0FAST/hdll7JyaSuvt5Kuq9CSs+EsDlP2+gQd3NjyBwEZWJJANfpd0H/yRBHegdhVXl5tks7/kSn8EEkxx+VuROpWbEaHjYSAKzmP5qe1LMb4g==
    username: AgAQDSOmzG3PtDF/KfE6nkoEpJPhfvo0PC1ldWBcueo5DfwaJHTMB/0oo1x2w2+gyYjHlIVP9JWjTGlnRn0bgB79f1pUAcFx6ln4eMbkQdmdm4lNXprr/TBasugibvB5o0y1nRG1vzyv/JtZOJjCmSkizjjCWtHnchlfDEBrBa4UHHC8G162jWLzJPR9Dhrfg+UvEU3IwiT98h1GlvcE3lMRWa4bcEEJ0aGKrRu7jwjGaEeRQl3oaKTiNpKKdWG8nzdJREk/XaCuhNef0bd/bPqDvpNTiQLax+Kn6Pdwe2DYa5LzDDPabsUY9XW7BPmCsChkiQAO7XyjvUoo2N0CoVHhBrWpTXOlhRqWIlhpx+EpX/f6ggZfWjR5+acy5tdpxm3QZRS5BjBzdnIbrF28yULDthV8gkAoYNVr3u3VCobfvU7wkHRXOjYGBsa+Ge9pTAN19C4t1QdubkrnNGyYYyEemt8z8LkKzHsKXjKuI+Yre1cpmb1nW2PQWWOIhLb4dZF5OtLq9AmTA1gl0+M2vy52iAs4Wu0+b2b1/1pnooQ8wWmV19mQ7W6+X2rRlT+eR+z9/hTsgh3GqNgHY030WwD5LeVaUxvbcpFAfhDZQ/hvqTxXy7AwgvSzN7uPMtxjOTAHwyoYu1Lz5eha4sowynznC6VyXCJfV1G3RVLBGHmo4/iQBB1Mes3HsnTUxulhJItE0oXDfg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: keycloak-admin
      namespace: keycloakx
