# kubeaid-sha256: 319a3097b4676fbc058ce052f62bc0444b468c62de32cd9f0ae4da8c02f0c63b
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloakx
spec:
  encryptedData:
    KEYCLOAK_PASSWORD: AgA8FiRd0xMoGPb9WnNTHoL/ytzk0lM8IvyOHDm1rpE+RWehrnLYro3tNCF8Sw3wHUYNr2CxWRRzZO6ikvU22DvmkASnmMym0YM8fQuZ9AuCzdUZCDSfyLbGyA696jcc2a6/C/SmaXGhpYkDmfbsTsEwIq44YkrbPIkV4r0IdJ1EGsQuOH7eNCZJ6RCckvK7e4IeHTLk4hnj/iWAFU+OJIh55A70qVPV8OOHEgzxIXjTlduXkxk9K3MRpGrhSHVbicCGGwRZ/n0TN/Qm053sZTP8pGJp9m0HGHMA6neyqB5yGvNMqUmQmfKMInh/t/rAeJj+35pPvMRwGi57+IhsBWvWzTFv1cFshqlaE22kW3aLuLliqqW2d3NyBgMo0wYpOzLf7n7jfANRlsjAYN0PN2tVUotvfzjxk8JlE3WPQikJS7CZ7gaIKEGnMUNHoA3rNKtuBMlN8iHktun2FNS33GH0jUIoQ6LP9dqMfB+5rlf43EIJ8xKtQ4ROPuhYPOak7cAyrUXEN3jTBzGPC6/+ytYFCmATdbn71vdJZAcebD2TX8EXVpq5tHAYucetcoZbVy3R968M0jnyc4jdav2o9xL5m5ufBe4q2nQXttTpAFx/1ISjVYYsl++vdE32h/NgnmefSeBB+tIBsyvSo3PfF466eqdjsKiaqC9/aX8cPP4SvT//FsO/oW3snyDUk8IPTw/1AqYmi8mccGfkbhV/n7ovnVJZl/kLbnwNa6b28+qLqA==
    username: AgCWkyO7ess9NDu0sVZKb9X5BJc9IQp43O6SU9hb/9ALyIa5J0TtMQbYMf/18/LNvDM0kHzWBPBgi60ouxbzYVnv3aZvaO4jQ7JXlRmw7LZuM1uPdr0z9spK3lko+/l707TzfSvykdWDOrTuNH+zvp85itQZ6mfwf5z5InirDnC4QIVbMyI8msBU/CgtYMTWWBj3dapvMCLVx+57m8HMiTa5QHwMmb45+Eor7m6T7MEJ7owzrMhDPxXd9ecIVaWqY31q/UCmPuPN8DLkTSl2wwH3q53LsBohU9LMUaw2hr3/UFNwfvXLltHVQO9RN5yYlHZpHMHyzoXkjzFR2EjGh75fh/1nfinTLCnlGv6a1w1KKHsbYXL6ejpJjAiwDuGrSoZLWxA9nB99G8zRVYoh2qXV+H5lne/cYUxnTxBdPXQV7PDJfTFYDzexCShvhFX6YFUH+be9GE8MMPstr3HQCDK7wfSMJ125Qk41f6Kruxl7QJ+3uYaqECk9GI3zgO8iFJ/FLAqTWFlZg1KZREltr8vnKYMgYW79N7MOkYNZxgFpyjX92FWFxokV1np3kodGekz/G6XOkjE+hVJTHxxIlDbymP1nUInKJVOugtuDhns1ILtGfrEkp3JL1rDg0H0R3jVhD9VTU4LTQlfcso+ct9YTKcu+PFI1p+xJICvoD4fcvafrQIcT6m5Hf4soQKGNfTuZuRCjCA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: keycloak-admin
      namespace: keycloakx
