{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "api-tokens",
    "namespace": "obmondo-website",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "api-tokens",
        "namespace": "obmondo-website",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "gitea": "AgBkk5FZ0VkCGKROje7urWlc/lQtJDy9BPn9blHC3v2QR0bY2uCQoO75dTNJBtD4xjEmOSnPo8Jkl1pnycau0AL5wFqxgkpyyykHq3jodwPfj++s+vbKPpIiGOgBJomGYVZ0jPW+fhtu1ci00m0FA+yJCYSZvrNrE51O6K3bfBor7sxUX6JBJPsqUziQV+mqTymH+thwJKl8Lc0jxR9e6BGj7UEq/iuOm0eMLGaO0tyCBc9MZWqRXZs5+7qR0FBBQMK8jWR/w1szlc0dkmqiHqldyYFQao8Tnemd44d1SQ0KbcN5PE5CosGFnYqEgIX2/8FvlG0DpVbXzdzJUmwRpPFPSJL4fYjl/jb5yqqu4jaNXwRqB5SS0nMDyDdwSHAdDxxLm9rjXmkHVPzCEIBafG7hjL10/Cpu08WkG6ffo6aeVnYw+L77IxPiP0Enc3rZFHKtJilOiNAcb1wPMq4S/0SosLWpLWLeBBs1IGXy6z61CKq3LJzN0qLMEn5fc9C4356hoCuaCvC5WXtN0quXzn0t3nCtnY7iJ0KXHP2OzX64tPbBbFFviQnU1qIdwa0TLiYYLZpvkrUBU5fGp4Dxr/iBz8wAFMoMblO1MnebwCbj1EUjTy/FvRLjhszs3JOZQ0syI+1FDUXsKJ/MMJqVjeUwTSprolRgWA2s8zZERzBr92ltXGKgS6o9OdKh1wDffDRm83EbHEXwkqvzz5paro+NbERR+/M/HafaOvN0e4552nIy1KLltuS3"
    }
  }
}
