apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret-token
  namespace: obmondo-website
spec:
  encryptedData:
    aws-secret-key: AgAWfvujk/Y9p+2/UZNp8PpXWdLlzdFuEs5cHf2uxmBVSrjHDSVlNBB1JqDg0/geBHQY5dxCCHg2UVJ3WNkqFE1N/JBZ0JC/5MTlmAN8uvoiyky8LhkFbnlMn4JYUXGQyAG8XAUea2E7qv5zjxQDDKzlCyxNKaFWDgAZRNmVBlj2L8pLDRKaC9X1Lxu1Wh3rOaOvNFA5GtCwfzmroc3LYtDQ1hld9WwJSFMciwutPxynhmnBi+sTl4uK+ko8Tl09eWssD4kdNf2KmTgUw8On2pQ4A4OGLsMowZHYCOhcbh42FvfJ1opEi8ViFePZevlkFoRCbSqc/Vvwi+9oUS4XWQ/fVrvAJTFqmRxqZSiGdH2ud9HKFg/HNdGorm0llKF48NCj0PZehZF7mN8QTeDesh3zLCKYKzVdPwwykkvstc9awVgHZHrX9N/EIVYMtR+oHgwmDhgH46EN59tOb+z6P2AtYyj4MDfbPXFFM5M66Izp7nwMXA71VmAbYRXOcX5PBPI+hDTjv4RMFR7TGIIu7GLH0juImws5l8DmZh/OJgYTuOor9dLvOsdv8lh2zI/c3csYVnhDuUEY4cM32497lOwQtU7YWVSzNdtOaYp+HZm8M8irQeY1OB1gstT3hPVHSVPdvbPwNgIeeAaHe5kp1g0dO5Pih8rS8Cys9n0SlFpF5OFz7CCCGwiK8IJu1j+4I3sTSco6LonZSisngPvPbeHrakalMfCh2KI=
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret-token
      namespace: obmondo-website
