apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgB07xnVKsVVf7Bqz6vchsr8hroURWNnj2I932YUwV+YuOEEIKaFHajUBY7RlOrKaIVDrz65mwj5ssnO6W2QlUMcL9bgpiZ6DrHPyYM+hSE/PL6tFthRJVrKMZFQiDDFdhy3l2PvnMpzmE5hoOn6mlhSuu7jgaz7zZZZ6kdPE5q1bXk/BjKp7fDGJs2oSTTyKcHR8lKjzObk0DUoVx3S5IMbE/mUNA2Y+DcF+/juCdka8CYrRY7BkHWkdMybz8SK+OVPqQJ0DN3MgrNwb1Cn+o1IqrZfK3X5QlZwP2xBn/ZFZI1YquaEcb8DMkO0mds43w5+GtHRbWPX/qz4cjEj8iaD4dXSkj0jmiam0jr/Uk8ocoNrMXTs2KL5zd0e/cjFFrNe3TGWHI3wkdWBL+Q4I50TTyigsbdPEYMSicgrzqD0s2favrN6pWyaIvPeweKzszJmkvYMazLCt5GETtnYMRN5ZuOC0aQPYuRpSsuK7LwMRLMJQaG/D4JxgRPb5z9bhiHgcUX/1FzRmPKXC/pbwdrXmLUsnQ5FjGRWAUd/pagInM5/zmnxnFd61yNUOViIjwGwZ0a9Ygvwi3435HYJKDd26cHLm+HoHo516GAPPuhHKd7Q4jOYC472SgCJJ7S952qEY4NKmUs80tzVoQPD0Gd0sD3wY6on5wgfV629tkvKaHTMMVN+HWlA6AGbvCv+sQ4R6NpJgxaBkG3r6uX8zS8FBoZL4dPj5po9pf4330ANo4vvA8iXhNzI23AlAE0h6MNwMr5IVEClHHvNrlodyyN4D9sS/drp6/66lS6xf6c9P6QJrZqVZ9rm7nO2lVZ6AySmdixJo4d5RzSWntrXdCpOa2becZCzjCvbf/e93S9qKxmcIzFOyHvAKuyAe/COeRYzvRRaHJQ/Nc4ztQeHUCtCaHqpsyjYczbcqKWsb15JgUV2JuRu1bGhFfCh/kSzh7va+6e2Iro3Y0zeVkb6rRsNSA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
