apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgAU+6z6GcbTndtVzQCffduFqeDWfubPEu9JkSWWO5RBP0TyIwMa5Mg/hXhmE6gOySBJt7OO6/9oUdNWKFBcIhm+Z4GmgpF4QSgC5+opj2T/BQsrbOTM7XkZ31QNQN6NtDYVslEtIaZlhGWpHasXkPGB+JCwwOL97dBXuRTv2bXV85PShgMivmK0o2Gkxyl2PRGvIw4fBxAxRqEN3I9mYgwxBkpB0pzH6EoEc1QL3OsLdFek1qJ5QuvhQpwMLu3LLMs5HKM/QXXxsMpPnmpVQtnJ3Sbt5y8H2kVUOpPsp1PJzdkzGHNjC1p6S6BUE9EQ9/gqxdR8fMRSAa0MKmrnAhgsjyT4ZTMMUBNMBYw/qCvkqKIOMflCiRgUOAaAfaSgtcKu2Uzee1logmu48hxeJnhtMKZJnxF04Nb11e7aZz5GAEtbCwNgG4VUhuAu/GwQyeYGNq/kCTV6b8Td2vqY+arPh2xG1MBkJLX5Ac6paDNCPhPzatSV/wwK/kasUYKrZ47bA8Ci2UlqHCqVaSHhdSdq554wvZKeZwZgrK0mg1CjenPAQckI2RKXLPjeMzlSZRBbSclyfMr/sqrTBn6Zp0GnUpa6JSnoto8Pf01TIEFFBWlbDsXG+/jteHcQwt6IC3X/y/DX+YlabcuRFW7PT30DaYzKMGMkPPBVYhH5lgKtMS0ZLGoK4DXHSNTTUQwlnxvrP8JnSp62k6EBRwZelwB1TnSWPcYfFGxsEYVZ6IxvvptCr2ntx99fYH8S3DYWqerr3WuaT6TcgugzVS7gVea+XDyMrQB55xE6kXFHhGL+jdPmzIFyE8/QlTv433dviasDfUJg05RvvEK0BZxtFyNPvAPpuga1zbrhgaH/TvcByshMKKSY1heDNeTq96mH0hno8BEys6iHnPA6wvLw+0/itGgnxHQwCc/54m1uicGhh8zrg4pRkN6s2UY2E9lrmVYUbmlprqzjC5N+FSQbV/+0cA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
