---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: obmondo-gitea-ci
spec:
  encryptedData:
    .dockerconfigjson: AgBJ1fPFOAxXWyWdA8GVjS2E0iZluof5ob7uuMQNm1jEdaRNz4+6LvUcYBvposWFcStYNELkv2HJX1e/Qpi2wTv0OgWPijaRg015jsCptD3vVyDhu4jCTw94+EnNgWkz+T/+2XraJUVUWwjm9I6taakHDH/7YxZP9Jz5iCdMj9zbsh3JKeGf8WMwT/Cq0EINx7dfweK2MMA1INcQn3lZRNPgys/BuqhpqPI5q176ZG1UTpmMIgKmHqvF8BvMmmaIQLle8FFFqEKOmtyNGlrUnYKNoUD0AoF/dhuU1Epyeth/1jFM3U7ylg8IMMB5SG0LKMur35AJe0pVOlbUjZKAyUyDylY389R+aCiypSWLXW3HwQkUx73KWmLBuKQhEwBm57YHDghXOBkzC8xumYRaJ0aUpKphwKglhBJxMT5ZlcEhwK6XsEKeIq0zH7UZCvaQ17wmWDBwe1Rr3YjqHx3hioP3f85QhegC2NUcHmbJoaKWhsAxmg7CNVksKKLi5Rv3ztt628WkHFhnFSG120I89k87IzuDJcYZgkQkOvRda7QJdKmI7BJLkaCWNDeOSLA/6uUjH0gDICMyLFucr2Mfc9rbkE5O7R0RxjmhPwMaS+ZSr0X8k5w56Lq3msHwRvOMF/5EhDsunBBFh4NvAC5GMMPh/BLjkB+s9VjdYnEp8gVNLo3tVJ2rfRp/8vac/Q+RbWiNnaFXeLFNP6u5crQDtklppGqnJfkora2SdJaIY8nkHy/7Hezq03dHCCRZPU+sGjuppiej+TLfCKOh8XEFVambZGpYlBF7qwfvSOpNS4+4p74uDmtXp4IxaT+j51d3BM2zD4ZkUV+KVfeNScxKn0tmoKfLmW0ASrfpQtUPvPLpVHBqrlPdD4TSmzVo2aOSiWQDdvLTduEzo1vpS5FE9oF5f2JDDQiqDLgCzTMtrcjMPji+xULSX6s4lNrGX2jccuEGBYQ=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: obmondo-gitea-ci
    type: kubernetes.io/dockerconfigjson
