apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k8id-web-app-gitlab-registry
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgA1CCU7tS0WGwgLE97j8Gb4M8f4HLRgKBBw4cm9HkKIUiuMjBem9Wq2I8Ln5mqgr1hoICcgkeQHUWIQZJ9lceNu6pr/MW36i35vzB2kFDSI2H/i9CHUqxnpIuDmhquO3gioOL4PPslJY8kUaZ66vfHe7+142dn4zxbyAzB4XWPgwYszjzPPWqgPmauDX0SuztSnQ+TAGuTiEWMAUXWBE0mpmCnKO1TXwyOCfbbiInNTumSmASPn+7z0+dyX9wZ+Bw/3OYWnC7uUj3zWfuAZetkFWyy8Ve9ObUNkCyRvMt8+5/SCSouGPjYQx/cZWfEoZlVVjMNRky6q8BgaIIK1liP9jwOu2cd0OZa/lKKaKmeAf0ZSfTkI8qxXqAmHpFu0zy53lAxYbOQ67hfZdqhwxUMEd8LYhh926QHPqpVsPW/qosLM757LFuUgB+1DfXusrKqcRvYz2h5onHf8BsLdDybSBwtKZdWRAWwdM9u0Gb1apNQSGeninbylWJGZsKhari2ODfds/h4Yu0PIYOvuJmf5PCFYn78CLuXiWAXoHAMqlERdOMkCNZkeZzL5SohrVG7xPYhS9b+QF5eX4z63H0FtrLnjlASThN6yPkQ4tZ3TbV8NU40eT86pzJ1OrJSwksafwKggLcvYCF7ogHTszbrjsTgHjHk+dz+Q0QquA/dUintraXUMOda1gKSdK3OVVJLdFiAk8UV5XbiEXdWe6uhCp79cUNvy8tCMkxDgGAcLKPz+N0STopEZ4sp93ryTD9tFzFaEG8kBE9VkHD43kAOiW7n+RgOSXLji0hGSk+4RhsQhehOtBN6+l6WGz7v2Dpd5wQ+GxtQfBTyTmhIzbBwjP48KPhzDEno/c21vMcuVs6lG+vsVLjhus+fh9pRvQbG6MFvIte0XOW3CuhYj1tXBecuBLphWuYYkAFRh26uTUA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: k8id-web-app-gitlab-registry
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
