apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k8id-web-app-gitlab-registry
  namespace: obmondo-website
spec:
  encryptedData:
    .dockerconfigjson: AgA5iep58Cw7PLXJmMpHP/r61tmmL8cynN8PlFZkjjAMw3Przed3hKp9guUifCzB5YNFAbGMxjMdXSGu4LjkSDX6G10ObKbSiIgVG1ly+xXnjDx2uXTQj2qWQH9tf8QsAODjJJm7IwDcjEukwPww7P3UFHqU/gm3BCyWGbWHsBGtcSjhwc/x7jpnFKwU099mYFPDyXRtMIvhUcaC2R2Q1OGVtLyAeRjW8NI0IyAUfSJgyN2XwHC4nzRbaNx3e0Z3vPwNqSVWZ9UdFN+n4jfNsyPhodFc/3VluMHGNaRL5dNHt0W+KZGLbPC92WwPPKkJzoOcIRYB6oI18Lu2PyGAEkTZYT2sevL8isxhWIF40qgzy2fGi5g2iA76RIDyPyUxWv+DP+pidX0Zbw77OaDzZ2+PEt77/yaQuMhw73B7QkABQ3pCbEy2fcLKxOYr2mtEFj1lOjv/I0b4sirU8QTwJ7JMj5KBErWXImNUV+VAGbG4T9K1G8PyOq1vd1ZtwZPQeFqWn6DWh9KqTvLfUaHL9KUzlzJahrEMXkbwACOPE2Dsi+xllM2j9Ssvmz3fg/+lIBduW/UF1P3e+2geiFAyJ2TjZcL4YA0gYQB3iLMfpilUPrm0fp0zDyZsEV9XNUAUCTGb9/fozWy+jYU/bHULCmWbdkGJJ/IZYEpAIFfyCXxDtWHx/J0NFiLvKgro/2z97A+izF01Z1+QoZhwDFhFj05Mn9dWIPOdnRjoF4o9r8zwVXMxU6Zl8OBjKcJ4VmuJZyMZabauxQadOJfSYABmYcXSzjU9tNoveeDe99wPg7FlODbeDREfCWcMnVgf+UB+rj/FOJW6UythYaAYjDLbfMTrdCEc+DsWkPVfZCDD0Ao1fiVX2gUy4Nxq6C/NGORINm1jZ25u5WgN0XfoTMaHkwWWlAVpOHTGIcCzH2YaZwh03A==
  template:
    metadata:
      creationTimestamp: null
      name: k8id-web-app-gitlab-registry
      namespace: obmondo-website
    type: kubernetes.io/dockerconfigjson
