apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ssh-private-key
  namespace: obmondo-website
spec:
  encryptedData:
    ssh-private-key: AgAYt1KKyQRa5f/Ae5RG1nHr+RWBXvLS+0l1+bJRiNim5K4qtQBEa/84h0UBgfu8y4lHtmjQEYIB8qRrutEgEeiD91ARqwIrJZYFEfdNDW9TgU1uHlnB2xOctOMfgkCZQQhS/HW8BSSwsbXeGbrp5AIgU1hlcZp7joGoamKMrFAlTgVTaLTqdtfm8fLLspDz5fN3rDpAblZMf64qKkEea8WFutRAfTxgi5CM3S/Kmrd61/23vNYy77gbYzcofZgq+ws3WZTibGZaqQ6tPz13vqe3MHpD4m42OKWalGEBlNCcPXhm8gAJahb6SfQjbZX7U+PrBwgC8NMXB40HtbCoCeIUcSX8lsuTVObVjm3XlhY+S7XjFOoCt6X8zb/0nd6DMEFQMkqTD91REULJzHf1nkRnEAGDnRfCw/JCQ+sMEE37KolFOso7eLIUHagXv4ojNtODGbwwLj4MxrPFSeVOfPcGQ06wf/5x+gwxAchCHXdgnR9ZCCz0agnQ8+BL/WRipkwVXDCppa1kAeN6FpvJc/thhovKVGlBeIZHAC1usRIzDfm083eECiwR0kiSVBoFjfhpD8f4RBF+kiHW5L0WZJi39Xp3A4qLPho/ZPpxb5g+z8/CqtufJlpbcMUOSH5R05uMeV+O9mYN93v0gCpIkdJ+RnhkH3X8xh2GM2CrJmdY/T12XteIt5WdslGvT7przGm9QUaFu4+dfWFXY6YgkJjooaZLPqw1lR4Ws+bHHMVnMuspq+ZYtNHUsQDEcDc+kR91Z4sp2C+3PU1WG3BsNeCs3ye36GJijjZqj0Gd6O/SAC9VClooMk+qy9R4dF15BXK/OJxp0KK2ADZ3jnw0WMU1eXZa5CfHNL1GDbEEMlkD0tY44oORyuAootVUigd8Wmql74gJ0grExqKO8lzFVvm/IKWL7+YakN7Q9QRgteVxUOSWtkMYfYdseH+syQPeXxKlz3lctKGNtXq3HuDgkY3r/0S09oAczOpjOVsLpG9CemM9l99H27cM4cLhji3vFFF94MRkjZQO+8q1yE4znpclCjZt0r61pq+v3i4lQQm0wvcXb5SoHEFkb0LVH1aYxuDuhViFgUQeFG4brqNQeQp2eRPwhrDDQhHu8Xl2fZGpEPy+oas3leUesAU4ghwWIj6ZUsM1mOI4raH3XJMMoBSjMIL/Bi0iZKLo+1CTRcdUiTjAVC1RN5EyMPv8gcfd/Gz520V9mTTfbsmROg18pFqG4uVv1lNqai9VukU=
  template:
    metadata:
      creationTimestamp: null
      name: ssh-private-key
      namespace: obmondo-website

