apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: totp-enableit-api
  namespace: obmondo-website
spec:
  encryptedData:
    k8id: AgACZPfMLBYoQOVvlBOtqGcMGw2LSN0zV/NpVa45GPoDFV3VKYSPFZ/1BaExpZh7JXyA4IVcFHFn5kFGR5BXa44NSMfy47A6g+BWNnmM3qjwEIo9AfMRmeKy0e+yjuSr+cdh8N/ZvUz5KunjNAYiXnPWAtqs9yF1RX9ev/DSViCBfa9l64XgUDsdyTiOBp9BX8/c9h/V0a6LzCMEYEJJ99/xo6SyEJcHQruwojq+pXAdrrWEeqm9zDvuxTYqPi5mHqwLDMARd3kUveQ5W7brLu0/YpZgBtbf6qB4Cs0O+Ao2pelBK0WfD/FV/P9nsfIorAjO+8CaiNySnqTGCsOyNGq9PrgTKJp2MPN9CiGZSIcVG/qF4LjH8yTJSXxoiR+D+YYQlWh1x270wCP64GOltqvMpfU8xuhIyBxXf2gPhnKyTSa3/M+OVmE4cV1RbYy4Ig/0ejgdA0OgX+8BwXzdozATH7At3iWEq0Y9BH3u3BLTUCKghWHUJKHQaXRl4LDw2EOkzbY0KOH6KGW4CAZgYatvD4WkUMidVL0dtXJ4+9OLoSl2R2YH7zAXXRz7ePImPqk48JaFhn7B/7o4Yf40SgYIXW/vATYIwXaNvXLnShvb7WoT2xFAIseimYvKw9qjoENlJfZO3J4SfVWzD8rVurv+zqjtX53SrhYB5r3bCJdFm2lpk7PXUaBp5+/0J4LOYKpiVPwHQAUB6LyrhkAQIZujcyz86G9SfY2RZxV5mBMZx5mPpk8JFQaa
    obmondo: AgA8Zcxp2M/zqdYrlnFMQ+AM8YyuUarVYC1jJZBkXIffnjkFl5w45CPkbcDuyBFP1FaSzaWVKwwwUAfFZ2bVEhwnrzRSjOy5YI78wfs/NZ+1ASTCdrK+Ox3KW7IOsHbgqAAsgb3AbxQL+RJyMtCHrhzWEll4nonwgR6aSIgft0nZyDO9OfVdEMWjn5RevpNIvmS24gLD7tJs9TcBWB10GHjzXIYBhutE1BYKn491M8cdVJcJM270GiU6yCsuJPFXtXSiColV8Rjp/XpyDhAwxtk+u5YjhI36xFUMfQ6/k5ZgvTgjWf2DvIjr9+kxRNb9EDW67Wms/BYMUuAzqJtRXLAmm6mnuC9KWN9xf/YH+HqXmBMj0RmF16ueXA5dAgN0xDrFXzy3KGQRNZDnMR3M5MQ1u9Yz1shTJdrQhHwkCi/DfWK/PkrwMTx5QXkLaaPlDtXhQW655kxrH+gUtuZPZw1Ha3aigbb7zT7CgBHOkES8u8537jaiHAruiFkCQ+ifc7qnHQatXxu/y7c4uifmO6k4fAGDqcV8i5RztOIlVSZjLWOZmeqwJjV5MfLAnmaC0mZPPd1I7/TG4KScIaYiWBK62NsA+aTTnF53GWX6mx6etKJzr3x8Z40E4gBbmMbAELVeefU0E80jishyLeGcOB6GOmf8BewhxkUmezCyi5D9U4AwJgVNIz1i1Gpz9owROHIqbwJz8K1jlHHvl6XrCfKQzTEaUeaiawdm97Mu0TPTT4pCNHFZwZe9
  template:
    metadata:
      creationTimestamp: null
      name: totp-enableit-api
      namespace: obmondo-website
