minio:
  mode: standalone
  buckets:
    - name: mattermost-kbm
      policy: none
      purge: false
      veersioning: false
  storageClass: "rook-ceph-block"
  volumeName: ""
  accessMode: ReadWriteOnce
  persistence:
    enabled: true
    size: 100Gi
  ingress:
    enabled: true
    ingressClassName: traefik-cert-manager
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
    path: /
    hosts:
      - bucket.obmondo.com
    tls:
      - secretName: bucket.obmondo.com
        hosts:
          - bucket.obmondo.com
  users:
    - accessKey: mattermost
      existingSecret: users
      existingSecretKey: mattermost
      policy: readwrite
    - accessKey: admin
      existingSecret: users
      existingSecretKey: admin
      policy: readwrite
