replicaCount: 1
image:
  tag: v0.1.1
  pullPolicy: Always
ingress:
  hosts:
    - host: k8id.io
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.k8id.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: k8id-io-tls
      hosts:
        - k8id.io
        - www.k8id.io
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
