---
keycloak:
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: 'true'
    - name: KEYCLOAK_USER
      value: "admin"
  extraEnvFrom: |
    - secretRef:
        name: keycloak-admin
  dbchecker:
    enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
    rules:
      - host: keycloakx.kam.obmondo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: keycloakx-kam-ssl
        hosts:
          - keycloakx.kam.obmondo.com
