replicaCount: 1
image:
  tag: enableit-v4.4.0
  pullPolicy: Always
ingress:
  hosts:
    - host: enableit.dk
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.enableit.dk
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: enableit-dk-tls
      hosts:
        - enableit.dk
        - www.enableit.dk
