replicaCount: 1
image:
  tag: v1.0.0
  pullPolicy: Always
ingress:
  hosts:
    - host: obmondo.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: obmondo-com-tls
      hosts:
        - obmondo.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: traefik-tls-client-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: obmondo-website-cn-header-enableit-api@kubernetescrd
