replicaCount: 1
image:
  tag: latest
  pullPolicy: Always
ingress:
  hosts:
    - host: beta.obmondo.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: beta-obmondo-com-tls
      hosts:
        - beta.obmondo.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: traefik-tls-client-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: obmondo-website-cn-header-enableit-api@kubernetescrd
