gitlab-runner:
  replicas: 6
  gitlabUrl: https://gitlab.enableit.dk/
  envVars:
    name: RUNNER_TAG_LIST
    value: kam.obmondo.com, kam

runner:
  nameSpace:
    create: true
    name: obmondo-ci
  serviceAccount:
    create: true
    name: obmondo-gitlab-ci
