issuer:
  enabled: true
  issuerEmail: klavs@obmondo.com  # this is required
  production: true
  secret: kam-letsencrypt-key
  solvers:
    - type: http
      http01:
        ingress:
          ingressClassName: traefik-cert-manager
    - type: dns
      cloudProvider: cloudflare
      cloudProviderSecretRef:
        name: cloudflare-api-token-secret
        key: api-token
      dnsNames:
        - obmondo.com

cert-manager:
  prometheus:
    enabled: true
