channels:
  award: "artoo-test"
  standup: "artoo-test"
  management: "artoo-test"
  review: "artoo-test"
  internalAlert: "artoo-test"

backfill:
  from: "2025-01-01"

image:
  tag: "v0.2.2"

pem:
  enabled: true

imagePullSecrets:
  - name: harbor-registry-secret

extraEnvFrom:
  - secretRef:
      name: artoo-tokens
