imagePullSecrets:
  - name: mattermost-obmondo-registry-secret

initContainerCmd: "chown -R 1000:1000 /home/exporter"

env:
  - name: MATTERMOST_TEAM
    value: "obmondo"
  - name: MATTERMOST_TOKEN
    valueFrom:
      secretKeyRef:
        name: mattermost-stats-exporter
        key: bot-token
  - name: MATTERMOST_SERVER
    value: "https://chat.obmondo.com"

serviceMonitor:
  enabled: true
