backup:
  enabled: true
  image: ghcr.io/obmondo/backup-sealed-secrets-keys@sha256:6cc8952dbaaf4d29f60b6e5ab3f61d6dabeadcfd79cc72ca8620047857133bfd
  provider: aws
  s3Bucket: kam-sealed-secrets-backups
  s3Endpoint: https://s3.obmondo.com
  s3Secret: backup-sealed-secrets-s3-credentials
