relate:
  image:
    registry: registry.obmondo.com
    repository: obmondo/dockerfiles/upstream-relate
    tag: latest
    pullPolicy: Always
    pullSecret: gitlab.dk-dockerfiles-pullsecrets

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 100Mi

  ## Environment variables - db user+pass loaded from secret
  environment:
    - name: SMTPHOST
      value: 'mail.system'
    - name: SMTPPORT
      value: '587'
    - name: DBHOST
      value: 'obmondo-postgresql'
    - name: DBUSER
      valueFrom:
        secretKeyRef:
          name: relate-admin.obmondo-postgresql.credentials.postgresql.acid.zalan.do
          key: username
    - name: DBPASS
      valueFrom:
        secretKeyRef:
          name: relate-admin.obmondo-postgresql.credentials.postgresql.acid.zalan.do
          key: password

  ingress:
    enabled: true
    hostname: relate.kam.obmondo.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
    tls: true
    extraHosts:
      - name: relate.obmondo.com
        path: /

