image:
  repository: harbor.obmondo.com/obmondo/gitea-stats-exporter
  pullPolicy: Always

ingress:
  hosts:
    - host: gitea-stats.kam.obmondo.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gitea-stats0-kam-tls
      hosts:
        - gitea-stats.kam.obmondo.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
    traefik.ingress.kubernetes.io/router.middlewares: gitea-stas-exporter-redirect@kubernetescrd
