---
namespace: obmondo-website
trustedProxies:
  - 10.96.0.0/12
admins:
  - "klavs@obmondo.com"
  - "ashish@obmondo.com"
  - "klavs@obmondo.com"
  - "ashish@obmondo.com"
  - "aman@obmondo.com"
  - "emilhp@obmondo.com"
  - "deepak@obmondo.com"
  - "ketan@obmondo.com"
  - "faizan@obmondo.com"
  - "divyam@obmondo.com"
  - "suwarna@obmondo.com"
  - "rehan@obmondo.com"
  - "basit@obmondo.com"
  - "rishikesh@obmondo.com"
  - "soham@obmondo.com"
  - "mohammedyasin@obmondo.com"
  - "hritik@obmondo.com"
  - "victorine@obmondo.com"
  - "sanskar@obmondo.com"
  - "olayinka@obmondo.com"
  - "shubham@obmondo.com"
  - "anantharam@obmondo.com"
masters:
  - "klavs@obmondo.com"
  - "ashish@obmondo.com"
# Need to add service and pod CIDR here
internalIpRanges:
  - "135.181.21.167"
  - "135.181.21.154"
  - "135.181.21.153"
  - "135.181.223.235"
  - "65.21.130.86"
  - "65.21.130.85"
  - "78.46.72.21"
  - "176.9.124.207"
  - "85.10.211.48"
trustedProxies:
  - 192.168.0.0./16 # Verify
image:
  pullPolicy: Always
api:
  website: https://api.kam.obmondo.com
  domain: api.kam.obmondo.com
  puppetdb:
    url: 'http://puppet.enableit.dk:58080'
  puppetserver:
    url: 'http://puppet:8140'
  mattermost:
    channel: enableit
  chat:
    teamid: iu94xkqsgjgj5ne4eeie1harcr
    userid: dpg87od6hpy5zpnhjw99qhbw3r
persistence:
  enabled: true
ci:
  enabled: true

pgdump:
  enabled: false

ingress:
  hosts:
    - host: api.kam.obmondo.com
      paths:
        - path: /api/ping
          pathType: Prefix
          servicePort: 8080
        - path: /api/notify
          pathType: Prefix
          servicePort: 8080
        - path: /api/window
          pathType: Prefix
          servicePort: 8080
        - path: /api/tag
          pathType: Prefix
          servicePort: 8080
        - path: /api/user-location
          pathType: Prefix
          servicePort: 8080
        - path: /swagger/go
          pathType: Prefix
          servicePort: 8080
        - path: /api/timereg
          pathType: Prefix
          servicePort: 8080
        - path: /api/report/error
          pathType: Prefix
          servicePort: 8080
        - path: /api/invoice/
          pathType: Prefix
          servicePort: 8080
        - path: /Webtee
          pathType: Prefix
          servicePort: 8100
        - path: /
          pathType: ImplementationSpecific
          servicePort: 8088
  tls:
    - secretName: api-obmondo-com-tls
      hosts:
        - api.kam.obmondo.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik-cert-manager
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.options: traefik-api-puppet-agent-tls-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: obmondo-website-cn-header-enableit-api@kubernetescrd

postgresql:
  instances: 2

serviceMonitor:
  enabled: true
