mattermost-team-edition:
  persistence:
    data:
      size: 15Gi
  image:
    repository: mattermost/mattermost-team-edition
    tag: 10.3.1@sha256:5892ec2bdb79d74adafd2ef689ac4ea585370646a8028cc6da249ed2715ae6fa
  ingress:
    enabled: true
    path: /
    hosts:
      - chat.obmondo.com
    tls:
      - secretName: chat.obmondo.com
        hosts:
          - chat.obmondo.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
  extraPorts:
    - name: matternelle
      port: 8989
      protocol: TCP
  config:
    MM_GITLABSETTINGS_USERAPIENDPOINT: "https://keycloak.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/userinfo"
    MM_GITLABSETTINGS_AUTHENDPOINT: "https://keycloak.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/auth"
    MM_GITLABSETTINGS_TOKENENDPOINT: "https://keycloak.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/token"
    MM_TEAMSETTINGS_RESTRICTCREATIONTODOMAINS: "enableit.dk,obmondo.com,blackwoodseven.com,vsen.dk,gnhearing.com,gn.com,gnresound.com,jabra.com,ks.kk.dk,kk.dk,ebillet.dk,kilroy.net,hobbii.dk,mindcore.dk,hbkworld.com,churchdesk.com,sdfi.dk,pm.me,cybernordic.dk,opus.com,opusaris.com,rybner.dk,image2work.com,grandpedersen.dk,gmail.com,kds.dk"
    MM_TEAMSETTINGS_MAXUSERSPERTEAM: "500"
    MM_EMAILSETTINGS_SENDPUSHNOTIFICATIONS: "true"
    MM_EMAILSETTINGS_PUSHNOTIFICATIONSERVER: "https://push-test.mattermost.com"
    MM_SERVICESETTINGS_SITEURL: "https://chat.obmondo.com"
    MM_SERVICESETTINGS_COLLAPSEDTHREADS: "default_on"
    MM_SERVICESETTINGS_THREADAUTOFOLLOW: "true"
    MM_SERVICESETTINGS_ENABLELINKPREVIEWS: "true"
    MM_SERVICESETTINGS_RESTRICTLINKPREVIEWS: "github.com, gitea.obmondo.com"
    MM_PLUGINSETTINGS_ENABLE: "true"
    MM_PLUGINSETTINGS_PLUGINS: |-
      {
        "mattermost-autolink": {
          "EnableAdminCommand": true,
          "EnableOnUpdate": true,
          "Links": [
            {
              "ProcessBotPosts": true,
              "DisableNonWordPrefix": false,
              "DisableNonWordSuffix": false,
              "Disabled": false,
              "Name": "GN_SNOW",
              "Pattern": "(?P<ticket_id>TCK[0-9]{7})",
              "Scope": null,
              "Template": "[GNSNOW${ticket_id}](https://gnsn.service-now.com/text_search_exact_match.do?sysparm_search=${ticket_id})",
              "WordMatch": false
            },
            {
              "ProcessBotPosts": true,
              "DisableNonWordPrefix": true,
              "DisableNonWordSuffix": false,
              "Disabled": false,
              "Name": "operations",
              "Pattern": "\\B@operations?\\b",
              "Scope": null,
              "Template": "@deepak @basit @hritik @sidharth @divyam @smahar @kanha @franco-david @sanskar @vitamax @md-asif @yulian @nitish0 @olayinka @tomas",
              "WordMatch": false
            },
            {
              "ProcessBotPosts": true,
              "DisableNonWordPrefix": true,
              "DisableNonWordSuffix": false,
              "Disabled": false,
              "Name": "features",
              "Pattern": "\\B@features?\\b",
              "Scope": null,
              "Template": "@aman @anantharam @sanskar @archisman @faizan @kanha",
              "WordMatch": false
            },
            {
              "ProcessBotPosts": true,
              "DisableNonWordPrefix": true,
              "DisableNonWordSuffix": false,
              "Disabled": false,
              "Name": "product",
              "Pattern": "\\B@products?\\b",
              "Scope": null,
              "Template": "@amal @basit @emil @mayank @rishikesh @suwarna @rehan @sgupta",
              "WordMatch": false
            },
            {
              "ProcessBotPosts": true,
              "DisableNonWordPrefix": true,
              "DisableNonWordSuffix": false,
              "Disabled": false,
              "Name": "business",
              "Pattern": "\\B@business\\b",
              "Scope": null,
              "Template": "@bhavishya @esther @vitamax @olayinka @timothy @victorine",
              "WordMatch": false
            },
            {
              "ProcessBotPosts": true,
              "DisableNonWordPrefix": true,
              "DisableNonWordSuffix": false,
              "Disabled": false,
              "Name": "sales",
              "Pattern": "\\B@sales?\\b",
              "Scope": null,
              "Template": "@sankhadeep @divya",
              "WordMatch": false
            },
            {
              "ProcessBotPosts": true,
              "DisableNonWordPrefix": false,
              "DisableNonWordSuffix": false,
              "Disabled": false,
              "Name": "support",
              "Pattern": "https://gitea.obmondo.com/EnableIT/(?P<repo>.+)/issues/(?P<id>[0-9].+)",
              "Scope": null,
              "Template": "[${repo}#${id}](https://gitea.obmondo.com/EnableIT/${repo}/issues/${id})",
              "WordMatch": false
            }
          ],
          "PluginAdmins": "ajaiswal,klavsklavsen"
        }
      }

    MM_PLUGINSETTINGS_PLUGINSTATES: |-
      {
        "com.github.matterpoll.matterpoll": {
          "Enable":true
        },
        "com.github.moussetc.mattermost.plugin.giphy": {
          "Enable":true
        },
        "com.mattermost.apps": {
          "Enable":true
        },
        "mattermost-autolink": {
          "Enable":true
        },
        "memes": {
          "Enable":true
        },
        "com.gitlab.itk.fr.matternelle":{
          "Enable":true
        }
      }

matternelle:
  domain: webchat.obmondo.com

postgres:
  size: 15Gi
  instance: 2
  storageClass: zfs-localpv
  logicalbackup:
    enabled: true
    s3bucket: "kam-postgres-backups"
    provider: "s3"
    s3endpoint: "https://s3.obmondo.com"
    retension: "30"
