imagePullSecrets:
  - name: errbot-gitlab-registry

initContainerCmd: "chown -R 1000:1000 /home/errbot/data"

image:
  repository: harbor.obmondo.com/obmondo/errbot
  pullPolicy: Always
  tag: "v6.1.50"

additionalLabels:
  k8id.io/permissions: "allow-prometheus"

env:
  - name: BOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: errbot-mattermost-secrets
        key: bot-token
  - name: BOT_SERVER
    value: "chat.obmondo.com"
  - name: BOT_PORT
    value: "443"
  - name: BOT_SCHEME
    value: "https"
  - name: BOT_TEAM
    value: "Obmondo"
    # only bot admins are allowed to change bot configuration
  - name: BOT_ADMINS
    value: "@klavs,@ajaiswal,@aman0,@megh,@faizan,@hritik,@bhavishya"
