imagePullSecrets:
  - name: harbor-registry-secret

initContainerCmd: "chown -R 1000:1000 /home/errbot/data"

image:
  tag: "v6.3.21.1"

additionalLabels:
  kubeaid.io/permissions: "allow-prometheus"

env:
  - name: GITEA_TOKEN
    valueFrom:
      secretKeyRef:
        name: errbot-gitea-token
        key: token
  - name: BOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: errbot-mattermost-secrets
        key: bot-token
  - name: AI_SERVICES
    valueFrom:
      secretKeyRef:
        name: errbot-relate-token
        key: AI-Services
  - name: ISMS
    valueFrom:
      secretKeyRef:
        name: errbot-relate-token
        key: ISMS
  - name: DATA_PRIVACY
    valueFrom:
      secretKeyRef:
        name: errbot-relate-token
        key: data-privacy
  - name: INFORMATION_SECURITY
    valueFrom:
      secretKeyRef:
        name: errbot-relate-token
        key: information-security
  - name: QUALITY_MINDSET
    valueFrom:
      secretKeyRef:
        name: errbot-relate-token
        key: quality-mindset
  - name: TLS_CERT
    valueFrom:
      secretKeyRef:
        name: errbot-puppet-cert
        key: tls.crt
  - name: TLS_KEY
    valueFrom:
      secretKeyRef:
        name: errbot-puppet-cert
        key: tls.key

  - name: BOT_SERVER
    value: "chat.obmondo.com"
  - name: BOT_PORT
    value: "443"
  - name: BOT_SCHEME
    value: "https"
  - name: BOT_TEAM
    value: "Obmondo"
    # only bot admins are allowed to change bot configuration
  - name: BOT_ADMINS
    value: "@klavs,@ajaiswal,@aman0,@ketan"

serviceMonitor:
  enabled: true
