mail:
    config:
        general:
            TZ: 'Europe/Copenhagen'
            RELAYHOST: 'kolab.enableit.dk'
            ALLOWED_SENDER_DOMAINS: 'obmondo.com enableit.dk'
            LOG_FORMAT: 'plain'  # Change to JSON to get json log output
