backup:
  image: ghcr.io/obmondo/backup-sealed-secrets-keys@sha256:6cc8952dbaaf4d29f60b6e5ab3f61d6dabeadcfd79cc72ca8620047857133bfd
  backupBucket: kam-sealed-secrets-backups
  s3endpoint: https://s3.obmondo.com
  access_key_id: ops+kam+sealedsecret-backup
  access_secret: backup-sealed-secrets-pod-env
