---
teleport-cluster:
  clusterName: teleport.obmondo.com
  acme: false
  acmeEmail: "ops@enableit.dk"
  proxyListenerMode: "multiplex"
  authentication:
    secondFactor: "on"
  persistence:
    volumeSize: 40Gi
  highAvailability:
    certManager:
      enabled: true
      issuerName: letsencrypt
      issuerKind: ClusterIssuer
      addCommonName: false
