# kubeaid-sha256: 6bc983cb153087580784cda62632c3065f00ea986ca97f305ac5b8cb57484fda
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCSLiQupe7Dyn/mShQ1F9D0ekYRvAnIfBAvqxv6eG9Hv1UrsTrX/ISdd9tAnr9t0/FUuXpFElLwDcODOx+UpSEyvW7FaeEBnvKeovV4nVogWKLBPxjnlpxciBz8KWpYU9EejHNKuiY9aRu9mazNqSY5dZAwc2Oyz9VPUZXSHij8YeS11t6Q7iQ9CyeA5/9dESwd8ZjJJWpRnxM2344dAKMfsN5V1NWdnZnoRxpF4appPkIlhNA9DtoMiOZPQpDRJMIrBvAi+xU0LitkkIaFJaHvxi785AU01khwrDoS9FYqDwkySf/vzEWKy/hSJgwpNg/Cs77r+lgX2/nttmEOzSEcEZAYm5e17pPeuZfu2TNrnd0p/gb+uKneJ3A2VVNSl792CMOmtivJW8WbC12bK8x31EsZfO+4pBo+SmDiABdcsIgzdViJOL+KqhJPhtS4HmlFVzRZ4QT4W5vOYyAV1u+yctFOjFM5cQwmnHPrc+0127LSx8pXU9MUNlWM6PJOINkOIiCycI+90MO51kXt8uKxgP0TKh70MzA03K8/ETN5UQEpZXYhrJF9cCitaGogk0HfvkfMvD8MFGBVqxUzTbr3Qpfx/He7HxWbiEvi+cv3mzXlmggTQBeNmzvCoJTECEUsurVcBJNnOLjBPDNDfmntcqLdH95mN9BFKJ6iwpezSWwr0b7773BRgL7J1ZirKIKSAyiv3uiq6XuZWPsmZ482uABxXrDsx5MK/qM1XEUPl5jER+diVmUOzel6lorquB7no64eQgh040hmrWf0cqh4
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: cloud-credentials
      namespace: capi-cluster
