# kubeaid-sha256: 03c34af4b3e0d2ddaca636b41612d8c13fbdbf39c1c5f81ec9919c1cdb27b457
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAHXqNkDwkKBhTMz/qqQcRSWsMMUvvJQN56K+BssuG3XfgETcyXgp32oeqJpmxe65EXNTpe/p0KwfZflYK8tm7LcBF6q193oQWQRuhptfdB1AuNbD3EbEn/3+/QmFPuXHbbF4unWrBoCz4S6RZ64X/We+xinAQI1ijgWfxkwVghmc8mVs4qspuDa5LBbRn5VJ+TYdBiCPSsRK5eI7MiKowQyz9bTNd5/dRW8dB6JtyTi+QdLnjZ6MacZPv0/s2oL9G33QQspojdvx098Jd5nTN2vDxFeLEPT6jfIK0puXG+kjqRSZ662GXDoacKqS19P9xISCp/aI47rOGzMtQI1MJPyAX7CF8BlVC0pN1gko3DpJPXDfsmfFkcF2WxkgvhpLJMkh3NgYsmxFz30MxmahDLaejRPTEQW0Wpp0aLUp4PXZ0LnKYv2Fd0M6tbBSdVbvAqsbZGHK/nGP8rOGJGPwTLQL+k+LkloH9t3bYfEkM0tBdZxlpH5c1J3r6mQQ3jp0C4LOGkpBPNR/YynHSkoOV207pIORPsazS970Y8mei31nntkxy7lAi9KdEyT6CwKJjfbKHTrgEEdg7L3PHhppd5X5TGkJzWMKEdHnpqGqX0+kPr8nI44miEDq8wvc0Tx+/vmmgx2J9ejRm7ls+DHebaVEk+ynCeS8/Zi9SXefOgY6Tm3auw/LNAPXi2pSOtbww0H/vUOAGV4WzEjhbiHgsjc67Sz+kRCAiKef63eImANxYhdDt7BunKq2fq5BqL3nj1V9QrVMs2fapToLha7fhI
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: cloud-credentials
      namespace: capi-cluster
