# kubeaid-sha256: 53460eee7fa88b7bb576d0b9b2f4980fc414c1f15e0f478566affc278169a799
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgChOCflkHh9JzOAxu3uc37VVRlSSqP1jE9w+wFGJ01RHkMdoU7CnX3Ty8/0cH+LSkJFd3B02IPSEkB8nQEl0KuBj6EoJ+5PPun7IUpUk/r8azFmUW18pnD3QXBmAUO1qNHPwNtaFuZXEfSAIkrcmtoluBgw5YeyJ4OgEMRoQVxGMr4ty7DQBQ/Zk3Y0oMYyA92FfAbiZB/Ts7NavyHnQiZrqDdDysWUk4vhO8c6eE1tGdwHPPChoIi8Njh5n3qn9zF9FcotkdImvkwsC/7fNHvdUwcGiLlcKAL+CU8dtsb126hg4IjBh95mKY8SUM+Ot8GXsVLszXw8Z7svslsmmImcIsJr+QjijIBPBgrtPS5eQthey594wiSd9IGywhPpVqj9heA2tfaDdPXzsUyCgUx3brPxzB4O+PG0QPyV015XxU2+ukY8NfA6DosUlb73ERmrX8PCP+NXcXy2USARuTB8zBul60iSJiBTt2IjQrMxb8d5I95rjSbE2ktaB/MeqtZVPaXiR+Kg/2U7GSAXy03KCGBzGRECwxd0oTr5ZH98hD4dBGkmgUzwX1G9yCHIShfI/K4AdOdg0I4sCoD4is8LpsdiSWvF4F5xmGEZ5vdPlmI0XFA1beza4DfAudI/hKSGDqwzU/N5LdXqy/Ejr5h1E+jAADGcHc8MSj96MjSI+cvlJZqvX+sd11KFD0Y7pw/+e4VN0AZE7mHzt66SWOlKMyHntj6l8CYMPgG98awFLfeT/pnZxe9oO+sru3HqFbIbJehzwXdpgHPKCdsg4Xyv
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: cloud-credentials
      namespace: capi-cluster
