apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obmondo-k8s-agent-gitlab.enableit.dk-registry
  namespace: obmondo
spec:
  encryptedData:
    .dockerconfigjson: AgB4d45xGMOg2OFmBa7UKaA9IcxI1T/sESDZr5KqtgDp7EIpxdmOxfEk94tO5qlGY3XkhNTpxjxHGAxhcXK6y5ZxjTO1WSNod7//6moBRZPgPvubxM06DPYd2q8nGRBys6PwfTZnC93Zn+1NbR1rQatq/Bhy13TMgHFpn+DlXer43Vru3cPZcAZAIOzyorbXzJ5gOaKzglUq4EVXOwTHLSLV4q0J9ohw6A72nRJG7HiD3ZAc0piwZRrA46b7W64AvNFN7NXsgV4vNIz9wfEMHWCbWN/3VCPDXW1q2948itRple3gSXsnZ7Zit3z0VDHLQXCqCD2ALcD+HVZmfql00HbNhpWwCpr+LXtSIku6liCeESRmYiO0N6EtofALV2b0AG13Lhnz+VbMcY3U+G4mCT9dAu+nJfXo3HbpFmqRnvxg3osQlpdL2ABMk+ia5uNDZfHKsjTgaIIBboQNQnH1Nkj7ixjYtEVdOxaE9j+nVBQJOFzbCRDU0Vo5BI9Io5bUs7wHF5tUouYIm6KE8gS0ZpQcIQdyPMc8p2xRYk6WqWGQKhqFCDrzOTpy9f89c8qEpd+8ndtbDpvTJfyirr+8+bb6lmJrGPPpoFmR2V9EaeIudZsNOYp/BJBS4AWESw9sOH+rDQ1OLMsWKmQ1KEoCGU+K/vsMhDm5aeJWnHIQUZjo6atkZ5OhfUTyHAvGbazksJ8ro2kUbZ/tqe/P1QTrf4DRj3/9aFy0CXtjvCfDJQTBk4VDbgTVWJ0S24bLD8RRh3GgqVAk2GEFcHFsROykJuE6tlkZx/A3imyvH72Sz8kHlHJWmES7s14DKnODQTba7KDn8fO/chd0nh5KOR5nv7pjrmi3PP3n3hEO4s5zvKPp5H3nJREzehEOZafHcroooNFK2CTd988=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: obmondo-k8s-agent-gitlab.enableit.dk-registry
      namespace: obmondo
    type: kubernetes.io/dockerconfigjson
