apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgCyi7RsUXKu9g5VQGmAeHzEHqwG0lGmRfp0sRHZOxwsfJBqgZZ36Bz3xix8cnKWC+l3ZDrvLrXJMWvLc5o2xff+cQa1In3FY1DnJ1gS+IRt5KudpwgHY/BfmaPHS2gDnLpnFVB+CNjlFjmcLIgBETNQ787SD9oSEcDa5jHxzxLYXRYvC27hFTq2KdOrzDAMeXjSLCfV5LW7LQsMrhvbblMT/EeVN7PpTxvtwpra3XbjjGrRhAjzGtdSTS2fARB5GGW0gVasMUBZVb3Mt2th6NmScmGOW+kr0KmVJH0A8joubksJQFPhtV04TYwphkWSjOFQmCFdrb9IP+EhFbcNKDLM601NXphFKPFzAysKI1kr5FdP76e13zpqbUQVVryXxiJtyjdUGzWEfyuaWVNlvNsKPZrH9DZU71Q3hL7n5dHKxl4X9p3fgvKhT6ykLnLGaI/k2FsdEFBd/HjqhTyFydT60iJ4YV1mWulss2XZbJqgqazF29LBhTyvrxdO3YpwWVKP9cBi/MzIS2JwCczOngaGlIIOmxbJ6rzz/kBenAeqU6yZKlAoue4NQ5e14zlv8BXKUx6ghq7inng8SDy28v7WuoUinXE7MzAoNq3b6e79oTDyB0n+U5o/q1PVhp0im3uVYxdX0g2FxIDX22SlLI8mSLUDKqUqpwSbQGjEA0Sm20dpp42Ky6cBaN1tZk9nGujsbURWOeE4lxSnd/ehxJwqWSWjqvMDGfSkzeOvy+RmmAIBEsh4J9Gd
  template:
    metadata:
      creationTimestamp: null
      name: netbird-mgmt-api-key
      namespace: netbird

