apiVersion: v1
kind: Secret
metadata:
  name: kubeaid-config
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  name: a3ViZWFpZC1jb25maWc=
  password: YTA3ZjVjMGRmYjliMmYzMzdkYWFjZmUzYzhjNTA1OGU4ZWUyYjllZg==
  type: Z2l0
  url: aHR0cHM6Ly9naXRlYS5vYm1vbmRvLmNvbS9FbmFibGVJVC9rdWJlYWlkLWNvbmZpZy1lbmFibGVpdC5naXQ=
  username: ZW5hYmxlaXRfYm90
