---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgA1OgoxCXKbHhgrOUnsBXcX0mKOVfseueBUhShtSzxF37QpP3EaGx6bf4FcMawCOpdZlT/3oNhZat0OMcahl3i+JDB9fg6yo0zua7MwOJALFS2tPSZO7sSSCJBmQxCzJXkRyPGtay+74yuGwD6svTnKvEndtz3NNffJIReem7CJUOAvzYlBRN0ooBivVV+FZh53YNOEQKIdOpOoHmKJjWXn44f8rAh2xLdUn6BpfUkoUxlDfJ+VWbZfIN1kHzeoBon927a+O8abbJnwJBfPd8RUeaUJHvWiMZYBP1Drma5Mr0/sA29SbMdatOYqWqu/mRKYVvD075hUkEnPbYuwteTKxuWHoEwGvENuClQJmX689jIeE+3Zyx9iYbmZcKrXQqq4g6v+v/0XGHK0dX2EOPGwKd8NrAYS4k1Ahs54BMzyPd4QOdF4nQx6ZYZYwUo9suPYZmN0qRHFr4ApB2tBjJwcrWPJvpQtZxnb+376B1voOr9tora/eG0Z4dQtbdljnbQHWbrr3IQ6M8GHls43a2Fg7/45ilz+fruVJPpzx4UHbqizMv64jg3h0+ieNnTs7qPQW5TCA027zPrJDaIjATuRgqTu2xMaUUgUsCIFizAuSQtRS+wK7eUuHCMUi8v80UD1QqW4V+44DOi9hqjhvx/A86tE7Bs+LunSSuLMnDt+uo8gOq9itZ+Nn6C8urHngeIQ2ahRXsTKOSWugMTyKe/Ceg3O0+sXXLIptzmvlPMt9FYHoGG57w26JOrnNGwI1fzhNvStAocIhhUvywvuUTX1
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
