---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAdo6plBSt5fqMtCRjr8nRtqEvSMgdj8GkdkO4iPaITcXwjGrFpkqRve6l/GZIDja3HzZqcmX6Wj2/ObDjHndXjFg2FB8OSQxyeH/kiJxs3ZYypQTcwVFGgHZ4uc0q0TWYivA8uyvbRilZmyZdd4Ij65Ub86lA4l7rZ7Lbf0IyNg6J+Dc288i7XWeyEmJ1WvfE0ZmTA9uEER5QSVNM6o4wpldfBSQQmj9pdO/jeXS6CwjheyZH54m9gCgIII3HQe2iI4qqu9mh7hT+HWahKz88fi1josAOsmpeb1SRmkrk5E1xQ1/njXqf5hczXxYUAdhZ3/CuqudtdWvei52koVlAM2hueHw6r4QTpNd3DFiWxbup9RNuoryr8Y5YBkK06O61XVInh5WUIqxjF0y5V/PLCbd4BMkYvcY5MmUt+GyLByc+TouHbn2lkIsn15P2jgkCwllU6/AJ4sY5gEq/hYKGxwqSz18LhNDevzJXmT0fw75P0z8sTT2XkCMJ6A5pRdiP6Jvj4r+LsAWeCKcrTli3Dz/SRkIzS8NH89PYzT5dAkD5wIend6IzE70M+n2Fwut4aTWGGnteU+1+LLHTXEFR9re2MWg8v+tM3qpheaUxO+HhOLhxwLL2RfP6yV0XTyUjOxjKQfRMiqdlMK9HGFK+nOtwEQNSZvniNijSWRukG6zVdiJXa6piR52kuNv1fcvKkLz+/QOft/pGzz2+FjWNqJCkgKK2UGK9BbVv4vqrUUT23Db4VjYLyLMLcFohNv84cpeobKzVkJfsrHaJ0m8jn
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
