apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redmine-obmondo-dockerfiles-registry-secret
  namespace: redmine
spec:
  encryptedData:
    .dockerconfigjson: AgB+I9O++O0f8h9902bcFFLeEy3Bc16T3B7j+98P+9fgG9w6Ef17HQNiNyFwOcJYbL/tKai5Z0YwAUOp464XjUkFTmdLGdUjlugEeUXc4u9IlqgMvZtQbXkUYciqm8hDYQ+n/SDlfN460jsZjr3g5+MNXiPlFV9lH/OiInXQIIoXT/zQWaZ2Vk7gGWy9pjcZTw+3SqroIkYtXFUyLYzSkYHPcQ8/pMLOgPxF/8zft8ab7z3cEpm72JdTQbnTl68hw8B4XNJSKOJm0XeZc+bAuzmFd9tWjZQqoGUOzMcExK96LXbc2F0mLcvD/79I3gpn0oWNvMDW6CIlb5TKacUyHle6ZM0O/F7olOf76z4hIzuvpNl/hxRNUOUmbyW1lu5GlVlV65sUg0QdFWjyGW33x4OHe++HJlja7Hnvy8xzVSOfbsDh8oZIl3/4Dmq02mZqZFpzbfvShiTE2qtEzSIXM+HCqN/ImWxAVy6Uty2JRTwGvqaPSPGa65etV4IfMk5ElL9PlcL1axRbrOekGA4R8V6SX7nVgn6Yj8fDv6QC88EaKaQQfUrOSQYOwTH+oi6svXp3T1hBP9jRk42aTVesOXb8yNLa2Iv6KmPEYlrjTUvVmqLVDUk/JD6Sp4fH5EGpwyNZJR22d02qEndjgglYNxTNKDHqT9CtsKAWcgPJHWyiY6SRmIaoxmJLD8ggqdD3PQTuk+GLRtmnUK++BGlN2CUXVgcEVURnm5QYbaEdQfPVga5Yl5aVuvbXK+pjFy7ik6kE1LPA33C8kz8RYaXuJR+8/TWEEhrH3LILbDtFF08HxhddVKDCE1p0ufirXWd7i09BhpILSj8qlLCfxvuv9bh2Hlx2/5UgRkqIwnMOObd2edZU2F29QL7+N8VSfQ6CXSnq8MVg8AjJP8r2pYzYFeNmvEU9WNefdMm82cr1w2biyg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: redmine-obmondo-dockerfiles-registry-secret
      namespace: redmine
    type: kubernetes.io/dockerconfigjson

