# kubeaid-sha256: eaae299f2bb9f7b7a558dece62761786c005f1b6bdb92fddff80eca9d0dbecff
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    robot-password: AgC46cBrP1hT5cnBEuIGa9QlKE5IeQIcB4UtJWQVnYiDDI2w2ruB4p6xvm5N57DD8h310DeyvnW7tPVQBtF2O/N10NT3LU4u5oJY0iw9cCPsnWiSOrJ2AgGZqhUMkBRnPK4Gi4ewIVw5NlRZrfqxjxCRByC0dHsHBi9tXMFm7jXpqiG4tGbJxeGzKPkdvpqJ+FZcLj2/uN5B9XG2A/92hIkGVF5p/6UKHdbAACUOLvcHEIbCb2ctl7XOvq4lHzPldsioMSNbyuHtXmY39neRexx0AYXSRhC5+/aR0x7mKmsT7Mv+iHnqnCxeneEe4WteDWOJCwl4BvpT8TEYnKl/3PXwn6qjTd50s+Aqhs9NwJsc5pC/0n1SOivZcMOuhjrG5Qv4xesy0kVh6Q3YPjH2MsW9O8i0qAXHGixmX+bRD3myLvw1BtgRzY9ViLpLEvMuyqvUpHkuztVtcB84uRvHlSaZJb9Emov1P3iqwnNC4SGoF/BlLrsz7GJ8P4Da05ZXZy3+58mYI3xcrpeZgrntiXj6MQeOyDxxwg0rUCZbSaF8pQpQ66wZDNXPDHIScSsEwUiP1MIxcRGo/sirpJD6h7ErFtmfW2f1asiqjWMhu/ubMfqOlhhEmIDIIeh8a1J+oA/6V+hl+EU3sUod5lqVIe6QvgD0dPFDmqOE475E3Y8gDLHlKoNg87oq9zNbYiUJDPlD2rTbTwedt++01v8CvWlqSfGpNg==
    robot-user: AgCsbhqrKDIxioLB90xiuVVspo9+G9YELLpsq8bBdM3yyPEFNr+Fj3WIeOR7EsB5wMSJ2ybXD9gdsOIMjuokG7GU+aVwU2c5NQr7aMAGgLm69XaM88kMNb1tuqc4aePvj0ChYz9pj8Ey+31M5ooT0up2BXmKpHOYOecGVrADS1u5/eTScDbsGufJjrlC+VU+3sxSvaouz+kJ3kpGe20sbfJAoFasA+kw7+M++rREXnP/4dJ+yHNV86E7kawMUWw2ZZTWKJlsXzebF3hGfuDltkBe5MOQgj/ECoDZ+XUnfk2nal3vn4vY8hRPBAxoMuP7jMa21AA2ZbIZ6NXgXBWd3lQ5+lHIa66mjZyccBa79OSEEWBgeVvwhIJRtKCylmDq7T/0R41K5IiZVjqRrzZ/TwHUbTBahJQTY66zAkLysc1HAI4W/DZ8KbIxr6WoNmBr6jPSchVYUkWol9IlMCibcnQawSrTqSbBcQ9oKyAhS5pTov29kNAnGpK9pDPGg1dwP2zbMZfyddMG2VB1ZPx7uUAEFtSQRHz7Lry0kOI3Bgx7MEMoK9XBrQUjVW9F093vU9vlYrr3A+94eljyH/C8GwiOVx+IonQmh/ow3TkNzwi8W3wpv1hMEwb70+RdGu/VNgWbQWQBSO0BYtLxV/LZRHXqeBZqKvCPc1qkRz3pvQndlNYRVt92m/4/PFLIc7TtUKl6Czio9/70xV/uGaw=
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubeaid.io/managed-by: kubeaid
      name: cloud-credentials
      namespace: capi-cluster
