---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAhqzeimWlgb7+2H4UdpIe2bHkpcrjtMhsIxlzTkvuG5BLWn22vFg1xEyOM77bV1Vb5SOQngNhi3rY3csdCJvSaGO8DtE5DDnAknGcnzsJwHBsrkbh0+5TO5QRBFQCnidOPbPkQhqPv6IFJUo88xnW/N0q+5BPemjEJgD9zXeNSozQ7jafO//WRTuVMT25/5rI/apmZ7z/PdWsbkwpn3F/zdXaj8HXTpiNDrbl3LWPuzC1qSSrroz6c/Qe3XPwOiwi5F/SBAI6acHiKLHfMQB0dM4MF6doN65+DTd4Eudzz3aq7PYXyDzyBVrdNv4ajxDlGymoUnYN4Y//zO1NPXtV6wYigyJxY5WYEONZXLMZwWPW/ylHbZxHSrKY22fsCaN1A6lwFJmMxk7tDlADaZs9O7SCy7HcWrqZeExPfqW8t9VM5V+ijr19EX+QzqIIwdQ+yZkSHYq988BQbe4FnApXa6e1WC8LT1yzfRvbNWCDyV1A+HxqPAGffSJEroRlKCyP4zVHGKIECYHwDXRyqTP7J1UXpVa2xJ5p2ZUWpP5we2sKLFihE9PUnizle5NZ1VDfg5UOZkslX9W3R63JohfMT2VauEZX1KjkFYvEcIR8xn6KYf3xjC9fqul0wQSeBZP7SKwJCAH39ClSLWoXnonUjXP7wGh4KMZyiwRqxcjXYhngyaBJkyCLGMTW+iCM9tgIiyZ/kMtyQNvI9FchrZZRSxy394fKuTqi0igpVLW3hTg8NoEyxKgfEkc+KVMrCszEJ/Oqze3fwkTjFcI/rZEmk
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
