---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCOdE4HMaEJL0s18fglr5qKb6CUrvKRk0g9b0jWWb3PeUeHLc0UoEOFHFtLnhDiTMVebPvdVFFYZAlcEx9tahLfIpJdGW6pjkL5bAlPHL2Y3IQlbXRB3ptl0LvgJITfb/Hz/YN6fRVB1XCZPxcHNxzmcBRY2apky5APCKZCmxgUZM4kG58uJwg1PZWYDCQRtL6UhZy6dQ3ms+9NjTgV4UPu0RBFq3z4InM3KchzhfG9szzzsqc5afF0Ijqw460dfCpO5xZv+S88qwIAwuEsNGMu0etmLi+RNVEYXUte/fs7cIS5rnzFk84a1l7L4O2q2iS6CT5AdhqOB8fjdlUB37ivfwjKorMFj/wQMy5VXHqiD3Rjos4hYvIgqRfi/vmPXH4qxupQF/5eYg+Wla81eMJ2WQdo/EnCF25xGX5t5ziRS8EQ2hfzhIkdg4Gois7j4pFOZh5tziu2MxPfhJXJ1h1tZP1VZDcYhkHOOk51W7LKKyDfBqOokr5Fh0h2ZRuj+OOPU2pmu5qtai2v0pstp49coZqvQVodSi0GENBOkhpOkEIdthLDF3O6ZCI/OLsVNWFYKEXEWIBxyCqo4VWyZkXSOpM1Ubw7e8ILT1BPSDN4DEGhPNCuSquei2J2Hxq6CxUZYC4i61WAWE6Pl+mT+TBrXNbJuFJTg4PZCUbX7uZ++ZnH2jZyzJTzHv9be6rp0OopGf8m3cbvOYQFMovjZEtOAqB1PV5Xp35kgiHc7ZAXEK+ljuehUYuCci49WB/2Xg7K0FQHBYPC+NWHjOoxZiee
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
