apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB5R9EiY4hqR36EiBTCYs/W4kBn1IUHh+jj4Z9qlhhu2rO4hKGxdwMYkM0DuFa5UY3b2cRhGdu7UkaS2sK1Mx28OlkndhuCnC7H/eLqKZk2WpwZOJWrU0JAehuz4nipf4oUK1yX82ORfSt6iK41x8Ku403ib2BQF0JDGYEN8xnI77HCDXtHNx5v3WJSDlzU+WCblUJyK4WaBRstcYYr1neIxF+l80eAv/6XBvJpP+MIvx2eFRRjfabziFF4vSFQelxGoSYqCejD3neJo5MHnkkUG1lh74bP3ztHJKiSIsdC92zU6BK0uTU4gV29LMaKIMAOiGp2zcmOnncLNcDVN30gDh6DryqVMXtIM01vlA6+lyWN8/qabaT1DJeV5golgTFKSXkyepRuN9TYxpDrfhVqQJw7aX/pDaVNrSAkyO+RbUnSFJo9Dcj5rhGGmkAfApG0K81OQLApB1Wl2Onz/4zKbEI1Yds7dAm9BdAatqwtaNll1IaoSGWA9MJ1UUfvrA2BcqVg2l56GINJBHqaRTon1LDEHXZXcSNGHMqkmlkx/uU57bTLCWWiF9mMK7Vx/BOGXTxDHs/XScv8QDEoSN3IdVVxILX2fDsfs023/W+2Q72cQtbyRHhySHwogPNBfN5LL2BtSSewjRWh+w0K6I7sX7Ea+wM/3QcNJ8SpZcDYHXeV3b9OByoPNdgmGU/jaeLbwM/t1ktbwKT9P3dWyZSGrfQeJXSzqAC/aeSoadRKq/4gRFM2QeNm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

