apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: capi-cluster-robot-ssh
  namespace: capi-cluster
spec:
  encryptedData:
    ssh-privatekey: AgAEwr5HXE2iCDYkYzTvWh16lr4tEeNmF2ZUX/ogm16ID6Wn8FhWrbFQMDYicPtLtlbEJ7w5lXS3qSlzAXDIJeVCs+VJ4c5uwP37BaibJWfkw9nw+F0z/5Y7adiV577e7w2sLKibwaHDxD/g2sovjcDdURnm9zThPY78vZU5MiEDPKQDpEtTOAVgIwaYyYfjR0ePRQfIGsrFqqPxeX/P/nbNwSFewJGcjYP4T7hOkiHIQpFH7fTqYkMybbdO5IrlH7hGnNk0jxDK2l3bPPLPnsGiIsC/+LXe4v44vmN5bOAlZOkdjPuG3JlUPD785EGAvirAY3WMB8ZBsfD8Jb8kmIPB6u+U6eXURLIb2HiBV5JWT/muEslOd56b3g+NVZ/syaGk8+3I0LwdZPDUmUrXaj7xE/UADp3nvaxq/sqizUwicuTmnrTRoXElIkIPTUUt/HiyfmW2w+uv/HkkmN+TMB85B8bWgqA5QyKk4bggvNR7yexXhi1WxXGsHD8h611yBHY0t0dPYLmZdMp6m8uMBjZgKyBX0Axs6YEHzTr5VIZ+nxE00LmQtqBOhnpQg+QMHtSr2gXZPla2GD5cLYH+1ytG/SFVWc4L2DFu1D+qMCoCSMLO1EW+im3BUeomviFvB3w6+tqozd/HBfwo9SWYyBRrOCqh8KgBTvBUZ+fPavnkCJioJDpReUWmmgTdjxRac25zsbXtcqDd5RsU0UB+aJ9VVw==
    ssh-publickey: AgCObcOsWRIEcyRfTlqRdPYn5T8pBap23ns6rZpgbLNCMKkbrjOTNAQMaSrevOw/M/fmVB3S+B2+thV6WNTOSnz+ondocFJQU/gg3615h6qzEJru3xZqUGrqqvcD7KF5weMuc27EazXE8Uzc2rSkr0bo8JeS6gr9vTR11MrYPw1+z+wK9iDLYIAbEKOXVwR06Egr7fVwbHpGH1dsc+nhI5htSEbqxxV/4GsCAJug3IpIvko3MRZXy5yfIvcqjUju2+wl4GAphvFaoiTrG4Y0WtGHu3kRPBVIKMpWxT23uVzbeWqVoYBIipmPTu/WC3Qn65Q6ODmWyfeEPyv54ccjhgED/R98dVyPF65tdxFDbyNVJctjVMKC+L3xw5D971k8s9Mgohb7SErZGn9bQLnvh4k0vM0ELaMSAJY6hJXGE/HUzv34ZzBlKbVH5F4mVp9hexmzfSN6j85KLTlUNgWPLS3FU0NzTcRCEPpcrig+8QP5cqIw2pLw7cpO7HHwBTrIOF2U5ghOxqaMHYNb1OTTvH7wA1PzjlTxT9nKRRqKCMpz1iHpDJZ0OLhLMduBLNV7VO7sIXb1+BtOhhnw985CEHkRkqzxbSCu8uo2snutDOUnM/B+qzeBhRPJ8//eTlqvbbjv9D3I1PwA9NojIdw43xi7OlJnvgwRR9D27EsZwtd0+xO2TBVpG64UOmM2oFb1rWMxMoTRktF8DoNdctFB2MH9vhe3g/U=
  template:
    metadata:
      creationTimestamp: null
      name: capi-cluster-robot-ssh
      namespace: capi-cluster

