apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: capi-cluster-robot-ssh
  namespace: capi-cluster
spec:
  encryptedData:
    ssh-privatekey: AgCfml6HAQ/GbOwptJe5dNcqU44RCSXmam1abK/wDMA+OAyXq2lJSwMOP/n2YDQqFWe/xneS+dVLdLyI65klaftg9uMNwd/9qkTr9qGUWBWpgl3qnIfhiADoPxWR/SwDV0oHuE/nH0XTXeyo/QB5uZrA2wkZv8zXEZhAAhEojCXv2qqb4me+AE/O2/dxLal+Yp1wZGEdAgH6Ec8+2ZmTRQb8DcKQInDDr1RNMLGDpgHBVkV+6Eu7LtjKQKXuxJEiSAY2GxCeVJrW8qq3qAC8A1iH9C2+DCfYq8ooUEEYG49WdR34YD6LHOu5PEza/1JW+Cc89ZEznUI5gmUqb08DYab4Hjq9f9YOdKN5cTKa8TFFMXQMDBEiQsA+u8+86T/dIIvopHpuX7+2+I0cVSERX2SyBj4wFNYAeBXNF4JbW+E4p88z1A2Pc7PqgIM6emO1n/BWKTL8vXRPSZYMSi7BYGWNvuDdJqgDPctE08XiFPb3ZfaVSANWre7pe+AcafTuPqyOwwVT0IPLmCfqkqU3XuEnu8dzLtrOgnEVmXda5cCHdp9Q70sA2V0dgNULqYvg4jzrUvHWC7ws1VKSjKgTkLq0XXmrQqhTnnEMLrm5x/ELPKbxRGF0Q+C+c5cm5Gser/WGSh9xLAbXoAx2qPk23AAjKLypjqkVSq/zG2D6N5eTLQkt0qaaIGEWgI4PlE+x6ZN6AglMBXF2oAmRq07NuP7ATw==
    ssh-publickey: AgCpc+GzvwH1Gdw/47sPPGyG95lxH1r4g+Ysy2IXrVdtT2Ba2nGzAdbDRn5RZF282ipUEv7k0sIxKfDrBFVV2EE15H3g96KKVLA+tTedTGteoVcEt0sEvEgG7gIwRpO8nQa2KLXisEggKhPscZuxyvwM52PKU5f4XvTuu/M2blftx1ljlKuPOnYlCnuCDtLmeUbmcf7ePyzftlyW9btYNKHQBc9u7X0xpb+h8V4sa8lsThdFRnlvANQ0eHLheE0H6/of5o8sMGPO26cW1m+Z2Nl6U5hwZ38AmBuVTwQDTpEYZ/dgfvfRKiUVIMTTOLcAVlVVmhj17tFUoLqe/DIT4yWyDtW2X7MAm8tWmIsVqSCFtH5bPnCk+WYv/SOeXi0zlHfGVPsNiiPplymEHcA20U1TOVTsA5dSFOUNrou3/ceZzgP86jxdldoOTTRp7dGjuVpRlsmUcK87NpnNGatm/wOAPlCUr8MQIM6UfXH9PF+o/L8Rwrc71KCRa3JNRjRisBG0t/Sk8TqM0+mvfLPjZxhL5BZs+wxreCidTxslxWqG1b87u0Y7wKX+30Ex087ANKcKPEN6DOA7XxpQ63FPUcE271CL9n3AxEC1B6oMYFD6a9UUWg2ss4DulyqB5qDlNkfW5KoqtpZmaxFMxbvhu9KngSbf1+CkSbduUkZdY2YaYbI6vf6rRaeuPldLmmRBCaZMWW9ifQscGy8Oya0eYTPE5pJwucs=
  template:
    metadata:
      creationTimestamp: null
      name: capi-cluster-robot-ssh
      namespace: capi-cluster

