---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCEl6lFbB0rVeyRFHAfTAl5iTXGsLt4FEa63fYFaIL5VqKPi3DgDAfAHJ5v7NE7dTUvNCLtv1cSteEcUoR386MnigiMNN5ZwAQOmaGUFJVeX68VdteHVomz5ZuFGY7hj/vwLSulitMNI2bFNbon5g/jrjZfVxC0go5W/vPwMwJKJdb/HSUlYilcMP0I3q3y7lcNhnHpPdZADTNejHMgQ4CdwSmtVCzQDf1QPThH0rXZ6GofT2zQl/u+Qf03JlHC0xdWmv61afInGpUFgtRr3k4EJj/1PlHoD8eFoZ/bFW+pgL4zX2A7842bmZYPOMDtW3WY6eCQrPAEG6s/UhIFE7ftz6Io3hGETqDnPbEx5PK49h4ny4EEZKiJ27YcO/YXT4/IY2Rn+J8ak8P0W3p77Bvj8D5MvWa2bY6lU3gM4Y92c9bkOK5mNbnEcbBMOIwQHvTx6h10GItnLbcquB7FJApBg2bjPFLi7IKpsay73IOota+lAjnyjC948USCN/XEHv7OVNKiNf8bSo3qWUA1GlMU9X0dxLDpouj/OMW5ByXpV1X74L2PWQF02qSye6384vubwzyFIbU0lHM6et0f7H8saVm6UTo6KuFFQlwStQgj45Jx+nZO+o/dRjtlS3BrO+Io/bQxPm/kvAkcY9zSmqS77Fvk89tSL6z7wvATTf1hDSFRYT1QtoxtdFUGnp+7g1/o/EhsBPRrqSOAaoNvzZzWGA7eSqh1c0NLbgCgH8T6/b0fyqj0w0wuTcHhXepxqG5pHtyd7mtVx3lrW1E1Saey
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
