---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBkRDvwnh292hlvY36mAfCZCk6Z9sZqVkrugWXn/RieQNprO/a9YZQSSlWxEbWHbtNKrraAz1pQ3H0kwIJ1Kc5MhqGL++JHgyi9O/jPggF3c58qPuvkKyv1K6ohTSl21gU5BCoO0Hz22LIZuwD7+/Z7EmYuS0BXqz3CW20wRnBroHEeZiiUQ0yobPSkBE85CE6pM7Uc4ox3suS3KkfBzb7XxJfZpXjkKfE89RvGZHDyJxlXcwtSrGyYmLLaJz5ZSJki5ts4sZk78lBz9nSgRyG59ZR5Nk9G3Flp3kptWwzCutVUt6oIXQ8SPo0MxKA33X3OwGAC1ZFoCEHx0yb2xRLhS2+EV7WYiYEwZHQxJOtjE+4yiEvYTToa6VJHJ8Xo33IFei42jJOIPoRJN+S8RZIYYavczGik4Dqy3MkSLvc7SGJI/vgv02+sS3OE+ZuaLOr5vVV6ahuX+Vpc4FYGg88TBv3drCKm6AvRM66pfPZ1MXGqY7Jyk955cQp6NQpllXG1q1BffRnRo5X06z2/8kaE70J13dvJKDxuNCWSVgfvY2ogI7imFcyH4yCwvYeIxTxL53fBOImJX5eT+LvLTWdags4IxLf4Ga5vcK0xdLJU8zMfUmhGYmIf/ufK15VlNA9npbZ6UawxELh/DPqhIlyh59kxmsZ/tD9tR2p+AtXt2KPHnWO5bs7ICYy0deOYrpQD+Y+gvf0oVo4n75qzwyzFAtqx20o040bdxt/gjvh2yNgn/apliW9DLVyNae5iYN5/rP2NlIQMTMSWKL9zWQiA
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
