---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubeaid-argocd-auth
  namespace: monitoring
spec:
  encryptedData:
    token: AgB3fX4VHYuiJoZVSbwSHjDL9neP+xwSz4cbzzqjh/1vVTeOb9dGQeJeM+CxhWig72kO/3S3HPF8fbywq3hwg1LbemBdZpwXh/WYYmyD8C3/t+zabwJiv0wMrrSIv4QcaXWpUmpvbkIGyGFDPNXpixh0ZkUCPJnMuIekdhxpAaRnGV3Cfq6+CHRo7u30Gfh6fnDzs3sj7wbppxRHB7FSNsYm0KP9IXPYU90EY5zyD4NbgWLEMTDondZXKTV3XgFOdC0nrY8n5deITqartVnZFxV8+rQMxgAv/qRV2IkS5hcjx9irLI0WvF938tRnlY48VQp8KRt/7nqhKGerCfd4oq1S19irhSAZbzvIHZ7ySa7JjvR4m05DgicexX7vKpy9QRD/QIC6NvstBTd3o6ZFIXZGEKAIjO9FUccsPj8IAyRy9eDxIHRpwM3Xaa/nuQJA9ObNqVczlgbsd0HNP/X8aaMweaDOVQqckFdYkK7qW70PPIyl95SwxS7oe5E3tQKj/fY/8MXXsq3xZzp4uM3xWkWHjPQrDwhIriYuXWYg2X2+nqHovB4fHvZgY7/nHS0o8e7UivxTydFSR+PFPJTVGAcwU64ARtKCp34MPn1cxtwNICKcf2uFuiVXqm0+FOaTJCUSSVXtrOvUMyncuplnAoAJPbZ5M5v9VdyI6/PdppvjA1yjiYXfqKbOiuXDXZVpJPuN4WQw279wjDvMm+w5w8LtCI9yEYaqzoy9JvSJSMX+6TogyF6sMJWHR3sedceU7wOzlEt4b4QR2H2pOIsV8+eAn/BCBtJJ7JDJXjTOkf02sQTdf9OoPQbV/Nny7woz9ULc4H1RhMVfNGfIvzbMoNY3S5pUk4w5hTI4apSymrJESsPQVhej1hsH02ePisVcdaouNPf6Ln6rouTkrbzDjcM70PlrmKmNKRORVS31s4XLDfnfF0G0DP/NLlJQasMWX6SB4jw6qeu9lVBLdQ/DhjHLfTi8/CaYGKqIwzm8DoJCb0V7eexX5oDm139pVxP38oxLmQURJAvo
  template:
    metadata:
      name: kubeaid-argocd-auth
      namespace: monitoring
