---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opsmondo-registry-secret
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgCAfhDr0sj4JDpmN3tGU1f8VrbhGPf7vhISldEzFbleYpFudYcXk/WXT+rRI11Y14Ss9id+f8uqKGc8TrEo5DptMOz91YRWoss9NIdqrgYNmYJTWRb8n2ngco4esqkR2Tio99NQBOoHIyaryWHi30u8hqSdekS9hZw4+5ICx1i2TFtzXyoBhAd2nqsKw9oSPIU9K0uzBhlkeiGdn6vnctsTFNdZvJi8sydKvoS7vq8dGEGYBBphfW54IUiHgkbvsoehJXhUGEzS4CIDB19x3Jn5do7IVoTTVT9kXx0wW7Jq8A/GzXdTj5XI3iEMnwEZLKMbKF7PtJKEbBTdddL7gAnvmNptRGnCHyldiZEiar0u3RM2pepF1ltewbg0Dm5Y2yQtalni3CuDb0AC9rIoxW7TmqKlkleVZAv0tHaKhKKxiU3qkkFVIO6DIz4XCAXlauXWU+EAh3m5OTcRnxMi9+LEislYH2kRKppKNOC7GKjr4diycMDeXx7RIlAeY/v04p9JnxozUAIc90oDExmWGqSzc/uC47gm+KRrjsp81LGVznx7DXeMVnv8D5Y8NpBDGmvdT9HDCBSr7AIQmZOgXmGBeVUEmz5lqaYTsNPGqC5lCK4av999H/gMLQU0AyDl4NnLwIUuh7FVcX9LNjd5QSv53F4hxVdirvXADEzMf5cnI1R3Lb1kzDMDjRbLaHWDdSZo+mGu+JIBTxYlmYNRslea4+V0CDx0JzmBmyBE1Eh/w8K0KSZvwQO3Zd96SSLztBV6teMMna1IV++cVqtUK2VM15M7htlOWxpWnMgJN4uU+auU3n+sfNH2HMc19NGBreStXXKjF/GQslDfMPe9bCQqmiiaGQSXnsHZ8O4v89VsaaUPQP0CMaQTps6waRQi2TN1hoRZGFfkZcPUhUTZk1T6DXGl3+/PvDvr5Kl+5RtX9vNQIdSbirCni3Z2GIdmYMr4Wpqjo9ALxNhZldhuBgX04allqKtcIUP48Y1rfKdfnaHu78dt2EXb
  template:
    metadata:
      name: opsmondo-registry-secret
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson
