apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: errbot-obmondo-dockerfiles-registry-secret
  namespace: mattermost
spec:
  encryptedData:
    .dockerconfigjson: AgAQcu84XX9deLB0YtqLunHqHyhsisHKYmsB5Jf1ehBhxDIvyVCHHM1hWtf23Ga83idgMGBiy9hOe3jts7VOenMEJyVOXH44BFLIQ7EWWh8N9cjJ27cH0F2/JogugObjoWMJwzQGwBMNdH7uVRglKonwTwhd/VYZMDF7Z9Xh/KSqrv6BWFUOKcNSErtUXRIftJupk0W1GUKP4Tti/ajTmXigWltotEgrfRTV56724DdB7sX+x7z4XIx707vrdX7EVOZLN05Ceer2AexIHCsde9zuK3DTtEEi2m5WLEoq9JOmGOkqMk7FD+rG0LClqK8Mxdu40qyow62oX0WaQ8vAsyXXwAPSPs6rZVBYRUidlfOat4j8olrrutHb3/WCHuKnqo2pMzbE7HDeavz+KVXnUyRzyjkgGpP7Xz3OWJkl5C8clkltyXhr4/6QJOdbV7mHHZTFx+Ob4+S3q43+AA0zLt7KCNSoMThM0cV0vVF2bPxQNlXQYboDgV0hrZIAlp656dKsS0QwoEZ832Kk9c51CBtLGCMeXgjhYRPzXLcfhPwu+Bmd1ytbiMx19/kj7gqDbF6UesaXpZ1/XEhYGKqVY0X/Q05bv27aPfYb+pwfsEfrSxRE7oRQ290MEfJ8pkfMHLGj55YqOgAnPRkTQS/hjnjiIjyN4HkS2Llbp4VzAiDoK8XqzCPdtH8TpJDAHf5hikzYe15X0av+MRWv1YFog4SdgnN0fP5+CyxUVQ4AlQUtLpcOfqGLsnsg0dZWQIczICFnedJ+etFRptsQdBTrzs4K29+OHiwIzEluznXdWN3MWEONiQIfGYI0lR5BDc0L3ZJe8lbeZ/KjlvvUwM503wXN/QtW9EF8eHJqNc6ROjeOurECht8eoTxLmVPOYM3/6SFufuenJTJmfd1w/ZkCA7b0HTEtCaSwZMoTe+/nO8vIaA==
  template:
    metadata:
      creationTimestamp: null
      name: errbot-obmondo-dockerfiles-registry-secret
      namespace: mattermost
    type: kubernetes.io/dockerconfigjson
