---
hcloud-cloud-controller-manager:
  additionalTolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoSchedule

  env:
    HCLOUD_LOAD_BALANCERS_NETWORK_ZONE:
      value: eu-central

    
  networking:
    enabled: true
    network:
      valueFrom:
        secretKeyRef:
          name: cloud-credentials
          key: network
