---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCIVMVHLbWrgv0fX5UOhcq4neqNOJfJNUXSGsT4CnYu1JGzxkTT9Cw+J/o3GHaYfYE/KpPwk182xtQi9cDDcFvDTHB1qMt7tNJB+qwVJeNJPhNv3kEZoEsVJi3zd14ArhG/oIOhUlvpMpmLf0/ynR2gdJqOGTzTiQTBO2EHX78HvyzS2DMpceH8B9DCWprPL2IiBQ6OjdFp0JFOZViU1lwrKN6JLfJ684MDxK9jMqo8sf1KB53b3OmcrHugvTn/2q4dfFzQGaGWzmuZvkUOBtDIzjOMzOTq5AxaUqmzwjffMLSJgmr1MRN0/qsKedsRguanmAvvyU7wn0B6R0ch91r4idpq301MybfOHK1/JmQlBk8NU21X0DhuNtze42/vu8BJ819LvRBDZXsWzZ2YfyCzUzvQiBT8m5jb34k1xLvBdiZKmnu0uw4F/k3vgHHtRLGqaOQ3/i+lLgl1f+HwQtkZ/j0CfKo7B3pzQEEFdFj/kyZQQO23PRC6vt3MSxmUE+bkAj9vLkQrmy1aFwoEn3DHaHiva0xZvgA42h6HidTwG7zE2CGJ5x80iKsiXaXV6Hlq7aWyL1LoMnqlUsE13AjW/XHo1E1DRIRtRaagnLgv6MlE/8NKO2+6bbcd1r3i6XAqjiPgQPdcO0MhKVx7hgkR4WsHouKPwtLbRnDlqZEqNnlsuvyHN2Dbv5kZYt8aQAsA18xhoOG0RA2kOtnyqWOMjtL+zOhIY5dfnFNwOzGpqNXe5zrjLiiKpxRQNNI8RX8N21sxj00Uh3r5yU5pys5Q
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
