apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: puppet-git-secret
  namespace: puppetserver-niwyocdmk2
spec:
  encryptedData:
    netrc: AgBgx7GQIb8nXM8fgkIdvmAXAhSZH/khAuYk7nAWIZokSRROwVBfzakCSGY2pmxNt07pnBYXbAMl0Pl0SCDpI3BcOZ7d6v63pBNgG7CAlvxpDnoPvzywYruu46vE61cgV94bmOCrA1KIW7/n51UoPhcgZu5VDPGL00aOeqBNpD2fLC4aNP+RmradTqmjXoceeH48/I6WXg9In46p8QqE1tDx9tK+YKc3X3n5pQyK7a9x0Mtlu6rInxK8xI0+zzMEFjyqkjk5HRfoGPVPHmRtI/oPUiNeNw0tY26J9ghj+suacpyaQg97BnDrOPoTuCfjpI1o0sQxyHwmVH4T8Yntx0DLjI+eUC/2f3GnK6n/QnTHL4TpIPyifi+E6FwiuhbZ70OQjUgWouPy74fC01H7AxGyjufPjIhgIpH3+LWUiGepkamO2RKjcGXO5wSi7WD1WwT3qY0Mm4haLkZ9rdFGd2SDDroRGNaVCQcrV+xkUctCSPbc1ztmfVq+cOAedOEInbW6K+Ikv8B6trou5yGUKwCeq2xIwIQFqRCZUGUc/anYHnCYTDJowmzJxz/EiCIF5en8wA3eHNbjxZtcbAOSi7LuQg6/zGAzDZd0InMGFeXfTqQJWJY5BQQbgG7i2VeC2+3EoHVg/F+bnr1COsWk7Y3vr4UeOl3Sz9BXCOzc7qTa3ewG7wdxF0RYG0rPFZ13un57d7pa7/0YrQZSO6o8qTYJVSNqMu8WlfeRwEw1C+bnCNIESrYfv3dntG1xEMhDErjm6cU7Vgj/fSCt2NHB8YOPg5f/HZdQ0dvCsN355r8Pd0SE8GZ6eq89vAADU1MVnZLFsyE=
  template:
    metadata:
      creationTimestamp: null
      name: puppet-git-secret
      namespace: puppetserver-niwyocdmk2
