apiVersion: v1
kind: Service
metadata:
  name: alertmanager-main
  namespace: monitoring-{{ .Values.customerid }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9093
    targetPort: web
  selector:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: {{ .Values.customerid }}
    app.kubernetes.io/part-of: kube-prometheus
  sessionAffinity: ClientIP
