apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: "Host(`prometheus.obmondo.com`) && PathPrefix(`/{{ .Values.customerid }}`)"
    services:
    - kind: TraefikService
      name: noop@internal
  tls:
    options:
      name: puppet-agent-auth
      namespace: traefik

