apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.customerid }}
  namespace: monitoring-{{ .Values.customerid }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`prometheus.obmondo.com`) && Path(`/{{ .Values.customerid }}/api/v1/write`)
    priority: 10
    services:
    - kind: Service
      name: prometheus-main
      passHostHeader: true
      port: 9090
  tls:
    secretName: prometheus-{{ .Values.customerid }}-tls
    options:
      name: puppet-agent-auth@kubernetescrd
      namespace: traefik
    domains:
    - main: prometheus.obmondo.com
