---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: file-store-credentials
  namespace: mattermost-operator
spec:
  encryptedData:
    accesskey: AgCNfcdcwqLz07f2X3FfR1Fq69SJIHXuFeq10jcg1JbeENCjdMfWaklD/5OhSd/h2pQl3w8vWvlXcRgZPH1cfy+LUIQpaa6K1vEtxloA1luJR6HmeJvdYgNvEj9PBmRmpfYhWvkEm3JdhNoPNBPQbUHRMvL9wKJZ8z3Clnuf75GHbzQZdGz+W/O+pJ3iowQOCLEvkJR8FXiL/erEeWC6/yna09I4lTkpAyZYnD9vZzqHYuLQwdkGiS3cWl1p69OG2LG6BmtyU5SckFO2QdkVG2Xnt9Tyw4TJf2I1ilMnpKnjn2Vdv9E54zfUy+Ne0HpfWT+ozNla1v2gvIk+GqfDKcMd5UqemRFJCBE3EDjJ5Vvk41SNDa43+9XxTXjX+PUHhITS5KJ/Z+UFH19foZ5Gg+vIdp4rg/IpFIMfXn68nc7AxBRGqQt4GCHKL4NbHtWIE1gvzNmoO7io78xLKhjnjJFswy830lP1DagfwImPFumlAzNxLKhvIsjLHu1mjqq2OQ4bkTaMlNC/b71bE2K3nKxl9+gAsKV3a8VA6FK5bPiNiwjTKlPwJQJpmUrFrwOtPy51QbTOq7LROaWhJgCUU0DqQbjwyVNdGr2eayr61KiYT8eUXrHy8INm71R7QAMiNSNpUgf0M6xkKBenbnHm3yuVl1NS6jXvbjkdWRvrZaKUbnyhqOcC0hzCHOADPcwy7msKJ2oSRogfWTgi
    secretkey: AgBmCb5iEWtrR2LuLsSRilvQxUfBHURxBcZUyZD5C/o6Oaxkku26JD4OODuE/4YxY3WAb+9GTLxLi7FI4xalnDHbKOYjv8lLPZWlowqC05+JpfNdkMLVfP1h6KTGi0TRcIw2Ya1/IY4Ys2h1x22t3DDeTpdvQMWChnT+PDWIuLZ3eiAU9IMNN+29C7yhL8MMQRyGcw+oLT+jjfdfm2aPGN+HPYZ+Bd0DYQl1nbS5P3uxUU3kg/ZNDIwWcEyvSQM5KIylIJ5a872XsWAwMgLmI2uSmDupZ+G965SOmuLRom1cQPS9FXy/jN8lpRvZvp0qJzi8Y96zV7HZUswGaLCO5jH1A26r4tmlrnCBzyNrvffcxsQGrneg6BOwPjzQEwvMk0JczJ0ESdaK284tZkVaE4iYCr/yN2DwS79jlUX4tAs4+p8p9rJ1sZfnYkxUC1Cc2e7eJaUSUUVouVyS5oqwm7xvEOrEXMFLRIoVKfPpa8x/l6Pz+dqv5Qq1CMb2yjYIRZ8nuzGbhzmZAT523xgs6rOOC8G+vDc5OOXSfxypDHL3ThBunlmm+Yz/9tjk7G6d9qJqmmb67oPm0q/VuXwBQF4Ec9eP576l4Yp2Vokvl+y7/y5TFyyS7lx1U7Td/+7iT9lUZyI/MQ1Ps751y510exgym0Kp254EiWk4qIqvDPLKhUYZwHyT7OI2PC6hwk325u76/4XIwt6EBFQmIK/j7nAidxFUVg==
  template:
    metadata:
      creationTimestamp: null
      name: file-store-credentials
      namespace: mattermost-operator
