apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mattermost-pgsql-postgres-pod-env
  namespace: mattermost-operator
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBuDP+jNPwc/tSDYqpssz4+gEhW3wkkf3YZ15R0LujrgVmy4urDU9P97EYS28wahGY/AmWZAsaNTt6cnuotmEfbTPNwMlH2Syr3eWxC0we0TldZBXsSfxBOkTi1CqERyYuKoTjZ1xADlJ9LXe6JfEQOWvqj7VydfcM5oD4hYw5T8lBvsWuZtZFRweWgGK1HnBfG4Mc7F3n7qo3Yc1qwRqUtRaCTlBTN9GIw15bN2KuZwpJpzwyK+DseS3amUHKUT/VTP/dtACRJrbQAUI+wdYxJtXvWTHjfp8aHyX7J0KuIhDpZmzZ3+qHGr17yuu/y0QnoD2l7FvqLjLVXK7J3YrT+uM7DwRazqLbj9mha4TJ4Dgs1F6DLlvTXPNU3NKj9EP50S3dpmSMH07EAVEA35JXFwZ+0EiWRCPxkvqwNkgJLhS/5Qi3t5/yZqmcMa9cgeIaNfV94uYPht5uQQ6ww7W1XZ8jCPlI7VodvXbyWlvbDywKyI1FoNuqWHhZnZp9FEoTM280P9bnwh3yPbW/7Lziuc9mmyRpT5l9iltTf8fYF57aXx5Oxz9fypVCMuCH9EVcuXaLFIFAzrRq+52CS0utFSJnajhxi+lvUDetmrQVHbj3MvvbNX6j2rg+pr2wMvPejkcg3h4q87Ieqam8vL5kJhPkmG3ntmkIeQZbblhF07+O+4xz4/eiMQPmDXhSZGcnj7Iiz8w==
    AWS_SECRET_ACCESS_KEY: AgCBQDu+9sOMPepZ4Xfk7aDdDEv0epjkMgfNLi5zqMbntIivK4h/1vMDYGmuhFCFqcGogqtY/V9owdkF19JkDNUNBTFYS4lJHP8MILMCL71xTuSyi8wmivEoa/Ltgk6qekxdkfhw4tzPhRfY95+3GKZF8XHEWCeOU0zywmlYcO2SRh1T+OckNiJ62UOakQj3fbY0k8FZ5/IiNZGLsLMYYIqjNmhVitt5L5zjv8PEHkLufFyQDBmv+8UG/UjslZh6lqyAyoRV5VagosvPTbVsrnPyzTCnwv+nDSqcv8yHRM7ibW/ntesNIKXiV8tbzKj36QZZXjFpUjBl96E8VG1TRhs6vW810lL9AB7trZKvp3cj/OastDU/ZrALy/BjIKlgrxWZCTheOSItGHHHfRecAlxoSB99Qz7LHoSViy2tY9b4cHtIFrUDN9p3MUP4hkMUAFu6KJhX1+9JzRwffdNhdyfbl2/4vrtp6NwUjyHV7S7qd7Xtzye3oqFWx4E6sI4f5td+yy00FJyDrCb/fO7aQIMRLfVOXVx8JDoTq1nxkJIZGyQpn0S/UEkSEl5bA8iLOnVcrz+97l8O1UJ34TAoplucN1qS+h5TG14iIH09JhIT9bRu1xIY4MPzXgcidpDwAs8YuYzB2ZF9cqCWbu55iRd62rBbee22f3uEHudliG1mxOmXUvJgkhkpz6h6FUTnSrqOepD7t1cXbwOU0kg=
  template:
    metadata:
      creationTimestamp: null
      name: mattermost-pgsql-postgres-pod-env
      namespace: mattermost-operator
