apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBcie2QMrXl7UZ8bChmmEBqsO6lMRajIMqOgd5B3L0xspILJCpslfgb/n98b986sQ1j4oM8Edvc0ljbHiLdhDDaa+d7IPHIJKY3TyjKVN12PrFPNfBhngFQwqtwNy1USt2NdnEJ6LmnkUoUHEc11qtLlJN07apHRj0LtOEP7hGdDh2o1NDhqoYL/zptOyESE/JkOEu0jP+iX0OotSZUdo/J0WFRO+cMUDNq4Wx9fFf/ZWolXz/TzgvaGTpzBDIzNL+BkV7pPL5MkytNyTnESv4Jw1t2w2ml9SPmdxlBloSE9YKwuVU/H3LiVrlHxnQ1W3GuT/yXiIm28W+PJGrmYehiwHiEuNMrKxxhliZ0b0ronbTJjbI/egcUk1ZYpbU4ch3jleosIIUjpuVNaoAprlCPYoCoa99U67eAny9zBlSvgCzqXMDaugVhBzXbOsInwvePTM/ApuJEYMHyV75LIcrf0uamiVzh8b7QIc8hEb6tYbc0DD1yHZZXNtGMQfTDbmUAoHZoIfJCZYNMDW/skRhxCCKsbElMs8HLgOcs613nVmoAI4Jt6r/NlcB4ZHAS6Y/JtlPtCNWpOmoF6wEZiWYWauc7E8OITJ49JqCqP6b3DajVZpZtMReG5cjq5ue+rwcxik0LOAt1n54gDQ7Fu3beF6Zz7+ukMDffTDbXJ5nFTkhYCXqprCVsgdWY3qHV41popo1teGXrCVi8+oJKAqOrFEGgZHZtOIIURzoevqBhcGpZ5ZPy4tvl1bXnFrkjvC6dTJrIyVAaoMunT48aKW9f
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

