---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secret
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgAkEYP9RjIqLjYuIsk78EoITNgLAhz9dJUbJpUr9XQMZdxJBUEuBxKrhBWgkjqV9j7n4a3UTf7Pq3FVO1LEcNcKzWMh+hWXXh2i4o+C2MGH6OIANGhip5jVbKqiVgqQ5ZqGdy7zku+BhJ3oBsb1bRqxFWTpmVRFxjP2ZpvTu4mxOXKB6BoEFLbmId4v/eRbxCrxALCpm0e65l51/yK4fKf1B+AWMCK0zhe9DWo10KMQmB9GMK0uSYr594LPMfgNq+j2ZjePInnzOG+z+itU8Xct2OL4jJhewUhRjZwbL561FDbJ//RnhFWN4ahwulq1OGVzb7B1HQj6/yuzSkYxsNemxzKOPecQpk0LSQ1rHxPFK0jzq4mp37H5BwxLgP7eQC4v1E4RJed8tbWhEKv81nqlHmCH7/W+IIoMcq4kJLillLGQdoaogOIAEw12CLMHNU45GHSlMKP2gsXaHqjveUE5+USDqu6l0WEdydCa5ngKMsCX5Yf65sCpp1v2gc9dWI+ArQwokGW6otrzN1AA0aP2DCWpiZbywSZqyBc3/aY+g8qsflSsULTzIa4soy9cWSG/DSfrgqagd520iGHIdFb2KSssR0L8cjCngEZyNJzc4JC9f1wnbKjM8AC+xt8vCyUQ5O0VKg0NhKhIIiL4Nc9UX0Wo4JZlcGNhnJZjcuKsKuE07JIztpmzJwB2dbe9x2euapC0RJ14OsLpXux20ON5E8M=
    RUSTFS_SECRET_KEY: AgBETU2Jo7GcGAs/qIl1aaaFHhugtEKSZVD96pVOIp9q8/CPEcaWs3U70ta3gfPG1X/2BQMdABXXIaGiiTwOR0TcmhehCct1CxeLp3lUcdDbp2ZrkRTscTWxTiSzgzNYA9nOd7lApiIdPG0X7Wqjh0gwM9qY1C4ZFVvTWhB9cc6l4wuo5brPk6VuOttYmF5622rov2Hv3WjJJlTtauUZFyqsWbLuLkQTKk4p7fSgcboYvaQB33sZ2lbXb24+GO7WxwD51+k00gd33jQSF0vibn77Gz6n5le1abp7b1Drm6jcpIuMCG2YzDZdWSMYbooOA/SyiMoH+TtXcNPJsVTcl7O7mSeotD2HbyTQJn9+fTkmrw2hFxM5+ghiJth97lGZhErxGXuM+HXPva5MM4GedJbgnx7LbX0g8SBuNUgsKYpfrhV+oOjyNJOCbJZuUJdxuIQTElIzWkc1xLSdFLOzaKn7Mgr3dOyadweok/jTHWO+HMc4rXpf2MWtEVCRH3Ze7KphCwPk37meS1Ooy2wuDaJpMLaMF/ESt1sUp0pwa4y3hZAQ4NGRvCwyP7b6RpWLbzZpehNBjW2cZ82/CIc4jKZ0SR1Z0fGqGb+80Ao8XSPoeekNETjsAghZbEtJHfg5i8kZjZFnZZJKhuGaOxgOHkb638i3h1u2k07xQo5Dcz7oX13K3mslNG4i9VXdJr4vDlgxQzvS0IIzh8mnRY4nTHPmbWOP2mFPPwSnOYU9yUXhbztWlHGPpVN/
  template:
    metadata:
      name: rustfs-secret
      namespace: rustfs
