apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv-shared
allowVolumeExpansion: true
parameters:
  recordsize: "4k"
  shared: "yes"
  thinprovision: "no"
  compression: "off"
  fstype: "zfs"
  poolname: "mypool"
provisioner: zfs.csi.openebs.io
reclaimPolicy: Delete
