haproxy:
  # This is currently done in haproxy chart in k8id (i.e. this file in unused).
  # Once this bug is fixed we can move it here:
  # https://github.com/helm/helm/issues/9027
  containerPorts:
    http: null
    https: null
    stat: null
