rook-ceph-cluster:
  cephBlockPools:
    - name: replicapool
      spec:
        failureDomain: host
        replicated:
          size: 3
          requireSafeReplicaSize: true
      storageClass:
        name: rook-ceph-block
        enabled: true
        isDefault: true
        parameters:
          imageFormat: "2"
          imageFeatures: layering
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph # namespace:cluster
          csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph # namespace:cluster
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph # namespace:cluster
          csi.storage.k8s.io/fstype: ext4

  cephClusterSpec:
    storage:
      deviceFilter: "^sd[ab]4$"

  cephBlockPoolsVolumeSnapshotClass:
    enabled: true
    name: velero-snapshot
    isDefault: "true"
    deletionPolicy: Retain
    annotations:
      snapshot.storage.kubernetes.io/is-default-class: "true"
    labels:
      velero.io/csi-volumesnapshot-class: "true"
