issuer:
  enabled: true
  issuerEmail: klavs@obmondo.com
  production: true
  secret: kcm-letsencrypt-key
  solvers:
    - type: dns
      cloudProvider: cloudflare
      cloudProviderSecretRef:
        name: cloudflare-api-token-secret
        key: api-token
      dnsNames:
        - obmondo.com
        - "*.kcm.obmondo.com"
    - type: http
      http01:
        ingress:
          ingressClassName: traefik-cert-manager

cert-manager:
  prometheus:
    enabled: true
