apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hiera-git-secret
  namespace: puppetserver-abbnoa6nlk
spec:
  encryptedData:
    netrc: AgC7saGcqM+ALW6r+ZE4L4VOHgjdnSBJgH+RDub+EPYtZmO2ZD34n6TN2CnOiXGN/NT8sBSoXV+v6OPWoIc0a2RbzxSJpNWdeB2PZGiEeVINuqY4eAvjI8zQRLDpymhilBAQMaiEF7EZ5uYGk6EafuXv9ghLGcQz/PAi1YoO5Vc7Efx2SDsWQfjeDPdGqhHoGj9fjS6tcGpAWhAwDGwTpY12YH9T0TCXEwSKfNkg0sGBO57pdMevTGNgeU96owHwE3Y8Z0MnoSuMUnhI+i6cOl+GX62U5A59LJ9qc7yaoZhLBPGP3TE7lUcpLIrswe593e1jv4ajic8uevbNRziEQNCshR0E9h2MbQIhOt7ekCkynD6rtEe8o3siQO8QVeFHFbjQxVvmL41XF/V0Bxr4moaWukw8R04I6wAn/nF4uy9J15HavyZ/5q8fvFkJ8lKX8ta2pnzoHlIEV389J7KrdqfJSceOCjglRE/5W+BjSYnMFYNxSXLzp8/DH9tCjId7KQ+Uu0uk1CASb7LomedzBJ1UoxvR6lLvIxzgiXzEAfblGYu67k9KP6jJ0ffjcl6wVwZIB3UVuo+Ac+rdyJzFhPO0OnOtPpZVViwvducmF8O0gchn5LCxq7EcoEKpSgLv6QAI+SX05HpAdF8evqCJn+oKhCLQIsteaV4lgHLNBa7TXLvQLe2ed7LsKKepY6lfDSyWDcYXQkrOzLzY31rwFc9KITJcS0LvrebIc+IR7vRgYEqYOtGrzavU9sH4gjro1nJI85bAtEOMqbaWgEb4DbrLDEUXAzi9znOX+uET+9+KZ8In+BN0r/YHGjOZZohQBAyoKjhS
  template:
    metadata:
      creationTimestamp: null
      name: hiera-git-secret
      namespace: puppetserver-abbnoa6nlk
