provider:
  hetzner: true

global:
  clusterName: kcm.obmondo.com
  customerid: enableit
  kubernetes:
    version: v1.28.6
  caph:
    version: v1.0.0-beta.37
  kubeaid:
    repo: https://github.com/Obmondo/kubeaid.git
  kubeaidConfig:
    repo: https://github.com/Obmondo/kubeaid-config.git

hetzner:
  pods:
    cidrBlock: 10.244.0.0/16
  controlPlaneEndpoint:
    host: 65.108.24.157  # hel1float3.obmondo.com
    port: 6443  # kube-apiserver pod listen on this port
  controlPlaneLoadBalancer:
    enabled: false
  controlPlaneRegions:
    - hel1
  nodes:
    1866472:
      name: htzhel1-ax41d.enableit.dk
      maintenanceMode: false
      wwn:
        - '0x50000397cb700acd'
        - '0x500003981be00179'
    1866482:
      name: htzhel1-ax41e.enableit.dk
      maintenanceMode: false
      wwn:
        - "0x5000cca25ed86494"
        - "0x5000cca25ecf496b"
    1866484:
      name: htzhel1-ax41f.enableit.dk
      maintenanceMode: false
      wwn:
        - "0x50014ee2097c6ca4"
        - "0x50014ee2097c9304"
