loki-stack:
  loki:
    persistence:
      enabled: true
      size: 20Gi
      storageClassName: rook-ceph-block
    config:
      compactor:
        shared_store: filesystem
        working_directory: /data/loki/boltdb-shipper-compactor
        retention_enabled: true

      limits_config:
        enforce_metric_name: false
        max_entries_limit_per_query: 5000
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        # Retain logs for 7 days (168h); compactor will delete older chunks.
        retention_period: 168h
  promtail:
    enabled: true
    initContainer:
      - name: init
        image: docker.io/busybox:1.33
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - sysctl -w fs.inotify.max_user_instances=8192
        securityContext:
          privileged: true
    extraVolumes:
      - name: cilium-hubble
        hostPath:
          path: /var/run/cilium/hubble
          type: DirectoryOrCreate
    extraVolumeMounts:
      - name: cilium-hubble
        mountPath: /var/run/cilium/hubble
        readOnly: true
    config:
      snippets:
        extraScrapeConfigs: |
          - job_name: cilium-hubble-audited
            static_configs:
              - targets: [localhost]
                labels:
                  job: cilium-hubble
                  flow_type: audited
                  __path__: /var/run/cilium/hubble/audited.log*
            pipeline_stages:
              - json:
                  expressions:
                    verdict: verdict
                    source_namespace: source.namespace
                    destination_namespace: destination.namespace
              - labels:
                  verdict:
                  source_namespace:
                  destination_namespace:
          - job_name: cilium-hubble-dropped
            static_configs:
              - targets: [localhost]
                labels:
                  job: cilium-hubble
                  flow_type: dropped
                  __path__: /var/run/cilium/hubble/dropped.log*
            pipeline_stages:
              - json:
                  expressions:
                    verdict: verdict
                    source_namespace: source.namespace
                    destination_namespace: destination.namespace
              - labels:
                  verdict:
                  source_namespace:
                  destination_namespace:

