opsbridge:
  config:
    giteaUrl: "https://gitea.obmondo.com"
    giteaOwner: "EnableIT"
    giteaRepo: "qd2xcggwag"
    # Mattermost Configuration
    mattermostUrl: "https://chat.obmondo.com"
    # Dynamic Routing
    qaChannelName: "kilroy-alerts-qa"
    qaChannelTags: "@hritik @sidharth @smahar @franco-david @yulian @nitish0 @olayinka @kanha @onkar @gaurav"
    defaultAlertTags: "@operation"
