whoami:
  ingress:
    hosts:
      - host: whoami.kcm.obmondo.com
        paths:
          - /
    tls:
      - secretName: whoami-kcm-obmondo-com-tls
        hosts:
          - whoami.kcm.obmondo.com
    annotations:
      kubernetes.io/ingress.class: traefik-cert-manager
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

global:
  netpol:
    enabled: true
    releaseName: whoami
    traefik:
      namespace: traefik
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik

  whoami:
    netpol: true
