twenty:
  server:
    ingress:
      enabled: true
      className: "traefik-cert-manager"
      annotations:
        kubernetes.io/ingress.class: traefik-cert-manager
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/hostname: "crm.kcm.obmondo.com"
      hosts:
        - host: crm.kcm.obmondo.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: twenty-tls
          hosts:
            - crm.kcm.obmondo.com

global:
  postgresql:
    enabled: true
    instanceName: twenty
    instances: 1
    size: 20Gi
    database: twenty
    owner: twenty
    monitoring:
      enablePodMonitor: false
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 200m
    backups:
      enabled: false
    logicalbackup:
      enabled: false
