---
# default deny values
defaultDeny:
  enabled: true
  namespaces:
    argocd: {}
    test-oncall:
      excludedPods:
        - app: teleport-kube-agent
        - app.kubernetes.io/instance: obmondo-k8s-agent
        - app: gitea-stats-exporter
        - app.kubernetes.io/instance: gitea-stats-exporter
    whoami: {}
    obmondo:
      excludedPods:
        - app: gitea-stats-exporter
        - app.kubernetes.io/instance: kubeaid-agents
        - app.kubernetes.io/instance: obmondo-k8s-agent
        - app.kubernetes.io/instance: gitea-stats-exporter
        - app: teleport-kube-agent

