customerid: 7ejidqmfi9
puppetserver:
  puppetdb:
    fqdns:
      alternateServerNames: 7ejidqmfi9.puppetdb.obmondo.com
    persistence:
      size: 2Gi
    extraEnv:
      PUPPETDB_JAVA_ARGS: "-Xms512m -Xmx2500m -XX:+HeapDumpOnOutOfMemoryError"
  puppetserver:
    masters:
      extraEnv:
        PUPPETSERVER_JAVA_ARGS: "-Xms512m -Xmx5196m -XX:+HeapDumpOnOutOfMemoryError"
        PUPPETSERVER_MAX_ACTIVE_INSTANCES: 4
      resources:
        requests:
          memory: 6144Mi
          cpu: 3000m
        limits:
          memory: 6144Mi
      fqdns:
        alternateServerNames: 7ejidqmfi9.puppet.obmondo.com
    persistence:
      code:
        size: 20Gi
      data:
        size: 1Gi

g10k:
  hiera:
    extraRepository:
      7ejidqmfi9:
        remote: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-7ejidqmfi9.git
        basedir: /etc/puppetlabs/code/hiera-data/7ejidqmfi9

postgresql:
  instance: 1
  size: 8Gi
  recover: false
  resources:
    limits:
      memory: 1200Mi
    requests:
      memory: 1000Mi
      cpu: 200m
