global:
  blackbox:
    enabled: true
    interval: 30m
    url:
      - https://ebillet.prometheus.obmondo.com
      - https://ebillet.graphs.obmondo.com

prometheus:
  server: ebillet.prometheus.obmondo.com
  customerid: "ebillet"
  ingress:
    enabled: true
    domain: ebillet.prometheus.obmondo.com
    ingressClassName: traefik-cert-manager
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: traefik-prometheus-puppet-agent-tls-auth@kubernetescrd
  storage:
    size: 100Gi
    className: ceph-filesystem
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 70m
      memory: 1Gi

grafana:
  ingress:
    enabled: true
    domain: ebillet.graphs.obmondo.com
    ingressClassName: traefik-cert-manager
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.middlewares: monitoring-ebillet-grafana-chain@kubernetescrd

middleware:
  jwt:
    headers:
      authentication: ebillet
