harbor:
  updateStrategy:
    type: Recreate

  persistence:
    persistentVolumeClaim:
      registry:
        size: 270Gi
        storageClass: zfs-localpv
      jobservice:
        jobLog:
          size: 3Gi
          storageClass: zfs-localpv

# this instance is used for replication of our prod harbor which have logicalbackups enabled
global:
  blackbox:
    enabled: true
    interval: 30m
    url:
      - https://harbor.kcm.obmondo.com

  postgresql:
    enabled: true
    instanceName: harbor
    size: 6Gi
    monitoring:
      enablePodMonitor: false # we don't need barman backup alerts
