relate:
  image:
    registry: harbor.obmondo.com
    pullPolicy: Always
    pullSecret: gitlab.dk-dockerfiles-pullsecrets

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

  ## Environment variables - db user+pass loaded from secret
  environment:
    - name: SMTPHOST
      value: 'mail.system'
    - name: SMTPPORT
      value: '587'
    - name: DBHOST
      value: 'relate-pgsql-rw'
    - name: DBUSER
      valueFrom:
        secretKeyRef:
          name: relate-pgsql-app
          key: username
    - name: DBPASS
      valueFrom:
        secretKeyRef:
          name: relate-pgsql-app
          key: password
    - name: KEYCLOAK_SECRET
      valueFrom:
        secretKeyRef:
          name: relate-secret
          key: secret
    - name: KEYCLOAK_PUBLICKEY
      valueFrom:
        secretKeyRef:
          name: relate-secret
          key: publickey

  nginx:
    serverName: relate.obmondo.com
    rootDirectory: /var/www/relate
  ingress:
    enabled: true
    hostname: relate.obmondo.com
    path: /
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
    tls: true
    extraHosts:
global:
  blackbox:
    enabled: true
    interval: 30m
    url:
      - https://relate.obmondo.com

  postgresql:
    enabled: true
    instanceName: relate
    size: 10Gi
    backups:
      enabled: true
      destinationPath: "s3://kcm-relate"
      endpointURL: "https://s3.obmondo.com"
      cloud: "aws"
