---
keycloakx:
  dbchecker:
    enabled: true
  database:
    hostname: keycloak-pgsql-rw
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: "true"
      kubernetes.io/ingress.class: traefik-cert-manager
    rules:
      - host: keycloak-staging.kcm.obmondo.com
        paths:
          - path: /
            pathType: Prefix

postgresql:
  monitoring:
    enablePodMonitor: true
  storageClass: rook-ceph-block
  size: 8Gi
  backups:
    destinationPath: "s3://kcm-keycloak-postgres-backups"
    endpointURL: "https://s3.obmondo.com"
    provider: aws
    aws:
      enableKube2IAMIntegration: false

blackbox:
  probe: false
