global:
  blackbox:
    enabled: true
    probes:
      - module: http_2xx
        interval: 30m
        urls:
          - https://gitea-staging.kcm.obmondo.com

gitea:
  image:
    registry: harbor.obmondo.com
    repository: obmondo/gitea
    tag: v1.26.11-obmondo
    rootless: false
  imagePullSecrets:
    - name: harbor-registry-secret
  gitea:
    config:
      server:
        DOMAIN: gitea-staging.kcm.obmondo.com
        SSH_DOMAIN: gitea-staging.kcm.obmondo.com
        ROOT_URL: https://gitea-staging.kcm.obmondo.com
        SSH_PORT: 2222
        SSH_LISTEN_PORT: 22
  service:
    ssh:
      type: ClusterIP
      port: 2222
      clusterIP: ""
  extraDeploy:
    - apiVersion: traefik.io/v1alpha1
      kind: IngressRouteTCP
      metadata:
        name: gitea-staging-ssh
      spec:
        entryPoints:
          - gitea-ssh
        routes:
          - match: HostSNI(`*`)
            services:
              - name: gitea-staging-ssh
                port: 2222
    - apiVersion: batch/v1
      kind: Job
      metadata:
        name: gitea-bootstrap
        annotations:
          "helm.sh/hook": post-install
          "helm.sh/hook-delete-policy": hook-succeeded
      spec:
        parallelism: 1
        completions: 1
        backoffLimit: 1
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: gitea-bootstrap
                image: harbor.obmondo.com/obmondo/gitea-bootstrap:v1.0.10
                env:
                  - name: GITEA_URL
                    value: https://gitea-staging.kcm.obmondo.com
                  - name: GITEA_USERNAME
                    value: gitea_admin
                  - name: GITEA_PASSWORD
                    value: r8sA8CPHD9!bt6d
                  - name: POSTGRES_URI
                    valueFrom:
                      secretKeyRef:
                        name: gitea-staging-pgsql-app
                        key: uri

  ingress:
    enabled: true
    className: traefik-cert-manager
    annotations:
      kubernetes.io/ingress.class: traefik-cert-manager
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: gitea-staging.kcm.obmondo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-staging-tls
        hosts:
          - gitea-staging.kcm.obmondo.com
