mattermost-operator:
  mattermostOperator:
    enabled: true
    replicas: 1
    rbac:
      create: true
    serviceAccount:
      create: true
    env:
      maxReconcilingInstallations: 20
      maxReconcilingConcurrency: 10
      requeuOnLimitDelay: 20s
    image:
      repository: mattermost/mattermost-operator
      tag: v1.23.0
      pullPolicy: IfNotPresent
    args:
      - --enable-leader-election
      - --metrics-addr=0.0.0.0:8383
mattermost:
  name: mattermost
  image: mattermost/mattermost-team-edition
  imagePullPolicy: IfNotPresent
  version: 10.3.1
  size: 100users
  extraPorts:
    - name: matternelle
      containerPort: 8989
      protocol: TCP
  resources:
    limits:
      cpu: '5'
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 500Mi
  useServiceLoadBalancer: false
  serviceAnnotations: {}
  ingress:
    enabled: true
    host: mattermost-staging.kcm.obmondo.com
    tlsSecret: mattermost-staging.kcm.obmondo.com
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: traefik-cert-manager
  mattermostEnv:
    - name: MM_FILESETTINGS_AMAZONS3SSE
      value: "true"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "true"
    - name: MM_GITLABSETTINGS_ENABLE
      value: "true"
    - name: MM_GITLABSETTINGS_ID
      value: "mattermost"
    - name: MM_GITLABSETTINGS_SECRET
      value: "cnHtlkgqKSanPmh4upjOJUmHw4hJutdN"
    - name: MM_GITLABSETTINGS_USERAPIENDPOINT
      value: "https://keycloak.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/userinfo"
    - name: MM_GITLABSETTINGS_AUTHENDPOINT
      value: "https://keycloak.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/auth"
    - name: MM_GITLABSETTINGS_TOKENENDPOINT
      value: "https://keycloak.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/token"
    - name: MM_TEAMSETTINGS_RESTRICTCREATIONTODOMAINS
      value: "enableit.dk,obmondo.com"
    - name: MM_EMAILSETTINGS_SENDPUSHNOTIFICATIONS
      value: "true"
    - name: MM_EMAILSETTINGS_PUSHNOTIFICATIONSERVER
      value: "https://push-test.mattermost.com"
    - name: MM_SERVICESETTINGS_SITEURL
      value: "https://mattermost-staging.kcm.obmondo.com"
    - name: MM_SERVICESETTINGS_COLLAPSEDTHREADS
      value: "default_on"
    - name: MM_SERVICESETTINGS_THREADAUTOFOLLOW
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLELINKPREVIEWS
      value: "true"
    - name: MM_SERVICESETTINGS_RESTRICTLINKPREVIEWS
      value: "github.com"
    - name: MM_SERVICESETTINGS_ENABLEAPIUSERDELETION
      value: "true"
    - name: MM_PLUGINSETTINGS_ENABLE
      value: "true"
    - name: MM_PLUGINSETTINGS_PLUGINS
      value: |
        {
          "mattermost-autolink": {
            "EnableAdminCommand": true,
            "EnableOnUpdate": true,
            "Links": [
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "GN_SNOW",
                "Pattern": "(?P<ticket_id>TCK[0-9]{7})",
                "Scope": null,
                "Template": "[GNSNOW${ticket_id}](https://meet.jit.si)"
              },
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "devops",
                "Pattern": "\\B@devops\\b",
                "Scope": null,
                "Template": "[@devops](https://gnsn.service-now.com/text_search_exact_match.do?sysparm_search=${ticket_id})",
                "WordMatch": false
              },
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "gitlab",
                "Pattern": "MR-(?P<repo>.+)-(?P<id>\\d+)",
                "Scope": null,
                "Template": "[MR-${repo}-${id}](https://gitea.obmondo.com/Obmondo/${repo}/merge_requests/${id})",
                "WordMatch": false
              },
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "india",
                "Pattern": "\\B@india\\b",
                "Scope": null,
                "Template": "[@india](\\\\*@deepak@sandeep@aman0@sachin@ajaiswal\\\\*)",
                "WordMatch": false
              },
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "oncall",
                "Pattern": "\\B@oncall\\b",
                "Scope": null,
                "Template": "[@oncall](\\\\*@deepak@aman0\\\\*)",
                "WordMatch": false
              },
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "reviewer",
                "Pattern": "\\B@reviewer?\\b",
                "Scope": null,
                "Template": "[@reviewer](\\\\*@ajaiswal@klavsklavsen@runejuhl@aman0\\\\*)",
                "WordMatch": false
              },
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "support",
                "Pattern": "#(?P<ticket_id>[0-9]{4,5})",
                "Scope": null,
                "Template": "[issue#${ticket_id}](https://gitea.obmondo.com/issues/${ticket_id})",
                "WordMatch": false
              },
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "@meghashyam",
                "Pattern": "",
                "Scope": null,
                "Template": "",
                "WordMatch": false
              },
              {
                "DisableNonWordPrefix": false,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "@abhishek",
                "Pattern": "",
                "Scope": null,
                "Template": "",
                "WordMatch": false
              },
              {
                "ProcessBotPosts": true,
                "Name": "Duck AI",
                "Pattern": "\\B@duck-ai\\b",
                "Template": "[@duck-ai](https://duck.ai)",
                "Scope": null,
                "WordMatch": false
              },
              {
                "ProcessBotPosts": true,
                "DisableNonWordPrefix": true,
                "DisableNonWordSuffix": false,
                "Disabled": false,
                "Name": "operations",
                "Pattern": "\\B@operations?\\b",
                "Scope": null,
                "Template": "@deepak @basit @hritik @sidharth @divyam @smahar",
                "WordMatch": false
              }
            ],
            "PluginAdmins": "ajaiswal,klavsklavsen"
          }
        }
    - name: MM_PLUGINSETTINGS_PLUGINSTATES
      value: |
        {
          "com.github.matterpoll.matterpoll": {
            "Enable": true
          },
          "com.github.moussetc.mattermost.plugin.giphy": {
            "Enable": true
          },
          "com.mattermost.apps": {
            "Enable": true
          },
          "mattermost-autolink": {
            "Enable": true
          },
          "memes": {
            "Enable": true
          },
          "com.gitlab.itk.fr.matternelle": {
            "Enable": true
          },
          "com.github.scottleedavis.mattermost-plugin-remind": {
            "Enable": true
          }
        }
  licenseSecret: ""                      # Set your secret name if using enterprise license
  database:
    external:
      secret: db-credentials             # Name of Kubernetes secret for DB connection string
  fileStore:
    local:
      enabled: true
      storageSize: 50G
    external:
      url: nil

matternelle:
  domain: webchat-staging.obmondo.com

postgres:
  size: 20Gi
  recover: false
  pass: mattermost-pgsql-app
