prometheus:
  server: enableit.prometheus.obmondo.com
  ingress:
    enabled: true
    domain: enableit.prometheus.obmondo.com
    ingressClassName: traefik-cert-manager
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.options: traefik-prometheus-puppet-agent-tls-auth@kubernetescrd
  storage:
    size: 130Gi
    className: ceph-filesystem
  resources:
    limits:
      memory: 6Gi
    requests:
      cpu: 200m
      memory: 4Gi

grafana:
  ingress:
    enabled: true
    domain: enableit.graphs.obmondo.com
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: monitoring-enableit-grafana-chain@kubernetescrd
