prometheus:
  storage:
    size: 160Gi
    className: ceph-filesystem
  resources:
    limits:
      memory: 5Gi
    requests:
      cpu: 2000m
      memory: 3Gi
  externalUrl: /7ejidqmfi9
  routePrefix: /7ejidqmfi9
middleware:
  jwt:
    headers:
      authentication: 7ejidqmfi9
