customerid: enableit
puppetserver:
  global:
    extraEnv:
      AUTOSIGN_CLIENT_CERT: /opt/obmondo/ssl/puppetserver-enableit.crt
      AUTOSIGN_CLIENT_KEY: /opt/obmondo/ssl/puppetserver-enableit.key
  puppetdb:
    fqdns:
      alternateServerNames: enableit.puppetdb.obmondo.com
  puppetserver:
    masters:
      fqdns:
        alternateServerNames: enableit.puppet.obmondo.com
    persistence:
      data:
        size: 800Mi
    extraSecrets:
      - name: obmondo-clientcert
        mountPath: /opt/obmondo/ssl/puppetserver-enableit.key
        subPath: tls.key
      - name: obmondo-clientcert
        mountPath: /opt/obmondo/ssl/puppetserver-enableit.crt
        subPath: tls.crt

gfetch:
  repos:
    enableit:
      url: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-enableit.git
      local_path: /etc/puppetlabs/code/hiera-data/enableit
    niwyocdmk2:
      url: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-niwyocdmk2.git
      local_path: /etc/puppetlabs/code/hiera-data/niwyocdmk2
    p45k4z2vfh:
      url: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-p45k4z2vfh.git
      local_path: /etc/puppetlabs/code/hiera-data/p45k4z2vfh
    ebillet:
      url: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-ebillet.git
      local_path: /etc/puppetlabs/code/hiera-data/ebillet
    qd2xcggwag:
      url: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-qd2xcggwag.git
      local_path: /etc/puppetlabs/code/hiera-data/qd2xcggwag
    a0hu8x41ng:
      url: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-a0hu8x41ng.git
      local_path: /etc/puppetlabs/code/hiera-data/a0hu8x41ng

postgresql:
  instance: 1
  size: 2Gi
  recover: false
  resources:
    limits:
      memory: 500Mi
    requests:
      memory: 500Mi
      cpu: 200m
