image:
  repository: harbor.obmondo.com/obmondo/obmondo-backup-exporter
  tag: v1.0.0
imagePullSecrets:
  - name: harbor-registry-secret
exporter:
  postgres:
    max_rpo: 24h
    interval_rate: 0.25
    ignore_clusters:
      finance:
        - api-postgresql
      finance-test:
        - api-postgresql
      obmondo-website:
        - api-postgresql
      monitoring-staging:
        - gitea-staging-pgsql
      keycloak-staging:
        - keycloak-pgsql
      keycloak-test:
        - keycloak-pgsql
