customerid: niwyocdmk2
puppetserver:
  global:
    extraEnv:
      OBMONDO_ENV: "beta"
  puppetserver:
    masters:
      fqdns:
        alternateServerNames: niwyocdmk2.puppet.obmondo.com
  puppetdb:
    fqdns:
      alternateServerNames: niwyocdmk2.puppetdb.obmondo.com
  metrics:
    prometheus:
      puppetdb:
        serviceMonitor:
          enabled: false


puppetAgentExporter:
  serviceMonitor:
    enabled: false

gfetch:
  serviceMonitor:
    enabled: false

g10k:
  hiera:
    extraRepository:
      niwyocdmk2:
        remote: ssh://git@gitea.obmondo.com:2223/EnableIT/linuxaid-config-niwyocdmk2.git
        basedir: /etc/puppetlabs/code/hiera-data/niwyocdmk2

global:
  postgresql:
    enabled: true
    instanceName: puppetserver
    instances: 1
    monitoring:
      enablePodMonitor: false
    size: 2Gi
    resources:
      limits:
        memory: 500Mi
      requests:
        memory: 500Mi
        cpu: 200m
